// GENERATED by schema (lean-4.33.0) at - — DO NOT EDIT
// spec unknown | SchemaCore.Slice | 2 item(s) | content hash 12355479353295214739 | regen: just gen; drift fails CI
//
// THE WIRE (SchemaCore.Codec — the byte contract, ONE owner, cited):
//   bool     one byte, 0 = false, 1 = true (any other byte refuses);
//   u64      the canonical minimal LEB128 varint;
//   i64      the varint of the zigzag of the value;
//   string   varint length + one varint code point per char (NOT UTF-8);
//   option   tag 0 = none, 1 = some + payload;
//   result   tag 0 = ok + payload, 1 = err + payload;
//   list/map/set  varint count + elements/entries in payload order;
//   bounded  the varint of the value (the cap gates at decode).
// The Rust varint caps at 10 continuation groups (see dec_varint):
// every in-policy atom fits; longer forms refuse on BOTH sides.

/// The typed refusal — every out-of-policy byte shape maps to a ctor
/// (SchemaCore.Codec's accepted-byte policy: the exact image of the
/// encoder). Never a panic, never a silent misparse.
#[derive(Debug, Clone, PartialEq, Eq)]
#[rustfmt::skip]
pub enum CodecError {
    Truncated,
    InvalidTag(u8),
    NonCanonicalVarint,
    VarintOverflow,
    U64Range,
    I64Range,
    InvalidChar(u64),
    CapViolation { cap: u64, got: u64 },
    TrailingBytes,
}

/// The canonical minimal LEB128 varint (the u64 atom's wire form).
#[rustfmt::skip]
pub fn enc_varint(mut n: u64, out: &mut Vec<u8>) {
    loop {
        if n < 128 {
            out.push(n as u8);
            return;
        }
        out.push((128 + n % 128) as u8);
        n /= 128;
    }
}

/// Read one byte off the cursor.
#[rustfmt::skip]
pub fn dec_byte(bs: &mut &[u8]) -> Result<u8, CodecError> {
    if bs.is_empty() {
        return Err(CodecError::Truncated);
    }
    let b = bs[0];
    *bs = &bs[1..];
    Ok(b)
}

/// The canonical minimal varint: the FINAL group's payload zero in a
/// multi-group form refuses (0x80 0x00, 0x80 0x81 0x00 — any redundant
/// trailing zero group — NEVER accepted); beyond 10 groups the value
/// refuses (see the header note — Lean's unbounded-Nat decoder refuses
/// the same bytes downstream).
#[rustfmt::skip]
pub fn dec_varint(bs: &mut &[u8]) -> Result<u128, CodecError> {
    let mut result: u128 = 0;
    let mut groups = 0u32;
    loop {
        if groups >= 10 {
            return Err(CodecError::VarintOverflow);
        }
        let b = dec_byte(bs)?;
        result |= ((b & 0x7f) as u128) << (7 * groups);
        if b < 128 {
            if groups > 0 && (b & 0x7f) == 0 {
                return Err(CodecError::NonCanonicalVarint);
            }
            return Ok(result);
        }
        groups += 1;
    }
}

/// Bool: one byte, 0 = false, 1 = true; any other byte refuses.
#[rustfmt::skip]
pub fn dec_bool(bs: &mut &[u8]) -> Result<bool, CodecError> {
    match dec_byte(bs)? {
        0u8 => Ok(false),
        1u8 => Ok(true),
        other => Err(CodecError::InvalidTag(other)),
    }
}

/// u64: the varint, range-gated at 2^64 (never a silent wrap).
#[rustfmt::skip]
pub fn dec_u64(bs: &mut &[u8]) -> Result<u64, CodecError> {
    let n = dec_varint(bs)?;
    if n <= u64::MAX as u128 {
        Ok(n as u64)
    } else {
        Err(CodecError::U64Range)
    }
}

/// The zigzag map (0 -> 0, -1 -> 1, 1 -> 2, ...): signed over varint.
#[rustfmt::skip]
pub fn zigzag_i64(v: i64) -> u64 {
    ((v << 1) ^ (v >> 63)) as u64
}

/// i64: the zigzag varint, re-checked (a zigzag outside the Int64
/// range refuses — never a silent wrap).
#[rustfmt::skip]
pub fn dec_i64(bs: &mut &[u8]) -> Result<i64, CodecError> {
    let n = dec_varint(bs)?;
    let m = n >> 1;
    let i: i128 = if n % 2 == 0 { m as i128 } else { -(m as i128 + 1) };
    if i >= i64::MIN as i128
        && i <= i64::MAX as i128
        && zigzag_i64(i as i64) as u128 == n
    {
        Ok(i as i64)
    } else {
        Err(CodecError::I64Range)
    }
}

/// String: varint length + one varint code point per char (NOT UTF-8 —
/// the char-varint wire is the provable atom; see SchemaCore.Codec).
#[rustfmt::skip]
pub fn enc_str(s: &str, out: &mut Vec<u8>) {
    enc_varint(s.chars().count() as u64, out);
    for c in s.chars() {
        enc_varint(c as u64, out);
    }
}

/// String, decode half: each code point validated (a value that is not
/// a Unicode scalar value refuses).
#[rustfmt::skip]
pub fn dec_string(bs: &mut &[u8]) -> Result<String, CodecError> {
    let count = dec_varint(bs)?;
    if count > usize::MAX as u128 {
        return Err(CodecError::VarintOverflow);
    }
    let mut acc = String::new();
    for _ in 0..(count as usize) {
        let n = dec_varint(bs)?;
        match u32::try_from(n).ok().and_then(char::from_u32) {
            Some(c) => acc.push(c),
            None => {
                return Err(CodecError::InvalidChar(
                    u64::try_from(n).unwrap_or(u64::MAX),
                ))
            }
        }
    }
    Ok(acc)
}

/// Bounded: the varint, gated at the cap (a cap-violating value
/// refuses — never a silent wrap).
#[rustfmt::skip]
pub fn dec_bounded(cap: u64, bs: &mut &[u8]) -> Result<u64, CodecError> {
    let n = dec_varint(bs)?;
    if n < cap as u128 {
        Ok(n as u64)
    } else {
        Err(CodecError::CapViolation {
            cap,
            got: u64::try_from(n).unwrap_or(u64::MAX),
        })
    }
}

/// The builder's state markers (the typestate's set-ness index —
/// the builder discipline carried in RUST's types: `build` exists
/// ONLY in the all-`Set` state, so a field never set means a wrong
/// construction does not COMPILE — never a runtime refusal).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[rustfmt::skip]
pub struct Set;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[rustfmt::skip]
pub struct Unset;

/// The closed enums + the newtype faces (the block after the runtime
/// helpers — the universe's own types, below).

// THE CLOSED UNIVERSE'S RUST FACES (the schema's closed enums + the
// scalar sub-universe + the deterministic carrier — the model's
// guarantees carried in RUST's types, not tests).
//
// The closed enums ride the strum derives (the iteration + the
// string discipline: the tag strings are the LEAN ctor names,
// snake_case — the model's tag discipline). The newtypes are
// MANUAL (the dep judgment: no nutype/bon proc-macro lane — the
// honest manual version is the smaller, auditable one).

/// The closed Profile enum (SchemaCore.Profile — WHICH semantic a
/// scalar carries). CLOSED: the `fast` slot (the hardware-float
/// trade, its forfeits named) extends with its full fold — the
/// compiler drives every consumer's match — when its consumer lands.
#[derive(Clone, Debug, PartialEq, Eq, Hash,
  strum::EnumIter, strum::EnumCount, strum::Display, strum::EnumString)]
#[strum(serialize_all = "snake_case")]
pub enum Profile {
    /// The bare scalar's own semantics (the default).
    Plain,
    /// The fixed-point discipline (`Fixed` — the carrier below):
    /// exact checked addition, named floor rounding, total order,
    /// codec-legal on the u64 wire row.
    Deterministic,
}

/// The closed scalar sub-universe (SchemaCore.Ty's KeyTy — the
/// map/set keys + the declared keys' admitted materials).
#[derive(Clone, Debug, PartialEq, Eq, Hash,
  strum::EnumIter, strum::EnumCount, strum::Display, strum::EnumString)]
#[strum(serialize_all = "snake_case")]
pub enum KeyTy {
    Bool,
    U64,
    I64,
    String,
}

/// The key MATERIAL newtypes (the keys lane's admission gate
/// `keyOfTy`: only scalars are key material — these wrappers ARE
/// that gate's Rust face). Values enter through `try_new` —
/// validation at construction, ONE point; the model's next key
/// invariant lands HERE, never at the consumers.
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct KeyBool(bool);

#[rustfmt::skip]
impl KeyBool {
    /// The admitted key material (the gate's extension point).
    pub fn try_new(b: bool) -> Option<KeyBool> { Some(KeyBool(b)) }
    /// The carried scalar (the read face — the wire codecs take it).
    pub fn get(&self) -> bool { self.0 }
}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct KeyU64(u64);

#[rustfmt::skip]
impl KeyU64 {
    pub fn try_new(n: u64) -> Option<KeyU64> { Some(KeyU64(n)) }
    pub fn get(&self) -> u64 { self.0 }
}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct KeyI64(i64);

#[rustfmt::skip]
impl KeyI64 {
    pub fn try_new(n: i64) -> Option<KeyI64> { Some(KeyI64(n)) }
    pub fn get(&self) -> i64 { self.0 }
}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub struct KeyString(String);

#[rustfmt::skip]
impl KeyString {
    pub fn try_new(s: String) -> Option<KeyString> { Some(KeyString(s)) }
    pub fn get(&self) -> &str { &self.0 }
}

/// The deterministic carrier (SchemaCore.Profile's `Fixed scale` —
/// the `Money Cents` shape): the value IS `units`, an integer of the
/// scale's units; the rational reading is `units / SCALE`. The scale
/// lives in the TYPE (erases at runtime); the u64 wire capacity
/// lives in the type too (out-of-contract values unconstructible).
///
/// The PROMISES (each the model's law, never a hope): EXACT checked
/// addition (the overflow refuses — never a silent wrap), NAMED
/// floor rounding for multiplication (error strictly under one
/// unit), TOTAL order (no NaN hole). The FORFEITS (named, honesty
/// cuts both ways): hardware-float speed, dynamic range (magnitudes
/// past 2^64 / SCALE units refuse).
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Fixed<const SCALE: u64>(u64);

#[rustfmt::skip]
impl<const SCALE: u64> Fixed<SCALE> {
    /// The validated constructor: the scale-positivity gate lives
    /// HERE (a `Fixed<0>` is never constructible — a zero scale
    /// divides by zero; the model refuses at the ONE construction
    /// point, never after the fact).
    pub fn try_new(units: u64) -> Option<Fixed<SCALE>> {
        if SCALE == 0 {
            return None;
        }
        Some(Fixed(units))
    }

    /// The units (the raw carrier — the wire face + the arithmetic
    /// read it; the rational reading is `units / SCALE`).
    pub fn units(&self) -> u64 { self.0 }

    /// EXACT addition: the units' sum, no rounding; the wire
    /// capacity's overflow REFUSES (never a silent wrap).
    pub fn add_checked(&self, other: &Fixed<SCALE>) -> Option<Fixed<SCALE>> {
        self.0.checked_add(other.0).and_then(Fixed::try_new)
    }

    /// The named rounding for multiplication: the exact rational
    /// product, FLOORED (the truncating division — the error is
    /// strictly under one unit); the capacity's overflow refuses.
    /// (Unreachable for a zero scale: a `Fixed<0>` is unconstructible.)
    pub fn mul_floor(&self, other: &Fixed<SCALE>) -> Option<Fixed<SCALE>> {
        let p = (self.0 as u128) * (other.0 as u128);
        let q = p / (SCALE as u128);
        if q <= u64::MAX as u128 {
            Fixed::try_new(q as u64)
        } else {
            None
        }
    }

    /// CODEC LEGALITY (the model's promise): the carrier rides the
    /// EXISTING u64 wire row — the bytes are the bare u64 varint's,
    /// byte-for-byte, both directions.
    pub fn encode(&self, out: &mut Vec<u8>) {
        enc_varint(self.0, out);
    }

    /// The wire face, decode half (append-form; the exact-image form
    /// is the caller's `decode_full` discipline over the cursor).
    pub fn decode(bs: &mut &[u8]) -> Option<Fixed<SCALE>> {
        dec_u64(bs).ok().and_then(Fixed::try_new)
    }
}


#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Example {
    pub ready: bool,
    pub count: u64,
    pub delta: i64,
    pub label: String,
    pub note: Option<String>,
    pub tags: Vec<String>,
}

#[rustfmt::skip]
impl Example {
    /// Encode in SchemaCore.Codec's wire form (fields in schema order).
    pub fn encode(&self, out: &mut Vec<u8>) {
        // the operation's span (C1 — bind the guard: a dropped
        // guard is a zero-length span)
        let _span = Self::encode_scope();
        out.push(if *&self.ready { 1u8 } else { 0u8 });
        enc_varint(*&self.count, out);
        enc_varint(zigzag_i64(*&self.delta), out);
        enc_str(&self.label.as_str(), out);
        match &self.note { None => out.push(0u8), Some(inner) => { out.push(1u8); enc_str(inner.as_str(), out); } };
        enc_varint((&self.tags).len() as u64, out); for inner in (&self.tags).iter() { enc_str(inner.as_str(), out); }
    }

    /// Decode in SchemaCore.Codec's wire form (append-form: the
    /// unconsumed suffix stays on the cursor). Out-of-policy bytes
    /// are a typed CodecError, never a panic, never a silent misparse.
    pub fn decode(bs: &mut &[u8]) -> Result<Example, CodecError> {
        let _span = Self::decode_scope();
        let ready = dec_bool(bs)?;
        let count = dec_u64(bs)?;
        let delta = dec_i64(bs)?;
        let label = dec_string(bs)?;
        let note = { let tag = dec_byte(bs)?; match tag { 0u8 => None, 1u8 => { let inner = dec_string(bs)?; Some(inner) }, _ => return Err(CodecError::InvalidTag(tag)) } };
        let tags = { let count = dec_varint(bs)?; let mut acc = Vec::new(); for _ in 0..count { let inner = dec_string(bs)?; acc.push(inner); } acc };
        Ok(Example { ready, count, delta, label, note, tags })
    }

    /// The exact-image form: decode and require the whole input.
    pub fn decode_full(bs: &[u8]) -> Result<Example, CodecError> {
        let mut rest = bs;
        let value = Self::decode(&mut rest)?;
        if !rest.is_empty() {
            return Err(CodecError::TrailingBytes);
        }
        Ok(value)
    }

    /// The key-indexed lookup (notes/v3/02-data-plane.md §3): the
    /// declared primary key's determinacy makes the query
    /// Option-shaped — at most one row (SchemaCore.Keys'
    /// `lookup?_atMostOne` is the theorem; this is its Rust shape).
    pub fn get_by_label<'a>(rows: &'a [Example], key: &str) -> Option<&'a Example> {
        rows.iter().find(|r| r.label == key)
    }

    /// The conservative field query (02 §3): NO uniqueness claim —
    /// every match returns (the collection shape is the surface
    /// without a declared key; the determinacy discipline).
    pub fn find_by_ready<'a>(rows: &'a [Example], value: &bool) -> Vec<&'a Example> {
        rows.iter().filter(|r| &r.ready == value).collect()
    }

    /// The conservative field query (02 §3): NO uniqueness claim —
    /// every match returns (the collection shape is the surface
    /// without a declared key; the determinacy discipline).
    pub fn find_by_count<'a>(rows: &'a [Example], value: &u64) -> Vec<&'a Example> {
        rows.iter().filter(|r| &r.count == value).collect()
    }

    /// The conservative field query (02 §3): NO uniqueness claim —
    /// every match returns (the collection shape is the surface
    /// without a declared key; the determinacy discipline).
    pub fn find_by_delta<'a>(rows: &'a [Example], value: &i64) -> Vec<&'a Example> {
        rows.iter().filter(|r| &r.delta == value).collect()
    }

    /// The conservative field query (02 §3): NO uniqueness claim —
    /// every match returns (the collection shape is the surface
    /// without a declared key; the determinacy discipline).
    pub fn find_by_label<'a>(rows: &'a [Example], value: &String) -> Vec<&'a Example> {
        rows.iter().filter(|r| &r.label == value).collect()
    }

    /// The conservative field query (02 §3): NO uniqueness claim —
    /// every match returns (the collection shape is the surface
    /// without a declared key; the determinacy discipline).
    pub fn find_by_note<'a>(rows: &'a [Example], value: &Option<String>) -> Vec<&'a Example> {
        rows.iter().filter(|r| &r.note == value).collect()
    }

    /// The conservative field query (02 §3): NO uniqueness claim —
    /// every match returns (the collection shape is the surface
    /// without a declared key; the determinacy discipline).
    pub fn find_by_tags<'a>(rows: &'a [Example], value: &Vec<String>) -> Vec<&'a Example> {
        rows.iter().filter(|r| &r.tags == value).collect()
    }
    /// The operation spans (C1's observability face: the schema's
    /// namespace path as the scope-name source — dotted-static,
    /// 'static low-cardinality ONLY; high-cardinality data rides log
    /// kv, NEVER scope tags — the interned name leaks).
    pub const ENCODE_SPAN: &str = "schema.example.encode";
    pub const DECODE_SPAN: &str = "schema.example.decode";

    /// Enter the encode operation's span (bind the guard: a dropped
    /// guard is a zero-length span).
    #[inline]
    pub fn encode_scope() -> fast_observe::profiling::ScopeGuard {
        fast_observe::scope!(Self::ENCODE_SPAN)
    }

    /// Enter the decode operation's span (bind the guard: a dropped
    /// guard is a zero-length span).
    #[inline]
    pub fn decode_scope() -> fast_observe::profiling::ScopeGuard {
        fast_observe::scope!(Self::DECODE_SPAN)
    }
}

#[rustfmt::skip]
pub struct ExampleBuilder<F0, F1, F2, F3, F4, F5> {
    ready: Option<bool>,
    count: Option<u64>,
    delta: Option<i64>,
    label: Option<String>,
    note: Option<Option<String>>,
    tags: Option<Vec<String>>,
    state: std::marker::PhantomData<(F0, F1, F2, F3, F4, F5)>,
}

#[rustfmt::skip]
impl Example {
    /// The builder's entry: every field unset (and `build` is not
    /// callable until each setter has moved its state index).
    pub fn builder() -> ExampleBuilder<Unset, Unset, Unset, Unset, Unset, Unset> {
        ExampleBuilder {
            ready: None, count: None, delta: None, label: None, note: None, tags: None,
            state: std::marker::PhantomData,
        }
    }
}

impl<F1, F2, F3, F4, F5> ExampleBuilder<Unset, F1, F2, F3, F4, F5> {
    /// Set `ready` (the state index moves Unset -> Set).
    pub fn ready(self, ready: bool) -> ExampleBuilder<Set, F1, F2, F3, F4, F5> {
        ExampleBuilder {
            ready: Some(ready),
            count: self.count, delta: self.delta, label: self.label, note: self.note, tags: self.tags,
            state: std::marker::PhantomData,
        }
    }
}


impl<F0, F2, F3, F4, F5> ExampleBuilder<F0, Unset, F2, F3, F4, F5> {
    /// Set `count` (the state index moves Unset -> Set).
    pub fn count(self, count: u64) -> ExampleBuilder<F0, Set, F2, F3, F4, F5> {
        ExampleBuilder {
            count: Some(count),
            ready: self.ready, delta: self.delta, label: self.label, note: self.note, tags: self.tags,
            state: std::marker::PhantomData,
        }
    }
}


impl<F0, F1, F3, F4, F5> ExampleBuilder<F0, F1, Unset, F3, F4, F5> {
    /// Set `delta` (the state index moves Unset -> Set).
    pub fn delta(self, delta: i64) -> ExampleBuilder<F0, F1, Set, F3, F4, F5> {
        ExampleBuilder {
            delta: Some(delta),
            ready: self.ready, count: self.count, label: self.label, note: self.note, tags: self.tags,
            state: std::marker::PhantomData,
        }
    }
}


impl<F0, F1, F2, F4, F5> ExampleBuilder<F0, F1, F2, Unset, F4, F5> {
    /// Set `label` (the state index moves Unset -> Set).
    pub fn label(self, label: String) -> ExampleBuilder<F0, F1, F2, Set, F4, F5> {
        ExampleBuilder {
            label: Some(label),
            ready: self.ready, count: self.count, delta: self.delta, note: self.note, tags: self.tags,
            state: std::marker::PhantomData,
        }
    }
}


impl<F0, F1, F2, F3, F5> ExampleBuilder<F0, F1, F2, F3, Unset, F5> {
    /// Set `note` (the state index moves Unset -> Set).
    pub fn note(self, note: Option<String>) -> ExampleBuilder<F0, F1, F2, F3, Set, F5> {
        ExampleBuilder {
            note: Some(note),
            ready: self.ready, count: self.count, delta: self.delta, label: self.label, tags: self.tags,
            state: std::marker::PhantomData,
        }
    }
}


impl<F0, F1, F2, F3, F4> ExampleBuilder<F0, F1, F2, F3, F4, Unset> {
    /// Set `tags` (the state index moves Unset -> Set).
    pub fn tags(self, tags: Vec<String>) -> ExampleBuilder<F0, F1, F2, F3, F4, Set> {
        ExampleBuilder {
            tags: Some(tags),
            ready: self.ready, count: self.count, delta: self.delta, label: self.label, note: self.note,
            state: std::marker::PhantomData,
        }
    }
}


#[rustfmt::skip]
impl ExampleBuilder<Set, Set, Set, Set, Set, Set> {
    /// The disciplined constructor — TOTAL at the type level: it
    /// exists ONLY in the all-set state (the wrong construction
    /// does not compile). The `expect` is the type index's
    /// unreachable arm, never a real error path.
    pub fn build(self) -> Example {
        Example {
            ready: self.ready.expect("inhabited by the builder's type index"),
            count: self.count.expect("inhabited by the builder's type index"),
            delta: self.delta.expect("inhabited by the builder's type index"),
            label: self.label.expect("inhabited by the builder's type index"),
            note: self.note.expect("inhabited by the builder's type index"),
            tags: self.tags.expect("inhabited by the builder's type index"),
        }
    }
}

#[rustfmt::skip]
impl serde::Serialize for Example {
    fn serialize<S: serde::Serializer>(&self, serializer: S)
        -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut st = serializer.serialize_struct("Example", 6)?;
        st.serialize_field("ready", &self.ready)?;
        st.serialize_field("count", &self.count)?;
        st.serialize_field("delta", &self.delta)?;
        st.serialize_field("label", &self.label)?;
        st.serialize_field("note", &self.note)?;
        st.serialize_field("tags", &self.tags)?;
        st.end()
    }
}

#[rustfmt::skip]
impl<'de> serde::Deserialize<'de> for Example {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D)
        -> Result<Self, D::Error> {
        struct ExampleVisitor;
        impl<'de> serde::de::Visitor<'de> for ExampleVisitor {
            type Value = Example;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("struct Example")
            }
            fn visit_map<A: serde::de::MapAccess<'de>>(
                self, mut map: A,
            ) -> Result<Example, A::Error> {
                let mut ready: Option<bool> = None;
                let mut count: Option<u64> = None;
                let mut delta: Option<i64> = None;
                let mut label: Option<String> = None;
                let mut note: Option<Option<String>> = None;
                let mut tags: Option<Vec<String>> = None;
                while let Some(k) = map.next_key::<String>()? {
                    match k.as_str() {
                        "ready" => {
                            if ready.is_some() {
                                return Err(serde::de::Error::duplicate_field("ready"));
                            }
                            ready = Some(map.next_value()?);
                        }
                        "count" => {
                            if count.is_some() {
                                return Err(serde::de::Error::duplicate_field("count"));
                            }
                            count = Some(map.next_value()?);
                        }
                        "delta" => {
                            if delta.is_some() {
                                return Err(serde::de::Error::duplicate_field("delta"));
                            }
                            delta = Some(map.next_value()?);
                        }
                        "label" => {
                            if label.is_some() {
                                return Err(serde::de::Error::duplicate_field("label"));
                            }
                            label = Some(map.next_value()?);
                        }
                        "note" => {
                            if note.is_some() {
                                return Err(serde::de::Error::duplicate_field("note"));
                            }
                            note = Some(map.next_value()?);
                        }
                        "tags" => {
                            if tags.is_some() {
                                return Err(serde::de::Error::duplicate_field("tags"));
                            }
                            tags = Some(map.next_value()?);
                        }
                        _ => {
                            let _ = map.next_value::<serde::de::IgnoredAny>()?;
                        }
                    }
                }
                Ok(Example {
                    ready: ready.ok_or_else(|| serde::de::Error::missing_field("ready"))?,
                    count: count.ok_or_else(|| serde::de::Error::missing_field("count"))?,
                    delta: delta.ok_or_else(|| serde::de::Error::missing_field("delta"))?,
                    label: label.ok_or_else(|| serde::de::Error::missing_field("label"))?,
                    note: note.ok_or_else(|| serde::de::Error::missing_field("note"))?,
                    tags: tags.ok_or_else(|| serde::de::Error::missing_field("tags"))?,
                })
            }
        }
        deserializer.deserialize_struct("Example", &["ready", "count", "delta", "label", "note", "tags"], ExampleVisitor)
    }
}


#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ExampleEx {
    pub status: Result<u64, String>,
    pub counts: Vec<(String, u64)>,
    pub small: u64,
}

#[rustfmt::skip]
impl ExampleEx {
    /// Encode in SchemaCore.Codec's wire form (fields in schema order).
    pub fn encode(&self, out: &mut Vec<u8>) {
        // the operation's span (C1 — bind the guard: a dropped
        // guard is a zero-length span)
        let _span = Self::encode_scope();
        match &self.status { Ok(inner) => { out.push(0u8); enc_varint(*inner, out); }, Err(inner) => { out.push(1u8); enc_str(inner.as_str(), out); } };
        enc_varint((&self.counts).len() as u64, out); for (innerk, innerv) in (&self.counts).iter() { enc_str(innerk.as_str(), out); enc_varint(*innerv, out); }
        enc_varint(*&self.small, out);
    }

    /// Decode in SchemaCore.Codec's wire form (append-form: the
    /// unconsumed suffix stays on the cursor). Out-of-policy bytes
    /// are a typed CodecError, never a panic, never a silent misparse.
    pub fn decode(bs: &mut &[u8]) -> Result<ExampleEx, CodecError> {
        let _span = Self::decode_scope();
        let status = { let tag = dec_byte(bs)?; match tag { 0u8 => { let inner = dec_u64(bs)?; Ok(inner) }, 1u8 => { let inner = dec_string(bs)?; Err(inner) }, _ => return Err(CodecError::InvalidTag(tag)) } };
        let counts = { let count = dec_varint(bs)?; let mut acc = Vec::new(); for _ in 0..count { let innerk = dec_string(bs)?; let innerv = dec_u64(bs)?; acc.push((innerk, innerv)); } acc };
        let small = dec_bounded(42u64, bs)?;
        Ok(ExampleEx { status, counts, small })
    }

    /// The exact-image form: decode and require the whole input.
    pub fn decode_full(bs: &[u8]) -> Result<ExampleEx, CodecError> {
        let mut rest = bs;
        let value = Self::decode(&mut rest)?;
        if !rest.is_empty() {
            return Err(CodecError::TrailingBytes);
        }
        Ok(value)
    }

    /// The conservative field query (02 §3): NO uniqueness claim —
    /// every match returns (the collection shape is the surface
    /// without a declared key; the determinacy discipline).
    pub fn find_by_status<'a>(rows: &'a [ExampleEx], value: &Result<u64, String>) -> Vec<&'a ExampleEx> {
        rows.iter().filter(|r| &r.status == value).collect()
    }

    /// The conservative field query (02 §3): NO uniqueness claim —
    /// every match returns (the collection shape is the surface
    /// without a declared key; the determinacy discipline).
    pub fn find_by_counts<'a>(rows: &'a [ExampleEx], value: &Vec<(String, u64)>) -> Vec<&'a ExampleEx> {
        rows.iter().filter(|r| &r.counts == value).collect()
    }

    /// The conservative field query (02 §3): NO uniqueness claim —
    /// every match returns (the collection shape is the surface
    /// without a declared key; the determinacy discipline).
    pub fn find_by_small<'a>(rows: &'a [ExampleEx], value: &u64) -> Vec<&'a ExampleEx> {
        rows.iter().filter(|r| &r.small == value).collect()
    }
    /// The operation spans (C1's observability face: the schema's
    /// namespace path as the scope-name source — dotted-static,
    /// 'static low-cardinality ONLY; high-cardinality data rides log
    /// kv, NEVER scope tags — the interned name leaks).
    pub const ENCODE_SPAN: &str = "schema.example_ex.encode";
    pub const DECODE_SPAN: &str = "schema.example_ex.decode";

    /// Enter the encode operation's span (bind the guard: a dropped
    /// guard is a zero-length span).
    #[inline]
    pub fn encode_scope() -> fast_observe::profiling::ScopeGuard {
        fast_observe::scope!(Self::ENCODE_SPAN)
    }

    /// Enter the decode operation's span (bind the guard: a dropped
    /// guard is a zero-length span).
    #[inline]
    pub fn decode_scope() -> fast_observe::profiling::ScopeGuard {
        fast_observe::scope!(Self::DECODE_SPAN)
    }
}

#[rustfmt::skip]
pub struct ExampleExBuilder<F0, F1, F2> {
    status: Option<Result<u64, String>>,
    counts: Option<Vec<(String, u64)>>,
    small: Option<u64>,
    state: std::marker::PhantomData<(F0, F1, F2)>,
}

#[rustfmt::skip]
impl ExampleEx {
    /// The builder's entry: every field unset (and `build` is not
    /// callable until each setter has moved its state index).
    pub fn builder() -> ExampleExBuilder<Unset, Unset, Unset> {
        ExampleExBuilder {
            status: None, counts: None, small: None,
            state: std::marker::PhantomData,
        }
    }
}

impl<F1, F2> ExampleExBuilder<Unset, F1, F2> {
    /// Set `status` (the state index moves Unset -> Set).
    pub fn status(self, status: Result<u64, String>) -> ExampleExBuilder<Set, F1, F2> {
        ExampleExBuilder {
            status: Some(status),
            counts: self.counts, small: self.small,
            state: std::marker::PhantomData,
        }
    }
}


impl<F0, F2> ExampleExBuilder<F0, Unset, F2> {
    /// Set `counts` (the state index moves Unset -> Set).
    pub fn counts(self, counts: Vec<(String, u64)>) -> ExampleExBuilder<F0, Set, F2> {
        ExampleExBuilder {
            counts: Some(counts),
            status: self.status, small: self.small,
            state: std::marker::PhantomData,
        }
    }
}


impl<F0, F1> ExampleExBuilder<F0, F1, Unset> {
    /// Set `small` (the state index moves Unset -> Set).
    pub fn small(self, small: u64) -> ExampleExBuilder<F0, F1, Set> {
        ExampleExBuilder {
            small: Some(small),
            status: self.status, counts: self.counts,
            state: std::marker::PhantomData,
        }
    }
}


#[rustfmt::skip]
impl ExampleExBuilder<Set, Set, Set> {
    /// The disciplined constructor — TOTAL at the type level: it
    /// exists ONLY in the all-set state (the wrong construction
    /// does not compile). The `expect` is the type index's
    /// unreachable arm, never a real error path.
    pub fn build(self) -> ExampleEx {
        ExampleEx {
            status: self.status.expect("inhabited by the builder's type index"),
            counts: self.counts.expect("inhabited by the builder's type index"),
            small: self.small.expect("inhabited by the builder's type index"),
        }
    }
}

#[rustfmt::skip]
impl serde::Serialize for ExampleEx {
    fn serialize<S: serde::Serializer>(&self, serializer: S)
        -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut st = serializer.serialize_struct("ExampleEx", 3)?;
        st.serialize_field("status", &self.status)?;
        st.serialize_field("counts", &self.counts)?;
        st.serialize_field("small", &self.small)?;
        st.end()
    }
}

#[rustfmt::skip]
impl<'de> serde::Deserialize<'de> for ExampleEx {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D)
        -> Result<Self, D::Error> {
        struct ExampleExVisitor;
        impl<'de> serde::de::Visitor<'de> for ExampleExVisitor {
            type Value = ExampleEx;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("struct ExampleEx")
            }
            fn visit_map<A: serde::de::MapAccess<'de>>(
                self, mut map: A,
            ) -> Result<ExampleEx, A::Error> {
                let mut status: Option<Result<u64, String>> = None;
                let mut counts: Option<Vec<(String, u64)>> = None;
                let mut small: Option<u64> = None;
                while let Some(k) = map.next_key::<String>()? {
                    match k.as_str() {
                        "status" => {
                            if status.is_some() {
                                return Err(serde::de::Error::duplicate_field("status"));
                            }
                            status = Some(map.next_value()?);
                        }
                        "counts" => {
                            if counts.is_some() {
                                return Err(serde::de::Error::duplicate_field("counts"));
                            }
                            counts = Some(map.next_value()?);
                        }
                        "small" => {
                            if small.is_some() {
                                return Err(serde::de::Error::duplicate_field("small"));
                            }
                            small = Some(map.next_value()?);
                        }
                        _ => {
                            let _ = map.next_value::<serde::de::IgnoredAny>()?;
                        }
                    }
                }
                Ok(ExampleEx {
                    status: status.ok_or_else(|| serde::de::Error::missing_field("status"))?,
                    counts: counts.ok_or_else(|| serde::de::Error::missing_field("counts"))?,
                    small: small.ok_or_else(|| serde::de::Error::missing_field("small"))?,
                })
            }
        }
        deserializer.deserialize_struct("ExampleEx", &["status", "counts", "small"], ExampleExVisitor)
    }
}


// THE MIGRATION LANE'S RUST FACE (SchemaCore.Migrate — the migration
// lane landed Lean-side; this is its Rust surface): the versioned
// types + the derived upcaster. The plan is DERIVED Lean-side from
// the diff's change set + the type's defaults; SchemaTests pins the
// derivation to the plan below (runtime pin — the wf-recursive
// derivation is kernel-opaque, 06 §2); the fn renders the plan's
// steps, never a second derivation. The key `label` is carried
// UNCHANGED (stable identities, notes/v3/08-capabilities.md §19).
//
// The plan (v1 -> v2): carry ready, carry count, carry label, fill delta (the type's default)

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ExampleV1 {
    pub ready: bool,
    pub count: u64,
    pub label: String,
}

#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ExampleV2 {
    pub ready: bool,
    pub count: u64,
    pub label: String,
    pub delta: i64,
}

/// The derived upcaster (SchemaCore.Migrate's plan, rendered).
#[rustfmt::skip]
pub fn upcast_example_v1_to_example_v2(v: ExampleV1) -> ExampleV2 {
    ExampleV2 {
ready: v.ready,
count: v.count,
label: v.label,
delta: 0i64
    }
}

#[rustfmt::skip]
impl serde::Serialize for ExampleV1 {
    fn serialize<S: serde::Serializer>(&self, serializer: S)
        -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut st = serializer.serialize_struct("ExampleV1", 3)?;
        st.serialize_field("ready", &self.ready)?;
        st.serialize_field("count", &self.count)?;
        st.serialize_field("label", &self.label)?;
        st.end()
    }
}

#[rustfmt::skip]
impl<'de> serde::Deserialize<'de> for ExampleV1 {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D)
        -> Result<Self, D::Error> {
        struct ExampleV1Visitor;
        impl<'de> serde::de::Visitor<'de> for ExampleV1Visitor {
            type Value = ExampleV1;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("struct ExampleV1")
            }
            fn visit_map<A: serde::de::MapAccess<'de>>(
                self, mut map: A,
            ) -> Result<ExampleV1, A::Error> {
                let mut ready: Option<bool> = None;
                let mut count: Option<u64> = None;
                let mut label: Option<String> = None;
                while let Some(k) = map.next_key::<String>()? {
                    match k.as_str() {
                        "ready" => {
                            if ready.is_some() {
                                return Err(serde::de::Error::duplicate_field("ready"));
                            }
                            ready = Some(map.next_value()?);
                        }
                        "count" => {
                            if count.is_some() {
                                return Err(serde::de::Error::duplicate_field("count"));
                            }
                            count = Some(map.next_value()?);
                        }
                        "label" => {
                            if label.is_some() {
                                return Err(serde::de::Error::duplicate_field("label"));
                            }
                            label = Some(map.next_value()?);
                        }
                        _ => {
                            let _ = map.next_value::<serde::de::IgnoredAny>()?;
                        }
                    }
                }
                Ok(ExampleV1 {
                    ready: ready.ok_or_else(|| serde::de::Error::missing_field("ready"))?,
                    count: count.ok_or_else(|| serde::de::Error::missing_field("count"))?,
                    label: label.ok_or_else(|| serde::de::Error::missing_field("label"))?,
                })
            }
        }
        deserializer.deserialize_struct("ExampleV1", &["ready", "count", "label"], ExampleV1Visitor)
    }
}

#[rustfmt::skip]
impl serde::Serialize for ExampleV2 {
    fn serialize<S: serde::Serializer>(&self, serializer: S)
        -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut st = serializer.serialize_struct("ExampleV2", 4)?;
        st.serialize_field("ready", &self.ready)?;
        st.serialize_field("count", &self.count)?;
        st.serialize_field("label", &self.label)?;
        st.serialize_field("delta", &self.delta)?;
        st.end()
    }
}

#[rustfmt::skip]
impl<'de> serde::Deserialize<'de> for ExampleV2 {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D)
        -> Result<Self, D::Error> {
        struct ExampleV2Visitor;
        impl<'de> serde::de::Visitor<'de> for ExampleV2Visitor {
            type Value = ExampleV2;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                f.write_str("struct ExampleV2")
            }
            fn visit_map<A: serde::de::MapAccess<'de>>(
                self, mut map: A,
            ) -> Result<ExampleV2, A::Error> {
                let mut ready: Option<bool> = None;
                let mut count: Option<u64> = None;
                let mut label: Option<String> = None;
                let mut delta: Option<i64> = None;
                while let Some(k) = map.next_key::<String>()? {
                    match k.as_str() {
                        "ready" => {
                            if ready.is_some() {
                                return Err(serde::de::Error::duplicate_field("ready"));
                            }
                            ready = Some(map.next_value()?);
                        }
                        "count" => {
                            if count.is_some() {
                                return Err(serde::de::Error::duplicate_field("count"));
                            }
                            count = Some(map.next_value()?);
                        }
                        "label" => {
                            if label.is_some() {
                                return Err(serde::de::Error::duplicate_field("label"));
                            }
                            label = Some(map.next_value()?);
                        }
                        "delta" => {
                            if delta.is_some() {
                                return Err(serde::de::Error::duplicate_field("delta"));
                            }
                            delta = Some(map.next_value()?);
                        }
                        _ => {
                            let _ = map.next_value::<serde::de::IgnoredAny>()?;
                        }
                    }
                }
                Ok(ExampleV2 {
                    ready: ready.ok_or_else(|| serde::de::Error::missing_field("ready"))?,
                    count: count.ok_or_else(|| serde::de::Error::missing_field("count"))?,
                    label: label.ok_or_else(|| serde::de::Error::missing_field("label"))?,
                    delta: delta.ok_or_else(|| serde::de::Error::missing_field("delta"))?,
                })
            }
        }
        deserializer.deserialize_struct("ExampleV2", &["ready", "count", "label", "delta"], ExampleV2Visitor)
    }
}

