/-
# Gates.ArtifactManifest — the committed artifacts' inventory (`gates artifact-manifest [--write]`)

One generated table (notes/artifacts.manifest): every registered emitter's
declared outputs → (path, content hash, emitter). The hashes ARE the
byte-tie's own field — the regenerated body's `String.hash`, the same value
each GENERATED header embeds as `content hash` — so the manifest is the
artifact inventory as ONE queryable file. The byte-tie (`gates gen-check`)
stays the BINDING check; this gate is additive, and a later gen-check fast
path may consume the committed table instead of regenerating (NOT wired —
deliberate, this order).

Determinism: the emitters are pure `run` folds over the replayed registries
(the GenCheck preamble), rows are sorted by path, and there are no
timestamps — the volatile header fields the byte-tie exempts are absent
here by construction. `--write` regenerates the table; the default mode
diffs it (Driver.reportGate — the same drift/absent semantics as
axiom-report/coverage-matrix). A duplicate path ACROSS the two registries
fails before any write — the runtime twin of the registry audit test (the
one-writer rule).

LEGACY (non-module) file: meta env-extension access via Gates.Common
(the module-migration constraint: such drivers stay legacy).
-/
import Gates.Common
import Faults.Emit.Registry

open Lean
open CodegenCore.Emit (GeneratedFile)

namespace Gates.ArtifactManifest

/-- One manifest row: repo-root path, the regenerated body's content hash
    (`String.hash` — the byte-tie header's field), the owning emitter. -/
structure Entry where
  path : String
  hash : UInt64
  emitter : String
  deriving Inhabited

/-- Regenerate every registered emitter's artifacts IN MEMORY (the
    emitters are pure; this is the GenCheck collect loop) and lift them to
    (path, content hash, emitter) rows sorted by path. Never writes. -/
unsafe def collect : IO (Array Entry) := do
  let ctx ← Gates.loadGenCtx
  let mut entries : Array Entry := #[]
  for e in SchemaLang.Emit.emitters do
    for f in e.run ctx do
      entries := entries.push
        { path := f.path, hash := f.contents.hash, emitter := s!"schema-lang/{e.name}" }
  for (e, spec) in Faults.Emit.jobs do
    for f in e.run spec do
      entries := entries.push
        { path := f.path, hash := f.contents.hash, emitter := s!"faults/{e.name}" }
  return entries.qsort (fun a b => a.path < b.path)

/-- The committed inventory this gate diffs against. -/
def baselinePath : System.FilePath := "../../notes/artifacts.manifest"

/-- The deterministic table (sorted by path; no volatile fields). -/
def render (entries : Array Entry) : String :=
  String.intercalate "\n"
    ([ "# Artifact manifest — the committed generated artifacts' inventory"
     , ""
     , "GENERATED by `lake exe gates artifact-manifest --write` (lean/gates) — do not hand-edit."
     , "CI runs `gates artifact-manifest`; a diff against this file = the registered"
     , "emitters' artifact surface changed. One row per generated artifact: the"
     , "repo-root path, the regenerated body's `String.hash` — the same value the"
     , "GENERATED header embeds as `content hash` (the byte-tie's own field) — and"
     , "the emitter that owns the path (the one-writer surface, sorted by path)."
     , "Additive to `gates gen-check`, which stays the binding byte-tie."
     , ""
     , "| path | content hash | emitter |"
     , "| --- | --- | --- |" ]
     ++ (entries.toList.map fun e =>
          s!"| `{e.path}` | `{e.hash}` | `{e.emitter}` |"))

unsafe def run (write acceptDrift : Bool) : IO UInt32 := do
  let entries ← collect
  -- the one-writer rule, runtime twin: rows are path-sorted, so a duplicate
  -- path is adjacent. Fail BEFORE any write/diff — two writers on one path
  -- is a registry bug, not a manifest drift.
  let mut dup : Option String := none
  for i in [0:entries.size - 1] do
    if entries[i]!.path == entries[i+1]!.path then
      dup := some s!"{entries[i]!.path} ({entries[i]!.emitter} vs {entries[i+1]!.emitter})"
  if let some p := dup then
    IO.eprintln s!"artifact-manifest: DUPLICATE output path {p} — the \
      one-writer rule violated; fix the registries"
    return 1
  Driver.reportGate "artifact-manifest" "manifest" "the artifact surface changed"
    baselinePath (render entries) write acceptDrift false
    s!"artifact-manifest: {entries.size} artifact(s) in sync with the committed inventory"

end Gates.ArtifactManifest
