/-
# Kit.Emit — the emitter spine

The emitter-plugin model (15-patterns #10): ONE parsed spec, MANY
emitter plugins; each is a PURE TOTAL function from spec to files with
its declared outputs (nodup IN THE TYPE — the v3 upgrade: a colliding
`outputs` list fails to elaborate, there is no runtime rejection path);
the DRIVER owns IO (`runEmitters`); the artifact's header is the
GENERATED block whose content hash is the byte-tie anchor (the
byte-tie strips the header and hashes the content — ANY metadata is
safe; the header = information, the byte-tie = the content).

Provenance: mined from
`legacy/lean/codegen-core/CodegenCore/Emit/Core.lean` — the header
discipline, the plugin structure, the certified lane, the driver loop.
Deliberately excluded (no consumer in this landing; each lives at its
own layer, not core): name mangling (target-specific — one module per
TARGET), the JSON manifest builders, and the driver's git/clock
metadata assembly (tree-specific pathspecs — the driver's `mkGm`
callback supplies GenMeta; the pure core stays IO-free except at the
write).

The hash is core's `String.hash` (deterministic, 64-bit, zero code) —
NOT a crypto digest (the store's job); this one is the artifact's
self-description ("which spec state am I").

Core-only.

The five questions (notes/v3/01-core.md):
- root: Crossing — the artifact spine: a spec read into files (the
  target grammar's text).
- carrier grade: the emitter's law field — a correspondence instance
  cited per emitter (or an honest header note why not); the content
  hash is the byte-tie anchor.
- spine reading: THE spine — Registry → Interpretation → artifact
  (01 §5: an emitter IS an interpretation); the driver owns IO.
- ladder rung: the fold machinery is structural/total; the laws live
  at the emitters that instantiate it.
- gate row: gen-check (Gates.GenCheck) — the byte-tie row over the
  generated artifacts (SchemaCore's emitter is the first consumer).
-/

import Lean

namespace Kit.Emit

/-! ## The generated-file header -/

/-- Comment prefix per target: Lean/SQL `--`, Rust/WIT `//`,
    YAML/Python `#`, WAT `;;`. -/
inductive CommentStyle where
  | lean | doubleSlash | hash | wat

def CommentStyle.prefix : CommentStyle → String
  | .lean => "-- "
  | .doubleSlash => "// "
  | .hash => "# "
  | .wat => ";; "

def CommentStyle.line (s : CommentStyle) (text : String) : String :=
  s.prefix ++ text

/-- The generation metadata — assembled by the DRIVER (the only IO
    point: the clock + git); the emitters stay pure. -/
structure GenMeta where
  /-- The regen's wall-clock (ISO-ish, `YYYY-MM-DDTHH:MMZ`). -/
  time : String := "-"
  /-- The spec source's git short sha + the dirty marker (`+` = the
      working copy drifted past the sha). -/
  specSha : String := "unknown"
  /-- The registered item count (the spec's size, at a glance). -/
  items : Nat := 0
  /-- `String.hash` over the artifact's body (the header excluded) —
      the content's self-verification seed. -/
  contentHash : UInt64 := 0

/-- The generated-file header: TWO lines, dense metadata. `tool` names
    the emitting package, `specSource` the spec module. (TRAP honored:
    the binder cannot be named `meta` — a Lean keyword.) -/
def header (style : CommentStyle) (tool specSource : String) (gm : GenMeta) : String :=
  CommentStyle.line style
    (s!"GENERATED by {tool} (lean-{Lean.versionString}) at {gm.time} — DO NOT EDIT") ++ "\n"
    ++ CommentStyle.line style
      (s!"spec {gm.specSha} | {specSource} | {gm.items} item(s) | "
        ++ s!"content hash {gm.contentHash} | regen: just gen; drift fails CI")
    ++ "\n"

/-- One generated artifact: repo-root-relative path + content (header
    prepended by the driver, not by the emitter). -/
structure GeneratedFile where
  path : String
  contents : String

/-! ## The emitter plugin — outputs nodup IN THE TYPE -/

/-- An emitter plugin: one language target. Pure and total — `run` is
    a fold over the spec into files; the driver writes. The declared
    output paths carry their uniqueness AS A PROOF FIELD (the
    one-writer discipline, per emitter): a duplicate-path literal fails
    to elaborate. -/
structure Emitter (Spec : Type) where
  /-- Plugin name. -/
  name : String
  /-- Comment prefix for the generated header. -/
  style : CommentStyle
  /-- The spec module the artifacts derive from (audit provenance). -/
  specSource : String
  /-- Declared output paths, repo-root-relative. -/
  outputs : List String
  /-- THE one-writer discipline, in the type: no emitter declares the
      same output path twice. Default `by decide` over concrete lists. -/
  outputs_nodup : outputs.Nodup := by decide
  /-- Fold the spec into files. Pure and deterministic (tested). -/
  run : Spec → List GeneratedFile
  /-- OPTIONAL emission law. When `some L`, the driver SHOULD discharge
      `L spec` over the concrete spec and emit via `runCertified` — the
      artifact is unemittable without the discharged certificate.
      Defaults to `none` so plain `Emitter` literals compile unchanged. -/
  law : Option (Spec → Prop) := none

/-- The certificate an emitter demands over a concrete spec: `some L`
    requires the discharged `L spec`; `none` is trivially certified. -/
def Emitter.Cert (e : Emitter Spec) (spec : Spec) : Prop :=
  match e.law with
  | some L => L spec
  | none => True

/-- Proof-carrying emission: the certified lane. Plain `run` stays
    available (backward compatibility); certified drivers call here
    with the discharged certificate. -/
def Emitter.runCertified (e : Emitter Spec) (spec : Spec) (_cert : e.Cert spec) :
    List GeneratedFile := e.run spec

/-- Cross-emitter one-writer audit, data-level (the per-emitter nodup
    is in the type; the CROSS-emitter disjointness is a registry-level
    check — a `true` verdict is the discharge): no two emitters in the
    list declare the same output path. -/
def outputsDisjoint (es : List (Emitter Spec)) : Bool :=
  (es.flatMap (·.outputs)).Nodup

/-! ## The driver's write path -/

/-- Create the parent directories of `path` (all generated paths are
    slash-separated, so the drop-last computation always names a real
    directory). -/
def createParentDirs (path : System.FilePath) : IO Unit :=
  let dir := String.intercalate "/" ((path.toString.splitOn "/").dropLast)
  IO.FS.createDirAll dir

/-- Write one generated file, creating parent directories first. -/
def writeFileCreatingDirs (path : System.FilePath) (contents : String) : IO Unit := do
  createParentDirs path
  IO.FS.writeFile path contents

/-- The shared driver loop: for each (emitter, spec) job, run the
    emitter, prepend the header, and write each generated file.
    `tool` = the emitting package name. `mkGm` gives the driver control
    over per-file GenMeta (the clock + git + content hash — the ONLY IO
    point; the emitters stay pure). -/
def runEmitters {Spec : Type} (tool : String)
    (jobs : List (Emitter Spec × Spec))
    (mkGm : Emitter Spec → GeneratedFile → IO GenMeta) : IO Unit :=
  for (e, spec) in jobs do
    for f in e.run spec do
      let gm ← mkGm e f
      writeFileCreatingDirs f.path (header e.style tool e.specSource gm ++ f.contents)
      IO.println s!"wrote {f.path}"

end Kit.Emit
