//! lean-rust-wasm — guestlang framework crate.
#![feature(error_generic_member_access)]
//!
//! The fast-observe base wiring lives in `src/main.rs` (same shape as
//! fast-observe's `examples/demo.rs`); the library is intentionally thin
//! until the project has real shared types.

// The guestlang change algebra — OUR trait mirroring Lean's Dbsp.ChangeSpec
// (patch/valid); NOT the Feldera dbsp crate. Generated delta enums impl it.
pub mod dbsp;

// Generated artifacts moved to generated/rust/ (Goal C2) — included by
// path, module names unchanged so intra-crate `use crate::<x>_generated::*`
// still resolves. The emitters regenerate them (just gen); never edit.
#[path = "../generated/rust/dbsp_change_generated.rs"]
pub mod dbsp_change_generated;

#[path = "../generated/rust/pipeline_generated.rs"]
pub mod pipeline_generated;

// Generated by schema-lang (lean/schema-lang/GenMain.lean) — the Lean
// spec is authoritative; regenerate with `just gen`, never edit.
// rustfmt::skip on all generated modules: the emitter's output is the
// formatting authority; rustfmt reflowing generated files fights the
// byte-tie (regen would undo the reflow, fmt --check would flip forever).
#[rustfmt::skip]
#[path = "../generated/rust/schema_generated.rs"]
pub mod schema_generated;

// Generated by schema-lang (SchemaLang/Emit/GenRust.lean, W6.4): value
// GENERATORS for the schema records — arbitrary::Unstructured-driven,
// budget-threaded, collision-pooled. Feature-gated on `arbitrary` (the
// wire crate's pattern): no arbitrary in production builds.
#[cfg(feature = "arbitrary")]
#[rustfmt::skip]
#[path = "../generated/rust/gen_generated.rs"]
pub mod gen_generated;

// Delta contracts: per-record change variants impl dbsp::Change; the
// certified-delta tests (Stage E) ride along under #[cfg(test)].
#[rustfmt::skip]
#[path = "../generated/rust/delta_generated.rs"]
pub mod delta_generated;

// Generated by faults (lean/faults/GenMain.lean) — fast-observe error
// registry; codes allocated from the Lean registry, never hand-set.
#[rustfmt::skip]
#[path = "../generated/rust/faults_generated.rs"]
pub mod faults_generated;

// The certified dbsp circuit (lean/schema-lang Emit/Circuit) — the Lean
// proof (`incrementalize_ok`, cited in the header) IS the correctness
// story; guestlang-host's tests/circuit.rs replays it.
#[rustfmt::skip]
#[path = "../generated/rust/circuit_generated.rs"]
pub mod circuit_generated;
