/-
# Ledger tests — the minimal gate files' driver

The scaffold's gate floor: positive + negative controls over the
scaffolded impl, elaboration-checked (`#guard` fails the BUILD on
drift, not just the run). Grow this into TestKit's discipline as the
project does: PropSpec sweeps with the MANDATORY negative control,
DiffSpec for differential gates (TestKit/README, notes/reuse-map.md).

The W5.1 block: the `@[event_sourced]` dogfood — replay, journal codec,
rewind (the RewindableMachine instance), conservation — each law with
its sabotaged negative control (the doctrine: a control the sabotage
cannot pass).
-/
import Lean
import TestKit
import Ledger
import LedgerFn
import LedgerES

open LedgerES

-- Negative control first: the sentinel id → none.
#guard (LedgerImpl.ledger_get 0).isNone

-- Positive control: a real id → some (the record round-trips).
#guard (LedgerImpl.ledger_get 3).map (·.id) == some 3

-- The spec type survived the rename: the record exists with its fields.
#guard (LedgerImpl.ledger_get 1).map (·.label) == some "ledger"

/-! ## W5.1 — the `@[event_sourced]` dogfood (positive + negative controls) -/

-- the two-entry posting fixture
def e1 : Entry := ⟨1, 1, 2, 30⟩   -- 30 from account 1 to account 2
def e2 : Entry := ⟨2, 2, 1, 10⟩   -- 10 back
def entryLog : List Entry.Event := [.insert e1, .insert e2]

-- REPLAY (positive): the transfer fixture materializes the post-state.
#guard Account.replay (transferEvents 30) [] == [⟨1, "alice", 70⟩, ⟨2, "bob", 80⟩]

-- REPLAY (negative control): a sabotaged log (the credit leg dropped)
-- does NOT reconstruct the state.
#guard Account.replay ((transferEvents 30).take 3) [] != [⟨1, "alice", 70⟩, ⟨2, "bob", 80⟩]

-- REPLAY LAW exercised (replay-after-append = one more apply).
#guard Entry.replay (entryLog ++ [.insert e1]) [] ==
  SchemaLang.EventSourced.apply Entry.esKey (.insert e1) (Entry.replay entryLog [])

-- JOURNAL CODEC (positive): the entry log round-trips the wire.
#guard Entry.esDecodeJournal? (Entry.esEncodeJournal entryLog) == some (entryLog, [])

-- JOURNAL CODEC (negative control): a corrupted tag byte does not
-- decode to the original event (the EnumWire tag-sabotage pattern).
#guard (match Entry.esDecodeEvent? (7 :: Entry.esEncodeEvent (.insert e1)) with
        | some (e, _) => e != .insert e1
        | none => true)

-- the rewind fixture rides a NON-empty initial table (from empty, the
-- insert-inverses erase everything and no sabotage is observable)
def mallory : Account := ⟨7, "mallory", 999⟩

-- REWIND / the RewindableMachine (positive): the logged run's journal
-- rewinds to the initial table (reversal = the inverse delta).
#guard (Machines.RewindableMachine.runLogged Account.esMachine [mallory] (transferEvents 30)).map
  (fun (_, ds, fin) => Account.esMachine.rewind ds.reverse fin) == some [mallory]

-- REWIND-K = UNDO-K (positive): reverting the last two deltas (the
-- transfer legs) restores the post-open table.
#guard (Machines.RewindableMachine.runLogged Account.esMachine [mallory] (transferEvents 30)).map
  (fun (_, ds, fin) => Account.esMachine.rewind (ds.drop 2).reverse fin)
    == some [mallory, alice, bob]

-- REWIND (negative control): a TAMPERED suffix journal (the recorded
-- old balances shifted by one) does NOT restore the post-open table —
-- the recorded deltas are the undo information, not decoration. (The
-- control rides the suffix form: a full rewind ends in the
-- insert-inverses, whose erases wipe any tampered row.)
#guard (Machines.RewindableMachine.runLogged Account.esMachine [mallory] (transferEvents 30)).map
  (fun (_, ds, fin) => Account.esMachine.rewind
    ((ds.drop 2).reverse.map fun d => { d with old := d.old.map fun a => { a with balance := a.balance + 1 } })
    fin) != some [mallory, alice, bob]

-- CONSERVATION (positive): a balanced posting keeps the universe's total.
#guard total [1, 2] (balances (postEntry e1 [])) == total [1, 2] (balances [])

-- CONSERVATION (negative control): a one-legged posting (the debit leg
-- outside the universe — an external deposit) GROWS the total. The
-- conservation theorem's endpoint hypotheses are load-bearing.
#guard total [1, 2] (balances (postEntry ⟨9, 0, 2, 30⟩ [])) == total [1, 2] (balances []) + 30

-- The obligation row discharges at the proved tier.
#guard conservationObligation.discharge.isSome

/-! ## W9.5 — the witness-gated migration dogfood (the guestVerified lane)

The v1→v2 `Account` migration (id widened u32→u64), the witness
GENERATED by W9.4's machinery, the replay-through-migration gated by
`EventSourced.replayMigrated?`. Positive: the valid witness ACCEPTS and
the migrated segment replays, every applied row satisfying the compiled
invariant; the certificate round-trips the wire codec. Negative
controls (the doctrine's mandatory shape): a tampered claim and a
corrupted step proof REFUSE with `diverged`; an exhausted cap REFUSES
with `fuelExhausted`; a wrong-version envelope refuses at DECODE; a
mis-labeled obligation does not discharge. An unwitnessed migration is
UNREPRESENTABLE — the gate's only replay path takes the witness. -/

-- POSITIVE: the committed v1 segment replays through the migration,
-- witness-gated, to the post-state
#guard accountV1V2Replay == .ok [⟨1, "alice", 100⟩, ⟨2, "bob", 50⟩, ⟨3, "carol", 75⟩]

-- POSITIVE: every applied row satisfies the compiled `id > 0` (the
-- id-nonzero half of `ledger_valid`)
#guard (match accountV1V2Replay with
        | .ok st => st.all fun r =>
            SchemaLang.validates accountIdPositiveInv (Account.esToRow r)
        | .error _ => false)

-- POSITIVE: the certificate round-trips the wire codec (the guest
-- receives BYTES — envelope + payload, decode + resolve + re-check)
#guard (SchemaLang.Witness.decWitnessFor? Account.esFields
    SchemaLang.Emit.Witness.witnessVersion
    (SchemaLang.Witness.encWitness SchemaLang.Emit.Witness.witnessVersion
      (SchemaLang.Emit.Witness.surfaceHash Account.esFields).toNat accountV1V2Witness))
  == some accountV1V2Witness

-- POSITIVE (§7.3's headroom): the witness still accepts at exactly the
-- structural minimum fuel — `consumed × 4` is margin, never load-bearing
#guard (SchemaLang.EventSourced.replayMigrated? Account.esKey Account.esToRow
    upcastAccountV1 { accountV1V2Witness with fuel := 3 }
    (migrateAccountV1 accountV1Init) accountV1Log [migrateAccountV1 accountV1Init])
  == .ok [⟨1, "alice", 100⟩, ⟨2, "bob", 50⟩, ⟨3, "carol", 75⟩]

-- NEGATIVE CONTROL: a TAMPERED witness (the claim strengthened to
-- `id > 5` — false on bob, id 2) REFUSES — `diverged`, label named,
-- the events NOT applied
#guard (SchemaLang.EventSourced.replayMigrated? Account.esKey Account.esToRow
    upcastAccountV1
    { accountV1V2Witness with claim := .chain [⟨0⟩, ⟨1⟩] (.gt (.col "id") (.lit 5)) }
    (migrateAccountV1 accountV1Init) accountV1Log [migrateAccountV1 accountV1Init])
  == .error (.diverged "account-v1-v2-id-nonzero")

-- NEGATIVE CONTROL: a CORRUPTED step proof (the first step's proof is
-- `byEval`, not the v1 `byValidEval`) REFUSES — `diverged`
#guard (SchemaLang.EventSourced.replayMigrated? Account.esKey Account.esToRow
    upcastAccountV1
    { accountV1V2Witness with proof := .steps [.byEval 1, .byValidEval] }
    (migrateAccountV1 accountV1Init) accountV1Log [migrateAccountV1 accountV1Init])
  == .error (.diverged "account-v1-v2-id-nonzero")

-- NEGATIVE CONTROL (§7.3): WRONG FUEL — the same certificate below the
-- structural minimum (2 < 3) REFUSES — `fuelExhausted`, label named,
-- BEFORE any checking; no retry
#guard (SchemaLang.EventSourced.replayMigrated? Account.esKey Account.esToRow
    upcastAccountV1 { accountV1V2Witness with fuel := 2 }
    (migrateAccountV1 accountV1Init) accountV1Log [migrateAccountV1 accountV1Init])
  == .error (.fuelExhausted "account-v1-v2-id-nonzero")
#guard (SchemaLang.EventSourced.replayMigrated? Account.esKey Account.esToRow
    upcastAccountV1 { accountV1V2Witness with fuel := 0 }
    (migrateAccountV1 accountV1Init) accountV1Log [migrateAccountV1 accountV1Init])
  == .error (.fuelExhausted "account-v1-v2-id-nonzero")

-- NEGATIVE CONTROL: a wrong-version envelope refuses at DECODE (before
-- any checking — the envelope discipline)
#guard (SchemaLang.Witness.decWitnessFor? Account.esFields 999
    (SchemaLang.Witness.encWitness SchemaLang.Emit.Witness.witnessVersion
      (SchemaLang.Emit.Witness.surfaceHash Account.esFields).toNat accountV1V2Witness)).isNone

-- the migration obligation discharges at the fifth tier, evidence =
-- the witness artifact + label
#guard accountMigrationObligation.discharge ==
  some (.guestWitness "witnesses/account-v1-v2-id-nonzero.wtn" "account-v1-v2-id-nonzero")

-- NEGATIVE CONTROL (the mis-wire check): a guestVerified obligation
-- whose label is NOT the certificate's does not discharge
#guard (LedgerObligation.discharge
    { accountMigrationObligation with label := "account-v9-other" }).isNone

-- the refusal render names the obligation's label (LOUD, not silent)
#guard ((SchemaLang.EventSourced.MigrationRefusal.diverged
    "account-v1-v2-id-nonzero").render.splitOn "account-v1-v2-id-nonzero").length == 2

def main : IO UInt32 := do
  IO.println "LedgerTests: guards green (elab-time)"
  return 0
