/-
SchemaLang.Observe — the LEAN MANIFESTATION of the observability
contract (the fast-observe seam).

The doctrine's move: the spans are not something the host invents —
they are SPEC DATA. Every func item in the registry manifests as a
`SpanSpec` (the span name = the kebab fn name, the fields = the
params' names and their WIT types, the delivery tag); the
`observeEmitter` emits the Rust const table (`observability_generated.rs`)
that the host's call path consumes; the instrumentation covers EXACTLY
the registered funcs — an unregistered fn has no span, so the
observability surface = the spec surface BY CONSTRUCTION (the same
fold the world WIT uses, one authority).

The consumer: steel-host's `call` looks the export up in the generated
table and opens the fast-observe span for it (`profiling::instant`).
The table is byte-tied like every artifact: editing a schema fn's
signature changes the observed fields or fails CI.

Text assembly: structural `Std.Format` (hard `line`s — NO `group`s, so
`.pretty` cannot reflow; `nest` for the block bodies, `joinSep` for the
comma lists). The bytes are pinned identical to the pre-Format emitter
by an old-vs-new dump diff of every registry emitter's raw contents
plus this module's `observeRust` (all byte-equal); the span-row leaf
(the `(\"…\", \"…\")` pairs) keeps its escaping verbatim.

Deliberately NOT here (the follow-ups): the span NESTING (the call
tree = the middleware composition's shape — lands with the splicer
middleware), the sampling policy (fast-observe's own config), and the
WASI-side telemetry (the guest's spans — a wasm component cannot emit
host spans without a telemetry capability; that's the middleware's job).
-/
import SchemaLang.Emit.Wit

namespace SchemaLang.Observe

open CodegenCore.Emit (kebab)
open SchemaLang.Emit.Wit (tyWit)
open Std.Format

/-- The leaf of a dotted declaration name: `GuestImpl.getUser` →
    `getUser` (the world export name's source — the same leaf rule the
    world fold uses). -/
def leafOf (name : String) : String :=
  (name.splitOn ".").getLast!

/-- One span's observed field: the param's (kebab name, WIT type). -/
def spanFields (sig : FuncSig) : List (String × String) :=
  sig.params.map fun (p, t) => (kebab p, tyWit t)

/-- The span NAME for a func item: the kebab of the leaf. -/
def spanName (sig : FuncSig) : String := kebab (leafOf sig.name)

/-- One span's Rust const-table row (unindented — `observeRust` nests it):
    `SpanSpec { name: "…", delivery: "…", fields: &[(field, ty), …] }`,
    with the delivery tag as a field (the host logs the contract with
    the span). The quotes are the f! string's own escaping — the OUTPUT
    is Rust, whose braces are data here (`\{` emits the brace). -/
def spanRow (sig : FuncSig) : Std.Format :=
  let fields := joinSep
    ((spanFields sig).map fun (n, t) => f!"(\"{n}\", \"{t}\")") (text ", ")
  let del := match sig.sem.delivery with
    | .once => "once"
    | .stream => "stream"
  f!"SpanSpec \{ name: \"{spanName sig}\", delivery: \"{del}\", fields: &[{fields}] }"

/-- The GENERATED Rust: the const table the host's call path consumes.
    One row per registered func item; the host cannot open a span the
    table does not declare. -/
def observeRust (items : List Item) : String :=
  let funcs := items.filterMap fun
    | .func sig => some sig
    | _ => none
  let doc : Std.Format :=
    f!"// GENERATED by schema-lang (lean-{Lean.versionString}) — DO NOT EDIT" ++ line
    ++ f!"// spans = spec data: the registry is the authority | regen: just gen; drift fails CI" ++ line
    ++ f!"/// One observed export: the span name + its fields + the delivery" ++ line
    ++ f!"/// contract (`once` = one result value; `stream` = incremental)." ++ line
    ++ f!"pub struct SpanSpec \{" ++
    nest 4 (line ++ f!"pub name: &'static str," ++ line
      ++ f!"pub delivery: &'static str," ++ line
      ++ f!"pub fields: &'static [(&'static str, &'static str)],")
    ++ line ++ f!"}" ++ line
    ++ line
    ++ f!"/// The observed surface = the registered schema fns, in registry order." ++ line
    ++ f!"pub const SPANS: &[SpanSpec] = &["
    ++ funcs.foldl (fun acc sig => acc ++ nest 4 (line ++ (spanRow sig ++ f!","))) ""
    ++ line ++ f!"];" ++ line
  doc.pretty

end SchemaLang.Observe
