/-
# SchemaLang.OrderMachine — the order lifecycle as a machine

The demo domain's (Demo.lean: User/Order/OrderError) lifecycle discipline,
modeled as a Machines machine — the SECOND machine in the tree and the
first DOMAIN machine: the pipeline machine (Pipeline.lean) models the
TOOLING, this one models the SOFTWARE the spec authors ship.

Two projections, per Machines.Core (the Pipeline.lean pattern):
- executable: `orderMachine.step?` / `.run` — invalid sequences rejected,
- proof: `orderMachine.tr` + the theorems below.

Proved here:
- `orderMachine.rank_advances` / `orderMachine.rank_advances_tr` (generated by the machine! rank clause) — every non-`reset` transition
  strictly increases the lifecycle rank (the lifecycle is a DAG whose
  only cycles pass through `reset`).
- `terminal_only_reset` — `delivered`/`cancelled` are TERMINAL: only
  `reset` leaves them (the lifecycle cannot silently reopen).
- `reject_*` — out-of-order and double-fire are observably rejected.
- `orderMachineTableStep?_eq_step?` — the emitted Rust table IS the machine
  (the same discipline that governs the pipeline driver).

Consumption: `SchemaLang.Emit.Machine` folds `orderMachineTrans` into Rust
(`src/order_machine_generated.rs`); steel-host's test replays the
lifecycle trace against the generated step fn. The battery
(`conformance`) sweeps the full state space; the pipelineDead machine
(Pipeline.lean) is the global non-vacuity control for the battery.

Deliberate exclusion: no effectful transition payloads (Machines v1 has
no output channel — see Machines/Core.lean); the machine is the
DISCIPLINE model, the data effects ride the schema funcs.
-/

module

public import Machines.Dsl
public import Machines.Testing
public import SchemaLang.Item

@[expose] public section

open Machines.Dsl

namespace SchemaLang

/-! ## The lifecycle -/

/-- The order status: the machine's states (NOT a schema item — this is
    the lifecycle discipline, not wire data; the wire carries the order
    record, the host carries the status). `stray` is the state NO
    transition produces — the invariant excludes it, the battery
    enumerates it (non-vacuity: the machine PROVES the host can never
    synthesize it), the generated step rejects it. -/
inductive OrderStatus where
  | cart | placed | shipped | delivered | cancelled | stray
deriving Repr, BEq, DecidableEq, Inhabited

-- The machine. Terminal states (`delivered`/`cancelled`) reject every
-- event except `reset` (the recovery edge) — terminality is a THEOREM
-- below, not a convention. (plain comment: doc comments cannot precede
-- machine! — the custom command rejects them)
/-- Lifecycle rank: cart 0 → placed 1 → shipped 2 → delivered/
    cancelled 3. `cancelled` rides with `delivered` (both terminal);
    `stray` rides at 0 (unreachable — no transition targets it). -/
def OrderStatus.rank : OrderStatus → Nat
  | .cart => 0 | .placed => 1 | .shipped => 2
  | .delivered => 3 | .cancelled => 3 | .stray => 0

-- W2.3: the `states:` clause makes machine! generate the entourage this
-- file used to hand-write — `orderMachineStates` (the state space),
-- `orderMachineTrans` (the transition table, computed from the machine),
-- `orderMachineTableStep?` + the agreement theorem
-- `orderMachineTableStep?_eq_step?`, and the `DecidablePred
-- orderMachine.Inv` instance. The hand copies are deleted below.
machine! orderMachine where
  State: OrderStatus
  Inv: fun s => s ≠ .stray
  rank: OrderStatus.rank rewind: reset
  states: [.cart, .placed, .shipped, .delivered, .cancelled, .stray]
  event: place guard: (fun s => s = .cart) action: (fun _ _ => .placed)
  event: ship guard: (fun s => s = .placed) action: (fun _ _ => .shipped)
  event: deliver guard: (fun s => s = .shipped) action: (fun _ _ => .delivered)
  event: cancel guard: (fun s => s = .cart || s = .placed) action: (fun _ _ => .cancelled)
  event: reset guard: (fun _ => true) action: (fun _ _ => .cart)

/-- The conformance battery: deadlock-freedom (reset is always
    enabled), guard coverage, invariant non-vacuity over
    `orderMachineStates` — the stray state included (that's the point:
    the invariant is FALSE on it, the non-vacuity check has something to
    see, and no transition reaches it). The state space and the
    `DecidablePred orderMachine.Inv` instance are machine!-generated. -/
def orderConformance : List (String × TestKit.CheckResult) :=
  Machines.Testing.conformance orderMachine orderMachine.labels orderMachineStates
    orderMachine.labels_complete

/-! ## The proved discipline -/

/-- Terminal states: only `reset` leaves them. A delivered order cannot
    be re-shipped; a cancelled order cannot be re-placed — silently
    reopening the lifecycle is IMPOSSIBLE, not forbidden. -/
theorem terminal_only_reset (s s' : OrderStatus) (l : orderMachine.Label)
    (htr : orderMachine.tr s l s')
    (hd : s = .delivered ∨ s = .cancelled) :
    l = .reset := by
  obtain ⟨w, hw⟩ := htr
  rcases hd with hd | hd <;> subst hd
  · cases l <;> simp [orderMachine, orderMachine.spec] at w ⊢
  · cases l <;> simp [orderMachine, orderMachine.spec] at w ⊢

/-- The happy path EXECUTES: place, ship, deliver. -/
theorem lifecycle_happy_path : orderMachine.run .cart [.place, .ship, .deliver]
    = some ([(.place, .placed), (.ship, .shipped), (.deliver, .delivered)], .delivered) :=
  rfl

/-- The cancel path EXECUTES from either open state. -/
theorem cancel_from_placed : orderMachine.run .cart [.place, .cancel]
    = some ([(.place, .placed), (.cancel, .cancelled)], .cancelled) :=
  rfl

/-- Out-of-order firing is REJECTED, observably. -/
theorem reject_ship_before_place : orderMachine.run .cart [.ship] = none := rfl

/-- Double-fire is REJECTED, observably (a placed order cannot be
    re-placed). -/
theorem reject_double_place : orderMachine.run .cart [.place, .place] = none := rfl

/-- The terminal state's step is `none` for every non-reset event (the
    executable reading of `terminal_only_reset`). -/
theorem delivered_step_none (l : orderMachine.Label)
    (hnr : l ≠ .reset) : orderMachine.step? .delivered l = none := by
  cases l <;> simp [orderMachine, orderMachine.spec] at hnr ⊢

/-! ## The emitted table — the driver's data

machine!-generated (W2.3): `orderMachineTrans` is the transition DATA
the emitter folds (`Emit.Machine.matchArms` generates the Rust match
from its rows — computed from `step?` over the enumerated space,
label-major, the deleted hand copy's exact row order including the
`reset`-from-`stray` row), `orderMachineTableStep?` is the structural
reading, and `orderMachineTableStep?_eq_step?` pins the structural
reading to the machine over the enumerated states (all six — the
theorem is membership-qualified and every `OrderStatus` is a member).
The emitter's wildcard-check + the Rust-side replay test guard the
data reading.
-/

end SchemaLang
