/-
# SchemaLang.Pipeline — the forge build pipeline as a Machine

The pipeline stages (reflection → universeCheck → emitters → byte-tie)
modeled as a guarded state machine (Machines.Machine, authored via
`machine!`). The universe it processes is `SchemaLang.Item`'s `List Item`
(see `universeCheck`, `universeWellFormed`); this file models the STAGE
discipline, not the item algebra.

Two projections, per Machines.Core:
- executable: `pipeline.step?` / `pipeline.run` — invalid sequences are
  REJECTED (a `check` fired without `reflect` returns `none`),
- proof: `pipeline.tr` + `run_preserves` — every successful run ends in an
  invariant-satisfying state; `failed` is the one state the invariant
  excludes (errors are observable states, not silent ones).

Acyclicity: the happy path is a linear chain
idle → reflecting → checked → emitted → tied. `rank_advances` proves every
non-`reset` transition strictly increases `rank` (no cycle without reset);
`happy_path` executes the chain end-to-end.

The conformance battery (Machines.Testing.conformance) sweeps the full
6-state space; `Pipeline.pipelineConformance` is the positive result,
`pipelineGuardControl` the negative control (a dead-event machine must
FAIL guard coverage — the battery is not vacuous).
-/

module

public import Machines.Dsl
public import Machines.Testing
public import SchemaLang.Item

@[expose] public section

open Machines.Dsl

namespace SchemaLang

/-! ## States, events, machine -/

/-- The pipeline states. `failed` carries the stage that failed plus its
    diagnostics (the `universeCheck` diagnostic authority, stage-tagged). -/
inductive PipelineState where
  | idle
  | reflecting    -- @[schema] reflection ran, registry populated
  | checked       -- universeCheck passed (wellFormed, no diags)
  | emitted       -- all emitters ran, artifacts written
  | tied          -- byte-tie clean (artifacts match committed)
  | failed (stage : String) (diags : List String)
deriving Repr, BEq, DecidableEq, Inhabited

-- The pipeline machine. Every stage's guard is its predecessor state;
-- `reset` is always enabled (the recovery edge, including out of
-- `failed`). The invariant excludes ONLY `failed` — an error state is
-- not a legal resting state. (plain comment: doc comments cannot
-- precede machine! — the custom command rejects them)
/-- Position along the happy chain; `failed` and `idle` both rank 0
    (both only leave via `reset`, which re-enters at 0). -/
def PipelineState.rank : PipelineState → Nat
  | .idle => 0
  | .reflecting => 1
  | .checked => 2
  | .emitted => 3
  | .tied => 4
  | .failed _ _ => 0

-- W2.3: the `states:` clause makes machine! generate the entourage this
-- file used to hand-write — `pipelineStates` (the state space),
-- `pipelineTrans` (the transition table, computed from the machine),
-- `pipelineTableStep?` + the agreement theorem
-- `pipelineTableStep?_eq_step?`, and the `DecidablePred pipeline.Inv`
-- instance. The Inv is written as the DISJUNCTION of the legal states
-- (not a `match`) so the generated instance's `inferInstanceAs`
-- synthesizes — the match form is the documented opt-out (Machines.Dsl).
machine! pipeline where
  State: PipelineState
  Inv: fun s =>
    s = .idle ∨ s = .reflecting ∨ s = .checked ∨ s = .emitted ∨ s = .tied
      -- `failed` is NOT in the invariant (error state)
  rank: PipelineState.rank rewind: reset
  states: [.idle, .reflecting, .checked, .emitted, .tied, .failed "check" ["dupName `user`"]]
  event: reflect guard: (fun s => s = .idle) action: (fun _ _ => .reflecting)
  event: check guard: (fun s => s = .reflecting) action: (fun _ _ => .checked)
  event: emit guard: (fun s => s = .checked) action: (fun _ _ => .emitted)
  event: tie guard: (fun s => s = .emitted) action: (fun _ _ => .tied)
  event: reset guard: (fun _ => true) action: (fun _ _ => .idle)

/-- The conformance battery: deadlock-freedom + guard coverage +
    invariant non-vacuity over the full state space (the 5 invariant
    states + one representative failure — `pipelineStates`). Labels AND
    the state space are GENERATED by `machine!` (`pipeline.labels`,
    `pipelineStates`), as is the `DecidablePred pipeline.Inv` instance. -/
def pipelineConformance : List (String × TestKit.CheckResult) :=
  Machines.Testing.conformance pipeline pipeline.labels pipelineStates pipeline.labels_complete

-- NEGATIVE CONTROL: a machine with an unsatisfiable guard (a dead event)
-- must FAIL guard coverage — proves the battery is not vacuous.
machine! pipelineDead where
  State: Nat
  Inv: fun _ => True
  event: tick guard: (fun _ => true) action: (fun s _ => s + 1)
  event: dead guard: (fun s => s > 0 ∧ s < 0) action: (fun s _ => s)
    safety: (by intro s h; simp at h)

/-! ## Acyclicity — the happy path is a linear chain -/

/-- The happy path EXECUTES: reflect, check, emit, tie — idle to tied in
    four accepted steps. -/
theorem happy_path : pipeline.run .idle [.reflect, .check, .emit, .tie]
    = some ([(.reflect, .reflecting), (.check, .checked), (.emit, .emitted), (.tie, .tied)], .tied) :=
  rfl

/-- Out-of-order firing is REJECTED, observably: `check` without
    `reflect` cannot start the pipeline. -/
theorem reject_out_of_order :
    pipeline.run .idle [.check] = none := rfl

/-- `reset` recovers from ANY state, `failed` included — the error state
    is a resting place, not a wedge. -/
theorem reset_from_failed :
    pipeline.run (.failed "tie" ["artifact drift"]) [.reset] = some ([(.reset, .idle)], .idle) :=
  rfl

/-! ## The stage machine, as the driver consumes it

forge (crates/forge) sequences its gen/check phases through the
GENERATED stage machine (`src/pipeline_generated.rs`, emitted by the
`pipelineEmitter`). The table stack is machine!-GENERATED (W2.3):
`pipelineTrans` is the transition DATA the emitter folds
(`Emit.Registry.pipelineArms` generates the Rust match from its rows,
with the reset-wildcard collapse checked against it),
`pipelineTableStep?` is the table as a lookup, and
`pipelineTableStep?_eq_step?` PROVES the table IS the machine's `step?`
over the enumerated states — so the emitted Rust (which mirrors this
match — the Rust-side `happy_path_assertions` + the spliced-run tests
are its drift guards) is the machine, not a sketch of it: the proved
`rank_advances`/`reject_out_of_order` govern the driver.

Two readings of one machine: the DATA (`pipelineTrans`, label-major,
stated in enumeration order — COMPUTED from `step?`, so it cannot drift
from the guards; its `reset` rows now include the enumerated `failed`
state, where the deleted hand copy stopped at the concrete five — the
emitter's wildcard fold produces the same arms either way) and the
structural lookup (`pipelineTableStep?`, keyed by exact state — the
payload-carrying `failed` states the table can't enumerate ride the
Rust-side structural arm, as before).
-/

end SchemaLang
