/-
# Substrait.Decode.Plan — the plan driver and the parser-layer inversion theorems

W5.3 phase 1: split of the monolithic Decode.lean along its section
structure (pure code-motion; statements unchanged).
W5.3 phase 2b: the extensions/version line shapes read the shared
`Substrait.Grammar` tokens and the `ExtKind` block table (`kindOf`'s
if-chain is `ExtKind.ofHeader`; `parseDeclEntry` takes the kind row); the
char-headed entry bodies are top-level (`parseUrnEntryBody`/
`parseDeclEntryBody`/`parseDeclEntryAt` — the `withNull` discipline) so the
the char-headed entry bodies are top-level (`parseUrnEntryBody` /
`parseDeclEntryBody` / `parseDeclEntryAt` — the `withNull` discipline) so the
row inversions reduce by equation lemma.  The extension/version INVERSION
THEOREMS live in `Substrait.Decode.Inversions` (generated by
`declare_inversion` — see `Substrait.Meta.Inversion`); the resolution kit
below is PUBLIC because those generated theorems consume it across the
module boundary.  `parseRootNames_emitted` (the Root-names row) stays here
hand-written: its proof rides this module's private `splitTopLevel` /
identifier lemma stack.
-/

module

public import Substrait.Decode.Rel

@[expose] public section

namespace Substrait.Decode

-- ── the plan driver ─────────────────────────────────────────────────────────

/-- The `'@'`-headed URN entry body — top-level so the equation lemmas
    exist (the `withNull` discipline: the inversion proofs reduce it via
    `parseUrnEntryBody.eq_1`). The row shape is the emitter's
    `Emit.Text.urnLine` (inverted by `parseUrnEntry_urnLine` below). -/
def parseUrnEntryBody : List Char → Option Proto.SimpleExtensionUrn
  | '@' :: rest =>
      match scanNat (rest.dropWhile (· == ' ')) with
      | some (a, r1) =>
        match expect Grammar.colonTok r1 with
        | some r2 => some { extensionUrnAnchor := a, urn := String.ofList (r2.drop 1) }
        | none => none
      | none => none
  | _ => none

/-- `@  1: urn` — a URN entry (anchors right-justified to width 3): skip
    leading spaces, then the body. -/
def parseUrnEntry (cs : List Char) : Option Proto.SimpleExtensionUrn :=
  parseUrnEntryBody (cs.dropWhile (· == ' '))

/-- The mid-entry `'@'` (the urn-reference separator of a declaration
    entry) — top-level for the equation lemmas. -/
def parseDeclEntryAt (kind : Grammar.ExtKind) (anchor : Nat) :
    List Char → Option Proto.ExtensionDeclaration
  | '@' :: r2 =>
      match scanNat (r2.dropWhile (· == ' ')) with
      | some (urnRef, r3) =>
        match expect Grammar.colonTok r3 with
        | some r4 => some (kind.toDecl urnRef anchor (String.ofList (r4.drop 1)))
        | none => none
      | none => none
  | _ => none

/-- The `'#'`-headed declaration entry body — top-level for the equation
    lemmas (inverted by `parseDeclEntry_declLine` below). -/
def parseDeclEntryBody (kind : Grammar.ExtKind) :
    List Char → Option Proto.ExtensionDeclaration
  | '#' :: rest =>
      match scanNat (rest.dropWhile (· == ' ')) with
      | some (anchor, r1) => parseDeclEntryAt kind anchor (r1.dropWhile (· == ' '))
      | none => none
  | _ => none

/-- `#  1 @  1: name` — a declaration entry, built via the shared
    `Grammar.ExtKind` table row. -/
def parseDeclEntry (kind : Grammar.ExtKind) (cs : List Char) : Option Proto.ExtensionDeclaration :=
  parseDeclEntryBody kind (cs.dropWhile (· == ' '))

/-- The extensions section: URN entries, then Functions/Types/Type
    Variations blocks. Returns the plan fields and the FnCtx. -/
def parseExtensions : List String → Option (List Proto.SimpleExtensionUrn × List Proto.ExtensionDeclaration × FnCtx × List String)
  | [] => none
  | l :: rest =>
    if l == Grammar.urnsHeader then
      let urns := rest.takeWhile (fun l => l.startsWith Grammar.urnEntryPfx)
      let urnVals := urns.map (parseUrnEntry ·.toList)
      if urnVals.any (· == none) then none
      else parseDeclBlocks [] [] (rest.length + 1) (rest.drop urns.length) |>.map fun (ds, rest') =>
        (urnVals.filterMap id, ds, fnCtxOf ds, rest')
    else parseDeclBlocks [] [] ((l :: rest).length + 1) (l :: rest) |>.map fun (ds, rest') =>
      ([], ds, fnCtxOf ds, rest')
where
  /-- The function declarations → (name, anchor) pairs — the FnCtx both
      sections build (one helper, used twice). -/
  fnCtxOf (ds : List Proto.ExtensionDeclaration) : FnCtx :=
    ds.filterMap fun d => match d with | .function _ a n => some (n, a) | _ => none
  /-- The block loop: the header line → its `Grammar.ExtKind` row (the SAME
      table the emitter's `kindSection` renders from), then that kind's
      entries. -/
  parseDeclBlocks (acc : List Proto.ExtensionDeclaration) (curKind : List Proto.ExtensionDeclaration) :
      Nat → List String → Option (List Proto.ExtensionDeclaration × List String)
    | 0, _ => none
    | bfuel + 1, l :: rest =>
      match Grammar.ExtKind.ofHeader l with
      | none => some (acc, l :: rest)
      | some k =>
          let es := rest.takeWhile (fun l => l.startsWith Grammar.declEntryPfx)
          let vs := es.map (parseDeclEntry k ·.toList)
          if vs.any (· == none) then none
          else parseDeclBlocks (acc ++ vs.filterMap id) curKind bfuel (rest.drop es.length)
    | _ + 1, [] => some (acc, [])

/-- The `=== Version X.Y.Z` header plus optional producer/git_hash lines. -/
def parseVersion : List String → Option (Proto.Version × List String)
  | l :: rest =>
    match expect Grammar.versionPfx l.toList with
    | some r1 =>
      match scanNat r1 with
      | some (mj, r2) => match expect Grammar.dotTok r2 with
        | some r3 => match scanNat r3 with
          | some (mn, r4) => match expect Grammar.dotTok r4 with
            | some r5 => match scanNat r5 with
              | some (pt, []) =>
                let producer := match rest with
                  | p :: _ =>
                    if p.startsWith Grammar.producerPfx then
                      [p.drop Grammar.producerPfx.length] else []
                  | _ => []
                let afterP := if producer.isEmpty then rest else rest.drop 1
                let git := match afterP with
                  | g :: _ =>
                    if g.startsWith Grammar.gitHashPfx then
                      [g.drop Grammar.gitHashPfx.length] else []
                  | _ => []
                let afterG := if git.isEmpty then afterP else afterP.drop 1
                some ({ majorNumber := mj, minorNumber := mn, patchNumber := pt
                      , producer := (producer.headD "").toString, gitHash := (git.headD "").toString }, afterG)
              | _ => none
            | none => none
          | none => none
        | none => none
      | none => none
    | none => none
  | [] => none

/-- The `Root[names]` line's name list (the `withClause` row shape: the
    emitter writes `kwRoot ++ sep sepTok (names.map name) ++ "]"`; the
    takeWhile strips the closing `]` — a quoted name containing `]` splits
    wrongly, the documented v0 limitation). Inverted by
    `parseRootNames_emitted` below. -/
def parseRootNames (cs : List Char) : Option (List String) :=
  let inner := (cs.drop Grammar.kwRoot.length).takeWhile (· ≠ ']')
  let names := (splitTopLevel inner 0 []).map fun item =>
    (scanName item).map (·.1)
  if names.any (· == none) then none else some (names.filterMap id)

/-- The `=== Plan` body: plan rels separated by blank lines. A `Root[…]`
    line takes an indented child (one `Grammar.indentUnit`). -/
def parsePlanRels (ctx : FnCtx) : Nat → List String → Option (List Proto.PlanRel)
  | _, [] => some []
  | 0, _ => none
  | fuel + 1, "" :: rest => parsePlanRels ctx fuel rest
  | fuel + 1, l :: rest =>
    if l.startsWith Grammar.kwRoot then
      match parseRootNames l.toList with
      | none => none
      | some names =>
        match parseRelTree ctx (rest.length + 1) Grammar.indentUnit.length rest with
        | some (input, rest') =>
          (parsePlanRels ctx fuel rest').map
            (.root names input :: ·)
        | none => none
    else
      match parseRelTree ctx (rest.length + 1) 0 (l :: rest) with
      | some (r, rest') => (parsePlanRels ctx fuel rest').map (.rel r :: ·)
      | none => none

/-- **The decoder**: text → `Proto.Plan`. The inverse of `Emit.Text.emit`
    (for plans whose rels are all in the grammar; the lossy spots — explicit
    `.direct` vs absent emit kinds, `advancedExtension`, unsorted extension
    declarations — are documented in the module doc). -/
def parsePlan (text : String) : Option Proto.Plan := do
  let lines := text.splitOn "\n"
  let lines := match lines.getLast? with
    | some "" => lines.dropLast
    | _ => lines
  let (version, rest1) := match lines with
    | l :: _ =>
      if l.startsWith Grammar.versionPfx then
        match parseVersion lines with
        | some (v, r) => (some v, r)
        | none => (none, lines)
      else (none, lines)
    | [] => (none, [])
  match rest1 with
  | l1 :: rest2 =>
    if l1 == Grammar.sectionExtensions then
      let (urns, decls, fctx, rest3) ← parseExtensions rest2
      let rest4 := match rest3 with | "" :: r => r | r => r
      match rest4 with
      | l2 :: rest5 =>
        if l2 == Grammar.sectionPlan then
          let rels ← parsePlanRels fctx (rest5.length + 1) rest5
          some { version, extensionUrns := urns, extensions := decls, relations := rels }
        else none
      | [] => none
    else if l1 == Grammar.sectionPlan then
      let rels ← parsePlanRels [] (rest2.length + 1) rest2
      some { version, extensionUrns := [], extensions := [], relations := rels }
    else none
  | [] => none

/-! ## relations: the inversion theorems (the last parser layer) -/

/- The relation layer is multi-line; the emitter (`Emit.Text.relLines`) writes
   indented lines and the parser (`parseRelTree`/`parseChildren`) recovers the
   indentation tree.  These theorems invert that layer for the well-formed
   fragment: Read (named table with a non-empty schema of plain-typed
   columns), Filter (a field-ref condition), Project (field-ref expressions),
   all with `common = none` (the documented lossiness — explicit emit
   mappings print identically to none and are canonicalized away). -/

/-- A character that `splitTopLevel` passes through unchanged (not the `, `
    separator and not a depth-tracked bracket). -/
def plainChar (c : Char) : Prop :=
  c ≠ ',' ∧ c ≠ '(' ∧ c ≠ ')' ∧ c ≠ '<' ∧ c ≠ '>' ∧ c ≠ '[' ∧ c ≠ ']'

/-- A char list all of whose chars are plain. -/
def Plain (cs : List Char) : Prop := ∀ c ∈ cs, plainChar c

-- The seven `plainChar` guards (`,` `(` `)` `<` `>` `[` `]`) are used as the
-- raw conjunction projections `h.1`, `h.2.1`, … at the split sites below.

/-- A plain char has `c == '(' = false`, etc. (the depth tests fail). -/
private theorem plain_beq_open (c : Char) (h : plainChar c) :
    (c == '(' || c == '<' || c == '[') = false := by
  have h1 : (c == '(') = false := by
    apply Bool.eq_false_iff.mpr
    intro j
    exact h.2.1 (beq_iff_eq.mp j)
  have h2 : (c == '<') = false := by
    apply Bool.eq_false_iff.mpr
    intro j
    exact h.2.2.2.1 (beq_iff_eq.mp j)
  have h3 : (c == '[') = false := by
    apply Bool.eq_false_iff.mpr
    intro j
    exact h.2.2.2.2.2.1 (beq_iff_eq.mp j)
  rw [h1, h2, h3]
  rfl

/-- A plain char has `c == ')' = false`, etc. (the close tests fail). -/
private theorem plain_beq_close (c : Char) (h : plainChar c) :
    (c == ')' || c == '>' || c == ']') = false := by
  have h1 : (c == ')') = false := by
    apply Bool.eq_false_iff.mpr
    intro j
    exact h.2.2.1 (beq_iff_eq.mp j)
  have h2 : (c == '>') = false := by
    apply Bool.eq_false_iff.mpr
    intro j
    exact h.2.2.2.2.1 (beq_iff_eq.mp j)
  have h3 : (c == ']') = false := by
    apply Bool.eq_false_iff.mpr
    intro j
    exact h.2.2.2.2.2.2 (beq_iff_eq.mp j)
  rw [h1, h2, h3]
  rfl

/-- A plain prefix is accumulated into `cur` by `splitTopLevel` (no splits
    at depth 0, no depth changes). -/
theorem splitTopLevel_plain_prefix (x rest cur : List Char) (hplain : Plain x) :
    splitTopLevel (x ++ rest) 0 cur = splitTopLevel rest 0 (x.reverse ++ cur) := by
  induction x generalizing cur with
  | nil => simp
  | cons c cs ih =>
    have hp := hplain c (by simp)
    have hcs : Plain cs := by
      intro a ha
      exact hplain a (by simp [ha])
    rw [List.cons_append]
    rw [splitTopLevel.eq_3 0 cur c (cs ++ rest) (by
      intro rest' h0 hc hrest
      exact (hp.1 hc).elim)]
    rw [plain_beq_open c hp, plain_beq_close c hp]
    simp
    rw [ih (c :: cur) hcs]

/-- `splitTopLevel` on a lone `]` just accumulates it (the depth saturates
    at 0 for Nat subtraction). -/
theorem splitTopLevel_rbracket_cur (cur : List Char) :
    splitTopLevel [']'] 0 cur = [cur.reverse ++ [']']] := by
  rw [splitTopLevel.eq_3 0 cur ']' [] (by
    intro rest' h0 hc hrest
    cases hrest)]
  have hbr := show (']' == '(' || ']' == '<' || ']' == '[') = false by decide
  have hbc := show (']' == ')' || ']' == '>' || ']' == ']') = true by decide
  rw [hbr, hbc]
  simp
  rw [splitTopLevel.eq_1 0 (']' :: cur)]
  simp [List.reverse_cons]

/-- A single plain item followed by `]` stays one item (the `]` merges in). -/
theorem splitTopLevel_plain_rbracket (x : List Char) (hplain : Plain x) :
    splitTopLevel (x ++ [']']) 0 [] = [x ++ [']']] := by
  rw [splitTopLevel_plain_prefix x [']'] [] hplain]
  simp
  rw [splitTopLevel_rbracket_cur x.reverse]
  simp [List.reverse_reverse]

/-- A plain head followed by the `, ` separator splits off the head. -/
theorem splitTopLevel_comma_head (x rest : List Char) (hplain : Plain x) :
    splitTopLevel (x ++ ([',', ' '] ++ rest)) 0 [] = x :: splitTopLevel rest 0 [] := by
  rw [splitTopLevel_plain_prefix x ([',', ' '] ++ rest) [] hplain]
  change splitTopLevel (',' :: ' ' :: rest) 0 (x.reverse ++ []) = x :: splitTopLevel rest 0 []
  rw [splitTopLevel.eq_2 (x.reverse ++ []) rest]
  simp [List.reverse_reverse]

/-- `splitTopLevel` over the joined items: the head goes to the result, the
    last item absorbs the tail (`]`). -/
def splitAppend (xss : List (List Char)) (tail : List Char) : List (List Char) :=
  match xss with
  | [] => []
  | [x] => [x ++ tail]
  | x :: rest => x :: splitAppend rest tail

/-- The rendered `name:type` column text. -/
def colText (n b : String) : String := Emit.Text.name n ++ ":" ++ b

/-- **The named-column inversion**: `name:type` scans back to the name and
    the parsed type (the type text is consumed via the length-fuel
    inversion). -/
theorem parseNamedCol_emitted (n : String) (t : Proto.PType) (b : String)
    (rest : List Char) (hemit : Emit.Text.typeText t = .ok b)
    (hrest : rest.head? ≠ some '?') :
    parseNamedCol ((colText n b).toList ++ rest) = some (n, t, rest) := by
  unfold parseNamedCol colText
  rw [String.toList_append, String.toList_append]
  -- scanName ((name n).toList ++ ":".toList ++ b.toList ++ rest)
  have hsc' : scanName ((Emit.Text.name n).toList ++ (":".toList ++ (b.toList ++ rest))) =
      some (n, ":".toList ++ (b.toList ++ rest)) := by
    have hs := scanName_name n (":".toList ++ (b.toList ++ rest))
      (Or.inr ⟨':', b.toList ++ rest, rfl, by decide⟩)
    exact hs
  -- normalize the goal's left-nested append chain to the hsc' form
  have hassoc : (Emit.Text.name n).toList ++ ":".toList ++ b.toList ++ rest =
      (Emit.Text.name n).toList ++ (":".toList ++ (b.toList ++ rest)) := by
    simp [List.append_assoc]
  rw [hassoc]
  rw [hsc']
  -- the match over `some` reduces
  -- reduce the outer match (the scanName result is some), then the expect
  -- match, then the type inversion; the final map over some reduces by rfl
  dsimp only
  rw [expect_self ":" (b.toList ++ rest)]
  simp only []
  rw [parseType_len_invert t b rest hrest hemit]
  rfl

/-- The `, `-joined column text of a column list. -/
def colsText (cols : List (String × String)) : String :=
  Emit.Text.sep ", " (cols.map (fun x => colText x.1 x.2))

/-- Elementwise inversion of `splitAppend`: the i-th element of the result
    is the i-th input, extended by `tail` exactly at the last index. -/
theorem splitAppend_getElem? : ∀ (xss : List (List Char)) (tail : List Char)
    (i : Nat) (hi : i < xss.length),
    (splitAppend xss tail)[i]? = some (xss[i]'hi ++ if i = xss.length - 1 then tail else []) := by
  intro xss
  induction xss with
  | nil => intro tail i hi; simp at hi
  | cons x rest ih =>
      intro tail i hi
      cases rest with
      | nil =>
          have hi' : i < 1 := by simpa using hi
          have hi0 : i = 0 := by omega
          subst i
          simp [splitAppend]
      | cons y rest' =>
          cases i with
          | zero =>
              simp [splitAppend]
          | succ j =>
              have hj : j < (y :: rest').length := Nat.lt_of_succ_lt_succ hi
              have hiff :
                  (j + 1 = (x :: y :: rest').length - 1 ↔
                   j = (y :: rest').length - 1) := by
                have hlen : (x :: y :: rest').length = (y :: rest').length + 1 := by
                  simp [List.length_cons]
                have hgt0 : 0 < (y :: rest').length := by simp
                constructor
                · intro h; omega
                · intro h; omega
              have hc : (y :: rest')[j]'hj = (x :: y :: rest')[j+1]'hi := by
                rw [List.getElem_cons_succ]
              have hif : (if j = (y :: rest').length - 1 then tail else []) =
                  (if j + 1 = (x :: y :: rest').length - 1 then tail else []) := by
                by_cases hJ : j = (y :: rest').length - 1
                · have hpos : j + 1 = (x :: y :: rest').length - 1 := hiff.mpr hJ
                  simp [hJ]
                · have hnj : ¬ j + 1 = (x :: y :: rest').length - 1 := by
                    intro h
                    exact hJ (hiff.mp h)
                  simp
              simp only [splitAppend, List.getElem?_cons_succ]
              rw [ih tail j hj]
              rw [hc]
              rw [hif]

/-- The map over a column list, positioned: the i-th mapped element is the
    `colText` of the i-th `(name, b)` pair. -/
theorem colTexts_getElem (cols : List (String × String)) (i : Nat)
    (h : i < cols.length) (h' : i < (cols.map (fun x => (colText x.1 x.2).toList)).length) :
    (cols.map (fun x => (colText x.1 x.2).toList))[i]'h' =
      (colText (cols[i]'h).1 (cols[i]'h).2).toList := by
  simp [List.getElem_map]

/-- **The column-list inversion** (indexed restate): the `, `-joined column
    texts, `splitAppend`-ed with the trailing `]` of the header close, parse
    back to the per-column `(name, type, rest)` triples, where the rest is
    `[']']` exactly at the last index and `[]` elsewhere. – The original draft
    stated this by value equality (`rest = …`), which needs
    `DecidableEq Proto.PType` (mutual inductives don't derive it on this
    toolchain); the indexed formulation with `i = cols.length - 1` dodges it
    entirely. -/
theorem splitAppend_map_parseNamedCol
    (cols : List (String × String))
    (htype : ∀ x ∈ cols, ∃ t : Proto.PType, Emit.Text.typeText t = .ok x.2)
    (i : Nat) (hi : i < cols.length) :
    ((splitAppend (cols.map (fun x => (colText x.1 x.2).toList)) [']']).map parseNamedCol)[i]?
      = some (some ((cols[i]'hi).1,
          (htype (cols[i]'hi) (List.getElem_mem (l := cols) hi)).choose,
          if i = cols.length - 1 then [']'] else [])) := by
  let texts : List (List Char) := cols.map (fun x => (colText x.1 x.2).toList)
  have hlen : texts.length = cols.length := by simp [texts]
  have hlen' : texts.length - 1 = cols.length - 1 := by omega
  have hcond : (i = texts.length - 1 ↔ i = cols.length - 1) := by
    constructor
    · intro h; omega
    · intro h; omega
  have htext : texts[i]'(by simpa [hlen] using hi) =
      (colText (cols[i]'hi).1 (cols[i]'hi).2).toList := by
    simp [texts]
  by_cases hlast : i = cols.length - 1
  · let t : Proto.PType := (htype (cols[i]'hi) (List.getElem_mem (l := cols) hi)).choose
    have hemit : Emit.Text.typeText t = .ok (cols[i]'hi).2 :=
      (htype (cols[i]'hi) (List.getElem_mem (l := cols) hi)).choose_spec
    have hlteq : i = texts.length - 1 := hcond.2 hlast
    rw [List.getElem?_map]
    rw [splitAppend_getElem? texts [']'] i (by simpa [hlen] using hi)]
    simp only [Option.map_some]
    rw [if_pos hlteq]
    rw [htext]
    rw [parseNamedCol_emitted (cols[i]'hi).1 t (cols[i]'hi).2 [']'] hemit (by decide)]
    rw [if_pos hlast]
  · -- the not-last column: the rest is `[]`
    let t : Proto.PType := (htype (cols[i]'hi) (List.getElem_mem (l := cols) hi)).choose
    have hemit : Emit.Text.typeText t = .ok (cols[i]'hi).2 :=
      (htype (cols[i]'hi) (List.getElem_mem (l := cols) hi)).choose_spec
    have hnotlteq : ¬ i = texts.length - 1 := by
      intro h
      exact hlast (hcond.1 h)
    rw [List.getElem?_map]
    rw [splitAppend_getElem? texts [']'] i (by simpa [hlen] using hi)]
    simp only [Option.map_some]
    rw [if_neg hnotlteq]
    rw [htext]
    rw [parseNamedCol_emitted (cols[i]'hi).1 t (cols[i]'hi).2 [] hemit (by simp)]
    rw [if_neg hlast]

-- ── the bindings/line-shape inversions (W5.3 phase 2b) ────────────────────

/-- The emitter's space repetition, list-form. -/
private theorem replicate_space (k : Nat) :
    (Emit.Text.replicate " " k).toList = List.replicate k ' ' := by
  have hs : " ".toList = [' '] := by decide
  rw [Emit.Text.replicate, String.toList_join, List.flatMap_replicate, hs,
    List.flatten_replicate_singleton]

/-- The right-justified anchor field, space-stripped, with a tail: the
    padding is exactly the leading-space run the decoder's `dropWhile`
    consumes, leaving the digits.  PUBLIC: the generated row inversions
    (Substrait.Decode.Inversions — `declare_inversion`) consume it across
    the module boundary. -/
theorem rightJustify_dropWhile_append (a : Nat) (tail : List Char) :
    ((Emit.Text.rightJustify 3 a).toList ++ tail).dropWhile (· == ' ') =
      (toString a).toList ++ tail := by
  unfold Emit.Text.rightJustify
  by_cases h : (toString a).length ≥ 3
  · rw [if_pos h]
    cases hs : (toString a).toList with
    | nil => exact (toString_toList_ne_nil a hs).elim
    | cons c cs =>
      rw [List.cons_append, List.dropWhile_cons_of_neg]
      have hd := toString_head_isDigit a c cs hs
      intro hc
      rw [beq_iff_eq.mp hc] at hd
      exact absurd hd (by decide)
  · rw [if_neg h, String.toList_append, replicate_space, List.append_assoc]
    rw [List.dropWhile_append_of_pos (fun x hx => by
      rw [List.mem_replicate] at hx
      rw [hx.2]
      rfl)]
    cases hs : (toString a).toList with
    | nil => exact (toString_toList_ne_nil a hs).elim
    | cons c cs =>
      rw [List.cons_append, List.dropWhile_cons_of_neg]
      have hd := toString_head_isDigit a c cs hs
      intro hc
      rw [beq_iff_eq.mp hc] at hd
      exact absurd hd (by decide)

/-- `expect colonTok` on a literal `:` head (public: consumed by the
    generated row inversions across the module boundary). -/
theorem expect_colon (rest : List Char) :
    expect Grammar.colonTok (':' :: rest) = some rest :=
  expect_cons_tok Grammar.colonTok [':'] rest (by decide)

/-- `expect dotTok` on a literal `.` head (public: consumed by the
    generated row inversions across the module boundary). -/
theorem expect_dot (rest : List Char) :
    expect Grammar.dotTok ('.' :: rest) = some rest :=
  expect_cons_tok Grammar.dotTok ['.'] rest (by decide)

/-- The version dots' tail is not a digit (scanNat stops there).  These
    stop lemmas are PUBLIC: the generated row inversions choose them from
    the segment right after an anchor/number. -/
theorem notDigitHead_dot (rest : List Char) : notDigitHead ('.' :: rest) :=
  Or.inr ⟨'.', rest, rfl, by decide⟩

/-- The entry colon tail is not a digit. -/
theorem notDigitHead_colon (rest : List Char) : notDigitHead (':' :: rest) :=
  Or.inr ⟨':', rest, rfl, by decide⟩

/-- The `" @"` separator tail is not a digit. -/
theorem notDigitHead_space (rest : List Char) : notDigitHead (' ' :: rest) :=
  Or.inr ⟨' ', rest, rfl, by decide⟩

/-- A prefix-glued line starts with its prefix (`String.startsWith` bridge
    to the list prefix relation). -/
theorem startsWith_append (pre s : String) : (pre ++ s).startsWith pre = true := by
  rw [String.startsWith_string_iff, String.toList_append]
  exact ⟨s.toList, rfl⟩

/-- A prefix clash at a concrete index: the pattern's `i`-th char differs
    from the target's, so no prefix relation. -/
private theorem not_prefix_of_getElem_clash {p s : List Char} {i : Nat} {c d : Char}
    (hp : p[i]? = some c) (hs : s[i]? = some d) (hcd : c ≠ d) : ¬ p <+: s := by
  rintro ⟨t, ht⟩
  obtain ⟨hlt, -⟩ := List.getElem?_eq_some_iff.mp hp
  have h := congrArg (fun l => l[i]?) ht
  rw [List.getElem?_append_left hlt, hp, hs] at h
  exact hcd (Option.some.inj h)

/-- The producer/git prefixes clash at the third char (`p` vs `g`): a
    `git_hash` line is never mistaken for a `producer` line. -/
theorem gitHash_ne_producerPfx (s : String) :
    (Grammar.gitHashPfx ++ s).startsWith Grammar.producerPfx = false := by
  rw [String.startsWith_string_eq_false_iff]
  exact not_prefix_of_getElem_clash (i := 2) (c := 'p') (d := 'g') (by decide)
    (by
      rw [String.toList_append,
        show Grammar.gitHashPfx.toList = [' ', ' ', 'g', 'i', 't', '_', 'h', 'a', 's', 'h', ':', ' ']
          from by decide]
      rfl)
    (by decide)

/-- Dropping a string prefix at the Slice level recovers the suffix
    (`parseVersion`'s `p.drop pfx.length` reads; the count is stated
    separately so length-normalizing simp sets can instantiate it). -/
theorem dropPrefix_copy (pre s : String) (n : Nat) (hn : n = pre.length) :
    ((pre ++ s).drop n).copy = s := by
  apply String.toList_inj.mp
  rw [String.toList_copy_drop, String.toList_append, hn]
  exact List.drop_left


-- ── the Root-names inversion (W5.3 phase 2b — the `withClause` row shape) ──

/-- Alpha characters differ from any non-alpha character (the bracket/
    separator targets are all non-alpha). -/
private theorem isAlpha_ne (c t : Char) (hc : c.isAlpha = true) (ht : t.isAlpha = false) :
    c ≠ t := by
  intro e
  rw [e] at hc
  rw [ht] at hc
  exact absurd hc (by decide)

/-- Digit characters differ from any non-digit character. -/
private theorem isDigit_ne (c t : Char) (hc : c.isDigit = true) (ht : t.isDigit = false) :
    c ≠ t := by
  intro e
  rw [e] at hc
  rw [ht] at hc
  exact absurd hc (by decide)

/-- An identifier character is `plainChar` (no `splitTopLevel` split, no
    depth change, and not the header-closing `]`). -/
private theorem isIdentChar_plain {c : Char} (h : Emit.Text.isIdentChar c = true) :
    plainChar c := by
  unfold Emit.Text.isIdentChar at h
  rw [Bool.or_eq_true, Bool.or_eq_true] at h
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;>
    rcases h with (hα | hd) | hu
  · exact isAlpha_ne c _ hα (by decide)
  · exact isDigit_ne c _ hd (by decide)
  · rw [beq_iff_eq.mp hu]; decide
  · exact isAlpha_ne c _ hα (by decide)
  · exact isDigit_ne c _ hd (by decide)
  · rw [beq_iff_eq.mp hu]; decide
  · exact isAlpha_ne c _ hα (by decide)
  · exact isDigit_ne c _ hd (by decide)
  · rw [beq_iff_eq.mp hu]; decide
  · exact isAlpha_ne c _ hα (by decide)
  · exact isDigit_ne c _ hd (by decide)
  · rw [beq_iff_eq.mp hu]; decide
  · exact isAlpha_ne c _ hα (by decide)
  · exact isDigit_ne c _ hd (by decide)
  · rw [beq_iff_eq.mp hu]; decide
  · exact isAlpha_ne c _ hα (by decide)
  · exact isDigit_ne c _ hd (by decide)
  · rw [beq_iff_eq.mp hu]; decide
  · exact isAlpha_ne c _ hα (by decide)
  · exact isDigit_ne c _ hd (by decide)
  · rw [beq_iff_eq.mp hu]; decide

/-- The emitter's `name` of an identifier is the identifier. -/
private theorem name_of_identifier {n : String} (h : Emit.Text.isIdentifier n = true) :
    Emit.Text.name n = n := by
  unfold Emit.Text.name
  rw [if_pos h]

/-- All chars of an identifier's emitted name are plain. -/
private theorem identChars_plain {n : String} (h : Emit.Text.isIdentifier n = true) :
    Plain (Emit.Text.name n).toList := by
  rw [name_of_identifier h]
  unfold Emit.Text.isIdentifier at h
  intro a ha
  cases hnl : n.toList with
  | nil => rw [hnl] at h; simp at h
  | cons c rest =>
    rw [hnl] at h
    simp only [Bool.and_eq_true] at h
    obtain ⟨hc, htail⟩ := h
    rw [hnl] at ha
    rcases List.mem_cons.mp ha with rfl | hin
    · exact isIdentChar_plain (by unfold Emit.Text.isIdentChar; rw [hc]; rfl)
    · exact isIdentChar_plain (List.all_eq_true.mp htail a hin)

/-- The name map over identifiers is the identity. -/
private theorem map_name_of_identifiers {names : List String}
    (h : ∀ n ∈ names, Emit.Text.isIdentifier n = true) :
    names.map Emit.Text.name = names := by
  induction names with
  | nil => rfl
  | cons x xs ih =>
    rw [List.map_cons, name_of_identifier (h x (by simp)),
      ih (fun y hy => h y (by simp [hy]))]

/-- If every string in a list and the separator all avoid a char, the
    `sep`-joined text avoids it. -/
private theorem sep_all_ne {d : String} {xs : List String} {c : Char}
    (hd : ∀ a ∈ d.toList, a ≠ c) (hxs : ∀ x ∈ xs, ∀ a ∈ x.toList, a ≠ c) :
    ∀ a ∈ (Emit.Text.sep d xs).toList, a ≠ c := by
  induction xs with
  | nil =>
    intro a ha
    have h1 : (Emit.Text.sep d ([] : List String)) = "" := by
      simp [Emit.Text.sep, String.intercalate_nil]
    rw [h1] at ha
    simp at ha
  | cons x xs ih =>
    intro a ha
    cases xs with
    | nil =>
      have h1 : Emit.Text.sep d [x] = x := by
        simp [Emit.Text.sep, String.intercalate_singleton]
      rw [h1] at ha
      exact hxs x (by simp) a ha
    | cons y ys =>
      have h1 : Emit.Text.sep d (x :: y :: ys) = x ++ d ++ Emit.Text.sep d (y :: ys) :=
        sep_cons d x (by simp)
      rw [h1, String.toList_append, String.toList_append] at ha
      have h2 := List.mem_append.mp ha
      rcases h2 with hx2 | hrest
      · have h3 := List.mem_append.mp hx2
        rcases h3 with hxx | hdd
        · exact hxs x (by simp) a hxx
        · exact hd a hdd
      · exact ih (fun z hz => hxs z (by simp [hz])) a hrest

/-- No `]` inside the `sep`-joined identifier names (the takeWhile boundary
    is exactly the header close). -/
private theorem sep_identifiers_ne_rbracket {names : List String}
    (h : ∀ n ∈ names, Emit.Text.isIdentifier n = true) :
    ∀ a ∈ (Emit.Text.sep Grammar.sepTok (names.map Emit.Text.name)).toList, a ≠ ']' := by
  apply sep_all_ne (by decide)
  intro x hx
  rw [List.mem_map] at hx
  obtain ⟨n, hn, rfl⟩ := hx
  intro a ha
  exact (identChars_plain (h n hn) a ha).2.2.2.2.2.2

/-- A lone plain item splits to itself. -/
private theorem splitTopLevel_single_plain (x : List Char) (hx : Plain x) :
    splitTopLevel x 0 [] = [x] := by
  have h := splitTopLevel_plain_prefix x ([] : List Char) [] hx
  rw [List.append_nil] at h
  rw [h]
  rw [splitTopLevel.eq_1]
  simp

/-- `splitTopLevel` over the joined identifier names recovers the names'
    char lists (nonempty — the empty join splits to `[[]]`, the empty-item
    corner). -/
private theorem splitTopLevel_identifiers {names : List String}
    (h : ∀ n ∈ names, Emit.Text.isIdentifier n = true) :
    names ≠ [] →
    splitTopLevel (Emit.Text.sep Grammar.sepTok (names.map Emit.Text.name)).toList 0 [] =
      names.map (·.toList) := by
  rw [map_name_of_identifiers h]
  induction names with
  | nil => intro hne; exact (hne rfl).elim
  | cons x xs ih =>
    intro _
    cases xs with
    | nil =>
      have hsep : Emit.Text.sep Grammar.sepTok [x] = x := by
        simp [Emit.Text.sep, String.intercalate_singleton]
      rw [hsep]
      rw [splitTopLevel_single_plain x.toList (by
        have hxp := identChars_plain (h x (by simp))
        rw [name_of_identifier (h x (by simp))] at hxp
        exact hxp)]
      rfl
    | cons y ys =>
      have hsep : Emit.Text.sep Grammar.sepTok (x :: y :: ys) =
          x ++ Grammar.sepTok ++ Emit.Text.sep Grammar.sepTok (y :: ys) :=
        sep_cons Grammar.sepTok x (by simp)
      rw [hsep, String.toList_append, String.toList_append]
      rw [show Grammar.sepTok.toList = [',', ' '] from by decide]
      rw [List.append_assoc]
      rw [splitTopLevel_comma_head x.toList _ (by
        have hxp := identChars_plain (h x (by simp))
        rw [name_of_identifier (h x (by simp))] at hxp
        exact hxp)]
      rw [ih (fun z hz => h z (by simp [hz])) (by simp)]
      rfl

/-- An identifier's bare text scans back to it (the `rest = []` form of
    `scanName_name`). -/
private theorem scanName_ident_self {n : String} (h : Emit.Text.isIdentifier n = true) :
    (scanName n.toList).map (·.1) = some n := by
  have h1 := scanName_name n ([] : List Char) (Or.inl rfl)
  rw [name_of_identifier h, List.append_nil] at h1
  rw [h1]
  rfl

/-- takeWhile over the header-closing `]`: a `]`-free inner text is kept,
    the close is dropped. -/
private theorem takeWhile_rbracket_stop (inner tail : List Char)
    (h : ∀ a ∈ inner, a ≠ ']') :
    (inner ++ ']' :: tail).takeWhile (· ≠ ']') = inner := by
  rw [List.takeWhile_append_of_pos (fun a ha => by
    have h' := h a ha
    -- the code's predicate is `fun x => decide (x ≠ ']')`
    show (decide (a ≠ ']')) = true
    rw [decide_eq_true_eq]
    exact h')]
  rw [List.takeWhile_cons_of_neg (by decide)]
  rw [List.append_nil]

/-- **The Root-name inversion** (`parse (emit x) = some x` for the
    `withClause` row shape): the emitter's `Root[n, …]` line yields the
    names back, for nonempty bare-identifier name lists (empty `Root[]` is
    rejected by the decoder, and a quoted name containing `]` splits wrongly
    — both documented v0 limitations at `parseRootNames`). -/
theorem parseRootNames_emitted (names : List String) (hne : names ≠ [])
    (hident : ∀ n ∈ names, Emit.Text.isIdentifier n = true) :
    parseRootNames ((Grammar.kwRoot ++ Emit.Text.sep Grammar.sepTok (names.map Emit.Text.name) ++
      "]").toList) = some names := by
  have hdrop : ((Grammar.kwRoot ++ Emit.Text.sep Grammar.sepTok (names.map Emit.Text.name) ++
        "]").toList.drop Grammar.kwRoot.length) =
      (Emit.Text.sep Grammar.sepTok (names.map Emit.Text.name)).toList ++ [']'] := by
    repeat rw [String.toList_append]
    rw [show ("]" : String).toList = [']'] from by decide]
    rw [List.append_assoc]
    exact List.drop_left
  unfold parseRootNames
  rw [hdrop]
  rw [takeWhile_rbracket_stop _ [] (fun a ha => sep_identifiers_ne_rbracket hident a ha)]
  simp only []
  rw [splitTopLevel_identifiers hident hne]
  have hmap : ((names.map (·.toList)).map fun item => (scanName item).map (·.1)) =
      names.map (fun n => (some n : Option String)) := by
    rw [List.map_map]
    apply List.map_congr_left
    intro x hx
    exact scanName_ident_self (hident x hx)
  rw [hmap]
  have hany : (names.map (fun n => (some n : Option String))).any (· == none) = false := by
    rw [List.any_eq_false]
    intro x hx
    rw [List.mem_map] at hx
    obtain ⟨y, -, rfl⟩ := hx
    have hb : ((some y : Option String) == none) = false := by rfl
    rw [hb]
    exact (by decide : ¬ (false = true))
  rw [hany]
  have hfilter : (names.map (fun n => (some n : Option String))).filterMap id = names := by
    induction names with
    | nil => rfl
    | cons x xs ih => simp [ih]
  rw [hfilter]
  rfl

-- ── the typed layer: Proto.Expression → Typed.Expr ──────────────────────

/-!

The wire → typed direction: `Proto.Expression` (what the wire/text carries)
decoded back into the schema-indexed `Substrait.Typed.Expr` GADT — the
inverse of `Typed.Expr.toProto` / `Typed.Args.toProto`.

Deliberate exclusions (the typed grammar has no syntax for them):
- `ifThen` / `cast` / `subquery`: `Typed.Expr` has only `literal`, `field`,
  `call` — the composite proto forms decode to `none`.
- `.null` literal payloads: `LiteralValue` has no null constructor.
- `userDefined` output types: the wire carries an anchor; recovering the
  `(urn, name)` pair needs a type registry the decode context (functions
  only) does not have — `stOfPType` returns `none`.
- `segment != none` field refs: the text grammar has no segment rule and the
  typed layer never produces one.
- `deterministic` / `sessionDependent` sig metadata: `Expr.toProto` erases
  both; decode reconstructs `deterministic := true`, `sessionDependent :=
  false`.  The round-trip statements compare at the Proto level (re-lowering
  the decoded expression), where the erasure is invisible.

Anchors: the decode-side function context `FnInv` is `(anchor, urn, name)`
triples — `fnInvOf` inverts `ExtCtx`'s 1-based `indexOf1` anchoring.

-/


end Substrait.Decode

end -- @[expose] public section
