-- GENERATED by scaffold (lean-4.33.0) at - — DO NOT EDIT
-- spec scaffold-golden | AppSpec DemoApp | 4 item(s) | content hash 12626047967700436582 | regen: just gen; drift fails CI
/-
# DemoApp.Reg — the generated registration module (Scaffold)

Generated from the AppSpec VALUE `Scaffold.AppSpec` (Scaffold.Spec —
the spec of record). The GENERATED header above is the
@[derived]-equivalent stamp (01 §5): the content hash is the
byte-tie anchor; DO NOT EDIT by hand — regen is a deliberate,
commit-visible act.

Five questions (notes/v3/01-core.md), filled from the AppSpec:
- root: crossing
- carrier grade: the lane item over the registry's nodup-in-type substrate
- spine reading: registration = append; the emitters fold the replay
- ladder rung: generated
- gate row: axioms, docs-check
Consumes (the schema registry refs): Order
Capabilities generated: registry-lane, emitter, diagnostics, tests
-/

import Kit.Lane

namespace DemoApp

/-! ## The lane item + the registration (capability: registry-lane, R3) -/

/-- The lane's item type: the skeleton's seed shape (the consumer
    widens the fields; the naming fn below pins the lookup key). -/
structure DemoAppItem where
  name : String
  weight : Nat
deriving Inhabited, Repr, BEq

-- The lane registration (Kit.Lane's ONE kit call — the env
-- extension + the attribute mount; the accessors, the fold hook
-- and the registry derive from the base name).
register_lane DemoAppItem where
  naming := fun it => it.name

end DemoApp
