# Verification recipes

# Full check: tests, clippy, fmt, typos, secrets.
check: test clippy fmt typos secrets

# nextest is the default runner. nextest does not run doctests —
# they run separately (flatland pattern).
test:
	cargo nextest run && cargo test --doc

clippy:
	cargo clippy --all-targets
	cargo clippy --all-targets --all-features

fmt:
	cargo fmt --check

# Everything formatter: rustfmt + dprint (treefmt.toml + .dprint.json).
format:
	treefmt

# Spell-check (typos.toml).
typos:
	typos

# Secret scanner (ripsecrets).
secrets:
	ripsecrets

# Auto-fix lint/format findings (separate target dir, no -Zthreads).
fix:
	cargo-clippy-fix
	cargo fmt

clippy-fix:
	cargo-clippy-fix

# Dependency hygiene
deny:
	cargo deny check

outdated:
	cargo outdated

machete:
	cargo machete

# Mutation testing (pass a module name: just mutants foo)
mutants name:
	cargo mutants -f {{name}}

# ── Codegen loop (buf-style: watched = same command, wrapped) ────────
# `gen`/`check`/`breaking` run identically in CI and in watchers. The
# watcher never changes what runs, only when.

# Fast type-check only, no emission (buf lint analog).
check-schema:
	@echo "TODO: guestlangc check"

# Schema-compat diff vs last released schema (buf breaking analog).
breaking:
	@echo "TODO: schema diff"

# Watchers — watchexec wraps the SAME commands, no redefinition.
# --restart: kill in-flight gen on new save (codegen is idempotent).
watch-gen:
	watchexec -r -w lean -e lean -- just gen

# Host restart on generated OUTPUTS + host code (not lean/ — the gen
# write into src/generated is what triggers this, one write per change).
watch-host:
	watchexec -r -w src -w wit -- cargo run

# Fast schema check without emission.
watch-check:
	watchexec -w lean -e lean -- just check-schema

# Property/fuzz ingress boundary tests (bolero). Corpora live in
# devenv state (DEVENV_STATE/bolero-corpus).
fuzz name:
	cargo bolero run {{name}}

# ── WASM guest component (wasip3, via wasm-component-ld + wasi-sdk sysroot) ──
wasm-guest:
	#!/usr/bin/env bash
	set -euo pipefail
	RUSTFLAGS="$RUSTFLAGS_WASIP3" cargo build -p guest-demo \
	  --target targets/wasm32-wasip3-local.json \
	  -Z build-std=std,panic_abort \
	  -Z json-target-spec
	echo "component: target/wasm32-wasip3-local/debug/guest_demo.wasm"
	wasm-tools validate target/wasm32-wasip3-local/debug/guest_demo.wasm
	echo "wasm-tools validate: clean"

# ── Proper component with lifted exports (host-embedder input) ──────
# The wasip3 linker wraps the core module (no raw core artifact on disk to
# embed WIT into), so the pure-export core module is built with
# wasm32-unknown-unknown (guest-demo uses no WASI), the world is embedded
# with `component embed`, and `component new` lifts the exports.
wasm-guest-component:
	#!/usr/bin/env bash
	set -euo pipefail
	RUSTFLAGS="$RUSTFLAGS_WASM32" cargo build -p guest-demo \
	  --target wasm32-unknown-unknown \
	  -Z build-std=std,panic_abort
	core=target/wasm32-unknown-unknown/debug/guest_demo.wasm
	embedded=target/wasm32-unknown-unknown/debug/guest_demo.embedded.wasm
	out=target/wasm32-unknown-unknown/debug/guest_demo.component.wasm
	wasm-tools component embed crates/guest-demo/guest-demo.wit "$core" -o "$embedded"
	wasm-tools component new "$embedded" -o "$out"
	wasm-tools validate "$out"
	echo "component: $out"
	wasm-tools component wit "$out"

# Gateway world component: the SSOT wit/gateway.wit (GENERATED by
# schema-lang) — guest-demo implements it via wit-bindgen, which embeds the
# component-type section, so `component new` lifts directly. watch-orders
# uses the wasi 0.3 async ABI (`async func` in WIT).
wasm-guest-gateway:
	#!/usr/bin/env bash
	set -euo pipefail
	RUSTFLAGS="$RUSTFLAGS_WASM32" cargo build -p guest-demo \
	  --target wasm32-unknown-unknown \
	  -Z build-std=std,panic_abort
	core=target/wasm32-unknown-unknown/debug/guest_demo.wasm
	out=target/wasm32-unknown-unknown/debug/guest_demo.gateway.component.wasm
	# Needs a wasm-tools CLI matching wit-bindgen 0.61's wit-component (0.258):
	# the async canonical-lift encoding predates nixpkgs' 1.256.
	WT="$HOME/.local/guestlang-tools/bin/wasm-tools"
	[ -x "$WT" ] || WT=wasm-tools
	"$WT" component new "$core" -o "$out"
	"$WT" validate "$out"
	echo "component: $out"
	"$WT" component wit "$out" | grep -E 'get-user|watch-orders'

# ── WASM compile checks (nightly + rust-src required) ────────────────
# RUSTFLAGS_WASIP3/RUSTFLAGS_WASM32 strip host-only flags (target-cpu=native,
# -Z*); these are the real gates for "does it build for wasm" without a link.
check-wasip3:
	RUSTFLAGS="$RUSTFLAGS_WASIP3" cargo check --target wasm32-wasip3 -Z build-std=std,panic_abort

check-wasm:
	RUSTFLAGS="$RUSTFLAGS_WASM32" cargo check --target wasm32-unknown-unknown

# ── Lean workspace (packages in dependency order) ────────────────────
# elan shims broken — invoke toolchain bin directly.
lean_tc := home_dir() / ".elan" / "toolchains" / "leanprover--lean4---v4.33.0" / "bin"
lean_pkgs := "TestKit Machines codegen-core substrait schema-lang faults dbsp wasm-backend"

lean-build:
	#!/usr/bin/env bash
	set -euo pipefail
	for p in {{lean_pkgs}}; do
	  (cd lean/$p && PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake build)
	done

lean-test: lean-build

# Codegen pipeline shim — all logic lives in the forge crate.
gen:
	cargo run -p forge -- gen

gen-check:
	cargo run -p forge -- gen --check

# ── Cloudflare Pages (devenv/dev/cloudflare.nix) ─────────────────────
# Pages as static host: no wrangler.toml, token via secretspec at
# runtime (never the shell env). Project name/dist from the nix module.

# One-time setup (interactive, browser OAuth — no token needed):
#   npx wrangler pages project create $CLOUDFLARE_PAGES_PROJECT

# Local serve of dist/ (deploy-parity: prod caching ships as dist/_headers).
serve:
	miniserve --interfaces 0.0.0.0 -p 8080 --hidden --header "Cache-Control: no-cache" $CLOUDFLARE_DIST_DIR

# Deploy dist/ to Pages. Token from secretspec (dotenv today, infisical
# later — consumers unchanged). CI passes CLOUDFLARE_* as repo secrets
# instead; see .github/workflows/deploy.yml.
deploy:
	secretspec run -- wrangler pages deploy "$CLOUDFLARE_DIST_DIR" --project-name="$CLOUDFLARE_PAGES_PROJECT"

# ── Docs (Astro Starlight; docs profile) ─────────────────────────────
doc-dev:
	cd docs-site && bun run dev

doc-build:
	cd docs-site && bun run build

# ── End-to-end demo (Stage G): edit Lean → working component ─────────
# Regenerates from the SSOT (Demo.lean + fault registries), rebuilds the
# gateway component from the generated WIT, and proves the loop: typed
# host bindings call the guest, structured User comes back; delta laws
# execute; WIT round-trips through the canonical parser.
demo:
	just gen
	just wasm-guest-gateway
	devenv shell --profile wasm -- bash -c \
	  'export CC=$HOME/lean-rust-wasm/.devenv/profiles/wasm/profile/bin/cc; \
	   cargo test -p steel-host && cargo test -p lean-rust-wasm'
	@echo "demo: edit Lean → component → typed calls — loop closed"

# ── Gates: every lean↔rust drift check in one shot ───────────────────
# wit-check: the canonical parser (wasm-tools) must accept our emitted
# WIT — it, not our printer, is the correctness authority. Prefers the
# cargo-installed 1.258 (matches wit-bindgen 0.61's wit-component for
# async-lift encodings); nixpkgs' wasm-tools works for plain WIT parsing.
wit-check:
	#!/usr/bin/env bash
	set -euo pipefail
	WT="$HOME/.local/guestlang-tools/bin/wasm-tools"
	[ -x "$WT" ] || WT=wasm-tools
	"$WT" component wit wit/gateway.wit > /dev/null

# Full gate: builds lean first (no stale oleans), then all drift checks.
gates: lean-build gen-check wit-check lean-axioms
	@echo "gates: clean"

# Axiom gate: sorryAx or an unexpected axiom fails the build (the allowed
# set is the core triple + native_decide's disclosed trust base).
lean-axioms:
	#!/usr/bin/env bash
	set -euo pipefail
	for p in {{lean_pkgs}}; do
	  out=$(cd lean/$p && PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env lean Tests/Axioms.lean 2>&1)
	  if echo "$out" | grep -q "sorryAx"; then echo "FAIL: sorryAx in $p"; exit 1; fi
	  bad=$(echo "$out" | grep -v "does not depend" | sed "s/.*depends on axioms: //" | tr -d "[]" | tr "," "\n" \
	    | sed "s/^ *//;s/ *$//" \
	    | grep -vE "^(propext|Classical.choice|Quot.sound|.*native_decide..*|)$" || true)
	  if [ -n "$bad" ]; then echo "FAIL: $p unexpected axioms:"; echo "$bad"; exit 1; fi
	  echo "$p: axioms clean"
	done

# ── The compiler line: LCNF → WAT → binary WASM ──────────────────────
# The backend re-runs Lean's LCNF pipeline (the leanir pattern) and emits
# WAT; wasm-tools parses (-g: DWARF + name section) and validates.
# Smoke: wasmtime --invoke runs the exports (double 21 = 42).
wasm-compile:
	#!/usr/bin/env bash
	set -euo pipefail
	TC="$HOME/.elan/toolchains/leanprover--lean4---v4.33.0/bin"
	(cd lean/wasm-backend && PATH="$TC:$PATH" "$TC/lake" build DemoFn wasm-gen \
	  && PATH="$TC:$PATH" "$TC/lake" exe wasm-gen)
	WT="$HOME/.local/guestlang-tools/bin/wasm-tools"
	[ -x "$WT" ] || WT=wasm-tools
	"$WT" parse -g lean/wasm-backend/target/demo.wat -o lean/wasm-backend/target/demo.wasm
	"$WT" validate lean/wasm-backend/target/demo.wasm
	# Differential smoke: the wasm results must equal Lean's own evaluation
	# (double 21 = 42 = adder 40 2; is-big 250 = 1; doubleArea = the FULL
	# object lifecycle; runPaps = closures + pool reuse). wasmtime lives
	# only in the wasm profile — absolute path (nested devenv PATH varies).
	WTIME="$HOME/.devenv/profiles/wasm/profile/bin/wasmtime"
	[ -x "$WTIME" ] || WTIME=$(find /nix/store -maxdepth 3 -name wasmtime -type f 2>/dev/null | head -1)
	inv() { (cd lean/wasm-backend && "$WTIME" run --invoke "$@" 2>&1 | tail -1); }
	[ "$(inv double 21)" = "42" ] \
	  && [ "$(inv adder 40 2)" = "42" ] \
	  && [ "$(inv is-big 250)" = "1" ] \
	  && [ "$(inv is-big 42)" = "0" ] \
	  && [ "$(inv double-area 5)" = "100" ] \
	  && [ "$(inv double-area 9)" = "324" ] \
	  && [ "$(inv double-area 1)" = "4" ] \
	  && [ "$(inv run-paps 5)" = "8" ] \
	  && [ "$(inv run-paps 9)" = "12" ] \
	  && [ "$(inv run-paps 0)" = "3" ] \
	  && [ "$(inv pick 1 3 4)" = "12" ] \
	  && [ "$(inv total 1 2 3)" = "6" ]
	# Component wrap: the COMPILED module as a component (steel-host loads it)
	"$WT" component embed -w demo lean/wasm-backend/demo-world.wit lean/wasm-backend/target/demo.wasm \
	  -o lean/wasm-backend/target/demo.embedded.wasm
	"$WT" component new lean/wasm-backend/target/demo.embedded.wasm \
	  -o lean/wasm-backend/target/demo.component.wasm
	"$WT" validate lean/wasm-backend/target/demo.component.wasm
	echo "wasm-compile: demo.wasm VALID + differential smoke green + component VALID"
