# Verification recipes

# Full check: tests, clippy, fmt, typos, secrets.
check: test clippy fmt typos secrets

# nextest is the default runner. nextest does not run doctests —
# they run separately (flatland pattern).
test:
	cargo nextest run && cargo test --doc

clippy:
	cargo clippy --all-targets
	cargo clippy --all-targets --all-features

fmt:
	cargo fmt --check

# Everything formatter: rustfmt + dprint (treefmt.toml + .dprint.json).
format:
	treefmt

# Spell-check (typos.toml).
typos:
	typos

# Secret scanner (ripsecrets).
secrets:
	ripsecrets

# Auto-fix lint/format findings (separate target dir, no -Zthreads).
fix:
	cargo-clippy-fix
	cargo fmt

clippy-fix:
	cargo-clippy-fix

# Dependency hygiene
deny:
	cargo deny check

outdated:
	cargo outdated

machete:
	cargo machete

# Mutation testing (pass a module name: just mutants foo)
mutants name:
	cargo mutants -f {{name}}

# ── Codegen loop (buf-style: watched = same command, wrapped) ────────
# `gen`/`check`/`breaking` run identically in CI and in watchers. The
# watcher never changes what runs, only when.

# Fast type-check only, no emission (buf lint analog): universeCheck
# over the demo registry; any diagnostic fails the gate.
check-schema:
	cd lean/schema-lang && PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake --dir ../.. exe schema check

# Schema-compat diff vs the committed baseline (buf breaking analog):
# goldens/universe.snapshot vs the current demo registry; breaking
# changes (removed/reshaped items) fail the gate. Re-baseline with
# `cd lean/schema-lang && lake --dir ../.. exe schema breaking --update`.
breaking:
	cd lean/schema-lang && PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake --dir ../.. exe schema breaking

# The snapshot-codec differential's fixtures (the fuzz-gap audit's gap
# #2): the Lean authority's seeded (snapshot-text, expected-item-dump)
# pairs for the Rust twin — crates/steel-host/tests/fixtures/
# snapshot_fixtures.txt, replayed by tests/snapshot_differential.rs.
# Byte-tie law: pinned seed, a regen is byte-identical (drift = a
# reviewable diff; the writer refuses a universe that fails the
# Lean-authority round trip).
snapshot-fixtures:
	cd lean/schema-lang && PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake --dir ../.. exe snapshot-fixtures

# ABSORBED-DIR INVOCATIONS (single-lake): lake does not walk up over a
# deleted lakefile, so a recipe that cds into an absorbed package dir adds
# `--dir ../..` (workspace = the root) and keeps the cwd for the exe's
# cwd-relative writes (the §7 gen-exe rule).

# Watchers — watchexec wraps the SAME commands, no redefinition.
# --restart: kill in-flight gen on new save (codegen is idempotent).
watch-gen:
	watchexec -r -w lean -e lean -- just gen

# Host restart on generated OUTPUTS + host code (not lean/ — the gen
# write into src/generated is what triggers this, one write per change).
watch-host:
	watchexec -r -w src -w wit -- cargo run

# Fast schema check without emission.
watch-check:
	watchexec -w lean -e lean -- just check-schema

# Property/fuzz ingress boundary tests (bolero). Corpora live in
# devenv state (DEVENV_STATE/bolero-corpus).
fuzz name:
	cargo bolero run {{name}}

# ── WASM guest component (wasip3, via wasm-component-ld + wasi-sdk sysroot) ──
wasm-guest:
	#!/usr/bin/env bash
	set -euo pipefail
	RUSTFLAGS="$RUSTFLAGS_WASIP3" cargo build -p guest-demo \
	  --target targets/wasm32-wasip3-local.json \
	  -Z build-std=std,panic_abort \
	  -Z json-target-spec
	echo "component: target/wasm32-wasip3-local/debug/guest_demo.wasm"
	wasm-tools validate target/wasm32-wasip3-local/debug/guest_demo.wasm
	echo "wasm-tools validate: clean"

# ── Proper component with lifted exports (host-embedder input) ──────
# The wasip3 linker wraps the core module (no raw core artifact on disk to
# embed WIT into), so the pure-export core module is built with
# wasm32-unknown-unknown (guest-demo uses no WASI), the world is embedded
# with `component embed`, and `component new` lifts the exports.
wasm-guest-component:
	#!/usr/bin/env bash
	set -euo pipefail
	RUSTFLAGS="$RUSTFLAGS_WASM32" cargo build -p guest-demo \
	  --target wasm32-unknown-unknown \
	  -Z build-std=std,panic_abort
	core=target/wasm32-unknown-unknown/debug/guest_demo.wasm
	embedded=target/wasm32-unknown-unknown/debug/guest_demo.embedded.wasm
	out=target/wasm32-unknown-unknown/debug/guest_demo.component.wasm
	wasm-tools component embed crates/guest-demo/guest-demo.wit "$core" -o "$embedded"
	wasm-tools component new "$embedded" -o "$out"
	wasm-tools validate "$out"
	echo "component: $out"
	wasm-tools component wit "$out"

# Gateway world component: the SSOT wit/gateway.wit (GENERATED by
# schema-lang) — guest-demo implements it via wit-bindgen, which embeds the
# component-type section, so `component new` lifts directly. watch-orders
# uses the wasi 0.3 async ABI (`async func` in WIT).
wasm-guest-gateway:
	#!/usr/bin/env bash
	set -euo pipefail
	RUSTFLAGS="$RUSTFLAGS_WASM32" cargo build -p guest-demo \
	  --target wasm32-unknown-unknown \
	  -Z build-std=std,panic_abort
	core=target/wasm32-unknown-unknown/debug/guest_demo.wasm
	out=target/wasm32-unknown-unknown/debug/guest_demo.gateway.component.wasm
	# Needs a wasm-tools CLI matching wit-bindgen 0.61's wit-component (0.258):
	# the async canonical-lift encoding predates nixpkgs' 1.256.
	WT="$HOME/.local/guestlang-tools/bin/wasm-tools"
	[ -x "$WT" ] || WT=wasm-tools
	"$WT" component new "$core" -o "$out"
	"$WT" validate "$out"
	echo "component: $out"
	"$WT" component wit "$out" | grep -E 'get-user|watch-orders'

# ── WASM compile checks (nightly + rust-src required) ────────────────
# RUSTFLAGS_WASIP3/RUSTFLAGS_WASM32 strip host-only flags (target-cpu=native,
# -Z*); these are the real gates for "does it build for wasm" without a link.
check-wasip3:
	RUSTFLAGS="$RUSTFLAGS_WASIP3" cargo check --target wasm32-wasip3 -Z build-std=std,panic_abort

check-wasm:
	RUSTFLAGS="$RUSTFLAGS_WASM32" cargo check --target wasm32-unknown-unknown

# ── Lean workspace (packages in dependency order) ────────────────────
# elan shims broken — invoke toolchain bin directly.
lean_tc := home_dir() / ".elan" / "toolchains" / "leanprover--lean4---v4.33.0" / "bin"
# SINGLE-LAKE (notes/single-lake-migration.md): every lean/ package is
# absorbed into the root lakefile — the root lakefile IS the inventory;
# lean_pkgs and lean-pkg-inventory RETIRED (nothing left to inventory).
# (lean-build lives below with the test-exe loop — one definition only.)

# Import-reachability gate: every test module must be reachable from its
# driver (the `Main.lean` beside it). `Axioms.lean` is a standalone entry
# point (run directly) and is excluded from the check. SINGLE-LAKE MIGRATION
# (§5 of notes/single-lake-migration.md): test roots are renamed per package
# (`<Pkg>Tests/` — the Tests.* names collide in one package), so the expected
# import line is `import <DirName>.<Mod>` with the DIRECTORY's name — `Tests`
# for a not-yet-absorbed package, `<Pkg>Tests` after its absorption.
lean-proof-roots:
	#!/usr/bin/env bash
	set -euo pipefail
	fail=0
	shopt -s nullglob
	for d in lean/*/Tests/ lean/*/*Tests/; do
	  [ -d "$d" ] || continue
	  root="$(basename "${d%/}")"
	  pkg="$(basename "$(dirname "${d%/}")")"
	  main="$d/Main.lean"
	  [ -f "$main" ] || continue
	  for tf in "$d"*.lean; do
	    base="${tf##*/}"
	    [ "$base" = "Main.lean" ] && continue
	    [ "$base" = "Axioms.lean" ] && continue
	    mod="${base%.lean}"
	    if ! grep -q "import $root\\.$mod\b" "$main" 2>/dev/null; then
	      echo "FAIL: lean/$pkg/$root/$base not imported in $root/Main.lean"
	      fail=1
	    fi
	  done
	done
	[ "$fail" = 0 ] || exit 1
	echo "lean-proof-roots: every test file reachable"

lean-build:
	#!/usr/bin/env bash
	set -euo pipefail
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake build)

# Per-package test-exe loop (the single-lake shape: `lake test` runs ONE
# driver — the root's; every other test exe is its own target). Each exe
# runs from its package dir (the §7 cwd rule — the goldens/ and target/
# readers) with the root workspace via --dir.
lean-test: lean-build
	#!/usr/bin/env bash
	set -euo pipefail
	declare -A exes=(
	  [edgepython]=EdgePythonTests [ledger]=LedgerTests
	  [feature-flags]=FeatureFlagsTests [proofkit]=ProofkitTests
	  [qlang]=QLangTests [substrait]=SubstraitTests [faults]=FaultsTests
	  [std]=GuestlangStdTests [schema-lang]=SchemaLangTests
	  [wasm-backend]=WasmBackendTests
	)
	for p in "${!exes[@]}"; do
	  echo "── lean-test: $p/${exes[$p]}"
	  (cd lean/$p && PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake --dir ../.. exe "${exes[$p]}") || exit 1
	done
	# TestKit/Machines: absorbed too — their test exes are root targets now.
	for px in TestKit:TestKitTests Machines:MachinesTests; do
	  d="${px%%:*}"; x="${px##*:}"
	  echo "── lean-test: $d/$x"
	  (cd lean/$d && PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake --dir ../.. exe "$x") || exit 1
	done
	echo "lean-test: all test exes green"

# Custom env/text linters (LintKit — notes/lean-refactor-guide.md Phase 6).
# The `guestlang-lint` driver runs over each package's own oleans via
# `lake env` (downstream libraries never import the linter machinery; the
# only LintKit imports in the tree are the recorded nolint/opt-out sites).
# Default-on linters: axiomAllowlist, dupDefBodies, packageNamespace,
# noLinterDisable, testImportDiscipline, importBan. recursiveSimpEqns is
# registered but default-OFF (2026-11 census: 83 hits, dominated by
# doctrine-§8 raw-equation parsers — see its option comment); census run:
#   lake env <LK> --enable=linter.guestlang.recursiveSimpEqns <roots>
# SINGLE-LAKE: every package lints from the ROOT package's env — one run,
# the module roots the old per-package `run <pkg>` lines covered, with
# --src-root mounts so the TEXT lints resolve `lean/<dir>/` sources.
lean-lint: lean-build
	#!/usr/bin/env bash
	set -euo pipefail
	LK=".lake/build/bin/guestlang-lint"
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" \
	  LintKit \
	  --src-root=LintKit=lean/LintKit)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" TestKit TestKitTests.Main \
	  --src-root=TestKit=lean/TestKit \
	  --src-root=TestKitTests=lean/TestKit)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" Machines MachinesTests.Main \
	  --src-root=Machines=lean/Machines \
	  --src-root=MachinesTests=lean/Machines)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" CodegenCore CodegenCoreTests.Main \
	  --src-root=CodegenCore=lean/codegen-core \
	  --src-root=CodegenCoreTests=lean/codegen-core)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" Substrait SubstraitTests.Main \
	  --src-root=Substrait=lean/substrait \
	  --src-root=SubstraitTests=lean/substrait)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" QLang QLangTests.Main \
	  --src-root=QLang=lean/qlang \
	  --src-root=QLangTests=lean/qlang)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" Proofkit ProofkitTests.Main \
	  --src-root=Proofkit=lean/proofkit \
	  --src-root=ProofkitTests=lean/proofkit)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" SchemaLang Demo SchemaLangTests.Main \
	  --src-root=SchemaLang=lean/schema-lang \
	  --src-root=Demo=lean/schema-lang \
	  --src-root=SchemaLangTests=lean/schema-lang)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" Faults Faults.Spec.Demo Faults.Spec.Host FaultsTests.Main \
	  --src-root=Faults=lean/faults \
	  --src-root=FaultsTests=lean/faults)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" Dbsp DbspTests.Main \
	  --src-root=Dbsp=lean/dbsp \
	  --src-root=DbspTests=lean/dbsp)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" GuestlangStd \
	  --src-root=GuestlangStd=lean/std)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" Ledger LedgerFn LedgerES \
	  --src-root=Ledger=lean/ledger \
	  --src-root=LedgerFn=lean/ledger \
	  --src-root=LedgerES=lean/ledger)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" FeatureFlags FeatureFlagsFn Templates \
	  --src-root=FeatureFlags=lean/feature-flags \
	  --src-root=Machine=lean/feature-flags \
	  --src-root=Templates=lean/feature-flags)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" WasmBackend DemoFn Oracle WasmBackendTests.Main \
	  --src-root=WasmBackend=lean/wasm-backend \
	  --src-root=DemoFn=lean/wasm-backend \
	  --src-root=Oracle=lean/wasm-backend \
	  --src-root=WasmBackendTests=lean/wasm-backend)
	(PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env "$LK" EdgePython EdgePythonTests.Main \
	  --src-root=EdgePython=lean/edgepython \
	  --src-root=EdgeGenMain=lean/edgepython \
	  --src-root=EdgePythonTests=lean/edgepython)

# Codegen pipeline shim — all logic lives in the forge crate.
gen:
	cargo run -p forge -- gen

# The byte-tie, delegated to the gates exe (Gates.GenCheck): in-process
# regen from the replayed registries + stripped compare (body bytes +
# embedded content hash; the header's timestamp/spec-sha exempt). Never
# writes — closes forge gen --check's `just gen dirties the tree`
# weakness. Same artifact surface as the old forge check.
gen-check:
	cd lean/gates && PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake --dir ../.. exe gates gen-check

# Every output declared in a forge jobs manifest exists and carries the
# GENERATED header (a headerless file at a declared path = hand-written
# file squatting on a generated artifact's path — the one-writer rule).
# SINGLE-LAKE: LintKit is absorbed — the exe runs from the root build dir.
artifact-headers:
	PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake env .lake/build/bin/guestlang-lint --artifacts-root=.

# ── Cloudflare Pages (devenv/dev/cloudflare.nix) ─────────────────────
# Pages as static host: no wrangler.toml, token via secretspec at
# runtime (never the shell env). Project name/dist from the nix module.

# One-time setup (interactive, browser OAuth — no token needed):
#   npx wrangler pages project create $CLOUDFLARE_PAGES_PROJECT

# Local serve of dist/ (deploy-parity: prod caching ships as dist/_headers).
serve:
	miniserve --interfaces 0.0.0.0 -p 8080 --hidden --header "Cache-Control: no-cache" $CLOUDFLARE_DIST_DIR

# Deploy dist/ to Pages. Token from secretspec (dotenv today, infisical
# later — consumers unchanged). CI passes CLOUDFLARE_* as repo secrets
# instead; see .github/workflows/deploy.yml.
deploy:
	secretspec run -- wrangler pages deploy "$CLOUDFLARE_DIST_DIR" --project-name="$CLOUDFLARE_PAGES_PROJECT"

# ── Docs site (docs-site/ — Astro Starlight; the flatland mirror) ────
# Starlight is the renderer (zero hand-roll). Tool = bun (bun.lock in
# docs-site/, pinned to the flatland dep versions). The schema-gen's
# LATER doc-gen4 lane: once doc-gen4 is wired, this is its home — doc-gen4
# generates API docs from Lean modules (the Starlight lane above is the
# static schema-ref doc; the two complement each other).
# docs emitter owns docs/api.md (just gen); this lane COPYs it into
# docs-site/src/content/docs/ at BUILD time (Starlight's docsLoader
# globs the content dir) with frontmatter prepended (the generator
# emits bare markdown). The copy is gitignored — docs/api.md stays
# the committed generated source. NOT wired into `gates`.
docs:
	#!/usr/bin/env bash
	set -euo pipefail
	# Host-cargo builds under devenv need the profile cc (ring's C bits
	# fail under the devenv clang — the demo recipe's CC export is the
	# established fix; fall back to the env's CC when the profile is absent).
	PCC="$HOME/lean-rust-wasm/.devenv/profiles/wasm/profile/bin/cc"
	[ -x "$PCC" ] && export CC="$PCC"
	just gen
	dst=docs-site/src/content/docs/api.md
	{ printf -- '---\ntitle: API\ndescription: The generated schema reference (demo:gateway) — emitted by SchemaLang.Docs.docsOf, do not hand-edit.\n---\n\n'; cat docs/api.md; } > "$dst"
	(cd docs-site && bun install --frozen-lockfile && bun run build)
	[ -s docs-site/dist/index.html ] || { echo "FAIL: dist/index.html missing or empty"; exit 1; }
	grep -q "guestlang" docs-site/dist/index.html || { echo "FAIL: branding missing from index.html"; exit 1; }
	grep -q "<table" docs-site/dist/api/index.html || { echo "FAIL: no GFM tables rendered in the API page"; exit 1; }
	echo "docs: Starlight build green — dist/ non-empty, branded, API tables rendered"

# ── Docs (Astro Starlight; docs profile) ─────────────────────────────
doc-dev:
	cd docs-site && bun run dev

doc-build:
	cd docs-site && bun run build

# ── End-to-end demo (Stage G): edit Lean → working component ─────────
# Regenerates from the SSOT (Demo.lean + fault registries), rebuilds the
# gateway component from the generated WIT, and proves the loop: typed
# host bindings call the guest, structured User comes back; delta laws
# execute; WIT round-trips through the canonical parser.
demo:
	just gen
	just wasm-guest-gateway
	devenv shell --profile wasm -- bash -c \
	  'export CC=$HOME/lean-rust-wasm/.devenv/profiles/wasm/profile/bin/cc; \
	   cargo test -p steel-host && cargo test -p lean-rust-wasm'
	@echo "demo: edit Lean → component → typed calls — loop closed"

# ── Gates: every lean↔rust drift check in one shot ───────────────────
# wit-check: the canonical parser (wasm-tools) must accept our emitted
# WIT — it, not our printer, is the correctness authority. Prefers the
# cargo-installed 1.258 (matches wit-bindgen 0.61's wit-component for
# async-lift encodings); nixpkgs' wasm-tools works for plain WIT parsing.
wit-check:
	#!/usr/bin/env bash
	set -euo pipefail
	WT="$HOME/.local/guestlang-tools/bin/wasm-tools"
	[ -x "$WT" ] || WT=wasm-tools
	"$WT" component wit wit/gateway.wit > /dev/null

# Full gate: builds lean first (no stale oleans), then all drift checks.
gates: lean-proof-roots lean-build gen-check artifact-headers wit-check lean-axioms native-policy kernel-check manifest-check coverage check-schema breaking wasm-diff-check splice-smoke rt-conformance lean-lint budget-check
	@echo "gates: clean"

# Axiom gate (delegated to the gates exe — Gates.Axioms): one process,
# per gated package every declaration's kernel axiom cone (CollectAxioms)
# checked against LintKit's allowlist (consumed via LintKit's own runner,
# not re-encoded), plus a diff against the committed
# notes/axiom-report.md — a silent axiom-surface change fails the gate.
# Re-baseline with `cd lean/gates && lake exe gates axioms --write`.
# Requires `lean-build` (the gated packages' oleans).
lean-axioms:
	#!/usr/bin/env bash
	set -euo pipefail
	# wasm-backend's Tests exe not in defaultTargets (guide 2.4) — the
	# report covers its test root, so its oleans must exist.
	(cd lean/wasm-backend && PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake --dir ../.. build WasmBackendTests)
	# SHARDED per package (the monolithic one-process mode peaked ~26.5GB
	# and OOM'd this box; per-package peaks ~2-4GB — the sharding order).
	cd lean/gates && for p in LintKit TestKit Machines codegen-core substrait qlang proofkit schema-lang faults dbsp std wasm-backend ledger feature-flags edgepython; do \
	  PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake --dir ../.. exe gates axioms --package $p || exit 1; \
	done

# Lakefile ↔ manifest drift (delegated to the gates exe — Gates.Manifest):
# every lean/*/lake-manifest.json agrees with its lakefile.toml
# (require↔entry, rev pins, checkout HEADs). Structural + offline.
manifest-check:
	cd lean/gates && PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake --dir ../.. exe gates manifest-check

# The coverage matrix (delegated to the gates exe — Gates.Coverage):
# Ty ctors x registered emitters x the oracle's replay surface; diffs the
# committed notes/coverage-matrix.md (`--strict` fails on quiet ctors —
# pass it via the exe: `cd lean/gates && lake exe gates coverage --strict`).
coverage:
	cd lean/gates && PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake --dir ../.. exe gates coverage

# The lean4lean double-check (delegated to the gates exe —
# Gates.KernelCheck): every gated package's modules replayed through the
# pure-Lean kernel. Requires `lean-build`. Disagreements are ledgered in
# notes/divergences.md (investigated before the gate is bypassed).
# SHARDED like lean-axioms (--package, the NativePolicy filter pattern):
# the unsharded single-process run exceeded 30 min on this box.
kernel-check:
	cd lean/gates && for p in LintKit TestKit Machines codegen-core substrait qlang proofkit schema-lang faults dbsp std wasm-backend ledger feature-flags edgepython; do \
	  PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake --dir ../.. exe gates kernel-check --package $p || exit 1; \
	done

# The native_decide policy (delegated to the gates exe —
# Gates.NativePolicy): no decl in the checked set depends on the
# `_native.native_decide.` trust base outside the grandfathered exiles
# (doctrine §3 — the lean4lean-checked set must stay kernel-replayable).
native-policy:
	#!/usr/bin/env bash
	set -euo pipefail
	# SHARDED like lean-axioms (one env per process — the full sweep
	# accumulates every package's env in one process and OOMs).
	cd lean/gates && for p in LintKit TestKit Machines codegen-core substrait qlang proofkit schema-lang faults dbsp std wasm-backend ledger feature-flags edgepython; do \
	  PATH="{{lean_tc}}:$PATH" {{lean_tc}}/lake --dir ../.. exe gates native-policy --package $p || exit 1; \
	done

# ── The compiler line: LCNF → WAT → binary WASM ──────────────────────
# The backend re-runs Lean's LCNF pipeline (the leanir pattern) and emits
# WAT; wasm-tools parses (-g: DWARF + name section) and validates.
# Smoke: wasmtime --invoke runs the exports (double 21 = 42).
wasm-compile:
	#!/usr/bin/env bash
	set -euo pipefail
	TC="$HOME/.elan/toolchains/leanprover--lean4---v4.33.0/bin"
	# THE OBSERVABILITY BYTE-TIE's snapshot: the regen REWRITES
	# src/observability_generated.rs in place — keep the committed surface
	# BEFORE it, so the compare after the regen can prove no drift
	# (target/ = the scratch dir, untracked).
	mkdir -p lean/wasm-backend/target
	cp src/observability_generated.rs lean/wasm-backend/target/observability_generated.rs.committed
	(cd lean/wasm-backend && PATH="$TC:$PATH" "$TC/lake" --dir ../.. build DemoFn wasm-gen oracle \
	  && PATH="$TC:$PATH" "$TC/lake" --dir ../.. exe wasm-gen)
	# THE OBSERVABILITY BYTE-TIE (the fast-observe seam — steel-host's
	# hot-reload span surface): strip the 2-line GENERATED header (the
	# wall-clock + git state vary per regen — the byte-tie only binds the
	# CONTENT) and compare the regenerated file against the committed
	# surface: a drift = a real ABI-surface change.
	if ! cmp -s <(tail -n +3 src/observability_generated.rs) \
	             <(tail -n +3 lean/wasm-backend/target/observability_generated.rs.committed); then
	  echo "FAIL: src/observability_generated.rs drifted from the committed surface — regenerate (just wasm-compile) + commit the observability surface"
	  exit 1
	fi
	WT="$HOME/.local/guestlang-tools/bin/wasm-tools"
	[ -x "$WT" ] || WT=wasm-tools
	"$WT" parse -g lean/wasm-backend/target/demo.wat -o lean/wasm-backend/target/demo.wasm
	"$WT" validate lean/wasm-backend/target/demo.wasm
	# The DIFFERENTIAL MANIFEST: run the oracle (real Lean evals over the
	# generated inputs) — Lean's semantics is the authority the wasm_diff
	# test replays against. Regenerated WITH the WAT so the manifest can
	# never go stale against the module it audits.
	(cd lean/wasm-backend && PATH="$TC:$PATH" "$TC/lake" --dir ../.. exe oracle \
	  | grep '^\[' > target/diff.json)
	# The SMOKE is the DIFFERENTIAL GATE (steel-host's wasm_diff): the
	# oracle manifest (regenerated above — Lean's own evals) replays
	# against the component, 160 rows + the sabotage control. The old
	# hand-written per-fn assertions (double 21 = 42, ...) were a stale
	# duplicate — one authority: Lean's semantics via the manifest.
	# Component wrap: the COMPILED module as a component (steel-host loads it)
	"$WT" component embed -w demo lean/wasm-backend/demo-world.wit lean/wasm-backend/target/demo.wasm \
	  -o lean/wasm-backend/target/demo.embedded.wasm
	"$WT" component new lean/wasm-backend/target/demo.embedded.wasm \
	  -o lean/wasm-backend/target/demo.component.wasm
	"$WT" validate lean/wasm-backend/target/demo.component.wasm
	echo "wasm-compile: demo.wasm VALID + differential smoke green + component VALID"

# The SPLICE-SMOKE gate: a PASSTHROUGH splicer (wac) instantiates the
# EMITTED component and re-exports its world — composition + validation
# by an INDEPENDENT tool (wac's own WIT resolver) = the independent
# proof the emitted WIT is well-formed. The composed component must
# still RUN (the splicer didn't break the exports).
splice-smoke:
	#!/usr/bin/env bash
	set -euo pipefail
	WT="$HOME/.local/guestlang-tools/bin/wasm-tools"
	WAC="$HOME/.local/guestlang-tools/bin/wac"
	[ -x "$WT" ] || WT=wasm-tools
	[ -x "$WAC" ] || WAC=wac
	# the passthrough document: re-export the demo world unchanged
	cat > lean/wasm-backend/target/splice.wac <<'WAC'
	package guestlang:spliced;
	let demo = new guestlang:demo { ... };
	export demo.double;
	export demo.adder;
	export demo.is-big;
	export demo.double-area;
	export demo.run-paps;
	export demo.total;
	export demo.pick;
	export demo.str-len-demo;
	export demo.greet;
	WAC
	"$WAC" compose lean/wasm-backend/target/splice.wac \
	  --dep guestlang:demo=lean/wasm-backend/target/demo.component.wasm \
	  -o lean/wasm-backend/target/spliced.component.wasm
	"$WT" validate lean/wasm-backend/target/spliced.component.wasm
	echo "splice-smoke: passthrough composed + spliced component VALID"

# The SPLICER-MW gate (Track 2d — notes/async-wrpc-oci-plan.md): the
# FIRST REAL middleware. The splicer-mw component wraps the demo
# world's scalar subset (double, is-big): count in an IN-WASM counter
# (`calls`), delegate to the INNER (the wac composition wires the
# demo component's exports to the middleware's imports), return
# unchanged. Zero hand-WAT — wit-bindgen wraps both sides. The test
# proves the inner ran THROUGH the interposer (42 + the counter + the
# spec's spans — the tracing seam: the spans = the spec's data, the
# counter = the middleware's own state).
# Standalone (NOT in `gates`): needs `just wasm-compile`'s artifacts
# (demo.component.wasm) + a cross-compile of the mw guest — more
# moving parts than the splice-smoke passthrough; wire into gates
# only if the wasm-compile prerequisite is already a gates given.
splicer-mw:
	#!/usr/bin/env bash
	set -euo pipefail
	RUSTFLAGS="$RUSTFLAGS_WASM32" cargo build -p splicer-mw \
	  --target wasm32-unknown-unknown \
	  -Z build-std=std,panic_abort
	mkdir -p target/spliced-mw
	WT="$HOME/.local/guestlang-tools/bin/wasm-tools"
	WAC="$HOME/.local/guestlang-tools/bin/wac"
	[ -x "$WT" ] || WT=wasm-tools
	[ -x "$WAC" ] || WAC=wac
	core=target/wasm32-unknown-unknown/debug/splicer_mw.wasm
	mw=target/spliced-mw/mw.component.wasm
	composed=target/spliced-mw/spliced-mw.component.wasm
	"$WT" component new "$core" -o "$mw"
	"$WT" validate "$mw"
	[ -f lean/wasm-backend/target/demo.component.wasm ] || { echo "FAIL: no demo.component.wasm — run 'just wasm-compile'"; exit 1; }
	# the composition: demo's exports feed the middleware's imports;
	# the middleware's exports = the served surface
	cat > target/spliced-mw/splice-mw.wac <<'WAC'
	package guestlang:spliced-mw;
	let demo = new guestlang:demo { ... };
	let mw = new guestlang:mw {
	  double: demo.double,
	  is-big: demo.is-big,
	  watch-counts: demo.watch-counts,
	};
	export mw.double;
	export mw.is-big;
	export mw.watch-counts;
	export mw.calls;
	WAC
	"$WAC" compose target/spliced-mw/splice-mw.wac \
	  --dep guestlang:demo=lean/wasm-backend/target/demo.component.wasm \
	  --dep guestlang:mw="$mw" \
	  -o "$composed"
	"$WT" validate "$composed"
	CC="$HOME/lean-rust-wasm/.devenv/profiles/wasm/profile/bin/cc" \
	  cargo test -p steel-host --test spliced_middleware
	echo "splicer-mw: middleware composed + inner routed + counter + spec spans green"

# The WASMI CONFORMANCE gate (the embeddable-runtime half of the dual-
# engine story): the SAME demo.wasm runs under the standalone rt (wasmi,
# core-wasm + trap-stubbed task intrinsics) with identical results to
# the wasmtime differential smoke — the IR seam is engine-agnostic.
# Needs the wasm-compile artifacts (like splice-smoke).
rt-conformance:
	#!/usr/bin/env bash
	set -euo pipefail
	[ -f lean/wasm-backend/target/demo.wasm ] || { echo "FAIL: no demo.wasm — run 'just wasm-compile'"; exit 1; }
	CC="$HOME/lean-rust-wasm/.devenv/profiles/wasm/profile/bin/cc" cargo test -p guestlang-rt
	echo "rt-conformance: wasmi runs the compiler line's output"

# ── EdgePython: the SECOND FRONTEND (the IR-seam neutrality proof) ────
# The honest Python subset (scalars only: +-*, < ==, if/else, while,
# calls, return) compiled by lean/edgepython DIRECTLY to the FROZEN
# WasmBackend.Wat AST (zero new constructors — the IR seam is the
# backend's), rendered, parsed + validated by the same wasm-tools
# pipeline, then run under BOTH engines with the SAME results the Lean
# parity theorems pin. No alloc/RC: nothing heap-allocated, so the
# guestlang runtime splice is simply not needed.
edgepython:
	#!/usr/bin/env bash
	set -euo pipefail
	TC="{{lean_tc}}"
	(cd lean/edgepython && PATH="$TC:$PATH" "$TC/lake" --dir ../.. build EdgePython EdgeGen EdgePythonTests py-gen \
	  && PATH="$TC:$PATH" "$TC/lake" --dir ../.. test \
	  && PATH="$TC:$PATH" "$TC/lake" --dir ../.. env lean EdgePythonTests/Axioms.lean > /dev/null \
	  && PATH="$TC:$PATH" "$TC/lake" --dir ../.. exe py-gen)
	WT="$HOME/.local/guestlang-tools/bin/wasm-tools"
	[ -x "$WT" ] || WT=wasm-tools
	"$WT" parse lean/edgepython/target/py.wat -o lean/edgepython/target/py.wasm
	"$WT" validate lean/edgepython/target/py.wasm
	CC="$HOME/lean-rust-wasm/.devenv/profiles/wasm/profile/bin/cc" \
	  cargo test -p steel-host --test edgepython
	CC="$HOME/lean-rust-wasm/.devenv/profiles/wasm/profile/bin/cc" \
	  cargo test -p guestlang-rt --test edgepython
	echo "edgepython: compiled + VALID + duel green (Lean × wasmtime × wasmi)"

# ── Template scaffold (notes/reuse-map.md — the instantiation lane) ──
# new-project: instantiate template/ as lean/<name> (the spec+impl
# skeleton), apply the renames (Thing→<Camel>, thing→<snake>),
# AUTO-register the package (the lean_pkgs line + the packagePrefixes
# rows), and print the manual follow-ups (the world's fold, the lint
# row). Undo with new-project-clean. NOT in gates — it mutates the tree.
new-project name:
	#!/usr/bin/env python3
	import os, re, shutil, sys
	name = "{{name}}"
	root = "{{justfile_directory()}}"
	if not re.fullmatch(r"[a-z][a-z0-9-]*", name):
	    sys.exit("new-project: name must be lowercase kebab-case (got '%s')" % name)
	camel = "".join(p.capitalize() for p in name.split("-"))
	snake = name.replace("-", "_")
	pkg = os.path.join(root, "lean", name)
	if os.path.exists(pkg):
	    sys.exit("new-project: lean/%s already exists" % name)
	tpl = os.path.join(root, "template")
	files = [
	    ("spec.lean", camel + ".lean"),
	    ("impl.lean", camel + "Fn.lean"),
	    ("project.json", "project.json"),
	    ("lakefile.toml", "lakefile.toml"),
	    ("Tests.lean", os.path.join("Tests", "Main.lean")),
	    ("Axioms.lean", os.path.join("Tests", "Axioms.lean")),
	    ("lean-toolchain", "lean-toolchain"),
	    ("lake-manifest.template.json", "lake-manifest.json"),
	    ("README.md", "README.md"),
	]
	for src, dst in files:
	    d = os.path.join(pkg, dst)
	    os.makedirs(os.path.dirname(d), exist_ok=True)
	    text = open(os.path.join(tpl, src)).read()
	    # the WORD-BOUNDARY rename: the plain replace ate "anything" ->
	    # "anyledger" (the dogfood finding #1!) — regex with the boundaries
	    # the LONGEST-FIRST order (the compound names: ThingFn/ThingImpl
	    # — the dogfood finding #3; \bThing\b misses them)
	    text = re.sub(r"\bThingFn\b", camel + "Fn", text)
	    text = re.sub(r"\bThingImpl\b", camel + "Impl", text)
	    text = re.sub(r"\bThingTests\b", camel + "Tests", text)
	    text = re.sub(r"\bThing\b", camel, text)
	    text = re.sub(r"\bthing_(?=[a-z])", snake + "_", text)
	    text = re.sub(r"\bthing\b", snake, text)
	    open(d, "w").write(text)
	# AUTO-registration 1: the lean_pkgs loop (justfile) — the entries are
	# lean/ DIRECTORY names (the kebab name), not the Lean package name.
	jf = os.path.join(root, "justfile")
	s = open(jf).read()
	m = re.search(r'lean_pkgs := "([^"]*)"', s)
	if m is None:
	    sys.exit("new-project: lean_pkgs line not found in justfile")
	if name not in m.group(1).split():
	    s = s[:m.end(1)] + " " + name + s[m.end(1):]
	    open(jf, "w").write(s)
	# AUTO-registration 2: the packagePrefixes rows (LintKit's lean_pkgs
	# mirror — one row per module root: <Camel> and <Camel>Fn).
	pf = os.path.join(root, "lean", "LintKit", "LintKit", "PackageNamespace.lean")
	s = open(pf).read()
	if re.search(r"\n\]\n\n/-- Parse the comma-separated", s) is None:
	    sys.exit("new-project: packagePrefixes anchor not found in LintKit")
	if ("(`" + camel + ",") not in s:
	    # the LAST row before the anchor may lack a trailing comma (the
	    # hand-written list's style) — add it, else the insertion is a
	    # parse error (the dogfood finding: `LedgerFn` row + the
	    # missing comma = LintKit red). The comma-carrying insert keeps
	    # the idempotence check (`(` + camel + `,` not in s) intact.
	    rows = (f"  (`{camel},       [`{camel}]),\n"
	            f"  (`{camel}Fn,     [`{camel}Fn])\n")
	    # simpler + robust: split at the anchor, comma-join
	    anchor = "\n]\n\n/-- Parse the comma-separated"
	    head, tail = s.rsplit(anchor, 1)
	    if not head.rstrip().endswith(","):
	        head = head.rstrip() + ","
	    s = head + "\n" + rows + anchor[1:] + tail
	open(pf, "w").write(s)
	# AUTO-registration 3: seed the git-dep checkouts. gonzalgo resolves
	# from the vendored bundle (vendor/gonzalgo.bundle — the pinned rev was
	# SINGLE-LAKE NOTE (2026-09-19): this scaffolding recipe predates the
	# monolith — it scaffolds a lean/<pkg> PACKAGE (own lakefile + cone),
	# which no longer exists as a shape. New work = a new [[lean_lib]] in
	# the root lakefile. The recipe below is kept for its registration
	# steps and will fail at the dep-seeding step; a new-library recipe
	# is a named follow-up. The seed
	import json
	mirror = os.path.join(root, "lean", "faults", ".lake", "packages")
	man = json.load(open(os.path.join(pkg, "lake-manifest.json")))
	depdir = os.path.join(pkg, ".lake", "packages")
	os.makedirs(depdir, exist_ok=True)
	seeded = []
	for d in man.get("packages", []):
	    if d.get("type") != "git":
	        continue
	    src = os.path.join(mirror, d["name"])
	    dst = os.path.join(depdir, d["name"])
	    if os.path.isdir(src) and not os.path.exists(dst):
	        shutil.copytree(src, dst, copy_function=os.link)
	        seeded.append(d["name"])
	if seeded:
	    print("seeded git deps (hardlink from lean/faults/.lake/packages): " + ", ".join(seeded))
	print(f"new-project: lean/{name} scaffolded (Thing → {camel}, thing → {snake})")
	print("auto-registered: lean_pkgs (justfile, entry = the lean/ dir name) + packagePrefixes (lean/LintKit/LintKit/PackageNamespace.lean)")
	print("")
	print("manual follow-ups:")
	print("  1. the WIT world's fold: lean/schema-lang/SchemaLang/Emit/Wit.lean —")
	print("     the witEmitter row (worldOf \"demo:gateway\" \"gateway\" items) is the")
	print("     demo pattern; add YOUR emitter module + one line in the emitters list")
	print("     (lean/schema-lang/SchemaLang/Emit/Registry.lean — no driver changes).")
	print(f"  2. the gen driver: lean/schema-lang/GenMain.lean imports Demo and")
	print(f"     replays #[`Demo] — point it at your spec module (module {camel}).")
	print("  3. the compiled world: DONE by the manifest — the project.json here")
	print("     (spec-modules + impl-modules) is the compile-set's single source:")
	print("     lean/wasm-backend/GenMain.lean loads the manifest's modules and folds")
	print("     the compile roots from the @[guest]/@[guest_std] marks (targetDeclsOf)")
	print("     and the exports from the schema registry (worldExportsOf) — no")
	print("     hand-list. To compile YOUR world, copy the wasm-gen driver into this")
	print("     package (it reads project.json beside itself — no edits).")
	print(f"  4. the lint row: a `run {camel} {camel} {camel}Fn` line in the lean-lint recipe (justfile).")
	print(f"  then: just gen && just gates — details in lean/{name}/README.md")

# new-project-clean: undo new-project (the scaffold-test cleanup): remove
# lean/<name> and revert BOTH auto-registrations.
new-project-clean name:
	#!/usr/bin/env python3
	import os, re, shutil, sys
	name = "{{name}}"
	root = "{{justfile_directory()}}"
	camel = "".join(p.capitalize() for p in name.split("-"))
	pkg = os.path.join(root, "lean", name)
	if os.path.isdir(pkg):
	    shutil.rmtree(pkg)
	    print(f"new-project-clean: removed lean/{name}")
	else:
	    print(f"new-project-clean: lean/{name} absent (nothing to remove)")
	jf = os.path.join(root, "justfile")
	s = open(jf).read()
	s2 = re.sub(r'(lean_pkgs := "[^"]*?) ' + name + '"', r'\1"', s)
	if s2 != s:
	    open(jf, "w").write(s2)
	    print("new-project-clean: reverted lean_pkgs (justfile)")
	pf = os.path.join(root, "lean", "LintKit", "LintKit", "PackageNamespace.lean")
	s = open(pf).read()
	s2 = re.sub(r"\n  \(`" + camel + r", +\[`" + camel + r"\]\),", "", s)
	s2 = re.sub(r"\n  \(`" + camel + r"Fn, +\[`" + camel + r"Fn\]\)\n\]", "\n]", s2)
	if s2 != s:
	    open(pf, "w").write(s2)
	    print("new-project-clean: reverted packagePrefixes (LintKit)")

# Self-verifying scaffold demo: scaffold → register → inventory → build
# → axiom gate → clean. NOT in gates (the tree-mutation round-trip).
scaffold-test:
	#!/usr/bin/env bash
	set -euo pipefail
	TC="{{lean_tc}}"
	just new-project demo-scaffold-test
	[ -f lean/demo-scaffold-test/lakefile.toml ] || { echo "FAIL: package dir missing"; exit 1; }
	if grep -rn --exclude-dir=.lake "Thing" lean/demo-scaffold-test; then
	  echo "FAIL: unreplaced Thing placeholder"; exit 1
	fi
	just lean-pkg-inventory
	(cd lean/demo-scaffold-test && PATH="$TC:$PATH" "$TC/lake" build)
	(cd lean/demo-scaffold-test && PATH="$TC:$PATH" "$TC/lake" env lean Tests/Axioms.lean)
	just new-project-clean demo-scaffold-test
	[ ! -d lean/demo-scaffold-test ] || { echo "FAIL: cleanup left the dir"; exit 1; }
	grep -E '^lean_pkgs := ".*demo-scaffold-test' justfile >/dev/null && { echo "FAIL: lean_pkgs not reverted"; exit 1; } || true
	grep -q "DemoScaffoldTest" lean/LintKit/LintKit/PackageNamespace.lean && { echo "FAIL: packagePrefixes not reverted"; exit 1; } || true
	echo "scaffold-test: round-trip green (scaffold → inventory → build → axiom gate → clean)"


# ── The mutation battery (test-the-tests — on-demand, NOT in gates) ──
# The gates claim to CATCH drift; this battery PROVES the teeth: for
# each gate, ONE engineered mutation that the gate MUST fail (red),
# then a hash-verified revert. A gate that stays green under its
# mutation is ceremony — the battery reports MUTATION NOT CAUGHT and
# exits 1. Run: `just mutation-proof` (expect several minutes; the
# oracle mutation rebuilds DemoFn + the steel-host replay).
mutation-proof:
	#!/usr/bin/env bash
	set -uo pipefail
	TC="{{lean_tc}}"
	ROOT="{{justfile_directory()}}"
	cd "$ROOT"
	PCC="$ROOT/.devenv/profiles/wasm/profile/bin/cc"
	BAK=target/mutation-bak
	mkdir -p "$BAK"
	fail=0

	save() { cp "$1" "$BAK/$(echo "$1" | tr '/' '_')"; }
	# Revert ONE mutated file: jj restore (the working copy IS a commit)
	# when tracked in the parent; a backup copy when the file is NEW in
	# the working copy (jj restore would delete it). Either way the
	# restoration is hash-verified — a mutated tree never survives.
	unmutate() {
	  local f="$1" key have want
	  key=$(echo "$f" | tr '/' '_')
	  if jj file list -r @- 2>/dev/null | grep -Fxq "$f"; then
	    jj restore "$f"
	    want=$(jj file show -r @- "$f" | sha256sum | cut -d' ' -f1)
	    have=$(sha256sum "$f" | cut -d' ' -f1)
	    [ "$want" = "$have" ] || { echo "FAIL: $f NOT restored"; exit 1; }
	    echo "reverted: $f (jj restore, hash-verified vs @-)"
	  else
	    cp "$BAK/$key" "$f"
	    have=$(sha256sum "$f" | cut -d' ' -f1)
	    [ "$have" = "$(sha256sum "$BAK/$key" | cut -d' ' -f1)" ] || { echo "FAIL: $f NOT restored"; exit 1; }
	    echo "reverted: $f (backup copy, hash-verified — file is new in the working copy)"
	  fi
	}
	# The mutation MUST fail its gate: gate exiting 0 = NOT CAUGHT.
	must_fail() {
	  local name="$1"; shift
	  if "$@"; then
	    echo "MUTATION NOT CAUGHT: $name"; fail=1
	  else
	    echo "caught: $name (gate went red as required)"
	  fi
	}

	# ── (a) BYTE-TIE vs `just gen-check` ──────────────────────────────
	# Corrupt a COMMITTED generated artifact: the byte-tie must reject.
	echo "── (a) byte-tie: append a byte to src/schema_generated.rs ──"
	f=src/schema_generated.rs
	save "$f"
	printf 'X' >> "$f"
	must_fail "byte-tie (gen-check)" \
	  devenv shell --profile wasm -- bash -c "export CC=$PCC; cargo run -p forge -- gen --check"
	unmutate "$f"
	grep -q "X$" "$f" && { echo "FAIL: $f still mutated (grep)"; exit 1; } || true

	# ── (b) ELAB GATE vs the flags build ─────────────────────────────
	# Misspell the key-nonempty invariant's column: the HasCol instance
	# search finds nothing — the module must FAIL TO BUILD.
	echo "── (b) elab gate: key → kye in the key-nonempty invariant ──"
	f=lean/feature-flags/FeatureFlags.lean
	save "$f"
	<<-'PYEOF' "$PCC/../python3" - "$f" || { echo "FAIL: apply failed"; exit 1; }
	import sys
	p = sys.argv[1]
	s = open(p).read()
	old = 'schema_invariant "key-nonempty" for Flag :=\n  SchemaLang.VExpr.gt (SchemaLang.VExpr.strlen (SchemaLang.VExpr.colOf "key"))'
	assert s.count(old) == 1, "anchor not found exactly once"
	open(p, "w").write(s.replace(old, old.replace('"key"', '"kye"')))
	PYEOF
	must_fail "elab gate (HasCol miss)" \
	  bash -c "cd lean/feature-flags && PATH='$TC:'$PATH '$TC/lake' build"
	unmutate "$f"
	grep -q '"kye"' "$f" && { echo "FAIL: $f still mutated (grep)"; exit 1; } || true

	# ── (c) AXIOM GATE vs the lean-axioms loop body ──────────────────
	# Inject a sorry theorem: the axiom check must flag sorryAx. Runs
	# the lean-axioms BODY for one package (feature-flags), not the loop.
	echo "── (c) axiom gate: inject theorem bad : True := by sorry ──"
	f=lean/feature-flags/Tests/Axioms.lean
	save "$f"
	printf '\ntheorem bad : True := by sorry\n' >> "$f"
	out=$(cd lean/feature-flags && PATH="$TC:$PATH" "$TC/lake" env lean Tests/Axioms.lean 2>&1 || true)
	if echo "$out" | grep -q "sorryAx"; then
	  echo "caught: axiom gate (sorryAx flagged)"
	else
	  echo "MUTATION NOT CAUGHT: axiom gate"; fail=1
	fi
	unmutate "$f"
	grep -q "by sorry" "$f" && { echo "FAIL: $f still mutated (grep)"; exit 1; } || true

	# ── (d) THE ORACLE vs the differential duel ──────────────────────
	# Corrupt the demo impl's strlen semantics (+1): Lean's evals seed the
	# regenerated manifest; the wasm side still computes the real length —
	# the differential replay MUST diverge. (The manifest itself is
	# regenerated by `lake exe oracle` — so the IMPLEMENTATION is
	# the mutation surface; the manifest can never go stale.) Scratch
	# note: diff.json is regenerated UNDER the mutation — rerun `just
	# wasm-compile` clean before the next steel-host replay.
	echo "── (d) the oracle: strlen +1 in GuestlangStd.StrOps ──"
	f=lean/std/GuestlangStd/StrOps.lean
	save "$f"
	<<-'PYEOF' "$PCC/../python3" - "$f" || { echo "FAIL: apply failed"; exit 1; }
	import sys
	p = sys.argv[1]
	s = open(p).read()
	old = "def strlen (s : String) : UInt64 := s.length.toUInt64"
	assert s.count(old) == 1, "anchor not found exactly once"
	open(p, "w").write(s.replace(old, old + " + 1"))
	PYEOF
	must_fail "differential duel (wasm_diff)" \
	  devenv shell --profile wasm -- bash -c "export CC=$PCC; just wasm-compile && cargo test -p steel-host --test wasm_diff"
	unmutate "$f"
	# wasm-compile's regen rewrote the observability surface's volatile
	# header (wall-clock) — restore the committed bytes.
	jj restore src/observability_generated.rs 2>/dev/null || true
	grep -q "s.length.toUInt64 + 1" "$f" && { echo "FAIL: $f still mutated (grep)"; exit 1; } || true

	# ── (e) THE COMPAT GATE vs `just breaking` ───────────────────────
	# Add a field to the demo's User record: the snapshot diff must
	# classify it as a shaped change (BREAKING, unremedied) → exit 1.
	echo "── (e) compat gate: User gains extra : UInt64 ──"
	f=lean/schema-lang/Demo.lean
	save "$f"
	<<-'PYEOF' "$PCC/../python3" - "$f" || { echo "FAIL: apply failed"; exit 1; }
	import sys
	p = sys.argv[1]
	s = open(p).read()
	old = """structure User where
	  id : UInt64
	  name : String
	  email : String
	  tags : List String"""
	assert s.count(old) == 1, "anchor not found exactly once"
	open(p, "w").write(s.replace(old, old + "\n  extra : UInt64"))
	PYEOF
	must_fail "compat gate (breaking)" just breaking
	unmutate "$f"
	grep -q "extra : UInt64" "$f" && { echo "FAIL: $f still mutated (grep)"; exit 1; } || true

	echo
	if [ "$fail" != 0 ]; then
	  echo "mutation-proof: RED — a gate missed its mutation (ceremony)"
	  exit 1
	fi
	echo "mutation-proof: 5/5 gates caught their engineered mutations"


# ── Size/perf budget gates — tighten on sight; loosening needs a commit message justification ──
#
# Budgets as of 2026-09-17:
#   SIZE: lean/wasm-backend/target/demo.component.wasm = 52524 bytes -> budget 80000 (1.5x rounded up)
#   2026-09-18 loosened to 175000: the guest gained the witness-verification
#   lane (W9.6: the checker + decode lane + streq/bounded-Nat lowerings are
#   COMPILED INTO the guest now) — 115246 bytes actual. Ratchet rule stands:
#   tighten on sight; further loosening needs a commit-message justification.
#   PERF: double(21) median @ 20 runs = 0.044s -> budget 0.135s (3x rounded up)
#
budget-check:
	#!/usr/bin/env bash
	set -euo pipefail
	WTS=$(command -v wasmtime || true)
	[ -x "$WTS" ] || WTS=$(find /nix/store -maxdepth 3 -name wasmtime -type f 2>/dev/null | head -1)
	[ -x "$WTS" ] || { echo "FAIL: wasmtime not found in PATH or nix store"; exit 1; }
	COMP=lean/wasm-backend/target/demo.component.wasm
	[ -f "$COMP" ] || { echo "FAIL: $COMP missing - run 'just wasm-compile'"; exit 1; }
	SIZE_BUDGET=175000
	PERF_BUDGET_SEC=0.135
	fail=0
	# SIZE check
	actual=$(stat --format=%s "$COMP")
	echo "size: $actual bytes (budget $SIZE_BUDGET)"
	if [ "$actual" -gt "$SIZE_BUDGET" ]; then
	  echo "FAIL: size $actual > budget $SIZE_BUDGET"
	  fail=1
	else
	  echo "  ok: $actual <= $SIZE_BUDGET"
	fi
	# PERF smoke: instantiate + invoke double(21) 20x, compute median wall time
	raw=$(mktemp)
	trap "rm -f $raw" EXIT
	for i in $(seq 1 20); do
	  T0=$(date +%s%N)
	  result=$("$WTS" run --invoke 'double(21)' "$COMP" 2>/dev/null)
	  T1=$(date +%s%N)
	  [ "$result" = 42 ] || { echo "FAIL: double(21) returned $result (expected 42)"; exit 1; }
	  echo $((T1 - T0)) >> "$raw"
	done
	sort -n "$raw" > "$raw.sorted"
	p10=$(awk 'NR==10{print; exit}' "$raw.sorted")
	p11=$(awk 'NR==11{print; exit}' "$raw.sorted")
	median_ns=$(( (p10 + p11) / 2 ))
	median_sec=$(awk -v ns="$median_ns" 'BEGIN{printf "%.3f", ns/1e9}')
	echo "perf: $median_sec s median over 20 runs (budget $PERF_BUDGET_SEC s)"
	budget_ns=$(awk -v b="$PERF_BUDGET_SEC" 'BEGIN{printf "%d", b*1e9 + 0.5}')
	if [ "$median_ns" -gt "$budget_ns" ]; then
	  echo "FAIL: median $median_sec s > budget $PERF_BUDGET_SEC s"
	  fail=1
	else
	  echo "  ok: $median_sec s <= $PERF_BUDGET_SEC s"
	fi
	[ "$fail" = 0 ] || { echo "budget-check: RED"; exit 1; }
	echo "budget-check: green - size + perf within budgets"

# The WASM-COMPILE byte-tie (was the byte-tie's hole — review
# 2026-09-16): the pipeline's committed outputs must match a fresh regen.
# Volatile: the 2-line GENERATED headers (timestamp + spec sha);
# target/diff.json is deterministic (proved by 2× regen 2026-09-17).
wasm-diff-check:
	#!/usr/bin/env bash
	set -euo pipefail
	D=lean/wasm-backend/target/wasm-diff-check
	mkdir -p "$D"
	cp lean/wasm-backend/demo-world.wit "$D/demo-world.wit.committed"
	cp src/observability_generated.rs "$D/observability_generated.rs.committed"
	cp lean/wasm-backend/target/diff.json "$D/diff.json.committed"
	just wasm-compile
	cmp -s lean/wasm-backend/target/diff.json "$D/diff.json.committed" \
	  || { echo "FAIL: target/diff.json drifted — regenerate (just wasm-compile) + commit"; exit 1; }
	for f in "lean/wasm-backend/demo-world.wit" "src/observability_generated.rs"; do
	  b=$(basename "$f")
	  if ! cmp -s <(tail -n +3 "$f") <(tail -n +3 "$D/$b.committed"); then
	    echo "FAIL: $f drifted from the committed surface — regenerate (just wasm-compile) + commit"
	    exit 1
	  fi
	done
	echo "wasm-diff-check: clean — all wasm-compile committed outputs match"
