// GENERATED by schema (lean-4.33.0) at - — DO NOT EDIT
// spec unknown | SchemaCore.Slice | 2 item(s) | content hash 17845240631642103753 | regen: just gen; drift fails CI
//! GENERATED commit-slice consumer (SchemaCore.Commit's duel —
//! notes/v3/03 section 3's DIFFERENTIAL level). The duel directory
//! tests/duel-commit/ carries the proposal vectors plus manifest.txt
//! (the generator row + one `<path>	<expectation>` row per vector),
//! all emitted by SchemaCore.Commit's duel emitter and committed
//! through the byte-tie — never hand-written, never hand-edited.
//!
//! THE SLICE (03 section 9): the handwritten command proposes a
//! delta; the violation queries check the post-state; the
//! transactional adapter commits against the SAME snapshot version.
//! This test is the Rust half: it re-proposes each committed delta
//! byte-identically and must agree verdict-for-verdict with the
//! Lean-side golden. Tested agreement — never a theorem; the
//! runtime-checked transition is the wasm wave's content.

use schema_generated::{dec_u64, enc_varint};

/// The duel manifest, compile-time pinned to the committed artifact.
const MANIFEST: &str = include_str!("duel-commit/manifest.txt");

/// The generated crate's repo-root prefix (the manifest's rows are
/// repo-root-relative; the test binary's cwd is the crate root).
const CRATE_PREFIX: &str = "crates/schema-generated/";

/// Kit.Duel's consumer contract: skip the 2-line GENERATED header and
/// the `generator` provenance row, split each row on the tab.
fn manifest_rows() -> Vec<(String, Option<String>)> {
    MANIFEST
        .lines()
        .skip(2)
        .filter(|line| !line.is_empty() && !line.starts_with("generator	"))
        .map(|line| {
            let mut parts = line.split('\t');
            let path = parts.next().expect("manifest row: path").to_string();
            let expect = parts.next().expect("manifest row: expectation");
            (path, expect.strip_prefix("decode ").map(str::to_string))
        })
        .collect()
}

/// Re-base a manifest row's repo-root-relative path to the crate root.
fn crate_path(row_path: &str) -> &str {
    match row_path.strip_prefix(CRATE_PREFIX) {
        Some(p) => p,
        None => row_path,
    }
}

/// The fixture mirror (SchemaCore.Commit's fixtureSnap): version 1,
/// two accounts, an empty ledger.
#[derive(Clone)]
struct Account {
    id: u64,
    balance: i64,
}

fn fixture() -> (u64, Vec<Account>, Vec<(u64, u64, u64, u64)>) {
    (
        1,
        vec![Account { id: 1, balance: 100 }, Account { id: 2, balance: 50 }],
        vec![],
    )
}

/// THE HANDWRITTEN COMMAND (03 section 3): a Rust-side transfer
/// between two accounts, PROPOSED on the wire (base, tid, src, dst,
/// amount — five canonical varints, the generated encoder's).
fn propose_transfer(base: u64, tid: u64, src: u64, dst: u64, amount: u64) -> Vec<u8> {
    let mut out = Vec::new();
    enc_varint(base, &mut out);
    enc_varint(tid, &mut out);
    enc_varint(src, &mut out);
    enc_varint(dst, &mut out);
    enc_varint(amount, &mut out);
    out
}

/// Decode a proposal off the wire (five varints; a truncated or
/// non-canonical vector is a typed None, never a panic).
fn dec_proposal(bs: &[u8]) -> Option<(u64, u64, u64, u64, u64)> {
    let mut rest: &[u8] = bs;
    let base = dec_u64(&mut rest).ok()?;
    let tid = dec_u64(&mut rest).ok()?;
    let src = dec_u64(&mut rest).ok()?;
    let dst = dec_u64(&mut rest).ok()?;
    let amount = dec_u64(&mut rest).ok()?;
    Some((base, tid, src, dst, amount))
}

/// The violation queries' mirror over the POST-STATE (the honest
/// first cut: full recomputation — the change-proportional face is
/// the dbsp-circuit wave's `incrementalize_ok`, named not faked).
fn violations(accounts: &[Account], transfers: &[(u64, u64, u64, u64)]) -> Vec<String> {
    let ids: Vec<u64> = accounts.iter().map(|a| a.id).collect();
    let mut out: Vec<String> = Vec::new();
    for id in &ids {
        if ids.iter().filter(|k| **k == *id).count() > 1 {
            out.push(format!("duplicate account id {}", id));
        }
    }
    for a in accounts {
        if a.balance < 0 {
            out.push(format!("negative balance: id {} balance {}", a.id, a.balance));
        }
    }
    for (tid, src, dst, _amount) in transfers {
        if !ids.contains(src) {
            out.push(format!("unresolved src: tid {}", tid));
        }
        if !ids.contains(dst) {
            out.push(format!("unresolved dst: tid {}", tid));
        }
    }
    out
}

/// The transactional adapter's mirror: the stale snapshot refuses
/// FIRST (03 section 3's race-honesty); the proposed delta applies to
/// a WORKING COPY (external effects never occur before authorization);
/// the violation query over the post-state decides; empty permits the
/// commit (apply + bump the version).
fn commit(
    version: &mut u64,
    accounts: &mut Vec<Account>,
    transfers: &mut Vec<(u64, u64, u64, u64)>,
    base: u64,
    tid: u64,
    src: u64,
    dst: u64,
    amount: u64,
) -> Result<(), String> {
    if base != *version {
        return Err(format!("stale {} vs {}", base, *version));
    }
    let mut accounts2 = accounts.clone();
    let mut transfers2 = transfers.clone();
    transfers2.push((tid, src, dst, amount));
    let amt = amount as i64;
    for a in accounts2.iter_mut() {
        if a.id == src {
            a.balance -= amt;
        }
        if a.id == dst && src != dst {
            a.balance += amt;
        }
    }
    let vs = violations(&accounts2, &transfers2);
    if vs.is_empty() {
        *accounts = accounts2;
        *transfers = transfers2;
        *version += 1;
        Ok(())
    } else {
        Err(format!("invalid: {:?}", vs))
    }
}

/// THE DUEL: every vector is re-proposed byte-identically (one wire,
/// two sides) and the adapter's verdict must match the manifest's
/// expectation. The duel must exercise BOTH verdicts.
#[test]
fn commit_duel() {
    let mut saw_accept = false;
    let mut saw_refuse = false;
    for (path, note) in manifest_rows() {
        let bytes = std::fs::read(crate_path(&path)).expect("duel vector file present");
        let (base, tid, src, dst, amount) = dec_proposal(&bytes)
            .unwrap_or_else(|| panic!("proposal {} does not decode", path));
        assert_eq!(
            propose_transfer(base, tid, src, dst, amount),
            bytes,
            "propose drift at {}",
            path
        );
        let (mut version, mut accounts, mut transfers) = fixture();
        let verdict = match commit(&mut version, &mut accounts, &mut transfers, base, tid, src, dst, amount) {
            Ok(()) => "accept",
            Err(_) => "refuse",
        };
        match &note {
            Some(n) if n == "accept" => {
                assert_eq!(verdict, "accept", "{}: expected accept", path);
                saw_accept = true;
            }
            None => {
                assert_eq!(verdict, "refuse", "{}: expected refuse", path);
                saw_refuse = true;
            }
            Some(n) => panic!("{}: unknown expectation {}", path, n),
        }
    }
    assert!(saw_accept && saw_refuse, "the duel must exercise both verdicts");
}

/// THE NEGATIVE CONTROL (the stale face): the stale vector's refusal
/// names STALENESS — a stale commit refuses on the VERSION, never on
/// the content.
#[test]
fn stale_refusal_names_staleness() {
    let mut found = false;
    for (path, note) in manifest_rows() {
        if note.is_some() {
            continue;
        }
        let bytes = std::fs::read(crate_path(&path)).expect("duel vector file present");
        let (base, tid, src, dst, amount) = dec_proposal(&bytes)
            .unwrap_or_else(|| panic!("proposal {} does not decode", path));
        let (mut version, mut accounts, mut transfers) = fixture();
        if base != version {
            found = true;
            match commit(&mut version, &mut accounts, &mut transfers, base, tid, src, dst, amount) {
                Err(e) => assert!(
                    e.starts_with("stale"),
                    "{}: wrong refusal reason: {}",
                    path,
                    e
                ),
                Ok(()) => panic!("{}: a stale proposal committed", path),
            }
        }
    }
    assert!(found, "the duel carries no stale vector");
}

/// THE NEGATIVE CONTROL (the refuse-with-rows face): an invalid
/// proposal's refusal carries the VIOLATING ROW as data (the payload
/// names the negative balance or the unresolved endpoint — 02's
/// discipline, never a bare false).
#[test]
fn invalid_refusal_carries_the_violating_row() {
    let mut found = false;
    for (path, note) in manifest_rows() {
        if note.is_some() {
            continue;
        }
        let bytes = std::fs::read(crate_path(&path)).expect("duel vector file present");
        let (base, tid, src, dst, amount) = dec_proposal(&bytes)
            .unwrap_or_else(|| panic!("proposal {} does not decode", path));
        let (mut version, mut accounts, mut transfers) = fixture();
        if base == version {
            match commit(&mut version, &mut accounts, &mut transfers, base, tid, src, dst, amount) {
                Err(e) => {
                    if e.starts_with("invalid") {
                        found = true;
                        assert!(
                            e.contains("negative balance") || e.contains("unresolved"),
                            "{}: the refusal lost the row: {}",
                            path,
                            e
                        );
                    }
                }
                Ok(()) => {}
            }
        }
    }
    assert!(found, "the duel carries no invalid vector");
}

/// THE NEGATIVE CONTROL (the differential's tooth): a tampered vector
/// MISSES the proposal — the flipped bytes either refuse to decode or
/// re-propose differently (a differential that cannot see a flip
/// proves nothing).
#[test]
fn tampered_vector_misses_the_proposal() {
    let mut exercised = false;
    for (path, note) in manifest_rows() {
        if note.is_none() {
            continue;
        }
        let orig = std::fs::read(crate_path(&path)).expect("duel vector file present");
        let mut bytes = orig.clone();
        let last = bytes.len() - 1;
        bytes[last] ^= 0x01;
        match dec_proposal(&bytes) {
            None => exercised = true, // the flip broke the varint — the typed refusal IS the pass
            Some((base, tid, src, dst, amount)) => {
                exercised = true;
                assert_ne!(
                    propose_transfer(base, tid, src, dst, amount),
                    orig,
                    "{}: tampered bytes re-proposed the committed vector",
                    path
                );
            }
        }
    }
    assert!(exercised, "the duel carries no accept vector to tamper");
}
