// GENERATED by schema (lean-4.33.0) at - — DO NOT EDIT
// spec unknown | SchemaCore.Slice | 2 item(s) | content hash 16980019741909676759 | regen: just gen; drift fails CI
//! GENERATED differential vectors + the Rust half of the Lean<->Rust
//! codec correspondence (notes/v3/03 section 3's differential level).
//! The vectors ride Kit.Duel's vector-set convention: the duel
//! directory tests/duel/ carries the vector files plus manifest.txt
//! (the generator row + one `<path>	<expectation>` row per vector),
//! all emitted by SchemaCore.Emit.Rust's duel emitter and committed
//! through the byte-tie — never hand-written, never hand-edited.

use schema_generated::{dec_bool, dec_i64, dec_string, dec_u64, enc_str,
  enc_varint, zigzag_i64, Example};

/// The duel manifest, compile-time pinned to the committed artifact.
const MANIFEST: &str = include_str!("duel/manifest.txt");

/// The generated crate's repo-root prefix (the manifest's rows are
/// repo-root-relative; the test binary's cwd is the crate root).
const CRATE_PREFIX: &str = "crates/schema-generated/";

/// One parsed manifest row: the vector path + the decode note (None =
/// the row expects a typed refusal).
struct Row {
    path: String,
    note: Option<String>,
}

/// Kit.Duel's consumer contract: skip the 2-line GENERATED header and
/// the `generator` provenance row, split each row on the tab.
fn manifest_rows() -> Vec<Row> {
    MANIFEST
        .lines()
        .skip(2)
        .filter(|line| !line.is_empty() && !line.starts_with("generator\t"))
        .map(|line| {
            let mut parts = line.split('\t');
            let path = parts.next().expect("manifest row: path").to_string();
            let expect = parts.next().expect("manifest row: expectation");
            Row { path, note: expect.strip_prefix("decode ").map(str::to_string) }
        })
        .collect()
}

/// Re-base a manifest row's repo-root-relative path to the crate root.
fn crate_path(row_path: &str) -> &str {
    match row_path.strip_prefix(CRATE_PREFIX) {
        Some(p) => p,
        None => row_path,
    }
}

/// The parsed atom pin (the manifest's `decode atom ...` note IS the
/// value-level pin — a drift from the bytes fails the test loudly).
#[derive(Debug, PartialEq, Eq)]
enum Atom {
    Bool(bool),
    U64(u64),
    I64(i64),
    Str(String),
}

fn parse_atom(note: &str) -> Option<Atom> {
    let rest = note.strip_prefix("atom ")?;
    let mut parts = rest.splitn(2, ' ');
    let kind = parts.next()?;
    let value = parts.next()?;
    match kind {
        "bool" => Some(Atom::Bool(value == "true")),
        "u64" => Some(Atom::U64(value.parse().ok()?)),
        "i64" => Some(Atom::I64(value.parse().ok()?)),
        "str" => Some(Atom::Str(value.to_string())),
        _ => None,
    }
}

/// The pinned Example row (the value the example_row bytes denote).
fn pinned_example() -> Example {
    Example {
        ready: true,
        count: 300,
        delta: -1,
        label: "hi".to_string(),
        note: Some("note".to_string()),
        tags: vec!["a".to_string(), "b".to_string()],
    }
}

/// BOTH directions on every `decode atom ...` row: bytes -> value
/// (decode, against the manifest's parsed pin), value -> bytes
/// (re-encode, byte-identical).
#[test]
fn manifest_atoms_decode_and_reencode() {
    for row in manifest_rows() {
        let note = match &row.note { Some(n) => n, None => continue };
        let pin = match parse_atom(note) { Some(a) => a, None => continue };
        let bytes = std::fs::read(crate_path(&row.path))
            .expect("duel vector file present");
        let mut rest: &[u8] = &bytes;
        let mut out = Vec::new();
        match pin {
            Atom::Bool(v) => {
                let got = dec_bool(&mut rest)
                    .unwrap_or_else(|e| panic!("atom {} refused: {e:?}", row.path));
                assert_eq!(got, v, "atom {} value drifted", row.path);
                out.push(if got { 1u8 } else { 0u8 });
            }
            Atom::U64(v) => {
                let got = dec_u64(&mut rest)
                    .unwrap_or_else(|e| panic!("atom {} refused: {e:?}", row.path));
                assert_eq!(got, v, "atom {} value drifted", row.path);
                enc_varint(got, &mut out);
            }
            Atom::I64(v) => {
                let got = dec_i64(&mut rest)
                    .unwrap_or_else(|e| panic!("atom {} refused: {e:?}", row.path));
                assert_eq!(got, v, "atom {} value drifted", row.path);
                enc_varint(zigzag_i64(got), &mut out);
            }
            Atom::Str(v) => {
                let got = dec_string(&mut rest)
                    .unwrap_or_else(|e| panic!("atom {} refused: {e:?}", row.path));
                assert_eq!(&got, &v, "atom {} value drifted", row.path);
                enc_str(got.as_str(), &mut out);
            }
        }
        assert!(rest.is_empty(), "atom {} left {rest:?} unconsumed", row.path);
        assert_eq!(out, bytes, "re-encode drifted for {}", row.path);
    }
}

/// BOTH directions on the `decode example` row: bytes -> Example
/// (decode), Example -> bytes (re-encode, byte-identical).
#[test]
fn manifest_rows_decode_and_reencode() {
    for row in manifest_rows() {
        if row.note.as_deref() != Some("example") { continue; }
        let bytes = std::fs::read(crate_path(&row.path))
            .expect("duel vector file present");
        let mut rest: &[u8] = &bytes;
        let value = Example::decode(&mut rest)
            .unwrap_or_else(|e| panic!("golden vector {} refused: {e:?}", row.path));
        assert!(
            rest.is_empty(),
            "golden vector {} left {rest:?} unconsumed", row.path
        );
        let mut out = Vec::new();
        value.encode(&mut out);
        assert_eq!(out, bytes, "re-encode drifted for {}", row.path);
    }
}

/// The example_row's bytes denote the PINNED value (the decode
/// direction at the value level, not just shape).
#[test]
fn example_row_denotes_the_pinned_value() {
    let row = manifest_rows()
        .into_iter()
        .find(|r| r.note.as_deref() == Some("example"))
        .expect("the manifest carries the example row");
    let bytes = std::fs::read(crate_path(&row.path))
        .expect("duel vector file present");
    let mut rest: &[u8] = &bytes;
    let value = Example::decode(&mut rest).expect("example_row decodes");
    assert_eq!(value, pinned_example());
}

/// The append-form law's Rust mirror: the encoding plus ANY suffix
/// decodes to the value plus the suffix (Pattern #2's composition).
#[test]
fn decode_is_append_form() {
    let row = manifest_rows()
        .into_iter()
        .find(|r| r.note.as_deref() == Some("example"))
        .expect("the manifest carries the example row");
    let mut bytes = std::fs::read(crate_path(&row.path))
        .expect("duel vector file present");
    bytes.push(0xFF);
    let mut rest: &[u8] = &bytes;
    let value = Example::decode(&mut rest)
        .unwrap_or_else(|e| panic!("append-form failed: {e:?}"));
    assert_eq!(value, pinned_example());
    assert_eq!(rest, &[0xFFu8]);
}

/// THE NEGATIVE CONTROL: every `refuse` row REFUSES — a typed
/// CodecError, never a panic, never a silent misparse.
#[test]
fn manifest_refuse_rows_refuse() {
    for row in manifest_rows() {
        if row.note.is_some() { continue; }
        let bytes = std::fs::read(crate_path(&row.path))
            .expect("duel vector file present");
        match Example::decode_full(&bytes) {
            Ok(_) => panic!("tampered vector {} decoded — the wire gate has a hole", row.path),
            Err(_) => {} // the typed refusal is the pass
        }
    }
}
