// GENERATED by schema (lean-4.33.0) at - — DO NOT EDIT
// spec unknown | SchemaCore.Slice | 2 item(s) | content hash 9621610023799999956 | regen: just gen; drift fails CI
//! GENERATED e2e validator — the twin-world discipline (wave-30 C2):
//! two loads of the same seeded log produce IDENTICAL state hashes at
//! EVERY step (the machines' determinism discipline, cited); the
//! per-rule expected values are pinned with notes.
//!
//! CI runs THIS (`just rust` — cargo test); the benches are the perf
//! face, run on demand (`just bench`).
//!
//! THE HASH: Kit.Emit.bytesHash's fold — TestingKit's Knuth-64 LCG
//! (h = (h + b) * 6364136223846793005 + 1442695040888963407,
//! wrapping, seeded 1442695040888963407) over the state's wire bytes.
//! ONE hash, both worlds compute it identically; a divergent step is
//! a loud per-step refusal, never a silent skew.

use mandate_delta::delta::{Table, dec_journal, enc_journal};
use mandate_delta::schema::{enc_row, fixtures};
use mandate_delta::{Delta, Row, Schema, Value};
use schema_generated::Example;

/// The registered schema items (the emitter's provenance face — the
/// validator is generated PER SCHEMA; a registry drift regenerates
/// THIS file and the pins move with it). 2 item(s): Example, ExampleEx.
const SCHEMA_ITEMS: [&str; 2] = ["Example", "ExampleEx"];

/// Kit.Emit.bytesHash's fold (the ONE hash — see the module header).
fn bytes_hash(bs: &[u8]) -> u64 {
    bs.iter().fold(1442695040888963407u64, |h, b| {
        (h + *b as u64)
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407)
    })
}

struct Lcg(u64);
impl Lcg {
    fn next(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        self.0
    }
    /// The tape's byte face (the top 8 bits — TestingKit.Tape.byte).
    fn byte(&mut self) -> u8 {
        (self.next() >> 56) as u8
    }
    /// The tape's below face (the high bits mod bound —
    /// TestingKit.Tape.below; modulo bias accepted for test data).
    fn below(&mut self, bound: u64) -> u64 {
        (self.next() >> 16) % bound
    }
}

/// The seeded op log over the generated codec face (`Example`, the
/// declared key `label`): tag 0/1 = insert/update (keyed upsert),
/// 2 = remove. ONE tape — same seed, same log, both worlds.
fn seeded_ops(n: usize, seed: u64) -> Vec<(u8, Example)> {
    let mut t = Lcg(seed);
    let mut out = Vec::with_capacity(n);
    for _ in 0..n {
        let tag = t.byte() % 3;
        let ready = t.byte() & 1 == 1;
        let count = t.next();
        let delta = (t.next() >> 1) as i64;
        let label = format!("k{}", t.below(16));
        let note = if t.byte() & 1 == 1 {
            Some(format!("n{}", t.below(1024)))
        } else {
            None
        };
        let ntags = t.below(4);
        let mut tags = Vec::new();
        for _ in 0..ntags {
            tags.push(format!("t{}", t.below(32)));
        }
        out.push((tag, Example { ready, count, delta, label, note, tags }));
    }
    out
}

/// The keyed application (the delta semantics over the codec face —
/// `SchemaCore.deltaApply`'s keyed upsert/erase).
fn apply(rows: &mut Vec<Example>, tag: u8, row: Example) {
    match tag {
        0 | 1 => match rows.iter().position(|r| r.label == row.label) {
            Some(i) => rows[i] = row,
            None => rows.push(row),
        },
        _ => {
            if let Some(i) = rows.iter().position(|r| r.label == row.label) {
                rows.remove(i);
            }
        }
    }
}

/// The codec-face state hash: the state's wire bytes (each row's
/// `encode` in table order) through the ONE hash.
fn state_hash(rows: &[Example]) -> u64 {
    let mut wire = Vec::new();
    for r in rows {
        r.encode(&mut wire);
    }
    bytes_hash(&wire)
}

/// The journal-face state hash: each row's `enc_row` bytes through
/// the ONE hash.
fn journal_state_hash(schema: &Schema, rows: &[Row]) -> u64 {
    let mut wire = Vec::new();
    for r in rows {
        enc_row(r, &mut wire);
    }
    bytes_hash(&wire)
}

/// The seeded delta log over the fixture schema (the journal face's
/// twin world — ONE tape, both loads).
fn seeded_deltas(n: usize, seed: u64) -> Vec<Delta> {
    let mut t = Lcg(seed);
    let mut out = Vec::with_capacity(n);
    for _ in 0..n {
        let id = t.below(64);
        let name = format!("n{}", t.below(1024));
        out.push(match t.byte() % 3 {
            0 => Delta::Insert(fixtures::fixture_row(id, &name)),
            1 => Delta::Update(fixtures::fixture_row(id, &name)),
            _ => Delta::Remove(Value::U64(id)),
        });
    }
    out
}

/// TWIN WORLD, codec face: world A applies the log directly; world B
/// loads each op through the GENERATED wire (encode → decode_full)
/// before applying. Identical state hashes at EVERY step — the seed's
/// chain tail is the PINNED known answer (4693743145306144929).
#[test]
fn twin_world_codec() {
    let ops = seeded_ops(96, 300);
    let mut world_a: Vec<Example> = Vec::new();
    let mut world_b: Vec<Example> = Vec::new();
    for (step, (tag, row)) in ops.iter().enumerate() {
        apply(&mut world_a, *tag, row.clone());
        let mut wire = Vec::new();
        row.encode(&mut wire);
        let back = Example::decode_full(&wire).expect("the log decodes");
        apply(&mut world_b, *tag, back);
        assert_eq!(
            state_hash(&world_a),
            state_hash(&world_b),
            "twin worlds diverged at step {} (same seed, two loads)",
            step
        );
    }
    assert_eq!(
        state_hash(&world_a),
        4693743145306144929,
        "the codec-face chain tail left its pinned known answer"
    );
}

/// TWIN WORLD, journal face: the whole log through the Lean journal
/// codec's wire, then two independent loads (the original deltas vs
/// the WIRE-LOADED deltas). Identical state hashes at EVERY step; the
/// chain tail is the PINNED known answer (5841812612511657845).
#[test]
fn twin_world_journal() {
    let schema = fixtures::fixture();
    let log = seeded_deltas(96, 301);
    let mut journal = Vec::new();
    enc_journal(&schema, &log, &mut journal);
    let decoded =
        dec_journal(&schema, &mut journal.as_slice()).expect("the journal decodes");
    assert_eq!(decoded, log, "the journal round-trips its own wire");
    let mut world_a = Table::new();
    let mut world_b = Table::new();
    for (step, (d_a, d_b)) in log.iter().zip(decoded.iter()).enumerate() {
        world_a.apply(&schema, d_a);
        world_b.apply(&schema, d_b);
        assert_eq!(
            journal_state_hash(&schema, world_a.rows()),
            journal_state_hash(&schema, world_b.rows()),
            "twin journal loads diverged at step {}",
            step
        );
    }
    assert_eq!(
        journal_state_hash(&schema, world_a.rows()),
        5841812612511657845,
        "the journal-face chain tail left its pinned known answer"
    );
}

/// The per-rule expected values (each names its note — the honest
/// known-answer table over the codec face's keyed semantics).
#[test]
fn per_rule_known_answers() {
    let mk = |label: &str, n: u64| Example {
        ready: true,
        count: n,
        delta: 0,
        label: label.to_string(),
        note: None,
        tags: Vec::new(),
    };
    // rule insert-new — note: keyed upsert APPENDS on an absent key.
    let mut rows = vec![mk("k0", 1)];
    assert_eq!(rows.len(), 1);
    assert_eq!(
        state_hash(&rows),
        10933067564000509762,
        "insert-new left its pinned hash"
    );
    // rule update-existing — note: FULL replacement at the first key
    // match; the count never grows.
    apply(&mut rows, 1, mk("k0", 2));
    assert_eq!(rows.len(), 1);
    assert_eq!(
        state_hash(&rows),
        1245298943954259335,
        "update-existing left its pinned hash"
    );
    // rule remove-existing — note: the FIRST key match is erased.
    apply(&mut rows, 2, mk("k0", 0));
    assert_eq!(rows.len(), 0);
    assert_eq!(
        state_hash(&rows),
        1442695040888963407,
        "remove-existing left its pinned hash (a priori: the bare seed)"
    );
    // rule remove-absent — note: the erase of an absent key is a
    // no-op (the total semantics); the state is unchanged.
    apply(&mut rows, 2, mk("k7", 0));
    assert_eq!(rows.len(), 0);
    assert_eq!(
        state_hash(&rows),
        1442695040888963407,
        "remove-absent left its pinned hash (a priori: the bare seed)"
    );
}

/// The schema manifest's provenance check (the per-schema face).
#[test]
fn schema_manifest_names_the_registered_items() {
    assert!(!SCHEMA_ITEMS.is_empty(), "the registry replay named no items");
    assert!(
        SCHEMA_ITEMS.contains(&"Example"),
        "the keyed fixture item must be registered"
    );
}
