// GENERATED by schema (lean-4.33.0) at - — DO NOT EDIT
// spec unknown | SchemaCore.Commit | 2 item(s) | content hash 6533152906452910210 | regen: just gen; drift fails CI
//! The serde face's round trips + the TWO-FACES honesty pin
//! (HAND-AUTHORED pin text, rendered by the emitter — the ONE writer;
//! never hand-edit the generated file, `just gen` restores).
//!
//! THE DISCIPLINE (the emitter's serde note, cited): the schema's
//! CANONICAL codec is SchemaCore.Codec's wire (the duel vectors in
//! tests/duel/ are its differential; the wire of record); the serde
//! impls are the ECOSYSTEM INTEROP face — a different byte encoding
//! with its own conventions. These pins hold the two faces APART
//! (never byte-equal — the honesty row) while each round trips on its
//! own (the interop face's behavior pin).
//!
//! Negative controls are MANDATORY: a missing field refuses, a
//! duplicate field refuses, an unknown field is ignored
//! (forward-compat), a wrong-typed value refuses.

use schema_generated::{Example, ExampleEx};

fn sample() -> Example {
    Example::builder()
        .ready(true)
        .count(300)
        .delta(-1)
        .label("hi".to_string())
        .note(Some("note".to_string()))
        .tags(vec!["a".to_string(), "b".to_string()])
        .build()
}

#[test]
fn serde_round_trip_example() {
    let v = sample();
    let text = serde_json::to_string(&v).expect("serialize");
    let back: Example = serde_json::from_str(&text).expect("deserialize");
    assert_eq!(back, v);
}

#[test]
fn serde_round_trip_example_ex_both_sum_faces() {
    let mk = |status| ExampleEx::builder()
        .status(status)
        .counts(vec![("k".to_string(), 1), ("j".to_string(), 2)])
        .small(7)
        .build();
    for v in [mk(Ok(5)), mk(Err("bad".to_string()))] {
        let text = serde_json::to_string(&v).expect("serialize");
        let back: ExampleEx = serde_json::from_str(&text).expect("deserialize");
        assert_eq!(back, v);
    }
}

#[test]
fn the_two_faces_are_honest_about_their_bytes() {
    // THE HONESTY ROW: the canonical wire (SchemaCore.Codec's — the
    // generated `encode`) and the serde JSON face are DIFFERENT byte
    // encodings of the same value. The wire of record stays the
    // codec's; serde is interop. A face that silently became the
    // other would fail this pin.
    let v = sample();
    let mut wire = Vec::new();
    v.encode(&mut wire);
    let json = serde_json::to_vec(&v).expect("serialize");
    assert_ne!(wire, json, "the wire and the interop face must differ");
    // and each decodes on ITS OWN face only
    assert!(Example::decode_full(&wire).is_ok());
    assert!(Example::decode_full(&json).is_err()); // the wire refuses JSON
    let back: Example = serde_json::from_slice(&json).expect("json face");
    assert_eq!(back, v);
}

#[test]
fn serde_missing_field_refuses() {
    // THE NEGATIVE CONTROL: a missing field is a typed serde refusal
    // (the same field the JSON carries — dropped here).
    let missing = r#"{"ready":true,"count":1,"delta":0,"label":"x","note":null}"#;
    let got: Result<Example, _> = serde_json::from_str(missing);
    assert!(got.is_err(), "a missing field must refuse");
}

#[test]
fn serde_duplicate_field_refuses() {
    // THE NEGATIVE CONTROL: a duplicate field is a typed refusal —
    // never a silent last-wins.
    let dup = r#"{"ready":true,"ready":false,"count":1,"delta":0,"label":"x","note":null,"tags":[]}"#;
    let got: Result<Example, _> = serde_json::from_str(dup);
    assert!(got.is_err(), "a duplicate field must refuse");
}

#[test]
fn serde_wrong_typed_value_refuses() {
    // THE NEGATIVE CONTROL: a wrong-typed value refuses (never a
    // silent reinterpretation).
    let wrong = r#"{"ready":true,"count":"300","delta":0,"label":"x","note":null,"tags":[]}"#;
    let got: Result<Example, _> = serde_json::from_str(wrong);
    assert!(got.is_err(), "a wrong-typed value must refuse");
}

#[test]
fn serde_unknown_field_ignored_forward_compat() {
    // The interop convention: an unknown field is interop, not drift —
    // ignored (the emitter's serde note).
    let ext = r#"{"ready":true,"count":300,"delta":-1,"label":"hi","note":"note","tags":["a","b"],"future":{"x":1}}"#;
    let got: Example = serde_json::from_str(ext).expect("unknown fields are ignored");
    assert_eq!(got, sample());
}
