/-
# Gates.GenCheck — the stripped byte-tie (`gates gen-check`)

The stripped byte-tie: the old check byte-compared the whole file, so
an innocent `just gen` (a new wall-clock + spec-sha in the 2-line
GENERATED header) dirtied the tree and read as drift. This gate
compares what the byte-tie actually BINDS (CodegenCore.Emit.Core's
contract: "the regen's header differs, the content's sha must not"):

1. the committed file's body bytes (everything after the 2-line header)
   vs the regenerated emitter output, AND
2. the committed header's embedded `content hash N` field vs
   `String.hash` of the regenerated body (the artifact's
   self-description must agree with the recomputed content).

Regeneration is IN-PROCESS: SchemaLang's emitter registry folds the
replayed Demo+FeatureFlags registries (Gates.Common.loadGenCtx — the
GenMain preamble), and Faults' `jobs` likewise. No subprocess, no
writes — this is a CHECKER: the check path never touches the tree.

Coverage note: exactly the artifacts of the two forge jobs manifests
(schema-lang's `emitters` + faults' `jobs`) — the same surface
`forge gen --check` byte-tied. wasm-backend's observability surface
keeps its own stripped byte-tie in `just wasm-compile` (different
driver, already stripped-correct).

LEGACY (non-module) file: meta env-extension access (the module-
migration constraint: such drivers stay legacy).
-/
import Gates.Common
import Faults.Emit.Registry

open Lean
open CodegenCore.Emit (Emitter GeneratedFile)

namespace Gates.GenCheck

/-- Per-artifact verdict. `hashDrift` without `contentDrift` should be
    impossible (the hash is over the same body) — if it ever fires, the
    committed header was hand-edited, which is exactly the squatting
    class the one-writer rule bans. -/
inductive Status where
  | identical | contentDrift | hashDrift | missing | headerMissing
  deriving BEq

instance : ToString Status where
  toString
    | .identical => "identical"
    | .contentDrift => "CONTENT DRIFT"
    | .hashDrift => "HASH DRIFT (body identical, header's content hash stale — hand-edited header?)"
    | .missing => "MISSING (committed artifact absent — run `just gen`)"
    | .headerMissing => "HEADER MISSING (a headerless file sits at a generated path)"

structure Result where
  path : String
  emitter : String
  status : Status

/-- Strip the 2-line GENERATED header; returns (header line 2, body).
    `splitOn`/`intercalate` round-trips bytes exactly, so the body
    compare is the full content minus the volatile header lines
    (timestamp + spec-commit). -/
def stripHeader (committed : String) : Option (String × String) :=
  match committed.splitOn "\n" with
  | l1 :: l2 :: rest =>
    if (l1.splitOn "GENERATED by").length > 1 then
      some (l2, String.intercalate "\n" rest)
    else none
  | _ => none

/-- The `content hash N` field of header line 2, as the field's decimal
    text (string-compare against `toString contents.hash` — exact, no
    Nat/UInt64 width question). -/
def contentHashField (line2 : String) : Option String :=
  match line2.splitOn "content hash " with
  | [_, rest] =>
    let digits := String.ofList (rest.toList.takeWhile Char.isDigit)
    if digits.isEmpty then none else some digits
  | _ => none

/-- Compare one regenerated file against its committed artifact. Reads
    only; never writes. -/
def checkOne (emitterName : String) (f : GeneratedFile) : IO Result := do
  unless ← (f.path : System.FilePath).pathExists do
    return ⟨f.path, emitterName, .missing⟩
  let committed ← IO.FS.readFile f.path
  match stripHeader committed with
  | none => return ⟨f.path, emitterName, .headerMissing⟩
  | some (line2, body) =>
    let hashOk := contentHashField line2 == some (toString f.contents.hash)
    let bodyOk := body == f.contents
    let status :=
      if bodyOk && hashOk then .identical
      else if !bodyOk then .contentDrift
      else .hashDrift
    return ⟨f.path, emitterName, status⟩

/-- The gate: regenerate in memory, compare stripped. Exit 1 on any
    non-identical artifact; the drifted paths print last (the actionable
    tail of the log). -/
unsafe def run : IO UInt32 := do
  let ctx ← Gates.loadGenCtx
  let mut results : Array Result := #[]
  for (e, files) in SchemaLang.Emit.certifiedJobs ctx do
    for f in files do
      results := results.push (← checkOne s!"schema-lang/{e.name}" f)
  for (e, spec) in Faults.Emit.jobs do
    for f in e.run spec do
      results := results.push (← checkOne s!"faults/{e.name}" f)
  let bad := results.filter (·.status != .identical)
  for r in results do
    IO.println s!"{r.status}  {r.path}  ({r.emitter})"
  IO.println ""
  if bad.isEmpty then
    IO.println s!"gen-check: {results.size} artifact(s), all identical \
      (stripped compare: body bytes + embedded content hash; header's \
      timestamp/spec-sha exempt by contract)"
    return 0
  IO.println s!"gen-check: {bad.size}/{results.size} artifact(s) drifted:"
  for r in bad do
    IO.println s!"  {r.path} — {r.status}"
  return 1

end Gates.GenCheck
