package demo:fixture-async;

interface fixture-async-types {
}

interface fixture-async-exports {
    watch: async func(id: u64) -> list<option<u64>>;
}

world fixture-async {
  export fixture-async-exports;
}
