//! The bolero property/fuzz LAYER over the hostgen SNAPSHOT PARSER
//! (`hostgen::parse_snapshot`, the Rust port of `SchemaLang.Snapshot`
//! — the format's authority is Lean's writer; the Rust side only
//! reads). Additive to the snapshot differential
//! (`snapshot_differential.rs`): that suite pins EXACT agreement with
//! the Lean authority's parse dumps on the committed fixtures; this
//! layer attacks everything around the fixtures.
//!
//! Two targets, both run under plain `cargo test` (bolero's test
//! engine, deterministic iteration count — not a cargo-fuzz-night
//! campaign):
//!
//! 1. ARBITRARY STRINGS: any bytes (lossy-UTF-8'd) are a snapshot;
//!    parse must NEVER panic. If it parses, the parsed universe must
//!    project (`surface_entries`) without panicking. This is the
//!    floor: `ParseError` with a 1-based line on anything malformed.
//! 2. FIXTURE-DIFFERENTIAL: the committed fixture pairs
//!    (`fixtures/snapshot_fixtures.txt` — GENERATED by the Lean
//!    authority, so an unmutated snap parsing Ok IS the Lean
//!    expectation; exact dump equality is the differential's pin) —
//!    a SINGLE random byte flip or deletion must leave the parser
//!    error-or-shape-stable: Ok parses keep the base item KIND
//!    sequence and member counts (names and type spellings may
//!    survive-or-fail, never silently restructure), Err is a
//!    structured `ParseError`. Byte flips cannot create item headers
//!    (no header keyword is one edit from another) or add members
//!    (a split member line cannot start a valid keyword) — so a
//!    shape change under a single edit is a PARSER finding, not an
//!    expectation of the format.
//!
//! Replay discipline: bolero prints `BOLERO_RANDOM_SEED=<n>` on a
//! failure; re-run with that env var set to reproduce the exact case.
//! The pair choice and the mutation schedule are pure functions of
//! the input bytes, so the seed alone reconstructs everything.

use std::path::PathBuf;
use std::sync::atomic::{AtomicUsize, Ordering};

use guestlang_host::hostgen::{self, Item};

/// The iterations per `cargo test` run (the CI lane — the long
/// campaigns are `just fuzz`'s business).
const ITERATIONS: usize = 256;

/// The fixture file (GENERATED by `lake exe snapshot-fixtures` — the
/// Lean authority's own well-formed snapshots).
fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/snapshot_fixtures.txt")
}

/// One fixture pair (only the snap half matters here — the expect
/// dump's EXACT comparison lives in snapshot_differential.rs).
struct Pair {
    name: String,
    snap: String,
}

/// Split the fixture file into pairs (the format `SnapshotRT.fixtureFile`
/// writes: `== u<i>` headers, `snap:` sections; `expect:` sections are
/// skipped — the differential owns them).
fn parse_fixture_file(text: &str) -> Vec<Pair> {
    let mut pairs = Vec::new();
    let mut cur: Option<(String, Vec<String>, u8)> = None; // (name, snap lines, section)
    for line in text.lines() {
        if let Some(name) = line.strip_prefix("== ") {
            if let Some((n, s, _)) = cur.take() {
                pairs.push(Pair { name: n, snap: s.join("\n") });
            }
            cur = Some((name.to_string(), Vec::new(), 0));
        } else if line == "snap:" {
            if let Some((_, _, sect)) = &mut cur {
                *sect = 1;
            }
        } else if line == "expect:" {
            if let Some((_, _, sect)) = &mut cur {
                *sect = 2;
            }
        } else if line.is_empty() || line.starts_with('#') {
            // header comment or blank
        } else if let Some((_, snap, sect)) = &mut cur {
            if *sect == 1 {
                snap.push(line.to_string());
            }
        }
    }
    if let Some((n, s, _)) = cur.take() {
        pairs.push(Pair { name: n, snap: s.join("\n") });
    }
    pairs
}

/// The fixture pairs with their base parses (the Lean-sanctioned
/// well-formed universes) and kind shapes.
struct Base {
    pairs: Vec<Pair>,
    shapes: Vec<Vec<String>>,
}

impl Base {
    fn load() -> Self {
        let text = std::fs::read_to_string(fixture_path())
            .unwrap_or_else(|e| panic!("reading the fixture file: {e}"));
        let pairs = parse_fixture_file(&text);
        assert!(pairs.len() >= 16, "the fixture file carries {} pairs — the generator regressed", pairs.len());
        let shapes = pairs
            .iter()
            .map(|p| {
                let items = hostgen::parse_snapshot(&p.snap)
                    .unwrap_or_else(|e| panic!("{}: the LEAN-authored fixture must parse: {e}", p.name));
                kind_shape(&items)
            })
            .collect();
        Self { pairs, shapes }
    }
}

/// The KIND shape of a parsed universe: one entry per item — the item
/// kind plus member counts, NO names, NO types (a single-byte edit
/// may rename or retype a member — `i8` → `u8` is one byte — but it
/// cannot create an item header or add a member line).
fn kind_shape(items: &[Item]) -> Vec<String> {
    items
        .iter()
        .map(|i| match i {
            Item::Record { fields, .. } => format!("record:{}", fields.len()),
            Item::Variant { cases, .. } => format!("variant:{}", cases.len()),
            Item::Func { params, sem, .. } => {
                format!("func:{}:{}", params.len(), usize::from(sem.is_some()))
            }
            Item::Resource { .. } => "resource".to_string(),
        })
        .collect()
}

/// Deterministic small PRNG seeded from the fuzz input: the pair
/// choice and mutation schedule are pure functions of the input, so a
/// printed seed replays exactly.
struct Lcg(u64);

impl Lcg {
    fn from_bytes(bytes: &[u8]) -> Self {
        let mut seed = 0xcbf2_9ce4_8422_2325u64; // FNV offset basis
        for b in bytes {
            seed ^= u64::from(*b);
            seed = seed.wrapping_mul(0x0000_0100_0000_01b3);
        }
        Self(seed | 1)
    }

    fn next(&mut self) -> u64 {
        self.0 = self.0.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1_442_695_040_888_963_407);
        self.0 >> 16
    }

    fn below(&mut self, n: u64) -> u64 {
        self.next() % n
    }
}

/// TARGET 1: arbitrary strings — the parser's floor. Never panic; a
/// parsed universe must project without panicking.
#[test]
fn parse_arbitrary_strings_never_panics() {
    let ran = AtomicUsize::new(0);
    bolero::check!()
        .with_iterations(ITERATIONS * 4)
        .for_each(|input: &[u8]| {
            ran.fetch_add(1, Ordering::Relaxed);
            let text = String::from_utf8_lossy(input);
            if let Ok(items) = hostgen::parse_snapshot(&text) {
                let universe = hostgen::Universe::new(items);
                let _ = universe.surface_entries();
            }
        });
    assert!(
        ran.load(Ordering::Relaxed) >= ITERATIONS * 4,
        "vacuous: the target did not run its iterations"
    );
}

/// TARGET 2: the fixture differential — single-byte mutations of the
/// Lean-authored fixtures stay error-or-shape-stable.
#[test]
fn mutated_fixtures_error_or_shape_stable() {
    let base = Base::load();
    let ran = AtomicUsize::new(0);
    bolero::check!()
        .with_iterations(ITERATIONS)
        .for_each(|input: &[u8]| {
            ran.fetch_add(1, Ordering::Relaxed);
            let mut r = Lcg::from_bytes(input);
            let idx = r.below(base.pairs.len() as u64) as usize;
            let mut bytes = base.pairs[idx].snap.clone().into_bytes();
            if bytes.is_empty() {
                return; // nothing to mutate in an empty pair
            }
            match r.below(2) {
                0 => {
                    let pos = r.below(bytes.len() as u64) as usize;
                    bytes[pos] = (r.next() & 0xff) as u8;
                }
                _ => {
                    let pos = r.below(bytes.len() as u64) as usize;
                    bytes.remove(pos);
                }
            }
            let mutated = String::from_utf8_lossy(&bytes);
            match hostgen::parse_snapshot(&mutated) {
                Err(e) => {
                    // the structured class: a real line number, always
                    assert!(e.line >= 1, "{}: ParseError.line must be 1-based", base.pairs[idx].name);
                }
                Ok(items) => {
                    assert_eq!(
                        kind_shape(&items),
                        base.shapes[idx],
                        "{}: a single-byte edit restructured the universe",
                        base.pairs[idx].name
                    );
                }
            }
        });
    assert!(
        ran.load(Ordering::Relaxed) >= ITERATIONS,
        "vacuous: the target did not run its iterations"
    );
}
