//! SNAPSHOT-CODEC DIFFERENTIAL (the fuzz-gap audit's gap #2): the
//! snapshot format has TWO hand-ported parsers — `SchemaLang.Snapshot`
//! (Lean, the format's AUTHORITY and sole writer) and
//! `hostgen::parse_snapshot` (the Rust twin) — and they had ZERO
//! agreement testing.
//!
//! Mechanism: the committed fixture file
//! (`fixtures/snapshot_fixtures.txt`) is GENERATED by the Lean
//! authority (`lake exe snapshot-fixtures`, regen: `just
//! snapshot-fixtures`; pinned seed, byte-identical regen). Each pair
//! carries the snapshot TEXT and the dump of what LEAN'S parse
//! produced — the authority's own answer. This test replays each
//! snapshot text through `hostgen::parse_snapshot` and asserts
//! equality with the authority.
//!
//! The dump's TYPES use an independent spelling (spaced S-expressions,
//! decoded by [`DumpTy::parse`] below — deliberately NOT
//! `hostgen::parse_ty_text`), so a drift in either side's snapshot
//! type parser CANNOT cancel between the two sides of the comparison.
//!
//! Pins (the three known cross-parser drifts, each fixed on the side
//! that was wrong — Lean is the format's authority, parse is lossless,
//! the format is LF-only):
//!   (a) empty `ty()` ref — the LEAN parser accepted it (a hole: the
//!       writer never emits one); now rejects on both sides;
//!   (b) kebab-at-parse — the RUST parser kebab-cased every name
//!       (lossy); parse is lossless on both sides now (the WIT wire
//!       spelling is the projection layer's — `surface_entries`);
//!   (c) CRLF — the RUST parser's `lines()` silently stripped `\r`;
//!       the writer never emits it, so CRLF is corruption: both sides
//!       reject, loudly.
//!
//! Negative control: the comparator itself is sabotaged (a mutated
//! dump) and MUST mismatch — proving the differential can fail.

mod common;

use common::fail;
use guestlang_host::hostgen::{self, Item, Ty};

/// The fixture file (GENERATED by `lake exe snapshot-fixtures`).
fn fixture_path() -> std::path::PathBuf {
    common::fixture("snapshot_fixtures.txt")
}

// ── the fixture file format ─────────────────────────────────────────

/// One generated pair: the snapshot text + the authority's parse dump.
struct Pair {
    name: String,
    snap: Vec<String>,
    expect: Vec<String>,
}

/// Split the fixture file into pairs (the format `SnapshotRT.fixtureFile`
/// writes: `== u<i>` headers, `snap:` and `expect:` sections).
fn parse_fixture_file(text: &str) -> Vec<Pair> {
    let mut pairs = Vec::new();
    // (name, snap lines, expect lines, section: 0=none 1=snap 2=expect)
    let mut cur: Option<(String, Vec<String>, Vec<String>, usize)> = None;
    for line in text.lines() {
        if let Some(name) = line.strip_prefix("== ") {
            if let Some((n, s, e, _)) = cur.take() {
                pairs.push(Pair {
                    name: n,
                    snap: s,
                    expect: e,
                });
            }
            cur = Some((name.to_string(), Vec::new(), Vec::new(), 0));
        } else if line == "snap:" {
            if let Some((_, _, _, sect)) = &mut cur {
                *sect = 1;
            }
        } else if line == "expect:" {
            if let Some((_, _, _, sect)) = &mut cur {
                *sect = 2;
            }
        } else if line.is_empty() || line.starts_with('#') {
            // header comment or blank — outside the sections
        } else if let Some((_, snap, expect, sect)) = &mut cur {
            match *sect {
                1 => snap.push(line.to_string()),
                2 => expect.push(line.to_string()),
                _ => fail(&format!("fixture: content outside a section: `{line}`")),
            }
        } else {
            fail(&format!("fixture: content before the first pair: `{line}`"));
        }
    }
    if let Some((n, s, e, _)) = cur.take() {
        pairs.push(Pair {
            name: n,
            snap: s,
            expect: e,
        });
    }
    pairs
}

/// The independent dump-type decoder — a tiny spaced-S-expression
/// parser (`( map string u64 )`, `( tensor 2 3 u64 )`, `( ref User )`),
/// deliberately independent of `hostgen::parse_ty_text` (no
/// cancellation between the differential's two sides).
struct DumpTy(Ty);

fn dump_ty<'a>(toks: &'a [&'a str]) -> Result<(DumpTy, &'a [&'a str]), String> {
    match toks.first() {
        None => Err("dump: expected a type, found end of line".to_string()),
        Some(&"(") => {
            let head = toks.get(1).ok_or("dump: `(` with no head")?;
            // the dims prefix: `( tensor 3 5 u64 )` — nat atoms ride
            // BEFORE the element (the dump spelling of the snapshot's
            // `;`-separated dims), zero dims = none
            if *head == "tensor" {
                let mut rest = &toks[2..];
                let mut dims = Vec::new();
                while let Some(t) = rest.first() {
                    match t.parse::<u64>() {
                        Ok(d) => {
                            dims.push(d);
                            rest = &rest[1..];
                        }
                        Err(_) => break,
                    }
                }
                let (elem, r) = dump_ty(rest)?;
                if r.first() != Some(&")") {
                    return Err("dump: `tensor` wants `)` after the element".to_string());
                }
                return Ok((DumpTy(Ty::Tensor(dims, Box::new(elem.0))), &r[1..]));
            }
            // the name atom: `( ref User )` — the payload is a NAME, not a
            // type, so it is read RAW (never parsed as a type token; this
            // is what keeps a type named `string` unambiguous)
            if *head == "ref" {
                let name = toks.get(2).ok_or("dump: `ref` wants a name atom")?;
                if toks.get(3) != Some(&")") {
                    return Err("dump: `ref` wants exactly one name atom".to_string());
                }
                return Ok((DumpTy(Ty::Named(name.to_string())), &toks[4..]));
            }
            let mut rest = &toks[2..];
            let mut args = Vec::new();
            while rest.first() != Some(&")") {
                let (t, r) = dump_ty(rest)?;
                args.push(t.0);
                rest = r;
                if rest.is_empty() {
                    return Err("dump: unterminated `(`".to_string());
                }
            }
            let rest = &rest[1..]; // consume the `)`
            // head + exact arity, both loud
            let arg_count = args.len();
            let bad =
                move |want: usize| format!("dump: `{head}` wants {want} arg(s), got {arg_count}");
            let mut it = args.into_iter();
            let ty = match *head {
                "option" | "list" | "future" | "stream" | "set" => {
                    let a = match it.next() {
                        Some(a) => a,
                        None => return Err(bad(1)),
                    };
                    if it.next().is_some() {
                        return Err(bad(1));
                    }
                    match *head {
                        "option" => Ty::Option(Box::new(a)),
                        "list" => Ty::List(Box::new(a)),
                        "future" => Ty::Future(Box::new(a)),
                        "stream" => Ty::Stream(Box::new(a)),
                        _ => Ty::Set(Box::new(a)),
                    }
                }
                "result" => {
                    let ok = it.next().ok_or_else(|| bad(2))?;
                    let err = it.next().ok_or_else(|| bad(2))?;
                    if it.next().is_some() {
                        return Err(bad(2));
                    }
                    Ty::Result(Box::new(ok), Box::new(err))
                }
                "map" => {
                    let k = it.next().ok_or_else(|| bad(2))?;
                    let v = it.next().ok_or_else(|| bad(2))?;
                    if it.next().is_some() {
                        return Err(bad(2));
                    }
                    Ty::Map(Box::new(k), Box::new(v))
                }
                other => return Err(format!("dump: unknown type head `{other}`")),
            };
            Ok((DumpTy(ty), rest))
        }
        Some(&atom) => {
            let ty = match atom {
                "bool" => Ty::Bool,
                "u8" => Ty::U8,
                "u16" => Ty::U16,
                "u32" => Ty::U32,
                "u64" => Ty::U64,
                "i8" => Ty::I8,
                "i16" => Ty::I16,
                "i32" => Ty::I32,
                "i64" => Ty::I64,
                "f32" => Ty::F32,
                "f64" => Ty::F64,
                "string" => Ty::String,
                "bytes" => Ty::Bytes,
                other => return Err(format!("dump: unknown type atom `{other}`")),
            };
            Ok((DumpTy(ty), &toks[1..]))
        }
    }
}

/// Decode one dump type: tokens → `Ty` (`( ref User )` → `Named("User")`).
fn dump_ty_text(line: &str) -> Ty {
    let toks: Vec<&str> = line.split(' ').filter(|t| !t.is_empty()).collect();
    let (ty, rest) = dump_ty(&toks).unwrap_or_else(|e| fail(&format!("dump: {e}: `{line}`")));
    if !rest.is_empty() {
        fail(&format!("dump: trailing tokens after a type: `{line}`"));
    }
    ty.0
}

/// The dump grammar: `item record|variant|func|resource` headers,
/// `fld`/`cs`/`p` members, `ret`, optional `sem` (present only when
/// non-default — mirroring the snapshot). The Lean side's
/// `SnapshotRT.dumpItem` is the writer; a drift in EITHER parser
/// surfaces as a mismatch here.
fn parse_dump(lines: &[String]) -> Vec<Item> {
    let mut items: Vec<Item> = Vec::new();
    for l in lines {
        let toks: Vec<&str> = l.split(' ').collect();
        match toks.as_slice() {
            ["item", "record", n] => items.push(Item::Record {
                name: n.to_string(),
                fields: Vec::new(),
            }),
            ["item", "variant", n] => items.push(Item::Variant {
                name: n.to_string(),
                cases: Vec::new(),
            }),
            ["item", "func", n] => items.push(Item::Func {
                name: n.to_string(),
                params: Vec::new(),
                // the `ret` line MUST follow — a missing ret fails below
                ret: Ty::Bool,
                sem: None,
            }),
            ["item", "resource", n] => items.push(Item::Resource {
                name: n.to_string(),
            }),
            ["fld", n, rest @ ..] => match items.last_mut() {
                Some(Item::Record { fields, .. }) => {
                    let t = dump_ty_text(&rest.join(" "));
                    fields.push((n.to_string(), t));
                }
                _ => fail(&format!("dump: `fld` outside a record: `{l}`")),
            },
            ["cs", n] => match items.last_mut() {
                Some(Item::Variant { cases, .. }) => cases.push((n.to_string(), None)),
                _ => fail(&format!("dump: bare `cs` outside a variant: `{l}`")),
            },
            ["cs", n, rest @ ..] => match items.last_mut() {
                Some(Item::Variant { cases, .. }) => {
                    let t = dump_ty_text(&rest.join(" "));
                    cases.push((n.to_string(), Some(t)));
                }
                _ => fail(&format!("dump: `cs` outside a variant: `{l}`")),
            },
            ["p", n, rest @ ..] => match items.last_mut() {
                Some(Item::Func { params, .. }) => {
                    let t = dump_ty_text(&rest.join(" "));
                    params.push((n.to_string(), t));
                }
                _ => fail(&format!("dump: `p` outside a func: `{l}`")),
            },
            ["ret", rest @ ..] => match items.last_mut() {
                Some(Item::Func { ret, .. }) => *ret = dump_ty_text(&rest.join(" ")),
                _ => fail(&format!("dump: `ret` outside a func: `{l}`")),
            },
            ["sem", ns, ds] => match items.last_mut() {
                Some(Item::Func { sem, .. }) => {
                    *sem = Some(hostgen::FuncSem {
                        null_sem: ns.to_string(),
                        determinism: ds.to_string(),
                        stream: false,
                    });
                }
                _ => fail(&format!("dump: `sem` outside a func: `{l}`")),
            },
            ["sem", ns, ds, "stream"] => match items.last_mut() {
                Some(Item::Func { sem, .. }) => {
                    *sem = Some(hostgen::FuncSem {
                        null_sem: ns.to_string(),
                        determinism: ds.to_string(),
                        stream: true,
                    });
                }
                _ => fail(&format!("dump: `sem` outside a func: `{l}`")),
            },
            _ => fail(&format!("dump: unrecognized line `{l}`")),
        }
    }
    items
}

/// The fixture pairs, parsed.
fn fixtures() -> Vec<Pair> {
    let text = std::fs::read_to_string(fixture_path())
        .unwrap_or_else(|e| fail(&format!("reading the fixture file: {e}")));
    let pairs = parse_fixture_file(&text);
    assert!(
        pairs.len() >= 16,
        "the fixture file carries {} pairs — the generator regressed",
        pairs.len()
    );
    pairs
}

// ── the differential ────────────────────────────────────────────────

#[test]
fn every_fixture_pair_agrees_with_the_lean_authority() {
    for pair in fixtures() {
        let snap = if pair.snap.is_empty() {
            String::new()
        } else {
            format!("{}\n", pair.snap.join("\n"))
        };
        let expect = parse_dump(&pair.expect);
        let got = hostgen::parse_snapshot(&snap)
            .unwrap_or_else(|e| fail(&format!("{}: the Rust twin failed: {e}", pair.name)));
        assert_eq!(
            got, expect,
            "{}: the two parsers DISAGREE on a well-formed universe",
            pair.name
        );
    }
}

/// The comparator's negative control: a MUTATED dump must mismatch —
/// if this passed, the differential could never fail (a vacuous green).
#[test]
fn the_comparator_bites_on_a_mutated_dump() {
    let pair = &fixtures()
        .into_iter()
        .find(|p| !p.expect.is_empty() && !p.snap.is_empty())
        .expect("a non-empty pair exists");
    let snap = format!("{}\n", pair.snap.join("\n"));
    let mut expect = parse_dump(&pair.expect);
    // sabotage: rename the first item
    let renamed = match &mut expect[0] {
        Item::Record { name, .. } | Item::Variant { name, .. } | Item::Resource { name } => {
            *name = format!("{name}-saboteur");
            true
        }
        Item::Func { name, .. } => {
            *name = format!("{name}-saboteur");
            true
        }
    };
    assert!(renamed, "the first item was renamed");
    let got = hostgen::parse_snapshot(&snap)
        .unwrap_or_else(|e| fail(&format!("{}: parse failed: {e}", pair.name)));
    assert_ne!(
        got, expect,
        "the mutated dump must MISMATCH — a differential that cannot fail proves nothing"
    );
}

// ── the three drifts' regression pins (Rust side) ───────────────────

#[test]
fn empty_ty_ref_is_rejected() {
    // drift (a): the LEAN side accepted `ty()` before the gate; the
    // Rust twin always rejected — both must reject now (the Lean pins
    // live in Tests/Main.lean's SnapshotRTPins)
    assert!(hostgen::parse_snapshot("record User\nfield id ty()\n").is_err());
}

#[test]
fn parse_is_lossless_no_kebab() {
    // drift (b): the Rust twin used to kebab-case at parse; parse is
    // LOSSLESS (the committed snapshot's own names survive verbatim)
    let universe = hostgen::Universe::new(
        hostgen::parse_snapshot(
            &std::fs::read_to_string(common::universe_snapshot_path())
                .unwrap_or_else(|e| fail(&format!("{e}"))),
        )
        .unwrap_or_else(|e| fail(&format!("{e}"))),
    );
    assert!(
        universe.find("getUser").is_some() && universe.find("get-user").is_none(),
        "func names stay verbatim (no kebab at parse)"
    );
    assert!(
        universe.find("OrderItem").is_some() && universe.find("order-item").is_none(),
        "record names stay verbatim (no kebab at parse)"
    );
    // ...while the PROJECTION still speaks the WIT wire spelling
    let entries = universe
        .surface_entries()
        .unwrap_or_else(|e| fail(&format!("{e}")));
    assert!(
        entries.iter().any(|(f, _)| f == "get-user"),
        "surface_entries kebabs (the projection layer's convention)"
    );
}

#[test]
fn crlf_is_rejected_on_both_sides() {
    // drift (c): the Rust `lines()` silently stripped `\r`; the format
    // is LF-only — CRLF is corruption, loud on both sides (the Lean
    // pins live in Tests/Main.lean's SnapshotRTPins)
    assert!(hostgen::parse_snapshot("record User\r\nfield id u64\r\n").is_err());
    assert!(hostgen::parse_snapshot("record User\nfield id u64\n").is_ok());
}
