/-
# CodegenCore.Emit.Core — the emitter discipline

Lifted from flatland's `Codegen.Emit.Core` (lean-v3 §7.2, D6, D7). The
rules:

- Target AST → skeleton → tokens → text. Text via `Std.Format`, never
  string interpolation for structure.
- Name-mangling in ONE module per target — the most common codegen bug
  class, centralized here.
- Deterministic output: sorted/registry-order emission, `StateM Nat` fresh
  names. Byte-tie CI regenerates and diffs (lean4-mlir's discipline).
- Every generated file carries the header citing its spec source — so an
  agent knows: regenerate, don't edit.
-/

namespace CodegenCore.Emit

/-- The generated-file header. Every artifact, always. `tool` names the
    emitting package (e.g. `"schema-lang"`), `specSource` the registry or
    spec module the artifacts derive from. Comment prefix per target:
    Lean/SQL `--`, Rust/WIT `//`, YAML/Python `#`, WAT `;;`. -/
inductive CommentStyle where
  | lean | doubleSlash | hash | wat

def CommentStyle.prefix : CommentStyle → String
  | .lean => "-- "
  | .doubleSlash => "// "
  | .hash => "# "
  | .wat => ";; "

def CommentStyle.line (s : CommentStyle) (text : String) : String :=
  s.prefix ++ text

/-! ## The generation metadata — the compact header

The header is 2 lines and carries REAL metadata: the wall-clock
regeneration time, the tool + the Lean version, the SPEC's git state
(short sha + the dirty flag + the commit time — deterministic per
commit), the item count, and the CONTENT hash (FNV-1a over the body —
the artifact self-describes which spec state produced it).

THE BYTE-TIE CONTRACT: the drift check STRIPS the header (the leading
comment lines) and hashes the content — so ANY metadata (even a
wall-clock) is safe: the regen's header differs, the content's sha
must not. The header = information; the byte-tie = the content.
-/

/- The content-hash field = the CORE's own hash (`String.hash`:
deterministic, 64-bit, zero code). NOT a crypto digest (the sha256 =
the forge's store's job); this one = the artifact's self-description
("which spec state am I"). The hand-rolled FNV-1a it replaced was
exactly the "rolling our own" the doctrine warns about — core had it. -/

/-- The generation metadata — assembled by the DRIVER (the only IO
point: the clock + git); the emitters stay pure. -/
structure GenMeta where
  /-- The regen's wall-clock (ISO-ish, `YYYY-MM-DDTHH:MMZ`). -/
  time : String := "-"
  /-- The spec source's git short sha + the dirty marker (`+` = the
  working copy drifted past the sha). -/
  specSha : String := "unknown"
  /-- The registered item count (the spec's size, at a glance). -/
  items : Nat := 0
  /-- `String.hash` over the artifact's body (the header excluded) —
  the content's self-verification seed. (The header above calls it a
  content hash; it is NOT FNV-1a — core's `String.hash` replaced the
  hand-rolled FNV-1a, see the block comment.) -/
  contentHash : UInt64 := 0

/-- The generated-file header: TWO lines, dense metadata. `tool` names
    the emitting package, `specSource` the spec module. Comment prefix
    per target: Lean/SQL `--`, Rust/WIT `//`, YAML/Python `#`, WAT `;;`.
    (TRAP: the binder cannot be named `meta` — it is a Lean keyword, the
    `meta def` modifier — the parser rejects it as a binder name.) -/
def header (style : CommentStyle) (tool specSource : String) (gm : GenMeta) : String :=
  CommentStyle.line style
    (s!"GENERATED by {tool} (lean-{Lean.versionString}) at {gm.time} — DO NOT EDIT") ++ "\n"
    ++ CommentStyle.line style
      (s!"spec {gm.specSha} | {specSource} | {gm.items} item(s) | "
        ++ s!"content hash {gm.contentHash} | regen: just gen; drift fails CI")
    ++ "\n"

/-- The driver's metadata assembly: the wall-clock + the SPEC's git state
    (short sha + the dirty flag) + the item count. The ONLY IO point —
    the emitters stay pure. `git diff --quiet` = the dirty test (exit 0 =
    clean, 1 = drifted; the spec-relevant paths only: lean/ + justfile). -/
def genMeta (items : Nat) (contentHash : UInt64) : IO GenMeta := do
  -- the git spawns = at the REPO ROOT (the drivers run from the package
  -- dirs; the pathspecs are root-relative)
  let git (args : List String) : IO String := do
    let out ← IO.Process.output { cmd := "git", args := args.toArray, cwd := some "../.." }
    if out.exitCode == 0 then pure out.stdout.trimAscii.toString else pure "unknown"
  let sha ← git ["rev-parse", "--short", "HEAD"]
  -- `diff HEAD` (not the bare diff): the jj colocation auto-syncs the
  -- git index to the working copy, so the bare diff is BLIND to the
  -- uncommitted changes — HEAD is the truth.
  let dirty ← IO.Process.output
    { cmd := "git", args := #["diff", "--quiet", "HEAD", "--", "lean", "justfile"]
      cwd := some "../.." }
  let dateOut ← IO.Process.output
    { cmd := "date", args := #["-u", "+%Y-%m-%dT%H:%MZ"] }
  let time := if dateOut.exitCode == 0 then dateOut.stdout.trimAscii.toString else "-"
  pure { time := time
       , specSha := sha ++ (if dirty.exitCode == 0 then "" else "+")
       , items := items
       , contentHash := contentHash }

/-! ## The emitter-plugin model (buf/protoc architecture)

ONE parsed spec, MANY emitter plugins. `Emitter Spec` is parameterized
over the spec descriptor type — schema-lang instantiates `Spec :=
List Item`; any other spec language reuses the model. Each plugin
declares its output paths (the one-writer audit surface) and is a pure
function from spec to files; the driver prepends headers and writes. -/

/-- One generated artifact: repo-root-relative path + content (header
    prepended by the driver, not by the emitter). -/
structure GeneratedFile where
  path : String
  contents : String

/-! ## The driver's write path

Emitters are pure (`run`); only DRIVERS write. The parent-dir
computation + `createDirAll` lives here once — every driver
(GenMains, golden updaters) shares it. -/

/-- Create the parent directories of `path` (all generated paths are
    slash-separated, so the drop-last computation always names a real
    directory). -/
def createParentDirs (path : System.FilePath) : IO Unit :=
  let dir := String.intercalate "/" ((path.toString.splitOn "/").dropLast)
  IO.FS.createDirAll dir

/-- Write one generated file, creating parent directories first. -/
def writeFileCreatingDirs (path : System.FilePath) (contents : String) : IO Unit := do
  createParentDirs path
  IO.FS.writeFile path contents

/-- An emitter plugin: one language target. -/
structure Emitter (Spec : Type) where
  /-- Plugin name (buf: the plugin suffix). -/
  name : String
  /-- Comment prefix for the generated header. -/
  style : CommentStyle
  /-- The spec module the artifacts derive from (audit provenance). -/
  specSource : String
  /-- Declared output paths, repo-root-relative. MUST be unique across
      the registry (the one-writer discipline, checked in Tests). -/
  outputs : List String
  /-- Fold the spec into files. Pure and deterministic (tested). -/
  run : Spec → List GeneratedFile
  /-- OPTIONAL emission law (W7.9 phase 1: the `CertifiedEmitter` pattern
      absorbed into the base structure). When `some L`, the driver SHOULD
      discharge `L spec` over the concrete spec and emit via
      `runCertified` — the artifact is unemittable without the discharged
      certificate. Defaults to `none` so every existing `Emitter` literal
      compiles unchanged; phase 2 (next wave) makes the law mandatory
      where a registry opts in. -/
  law : Option (Spec → Prop) := none

/-- The certificate an emitter demands over a concrete spec: `some L`
    requires the discharged `L spec`; `none` is trivially certified. -/
def Emitter.Cert (e : Emitter Spec) (spec : Spec) : Prop :=
  match e.law with
  | some L => L spec
  | none => True

/-- Proof-carrying emission: the certified lane. Phase 1 keeps `run`
    plain (backward compatibility); certified drivers call here with the
    discharged certificate — the `SpawnGate` shape from
    `Emit.Certified`'s doctrine comment. -/
def Emitter.runCertified (e : Emitter Spec) (spec : Spec) (_cert : e.Cert spec) :
    List GeneratedFile := e.run spec

/-- One-writer audit, decidable: no two emitters in the registry declare
    the same output path. Registries SHOULD ship the discharged theorem
    beside the registry:

    ```
    theorem myRegistry_outputs_nodup :
        Emitter.checkNodup myRegistry = true := by decide
    ```

    (Phase 2 carries the proof INSIDE the registry type, making collisions
    unconstructible; this wave keeps the check data-level. schema-lang's
    `pathsUnique` and faults' audit row are the existing instances of the
    pattern.) -/
def Emitter.checkNodup (es : List (Emitter Spec)) : Bool :=
  (es.flatMap (·.outputs)).Nodup

/-! ## Name mangling (one place, every target)

Identifiers arrive as registry names (dot/space/dash separated words).
Each target gets its convention; collision-safe by construction since
registry names are unique. -/

/-- Split a registry name into lowercase word parts: separators AND
    lower→Upper humps both split (`maxHealth` → [max, health]). -/
def words (s : String) : List String := Id.run do
  let mut cur : String := ""
  let mut out : List String := []
  let mut prevLower := false
  for c in s.toList do
    if c == '.' || c == '-' || c == '_' || c == ' ' then
      if cur != "" then out := out ++ [cur]
      cur := ""
      prevLower := false
    else if c.isUpper && prevLower then
      out := out ++ [cur]
      cur := c.toLower.toString
      prevLower := false
    else
      cur := cur ++ c.toLower.toString
      prevLower := !(c.isUpper)
  if cur != "" then out := out ++ [cur]
  return out

def capitalize (s : String) : String :=
  match s.toList with
  | [] => ""
  | c :: cs => String.ofList (c.toUpper :: cs)

/-- `foo_bar baz` → `fooBarBaz` (Rust fn, Lean field). Also WIT kebab via
    the `kebab` sibling in target modules. -/
def camel (s : String) : String :=
  match words s with
  | [] => ""
  | w :: ws => w ++ String.join (ws.map capitalize)

/-- `foo_bar` → `FooBar` (Rust/Lean type). -/
def pascal (s : String) : String := String.join ((words s).map capitalize)

/-- `FooBar baz` → `foo_bar_baz` (Rust module, SQL table). -/
def snake (s : String) : String := String.intercalate "_" (words s)

/-- `foo_bar` → `foo-bar` (WIT identifiers are kebab-case). -/
def kebab (s : String) : String := String.intercalate "-" (words s)

/-- Package-relative output → repo-root-relative (emitters run with CWD
    = the lean package dir and declare `../..`-paths; forge joins from
    the repo root). ONE copy, here: the manifest emitters (schema-lang's
    `jobJson`, faults' `forgeJobsLines`) must apply it exactly once. -/
def rootRel (p : String) : String :=
  match p.dropPrefix? "../../" with | some rest => rest.toString | none => p

/-- The shared driver loop: for each (emitter, spec) job, run the emitter,
    prepend the header, and write each generated file. `tool` = the emitting
    package name (e.g. `"schema-lang"`, `"faults"`). `mkGm` gives the driver
    control over per-file GenMeta — schema-lang precomputes GenMeta once and
    only varies contentHash; faults computes GenMeta per file with items=1.
    Emitted bytes match the hand-written loops exactly. -/
def runEmitters {Spec : Type} (tool : String) (jobs : List (Emitter Spec × Spec))
    (mkGm : Emitter Spec → GeneratedFile → IO GenMeta) : IO Unit :=
  for (e, spec) in jobs do
    for f in e.run spec do
      let gm ← mkGm e f
      writeFileCreatingDirs f.path (header e.style tool e.specSource gm ++ f.contents)
      IO.println s!"wrote {f.path}"

/-- Escape a JSON string (paths + names only — quotes and backslashes
    are the whole story). Shared by every manifest emitter (schema-lang's
    Registry + WitFixture both consume it; it lives here so neither can
    import-cycle the other). -/
def jsonStr (s : String) : String :=
  "\"" ++ (s.replace "\\" "\\\\").replace "\"" "\\\"" ++ "\""

/-- Rust keywords get a raw-identifier escape; the only mangling surprise
    that is allowed to exist. -/
def rustIdent (s : String) : String :=
  let kw := ["as", "break", "const", "continue", "crate", "else", "enum",
    "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop",
    "match", "mod", "move", "mut", "pub", "ref", "return", "self", "Self",
    "static", "super", "trait", "true", "type", "unsafe", "use", "where",
    "while", "async", "await", "dyn", "box"]
  let c := camel s
  if kw.contains c then s!"r#{c}" else c

end CodegenCore.Emit
