package demo:fixture-nested;

interface fixture-nested-types {
record nested {
  opt: option<u32>,
  lst: list<string>,
  res: result<u64, string>,
}
}

interface fixture-nested-exports {
}

world fixture-nested {
  export fixture-nested-exports;
}
