/-
# Machines.Core — the machine, its two projections

Design: flatland's notes/lean/lean-v3.md Part 5 + flatland's notes/lean/TOOLKIT.md §2.4.
Veil's two-projection shape, owned: actions are executable functions with
the guard PROOF threaded into construction (an UPDATE…WHERE cannot be
constructed without discharging its guard); the Prop relation is *derived*
from the same definition, so execution and proof case-split over the same
labels and cannot drift.

- Projection 1 (executable): `step?`, `run` — total, emit traces.
- Projection 2 (proof): `tr` — the two-state relation; preservation is a
  theorem (`run_preserves`), not a convention.

Deliberately absent (per lean-v3 D2): nondeterminism (own module, later),
WP/Hoare machinery (deterministic actions collapse it to a one-liner),
SMT. Convergence lives in `Machines.Convergent`; liveness (lentil-style
leads_to/wf1) is deferred — `Machines.Live` was removed as a dead
vocabulary seed with no consumers (recoverable via the op log).
-/

module

-- Elaboration-time only: the `declare_eqns` generator (plan §4, family 3;
-- additive meta import — constraint 7).
public meta import Machines.Tactics

-- Module discipline: all declarations public; bodies exposed
-- (step?/run must reduce across module boundaries for rfl/decide proofs).
@[expose] public section

namespace Machines

/-- An event: a decidable guard, an action that REQUIRES the guard's proof,
    and the invariant-preservation obligation. The author writes state +
    guard + action; the `safety` field is the PO slot (the Dsl layer will
    default it to `by decide`/`omega` — TOOLKIT §4.2 autoParam). -/
structure EventSpec (S : Type) (Inv : S → Prop) where
  guard : S → Bool
  action : (s : S) → guard s = true → S
  safety : ∀ s h, Inv s → Inv (action s h)

/-- A machine: state type, event labels, invariant, and the event family.
    `Label` should be an inductive over event names — see [machineAssemblePattern]. -/
structure Machine where
  State : Type
  Label : Type
  Inv : State → Prop
  event : Label → EventSpec State Inv

namespace Machine

variable (m : Machine)

/-- Is the event enabled (guard holds) in this state? -/
def enabled (s : m.State) (l : m.Label) : Bool := (m.event l).guard s

/-- Execute one event. `none` = not enabled. Total. -/
def step? (s : m.State) (l : m.Label) : Option m.State :=
  if h : (m.event l).guard s = true then some ((m.event l).action s h) else none

/-- The derived two-state relation (projection 2). -/
def tr (s : m.State) (l : m.Label) (s' : m.State) : Prop :=
  ∃ h : (m.event l).guard s = true, (m.event l).action s h = s'

/-- The two projections agree BY CONSTRUCTION: `tr` is the relational
    reading of `step?`. (The tie the oracle rests on.) -/
theorem tr_iff_step? (s : m.State) (l : m.Label) (s' : m.State) :
    m.tr s l s' ↔ m.step? s l = some s' := by
  constructor
  · intro h
    obtain ⟨hg, hact⟩ := h
    unfold step?
    rw [dif_pos hg]
    exact congrArg some hact
  · intro h
    unfold step? at h
    split at h
    · next hg =>
      exact ⟨hg, Option.some.inj h⟩
    · next =>
      simp at h

/-- A trace: the (label, post-state) history of an execution. Journals are
    traces; the replay checker consumes this type. -/
abbrev Trace (m : Machine) := List (m.Label × m.State)

/-- Run an event sequence, emitting the trace. `none` = some event's guard
    failed (the run is REJECTED — invalid sequences are observable, not
    silent). -/
def run (s : m.State) (ls : List m.Label) : Option (Trace m × m.State) :=
  match ls with
  | [] => some ([], s)
  | l :: rest =>
    match m.step? s l with
    | none => none
    | some s' =>
      match run s' rest with
      | none => none
      | some (tr, fin) => some ((l, s') :: tr, fin)

/-- One step preserves the invariant — the EventSpec.safety obligation,
    projected. -/
theorem step?_preserves (s : m.State) (l : m.Label) (s' : m.State)
    (h : m.step? s l = some s') (hi : m.Inv s) : m.Inv s' := by
  unfold step? at h
  split at h
  · next hg =>
    have hs := (m.event l).safety s hg hi
    have heq := Option.some.inj h
    rw [← heq]
    exact hs
  · next =>
    simp at h

/-- The invariant holds at the end of every successful run and at every
    recorded state — the correctness-by-construction payoff: a machine whose
    events all discharge `safety` CANNOT reach a bad state through `run`. -/
-- the @[simp] equation set: every recursive def ships these (lean/AGENTS.md
-- construction rule 1) — proofs consume `simp [Machine.run]`, never walk the
-- match structure by hand. GENERATED by `declare_eqns` (plan §4, family 3):
-- the run_nil/run_cons rfl-restatements, from `run`'s own equation lemmas.

@[simp] theorem step?_eq (s : m.State) (l : m.Label) :
    m.step? s l = if h : (m.event l).guard s = true
      then some ((m.event l).action s h) else none := rfl

declare_eqns Machine.run with run_nil run_cons

/-- Inversion at `cons`: a successful `run` step passes the guard, steps,
    and recurses; trace and final state are the cons of the step's record.
    (Kills the `Prod.mk.inj (Option.some.inj h)` ladder at the call sites.) -/
theorem run_cons_some {s : m.State} {l : m.Label} {ls : List m.Label}
    {tr : Trace m} {fin : m.State}
    (h : m.run s (l :: ls) = some (tr, fin)) :
    ∃ (s' : m.State) (tr' : Trace m) (fin' : m.State),
      m.step? s l = some s' ∧ m.run s' ls = some (tr', fin') ∧
        tr = (l, s') :: tr' ∧ fin = fin' := by
  simp only [run] at h
  split at h
  · next => contradiction
  · next s' hs =>
    split at h
    · next => contradiction
    · next tr' fin' hr =>
      obtain ⟨h1, h2⟩ := Prod.mk.inj (Option.some.inj h)
      exact ⟨s', tr', fin', hs, hr, h1.symm, h2.symm⟩

/-- Inversion at `cons`, guard side: a successful step is the guard proof
    plus the action equation. -/
theorem step?_eq_some {s : m.State} {l : m.Label} {s' : m.State}
    (h : m.step? s l = some s') :
    ∃ hg : (m.event l).guard s = true, (m.event l).action s hg = s' := by
  unfold step? at h
  split at h
  · next hg => exact ⟨hg, Option.some.inj h⟩
  · next => simp at h

theorem run_preserves (init : m.State) (hinit : m.Inv init)
    (ls : List m.Label) (tr : Trace m) (fin : m.State)
    (h : m.run init ls = some (tr, fin)) : m.Inv fin ∧ ∀ p ∈ tr, m.Inv p.2 := by
  induction ls generalizing init tr with
  | nil =>
    simp only [run, Option.some.injEq, Prod.mk.injEq] at h
    obtain ⟨rfl, rfl⟩ := h
    exact ⟨hinit, fun _ hp => by simp at hp⟩
  | cons l rest ih =>
    obtain ⟨s', tr', fin', hs, hr, htr, hfin⟩ := run_cons_some m h
    subst htr hfin
    have hs' := m.step?_preserves init l s' hs hinit
    obtain ⟨hfin, htr⟩ := ih s' hs' tr' hr
    constructor
    · exact hfin
    · intro q hq
      rcases List.mem_cons.mp hq with hqeq | hqtr
      · rw [hqeq]; exact hs'
      · exact htr q hqtr

/-! ## The transition table (the general form of the machine! `states:`
    entourage) -/

/-- The transition table computed from a step function: label-major rows
    over `ls`, inner states in enumeration order, enabled transitions
    only (the machine! `states:` clause's exact fold). -/
def tableOf {S L : Type} (step : S → L → Option S)
    (ls : List L) (ss : List S) : List (L × S × S) :=
  ls.flatMap fun l => ss.filterMap fun s => (step s l).map fun s' => (l, s, s')

/-- THE TABLE-FUNCTION LAW (the W-iso batch piece 2: finite functions
    over an enumerated label/state space ≅ their tables — the load-bearing
    direction): the computed table's lookup IS the step function, over the
    enumerated states. The machine! `states:` entourage's per-machine tie
    theorem is this lemma applied at the machine's `step?`; the
    label-coverage check stays per-machine (`labels_complete`'s decide —
    the compile IS the check). Stated over `DecidableEq` + decide-
    predicates (NOT `==`/`LawfulBEq`): a derived-BEq instance and
    `instBEqOfDecidableEq` are different operators, and Lean's
    `instLawfulBEq` only chains to the latter. -/
theorem tableLookup?_eq_step? {S L : Type} [DecidableEq S] [DecidableEq L]
    (step : S → L → Option S) (ls : List L) (ss : List S)
    (hls : ∀ l, l ∈ ls)
    (e : L) (s : S) (hsm : s ∈ ss) :
    Option.map (fun r : L × S × S => r.2.2)
        (List.find? (fun r => decide (r.1 = e) && decide (r.2.1 = s))
          (Machines.Machine.tableOf step ls ss))
      = step s e := by
  -- every matching row IS the (e, s, step s e) row: a row is (l₀, s₀, s')
  -- with step s₀ l₀ = some s', and the predicate pins l₀ = e, s₀ = s.
  have hrow : ∀ r ∈ Machines.Machine.tableOf step ls ss,
      (decide (r.1 = e) && decide (r.2.1 = s)) = true →
      r.1 = e ∧ r.2.1 = s ∧ step s e = some r.2.2 := by
    intro r hr hp
    obtain ⟨l₀, hl₀, hx⟩ := List.mem_flatMap.1 hr
    obtain ⟨s₀, hs₀, hxeq⟩ := List.mem_filterMap.1 hx
    cases hs : step s₀ l₀ with
    | none => rw [hs, Option.map_none] at hxeq; simp at hxeq
    | some s' =>
      rw [hs, Option.map_some] at hxeq
      have hrr : (l₀, s₀, s') = r := Option.some.inj hxeq
      have hp' : (decide ((l₀, s₀, s').1 = e) && decide ((l₀, s₀, s').2.1 = s)) = true := by
        rw [hrr]; exact hp
      obtain ⟨h₁ : l₀ = e, h₂ : s₀ = s⟩ := by
        simp only [decide_eq_true_eq, Bool.and_eq_true] at hp'
        exact hp'
      exact ⟨by rw [← hrr]; exact h₁, by rw [← hrr]; exact h₂,
        by rw [← h₁, ← h₂, hs, ← hrr]⟩
  rcases hf : (Machines.Machine.tableOf step ls ss).find?
      (fun r => decide (r.1 = e) && decide (r.2.1 = s)) with - | c
  · rw [hf, Option.map_none]
    rcases hstep : step s e with - | s'
    · rfl
    · exfalso
      exact List.find?_eq_none.mp hf (e, s, s')
        (List.mem_flatMap.2 ⟨e, hls e, List.mem_filterMap.2 ⟨s, hsm,
          by rw [hstep, Option.map_some]⟩⟩)
        (by simp)
  · rw [hf, Option.map_some]
    have hpred := List.find?_some hf
    have hcmem := List.mem_of_find?_eq_some hf
    obtain ⟨hc₁, hc₂, hc₃⟩ := hrow c hcmem hpred
    rw [hc₃]

end Machine

end Machines

end -- @[expose] public section
