//! THE LIFECYCLE DIFFERENTIAL — the implementation's behavior against
//! the model `Machines.HostLifecycle` (the Lean `machine!` declaration;
//! `Machines.HostLifecycle.hostLifecycleTrans_pin` is the table's
//! source of record). The evidence level is the DIFFERENTIAL (03 §3,
//! tested agreement — never a theorem):
//!
//! 1. THE LEGAL ROWS — every row of [`MODEL_TRANS`] (the mirror of the
//!    model's table) is driven through the REAL host: the four driven
//!    transitions as method calls, the four refusal transitions by
//!    sabotage (tampered artifacts, invalid bytes, wrong signature, a
//!    trapping guest). Each row's landing phase must equal the model's.
//! 2. THE ILLEGAL PAIRS — every (event, from) NOT in the table refuses
//!    with the TYPED `HostError::Lifecycle` and leaves the phase
//!    unchanged (the phase-guard discipline, swept).
//! 3. THE JOURNAL DISCIPLINE — the Live loop's crash honesty: a crash
//!    after the journal effect (before any acknowledgement) recovers
//!    on reopen; a proposal that never committed leaves NO trace; a
//!    torn tail recovers to the last good frame AND reports the cut.
//! 4. THE COMMIT DUEL — the live loop verdict-for-verdict against the
//!    Lean checker's committed expectations.
//!
//! Mandatory negative controls: the clean journal reports NO recovery
//! (the torn-tail tooth does not fire on clean logs); the committed
//! artifacts pass the happy path (the refusal teeth are not vacuously
//! wide); the duel's verdict is exercised at its refuse rows (the
//! committed manifest's `refuse` expectations genuinely refuse).

use mandate_delta::{Delta, Value};
use std::fs;
use std::path::PathBuf;

use mandate_host::{
    Account, EVENT_CALL, EVENT_INSTANTIATE, EVENT_LOAD, EVENT_START, EVENT_STOP, GUEST_GOLDEN,
    HostError, HostMachine, Live, MODEL_TRANS, Phase, bytes_hash, ledger_schema, run_commit_duel,
};

fn committed_dir() -> PathBuf {
    mandate_host::repo_gen_dir()
}

/// A fresh per-test copy of the committed component artifact set (the
/// tamper teeth mutate their copy, never the committed universe).
fn scratch(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "mandate-host-lifecycle-{}-{name}",
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("scratch dir");
    let committed = committed_dir();
    for f in [
        "component-slice.wasm",
        "component-slice.wasm.hdr",
        "component-slice.wit",
    ] {
        fs::copy(committed.join(f), dir.join(f)).expect("copy the committed artifact");
    }
    dir
}

/// A scratch dir carrying `wasm_bytes` as the component artifact, with
/// a FRESH sidecar computed over exactly those bytes (the hash tie
/// passes — the tie proves identity, not correctness — so the bytes
/// reach the engine and the ENGINE's refusal is what the differential
/// observes).
fn doctored_scratch(name: &str, wasm_bytes: &[u8]) -> PathBuf {
    let dir = scratch(name);
    fs::write(dir.join("component-slice.wasm"), wasm_bytes).expect("write the doctored bytes");
    let sidecar = format!(
        "// GENERATED by componentgen (lean-4.33.0) at - — DO NOT EDIT\n\
         // spec test | Guest.Component | 1 item(s) | content hash {} | regen: just gen\n",
        bytes_hash(wasm_bytes)
    );
    fs::write(dir.join("component-slice.wasm.hdr"), sidecar).expect("write the fresh sidecar");
    dir
}

/// Invalid component bytes: the committed component's MAGIC corrupted
/// (the tie passes; the engine refuses — refuseInstantiate's face).
fn invalid_component_bytes() -> Vec<u8> {
    let mut wasm = fs::read(committed_dir().join("component-slice.wasm")).expect("read");
    wasm[0] ^= 0xff;
    wasm
}

/// A VALID component carrying `add64` with the WRONG component RESULT
/// type (`string`, not `u64`) — the surface check passes (the arity is
/// the params' count: `add64/2`), the engine instantiates, and the
/// start-time typed lift refuses (refuseStart's face — the signature
/// teeth live at the lift, past the skew fail-fast's arity surface).
fn wrong_signature_bytes() -> Vec<u8> {
    let wat = r#"(component
  (core module $m
    (memory (export "memory") 1)
    (func (export "canonical_abi_realloc") (param i32 i32 i32 i32) (result i32) i32.const 1024)
    (type $core_add (func (param i64 i64) (result i32)))
    (func (type $core_add) (param i64 i64) (result i32) i32.const 1024)
    (export "add64" (func 1)))
  (core instance $i (instantiate $m))
  (alias core export $i "memory" (core memory $mem))
  (alias core export $i "canonical_abi_realloc" (core func $realloc))
  (type $t (func (param "a" u64) (param "b" u64) (result string)))
  (func $f (type $t) (canon lift (core func $i "add64") (memory $mem) (realloc $realloc)))
  (export "add64" (func $f)))"#;
    wat::parse_str(wat).expect("the wrong-sig component builds")
}

/// A VALID, correctly-signed `add64` that TRAPS on call (the model's
/// `trap` face).
fn trapping_bytes() -> Vec<u8> {
    let wat = r#"(component
  (core module $m (type (func (param i64 i64) (result i64)))
    (func (type 0) (param i64 i64) (result i64) unreachable)
    (export "add64" (func 0)))
  (core instance $i (instantiate $m))
  (type $t (func (param "a" u64) (param "b" u64) (result u64)))
  (func $f (type $t) (canon lift (core func $i "add64")))
  (export "add64" (func $f)))"#;
    wat::parse_str(wat).expect("the trapping component builds")
}

/// The tampered fixture (a flipped byte — the load-time hash tie
/// refuses): the Failed phase's construction site.
fn tampered_scratch(name: &str) -> PathBuf {
    let dir = scratch(name);
    let p = dir.join("component-slice.wasm");
    let mut wasm = fs::read(&p).expect("read");
    let last = wasm.len() - 1;
    wasm[last] ^= 0xff;
    fs::write(&p, wasm).expect("write");
    dir
}

/// A host driven TO the given phase (the sweep's fixture). `Failed`
/// rides the tampered-load path (the model's `refuseLoad`).
fn host_at(phase: Phase) -> HostMachine {
    let mut h = HostMachine::new();
    match phase {
        Phase::Unloaded => {}
        Phase::Loaded => {
            h.load(&committed_dir()).expect("load the committed set");
        }
        Phase::Instantiated => {
            h.load(&committed_dir()).expect("load");
            h.instantiate().expect("instantiate");
        }
        Phase::Running => {
            h.load(&committed_dir()).expect("load");
            h.instantiate().expect("instantiate");
            h.start().expect("start");
        }
        Phase::Stopped => {
            h.load(&committed_dir()).expect("load");
            h.instantiate().expect("instantiate");
            h.start().expect("start");
            h.stop().expect("stop");
        }
        Phase::Failed => {
            let dir = tampered_scratch("host-at-failed");
            h.load(&dir).expect_err("the tampered load refuses");
        }
    }
    assert_eq!(
        h.phase(),
        phase,
        "the fixture must land exactly at {phase:?}"
    );
    h
}

/// THE HAPPY PATH (and the refusal teeth's negative control): the
/// committed artifact set drives the FULL lifecycle — every phase
/// lands exactly where the model's table says.
#[test]
fn happy_path_lands_each_model_row() {
    let mut h = HostMachine::new();
    assert_eq!(h.phase(), Phase::Unloaded);
    h.load(&committed_dir()).expect("load");
    assert_eq!(h.phase(), Phase::Loaded);
    h.instantiate().expect("instantiate");
    assert_eq!(h.phase(), Phase::Instantiated);
    h.start().expect("start");
    assert_eq!(h.phase(), Phase::Running);
    let got = h.call(2, 3).expect("the golden call");
    assert_eq!(got, GUEST_GOLDEN);
    assert_eq!(
        h.phase(),
        Phase::Running,
        "the call is running's activity, not a transition"
    );
    h.stop().expect("stop");
    assert_eq!(h.phase(), Phase::Stopped);
}

/// THE LEGAL ROWS, driven: each of the four driven transitions from
/// its model `from`-phase lands the host at the model's `to`-phase.
#[test]
fn the_driven_rows_agree_with_the_model() {
    for (event, from, to) in MODEL_TRANS {
        // The refusal rows are ENVIRONMENT-INDUCED (no method drives
        // them) — the_differential pins them via sabotage in
        // `the_refusal_rows_agree_with_the_model`.
        if !matches!(
            *event,
            EVENT_LOAD | EVENT_INSTANTIATE | EVENT_START | EVENT_STOP
        ) {
            continue;
        }
        let mut h = host_at(*from);
        let result = match *event {
            EVENT_LOAD => h.load(&committed_dir()),
            EVENT_INSTANTIATE => h.instantiate(),
            EVENT_START => h.start(),
            EVENT_STOP => h.stop(),
            _ => unreachable!("filtered above"),
        };
        assert!(
            result.is_ok(),
            "{event} from {from:?} must drive: {result:?}"
        );
        assert_eq!(
            h.phase(),
            *to,
            "{event}: the landing phase must be the model's"
        );
    }
}

/// THE REFUSAL ROWS, induced: each refusal transition's terminal face
/// is `Failed` — the escape path is an EXPLICIT transition (03 §4),
/// and the typed error surfaces.
#[test]
fn the_refusal_rows_agree_with_the_model() {
    // refuseLoad: unloaded → failed — the tampered artifact set (the
    // load-time hash tie refuses).
    let mut h = HostMachine::new();
    let dir = tampered_scratch("refuse-load");
    let err = h.load(&dir).expect_err("refuseLoad");
    assert!(
        matches!(err, HostError::ContentHashMismatch { .. }),
        "{err:?}"
    );
    assert_eq!(h.phase(), Phase::Failed);

    // refuseInstantiate: loaded → failed — hash-tied bytes the engine
    // refuses to compile.
    let mut h = HostMachine::new();
    let dir = doctored_scratch("refuse-instantiate", &invalid_component_bytes());
    h.load(&dir)
        .expect("the doctored set loads (the tie passes)");
    assert_eq!(h.phase(), Phase::Loaded);
    let err = h.instantiate().expect_err("refuseInstantiate");
    assert!(matches!(err, HostError::EngineRefused(_)), "{err:?}");
    assert_eq!(h.phase(), Phase::Failed);

    // refuseStart: instantiated → failed — a valid component whose
    // export's signature drifts from the world's contract.
    let mut h = HostMachine::new();
    let dir = doctored_scratch("refuse-start", &wrong_signature_bytes());
    h.load(&dir).expect("load");
    h.instantiate()
        .expect("the wrong-sig component instantiates");
    let err = h.start().expect_err("refuseStart");
    assert!(matches!(err, HostError::ComponentSignature(_)), "{err:?}");
    assert_eq!(h.phase(), Phase::Failed);

    // trap: running → failed — a valid, correctly-signed export that
    // traps on call.
    let mut h = HostMachine::new();
    let dir = doctored_scratch("trap", &trapping_bytes());
    h.load(&dir).expect("load");
    h.instantiate().expect("instantiate");
    h.start().expect("start");
    let err = h.call(2, 3).expect_err("trap");
    assert!(matches!(err, HostError::Engine(_)), "{err:?}");
    assert_eq!(h.phase(), Phase::Failed);
}

/// THE ILLEGAL-PAIR SWEEP: every (event, from) NOT in the model's
/// table refuses TYPED (`HostError::Lifecycle` — the model's legality
/// made a type error) and leaves the phase UNCHANGED. The sweep is
/// total over the driven events × the phases, minus the legal rows.
#[test]
fn every_illegal_pair_refuses_typed_and_stays_put() {
    for from in Phase::ALL {
        for event in [EVENT_LOAD, EVENT_INSTANTIATE, EVENT_START, EVENT_STOP] {
            let legal = MODEL_TRANS
                .iter()
                .any(|(e, f, _)| *e == event && *f == from);
            if legal {
                continue;
            }
            let mut h = host_at(from);
            let result = match event {
                EVENT_LOAD => h.load(&committed_dir()),
                EVENT_INSTANTIATE => h.instantiate(),
                EVENT_START => h.start(),
                EVENT_STOP => h.stop(),
                _ => unreachable!("the driven events are enumerated"),
            };
            match result {
                Err(HostError::Lifecycle { from: f, event: e }) => {
                    assert_eq!(f, from.name(), "the error names the phase it refused");
                    assert_eq!(e, event);
                }
                other => panic!(
                    "{event} from {from:?}: expected the typed Lifecycle refusal, got {other:?}"
                ),
            }
            assert_eq!(
                h.phase(),
                from,
                "an illegal transition never moves the host"
            );
        }
    }
}

/// THE NAMED TOOTH (the task's example, pinned alone): a run export
/// before instantiation refuses — TYPED — from every phase the model
/// does not make callable.
#[test]
fn a_call_before_running_refuses_typed() {
    for from in Phase::ALL {
        if from == Phase::Running {
            continue;
        }
        let mut h = host_at(from);
        let err = h
            .call(2, 3)
            .expect_err("the call is legal only from Running (the model's guard)");
        assert!(
            matches!(
                err,
                HostError::Lifecycle {
                    event: EVENT_CALL,
                    ..
                }
            ),
            "{err:?}"
        );
        assert_eq!(h.phase(), from);
    }
}

/// THE MODEL MIRROR'S SHAPE: 8 rows, each (event, from) distinct, each
/// from/to a phase of the enumeration, and the four refusal rows all
/// land `Failed` (the terminal face). A mirror that grew a duplicate
/// or a phantom phase fails here (the drift the differential hunts).
#[test]
fn the_model_mirror_is_total_and_closed() {
    assert_eq!(MODEL_TRANS.len(), 8);
    let mut pairs: Vec<(&str, &str)> = MODEL_TRANS.iter().map(|(e, f, _)| (*e, f.name())).collect();
    pairs.sort();
    pairs.dedup();
    assert_eq!(
        pairs.len(),
        8,
        "each (event, from) pair appears at most once"
    );
    for (_, _, to) in MODEL_TRANS {
        assert!(
            Phase::ALL.contains(to),
            "every to-phase is in the enumeration"
        );
    }
    for (event, from, to) in MODEL_TRANS {
        if event.starts_with("refuse") || *event == "trap" {
            assert_eq!(
                *to,
                Phase::Failed,
                "{event} lands the terminal refusal face"
            );
            assert_ne!(
                *from,
                Phase::Failed,
                "no refusal fires FROM the terminal face"
            );
        }
    }
}

// ── The journal discipline: the Live loop's crash honesty ──────────

fn journal_scratch(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "mandate-host-liverec-{}-{name}",
        std::process::id()
    ));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("scratch dir");
    dir
}

/// The ledger row in the journal's field order (tid/src/dst/amount).
fn ledger_row(tid: u64, src: u64, dst: u64, amount: u64) -> mandate_delta::Row {
    mandate_delta::Row::build(
        &ledger_schema(),
        vec![
            Value::U64(tid),
            Value::U64(src),
            Value::U64(dst),
            Value::U64(amount),
        ],
    )
    .expect("the ledger row matches its own schema")
}

/// CRASH HONESTY, the mid-lifecycle cut: the commit's journal effect
/// landed (append + fsync — `Journal::record` returned), then the
/// process died BEFORE the acknowledgement (the in-memory apply, the
/// caller's verdict — simulated here by writing the journal DIRECTLY
/// and dropping everything). Recovery is honest: the durable log IS
/// the truth, and reopen reconstructs the full live state — the
/// transfer in the ledger, the balances moved, the version bumped.
#[test]
fn crash_after_the_journal_effect_recovers_honestly() {
    let dir = journal_scratch("crash-after-effect");
    let path = dir.join("journal.bin");
    {
        // The effect lands; the process "dies" before ANYTHING else.
        let mut j = mandate_host::Journal::open(&path, ledger_schema()).expect("open");
        j.record(Delta::Insert(ledger_row(7, 1, 2, 10)))
            .expect("the durable effect");
    }
    let live = Live::open(&path).expect("the reopen recovers the durable log");
    assert_eq!(
        live.version(),
        2,
        "the accepted commit's version bump survives the crash"
    );
    assert_eq!(
        live.transfers().len(),
        1,
        "the journaled transfer IS in the ledger"
    );
    assert_eq!(
        live.accounts(),
        &[
            Account {
                id: 1,
                owner: "alice".into(),
                balance: 90
            },
            Account {
                id: 2,
                owner: "bob".into(),
                balance: 60
            },
        ],
        "the balances moved: the derived state replays the durable effect"
    );
}

/// CRASH HONESTY, the other face: a PROPOSAL that never committed
/// (crash between propose and commit) leaves NO durable trace — the
/// reopen must NOT resurrect work that was never authorized. The
/// journal carries accepted effects, not intentions.
#[test]
fn a_proposal_that_never_committed_leaves_no_trace() {
    let dir = journal_scratch("crash-before-commit");
    let path = dir.join("journal.bin");
    {
        let live = Live::open(&path).expect("fresh");
        let p = live.propose(9, 1, 2, 25);
        // The proposal is computed... and the process dies. No commit,
        // no journal entry — `p` is pure data (a Copy), the point.
        let _ = p;
    }
    let live = Live::open(&path).expect("reopen");
    assert_eq!(live.version(), 1, "no accepted commit — no bump");
    assert!(
        live.transfers().is_empty(),
        "no journaled intent — the proposal is gone"
    );
    assert!(live.violations().is_empty());
    assert_eq!(
        live.accounts(),
        &[
            Account {
                id: 1,
                owner: "alice".into(),
                balance: 100
            },
            Account {
                id: 2,
                owner: "bob".into(),
                balance: 50
            },
        ],
        "the fixture state, untouched"
    );
}

/// THE TORN TAIL: a crash MID-APPEND (half a frame on disk) recovers
/// to the last good frame — and the cut is REPORTED (the recovery
/// report is data, never silence). The good prefix's commits survive.
#[test]
fn a_torn_tail_recovers_to_the_last_good_frame_and_reports() {
    let dir = journal_scratch("torn-tail");
    let path = dir.join("journal.bin");
    {
        let mut live = Live::open(&path).expect("fresh");
        let p1 = live.propose(1, 1, 2, 10);
        assert!(matches!(
            live.commit(&p1),
            Ok(mandate_host::LiveVerdict::Committed { .. })
        ));
        let p2 = live.propose(2, 2, 1, 5);
        assert!(matches!(
            live.commit(&p2),
            Ok(mandate_host::LiveVerdict::Committed { .. })
        ));
    }
    // The crash mid-append: half of a VALID next frame hits the disk.
    let mut bytes = fs::read(&path).expect("read the journal");
    let mut frame = Vec::new();
    assert!(
        mandate_delta::delta::enc_delta(
            &ledger_schema(),
            &Delta::Insert(ledger_row(3, 1, 2, 1)),
            &mut frame
        ),
        "the delta encodes"
    );
    bytes.extend_from_slice(&frame[..frame.len() / 2]);
    fs::write(&path, bytes).expect("write the torn journal");

    let live = Live::open(&path).expect("the recovering open refuses nothing here");
    let recovery = live.recovery().expect("the cut is REPORTED, never silent");
    assert!(
        recovery.frames == 2,
        "the good prefix carries the two commits"
    );
    assert_eq!(live.version(), 3, "the version rides the good prefix");
    assert_eq!(live.transfers().len(), 2);
    // The torn transfer is NOT in the recovered state (it never
    // completely landed — the honest recovery does not invent it).
    assert!(live.transfers().iter().all(|t| t.tid != 3));
}

/// THE REOPEN TOOTH (the Live loop's invariant, pinned): the
/// in-memory state is EXACTLY the journal's replay over the fixture —
/// commit N transfers, reopen, compare the full state.
#[test]
fn reopen_equivalence_the_state_is_the_journal_replay() {
    let dir = journal_scratch("reopen-equivalence");
    let path = dir.join("journal.bin");
    let committed: Vec<(u64, u64, u64, u64)> = vec![(1, 1, 2, 10), (2, 2, 1, 5), (3, 1, 2, 7)];
    let end_accounts: Vec<Account>;
    {
        let mut live = Live::open(&path).expect("fresh");
        for (tid, src, dst, amt) in &committed {
            let p = live.propose(*tid, *src, *dst, *amt);
            assert!(matches!(
                live.commit(&p),
                Ok(mandate_host::LiveVerdict::Committed { .. })
            ));
        }
        end_accounts = live.accounts().to_vec();
        assert_eq!(live.version(), 1 + committed.len() as u64);
    }
    let live = Live::open(&path).expect("reopen");
    assert_eq!(live.version(), 1 + committed.len() as u64);
    assert_eq!(live.transfers().len(), committed.len());
    assert_eq!(
        live.accounts(),
        &end_accounts,
        "the reopen reconstructs the same state"
    );
}

/// THE STALENESS TOOTH (the race-honesty carrier, pinned beside the
/// crash tests): a proposal computed at version 1 refused by a commit,
/// then resubmitted against a moved base REFUSES on the version —
/// typed `Stale`, both versions named, no state change, no journal
/// entry.
#[test]
fn a_stale_proposal_refuses_on_the_version() {
    let dir = journal_scratch("stale");
    let mut live = Live::open(&dir.join("journal.bin")).expect("fresh");
    let stale = live.propose(1, 1, 2, 10);
    let p2 = live.propose(2, 2, 1, 5);
    assert!(matches!(
        live.commit(&p2),
        Ok(mandate_host::LiveVerdict::Committed { version: 2 })
    ));
    match live.commit(&stale) {
        Ok(mandate_host::LiveVerdict::Stale { base: 1, got: 2 }) => {}
        other => panic!("the stale proposal must refuse with both versions: {other:?}"),
    }
    assert_eq!(live.version(), 2, "the refusal changed nothing");
    assert_eq!(live.transfers().len(), 1, "and journaled nothing");
}

/// THE COMMIT DUEL: the live loop runs the Lean-emitted proposal
/// vectors verdict-for-verdict against the Lean checker's committed
/// expectations (the differential's committed face). The honest
/// rendering names the tier: TESTED AGREEMENT, never a theorem.
#[test]
fn the_commit_duel_agrees() {
    let report =
        run_commit_duel(&mandate_host::live::repo_root()).expect("the committed duel runs");
    assert!(
        report.rows.len() >= 4,
        "the committed manifest's rows are present"
    );
    let verdict = report.verdict();
    assert!(
        matches!(verdict, mandate_host::RowVerdict::Agree),
        "the duel must agree: {}",
        report.render()
    );
    assert!(report.render().contains("TESTED AGREEMENT"));
}

// ---------------------------------------------------------------------------
// THE RELOAD (the D6 port): the component swap without a host restart —
// the composition discipline (stop's release + the fresh load →
// instantiate → start sequence, each a model row) + the identity pin.
// ---------------------------------------------------------------------------

/// THE PIN: a running host swaps the component and keeps serving — the
/// identity names the bytes now running (same bytes → same identity;
/// the golden discipline still holds after the swap).
#[test]
fn reload_swaps_and_names_the_identity() {
    let dir = scratch("reload-same");
    let mut h = host_at(Phase::Running);
    let old_identity = h.identity().expect("a running host has an identity");

    let got = h.reload(&dir).expect("the same-bytes swap succeeds");
    assert_eq!(h.phase(), Phase::Running);
    assert_eq!(got, old_identity, "same bytes = same identity");
    // the host still serves the golden after the swap
    let answered = h.call(2, 3).expect("the swapped component answers");
    assert_eq!(answered, GUEST_GOLDEN);
}

/// THE SWAP HONESTY: a swap to DIFFERENT bytes (the tampered component
/// — the hash tie refuses) is a typed refusal, the host lands in
/// `Failed` (the model's escape row), and the old identity is GONE
/// (the resources were released — no half-swap carries stale state).
#[test]
fn reload_refuses_a_tampered_swap_and_lands_failed() {
    let dir = tampered_scratch("reload-tampered");
    let mut h = host_at(Phase::Running);

    let err = h.reload(&dir).expect_err("the tampered swap refuses");
    assert!(
        matches!(err, HostError::ContentHashMismatch { .. }),
        "{err:?}"
    );
    assert_eq!(h.phase(), Phase::Failed);
    assert!(h.identity().is_none(), "a failed host carries no bytes");
}

/// The reload's phase discipline: the pre-run states refuse the
/// composition TYPED (the plain sequence is the path there — a
/// reload label on a fresh host is the illegal-transition refusal),
/// and the phase stays put.
#[test]
fn reload_from_unloaded_refuses_typed() {
    let mut h = HostMachine::new();
    let err = h
        .reload(&committed_dir())
        .expect_err("the pre-run reload refuses");
    assert!(
        matches!(
            err,
            HostError::Lifecycle {
                from: "unloaded",
                event: "reload"
            }
        ),
        "{err:?}"
    );
    assert_eq!(h.phase(), Phase::Unloaded);
}

/// The Failed-state honesty: a host that failed (the tampered swap's
/// terminal face) can swap — the reload is the recovery path (a fresh
/// instance, a fresh identity).
#[test]
fn reload_recovers_a_failed_host() {
    let mut h = host_at(Phase::Running);
    // force the failure: the tampered bytes refuse the hash tie at
    // reload — the host lands Failed (the model's escape row)
    let t = tampered_scratch("reload-recovery");
    let _ = h.reload(&t).expect_err("the tampered swap refuses");
    assert_eq!(h.phase(), Phase::Failed);

    // the recovery: the COMMITTED set reloads the failed host
    let got = h
        .reload(&committed_dir())
        .expect("the failed host recovers");
    assert_eq!(h.phase(), Phase::Running);
    assert_eq!(
        got,
        bytes_hash(&fs::read(committed_dir().join("component-slice.wasm")).expect("read"))
    );
}
