/-
Gates.ArtifactHeaders — the GENERATED-header gate
(`gates artifact-headers`; mined from the legacy justfile's
artifact-headers recipe + Gates, ported fresh).

Every generated artifact carries the 2-line GENERATED header (Kit.Emit's
driver prepends it; the byte-tie strips it). A headerless file at a
declared artifact path is a HAND-WRITTEN FILE SQUATTING on a generated
artifact's path — the one-writer rule's detection face.

Shape (the committed contract, verified per line):
  line 0: `// GENERATED by <writer> (...) — DO NOT EDIT`
  line 1: `// spec <sha> | <specSource> | <n> item(s) | content hash <h> | regen: just gen; drift fails CI`
Checked as: line 0 starts with `// GENERATED by ` and carries the
`— DO NOT EDIT` marker; line 1 names the spec (`spec `), the item count
(`item(s)`), and the content hash (`content hash `). The volatile fields
(clock, spec sha, hash VALUE) are gen-check's business — this gate owns
PRESENCE + SHAPE only.

Surface: the emitters' declared outputs (read from `SchemaCore.regen` —
the same one-regen surface gen-check byte-ties; never a hand-copied
artifact list).

No baseline file — the gate is computed over the committed bytes
(expected violations: none).

The five questions (notes/v3/01-core.md):
- root: none — the header-shape audit over the artifact surface.
- carrier grade: none — line-shape checks over committed bytes.
- spine reading: the artifact stage's provenance face (the header).
- ladder rung: n/a.
- gate row: the artifact-headers row itself (`gates artifact-headers`).
-/
import Lean
import Gates.Packages
import Gates.Common
import SchemaCore

open Lean

namespace Gates.ArtifactHeaders

/-- One artifact's header verdict (ctors, never strings). -/
inductive HeaderVerdict where
  | ok
  | absent
  | malformed (why : String)

/-- The 2-line shape check over the COMMITTED bytes. -/
def headerVerdict (committed : String) : HeaderVerdict :=
  let lines := committed.splitOn "\n"
  match lines[0]?, lines[1]? with
  | some l0, some l1 =>
      if !(l0.startsWith "// GENERATED by ") then
        .malformed "line 0 is not the `// GENERATED by …` block"
      else if !(l0.contains "DO NOT EDIT") then
        .malformed "line 0 lacks the DO NOT EDIT marker"
      else if !(l1.contains "spec ") then
        .malformed "line 1 lacks the spec field"
      else if !(l1.contains "item(s)") then
        .malformed "line 1 lacks the item count"
      else if !(l1.contains "content hash ") then
        .malformed "line 1 lacks the content hash"
      else .ok
  | _, _ => .malformed "file has fewer than 2 lines"

/-- `gates artifact-headers` — presence + shape over every committed
    generated artifact. Exit 1 on any malformed/absent header. -/
unsafe def run : IO UInt32 := do
  let pkg : PkgSpec := { dir := "SchemaCore", roots := #[`SchemaCore.Slice] }
  Gates.withPkgEnv "artifact-headers" pkg fun env => do
    match SchemaCore.regen env with
    | .error e =>
      IO.eprintln s!"artifact-headers: REGEN FAILED — {e}"
      return 1
    | .ok r => do
      let mut failed := false
      let mut ok := 0
      for f in r.files do
        let path : System.FilePath := f.path
        unless ← path.pathExists do
          IO.eprintln s!"artifact-headers: {f.path} ABSENT — a declared \
            artifact has no committed file"
          failed := true
          continue
        let committed ← IO.FS.readFile path
        match headerVerdict committed with
        | .ok => ok := ok + 1
        | .malformed why => do
          IO.eprintln s!"artifact-headers: {f.path} MALFORMED — {why}; \
            a headerless file at a generated path is a hand-written file \
            squatting on the one-writer rule"
          failed := true
        | .absent => pure ()
      if failed then return 1
      IO.println s!"artifact-headers: clean — {ok} artifact(s) carry the \
        2-line GENERATED header"
      return 0

end Gates.ArtifactHeaders
