/-
Gates.Axioms — the per-library axiom sweep (`gates axioms [--write]`;
mined from legacy/lean/gates/Gates/Axioms.lean, simplified to the fresh
tree's scale).

For each gated package (Gates.Packages), its root modules are
`importModules`'d (oleans built by `lake build` — this gate never
builds), every declaration defined in those modules gets its axiom cone
from the kernel's own `Lean.collectAxioms` (the `#print axioms`
machinery), and the cone is checked against the allowlist by CONSUMING
`LintKit.runLintersOnDecls` with every non-axiom linter disabled (the
allowlist itself — `LintKit.isAllowedAxiom` — lives in
LintKit.AxiomAllowlist and is never re-encoded here). `@[nolint]` and
`set_option` snapshots are honored exactly as in the lint runner (the
same runner code path).

The committed baseline is ONE file (notes/axiom-report.md), one
`## <dir>` section per package; without `--write`, a diff against it IS
the CI gate (a silent axiom-surface change fails).

Re-baseline discipline (the loud re-baseline): `--write` REFUSES a
non-empty diff unless `--accept-drift` is also passed — a re-baseline
must not pre-authorize future taint; it is a deliberate act. Writing an
IN-SYNC report is always allowed (a no-op). Violations and load failures
exit 1 regardless of `--write`.

Deliberate exclusion vs the legacy module: the SHARDED mode (one child
process per package, one env per process). The legacy sharding fixed a
~26.5GB peak (every gated package's env in one process — libgc's
conservative stack scan retains each dropped env); this tree's gate
imports two core-only libraries. The sharded protocol arrives with the
first gated package heavy enough to need it.

The five questions (notes/v3/01-core.md):
- root: none — the gate over the tree's axiom surface.
- carrier grade: none — the axiom cone is kernel-collected, not a
presentation crossing.
- spine reading: the interpretation stage (gated envs → decls → cones
→ the committed baseline's diff).
- ladder rung: the ENFORCEMENT of 01 §7's ladder — the allowlist
accepts the core triple + the disclosed native_decide trust base,
nothing else.
- gate row: the axiom-gate row itself (`gates axioms`).
-/
import Lean
import LintKit
import Gates.Packages
import Gates.Common

open Lean

namespace Gates.Axioms

open Gates (PkgSpec gatedPackages)

structure PkgReport where
  dir : String
  decls : Nat := 0
  /-- The distinct axiom set the package's decls depend on, sorted. -/
  axioms : Array Name := #[]
  violations : Array LintKit.LintFinding := #[]
  loadError : Option String := none

/-- Axiom-only lint config: every non-axiom linter whole-disabled at the
    CLI-override level (the runner skips the pass entirely); the axiom
    allowlist keeps its default-on + per-decl snapshot/nolint semantics. -/
def axiomOnlyConfig : LintKit.DriverConfig :=
  { overrides := ({} : NameMap Bool)
      |>.insert `linter.guestlang.dupDefBodies false
      |>.insert `linter.guestlang.packageNamespace false }

/-- Per-package analysis over its imported environment: the allowlist
    violations (LintKit's runner, unmodified) + the distinct axiom union
    (the kernel's CollectAxioms per decl). -/
def analyzeEnv (roots : Array Name) :
    CoreM (Array Name × Array LintKit.LintFinding × Array Name) := do
  let decls ← LintKit.packageDecls (← getEnv) roots
  let findings ← LintKit.runLintersOnDecls decls axiomOnlyConfig
  let mut axs : NameSet := {}
  for d in decls do
    for a in ← collectAxioms d do
      axs := axs.insert a
  return (decls, findings, axs.toArray.qsort Name.quickLt)

/-- Import one package's roots via the shared loadPkgEnv preamble and
    analyze. -/
unsafe def analyzePkg (base : SearchPath) (pkg : PkgSpec) : IO PkgReport := do
  match ← Gates.loadPkgEnv base pkg with
  | .error e =>
    return { dir := pkg.dir, loadError := some e }
  | .ok env =>
    -- the package's EXACT roots (no getRoot widening): the fixture-rig
    -- namespaces' planted violators must stay out of the decl-level
    -- sweep (the lint driver's lintModulesExact discipline, same reason)
    let modRoots := pkg.roots
    let ctx : Core.Context := { fileName := "<gates-axioms>", fileMap := default }
    let (res, _) ← (analyzeEnv modRoots).toIO ctx { env := env }
    let (decls, findings, axs) := res
    return { dir := pkg.dir, decls := decls.size, axioms := axs, violations := findings }

/-- The committed report this gate diffs against. -/
def reportPath : System.FilePath := "notes/axiom-report.md"

/-- The committed report's fixed header (everything before the first
    `## ` section line). -/
def reportHeader : List String :=
  [ "# Axiom report — the global axiom surface"
  , ""
  , "GENERATED by `lake exe gates axioms --write` — do not hand-edit."
  , "CI runs `gates axioms` without `--write`; a diff against this file fails the gate."
  , ""
  , "Per package: every declaration of the listed root modules gets its axiom cone"
  , "from the kernel's CollectAxioms; the allowlist (propext, Classical.choice,"
  , "Quot.sound, disclosed _native.native_decide./_native.bv_decide. trust bases)"
  , "is LintKit.AxiomAllowlist's, consumed via LintKit.runLintersOnDecls."
  , "" ]

/-- One package block (deterministic: axioms sorted, violations sorted
    by decl name upstream). Ends with its blank separator line. -/
def renderBlock (r : PkgReport) : List String :=
  match r.loadError with
  | some e =>
    [ s!"## {r.dir}", "", s!"LOAD FAILED: {e}", "" ]
  | none =>
    [ s!"## {r.dir} — {r.decls} decls checked"
    , ""
    , s!"axioms used: {if r.axioms.isEmpty then "(none — fully constructive)"
        else String.intercalate ", " (r.axioms.map toString).toList}"
    , s!"violations: {if r.violations.isEmpty then "none"
        else toString r.violations.size ++ " (see gate output)"}"
    , "" ]

/-- One package's result line + violation messages, on STDERR (the
    shard's human face; stdout is the report block). Returns whether it
    failed (load error or allowlist violations). -/
def printReportStderr (r : PkgReport) : IO Bool := do
  match r.loadError with
  | some e =>
      IO.eprintln s!"{r.dir}: LOAD FAILED — {e}"
      return true
  | none =>
      IO.eprintln s!"{r.dir}: {r.decls} decls, axioms [{String.intercalate ", " (r.axioms.map toString).toList}], {r.violations.size} violation(s)"
      for v in r.violations do
        IO.eprintln v.message
      return !r.violations.isEmpty

/-- ONE package's shard (the per-package process — the memory
    discipline: libgc's conservative stack scan retains each dropped
    env, and 37 gated packages folded in one process peaked past the
    OOM line, observed): the report BLOCK on stdout (the parent
    assembles the baseline from the shards' blocks), the human line +
    violations on stderr, exit 1 on violations or a load failure. -/
unsafe def runPkg (pkg : PkgSpec) : IO UInt32 := do
  Lean.initSearchPath (← Lean.findSysroot)
  let base ← Lean.searchPathRef.get
  let r ← analyzePkg base pkg
  for l in renderBlock r do
    IO.println l
  let failed ← printReportStderr r
  return if failed then 1 else 0

/-- `gates axioms [--package=<dir>]` — the shard dispatch: with the
    flag, ONE package's scan (the child's body, its report block on
    stdout); without, one CHILD PROCESS per gated package (stdio
    inherited for the human faces) and the captured blocks assembled
    into the committed baseline's fresh render. -/
unsafe def run (write acceptDrift : Bool) (package : Option String) : IO UInt32 := do
  match package with
  | some dir =>
      match gatedPackages.toList.find? fun p => p.dir == dir with
      | none =>
          IO.eprintln s!"axioms: --package={dir} names no Gates.Packages row"
          return 1
      | some pkg => runPkg pkg
  | none =>
      -- initSearchPath reads LEAN_PATH (`lake exe` supplies the dep
      -- closure) + the sysroot; the shards' loadPkgEnv prepends the
      -- root build dir per import.
      Lean.initSearchPath (← Lean.findSysroot)
      let mut blocks : Array String := #[]
      let mut failed := false
      for pkg in gatedPackages do
        let child ← IO.Process.spawn
          { cmd := "lake"
          , args := #["exe", "gates", "axioms", s!"--package={pkg.dir}"]
          , stdout := .piped, stderr := .inherit }
        let block ← child.stdout.readToEnd
        let code ← child.wait
        blocks := blocks.push block
        if code != 0 then failed := true
      let text :=
        String.intercalate "\n"
          (reportHeader ++ (blocks.toList.flatMap (·.splitOn "\n")))
      -- the write-or-diff tail: reportGate's accept-drift discipline
      Driver.reportGate "axioms" "report" "the axiom surface changed"
        reportPath text write acceptDrift failed
        "axioms: clean — every decl's cone inside the allowlist, report in sync"

end Gates.Axioms
