/-
Gates.Census — the proof-hygiene CENSUS rows, promoted to baselined
report-gates (the axiom-report pattern: the fresh render committed,
drift flagged, the loud re-baseline discipline) at 09 §8's trigger —
the first adjudicated NONEMPTY run.

* `decide-first-census` — `linter.guestlang.decideFirst` (04 §1: a
  decidable closed finite space gets `decide`, not a hand script).
* `zero-citation-census` — `linter.guestlang.zeroCitation` (the
  proof-level leftover rule: a theorem cited nowhere outside its own
  module is the proof layer's dead code — or the named public-API/
  load-bearing `@[nolint]` row).
* `evidence-redundancy-census` — `linter.guestlang.evidenceRedundancy`
  (B6; D37; 16-surface §3: re-proofs of carried laws + weaker-than-
  kernel obligation rows — the entourage's first question, at the
  hand-written face).

Promotion, not hard-gating: the census linters stay default-OFF (their
heuristics' limits are named in their own headers — promoting them to
FAIL-on-finding would tax every honest declaration with the census's
uncertainty, the 09 §8 reasoning verbatim); the gate consumes the
FINDINGS as data. A drift — a new finding, or one adjudicated away —
fails the row until the deliberate re-baseline names it.

The shard rides `Gates.shardDispatch` (one child per gated package —
the memory discipline; the report block on stdout, the parent assembles
the baseline — the Axioms twin's shape) + `Driver.reportGate` (the
write-or-diff tail).

The five questions (notes/v3/01-core.md): none of its own — the
censuses' answers live in their linters (DecideFirst/ZeroCitation);
this module is the gate rows.
-/
import Lean
import LintKit
import Gates.Packages
import Gates.Common

namespace Gates.Census

open Gates (PkgSpec gatedPackages)
open Lean

/-- One census row's identity: the linter option + the committed baseline
+ the human name (the two rows are ONE shape). -/
structure Census where
  /-- The default-OFF linter option the census enables. -/
  opt : Name
  /-- The committed baseline (the axiom-report pattern). -/
  path : System.FilePath
  /-- The gate row's name (the dispatch + the report face). -/
  gate : String

/-- The decide-first census: 04 §1's rung discipline, census mode. -/
def decideFirst : Census :=
  { opt := `linter.guestlang.decideFirst
    path := "notes/decide-first-census.md", gate := "decide-first-census" }

/-- The zero-citation census: the proof-level leftover rule, census mode. -/
def zeroCitation : Census :=
  { opt := `linter.guestlang.zeroCitation
    path := "notes/zero-citation-census.md", gate := "zero-citation-census" }

/-- The evidence-redundancy census: D37's teeth (B6), census mode. -/
def evidenceRedundancy : Census :=
  { opt := `linter.guestlang.evidenceRedundancy
    path := "notes/evidence-redundancy-census.md",
    gate := "evidence-redundancy-census" }

/-- The census lint config: EVERY env-linter whole-disabled except the
census linter, enabled at the CLI-override level (the runner skips the
disabled passes entirely; the axiomOnlyConfig shape). -/
def censusConfig (c : Census) : LintKit.DriverConfig :=
  { overrides :=
      (({} : NameMap Bool)
        |>.insert `linter.guestlang.axiomAllowlist false
        |>.insert `linter.guestlang.dupDefBodies false
        |>.insert `linter.guestlang.packageNamespace false
        |>.insert `linter.guestlang.bareChecker false
        |>.insert `linter.guestlang.verdictCtors false
        |>.insert `linter.guestlang.recursiveSimpEqns false
        |>.insert `linter.guestlang.guestBan false
        |>.insert `linter.guestlang.graduation false
        |>.insert `linter.guestlang.decideFirst false
        |>.insert `linter.guestlang.zeroCitation false
        |>.insert `linter.guestlang.evidenceRedundancy false)
        |>.insert c.opt true }

/-- One package's census analysis over its loaded env: the census
linter's findings, the decl names sorted (the deterministic report). -/
def analyzeEnv (c : Census) (roots : Array Name) :
    Lean.CoreM (Array Name) := do
  let decls ← LintKit.packageDecls (← getEnv) roots
  let findings ← LintKit.runLintersOnDecls decls (censusConfig c)
  return (findings.map (·.decl) |>.qsort Name.quickLt)

/-- The committed report's fixed header (everything before the first
`## ` section line). -/
def reportHeader (c : Census) (title descr : String) : List String :=
  [ s!"# {title}"
  , ""
  , s!"GENERATED by `lake exe gates {c.gate} --write` — do not hand-edit."
  , s!"CI runs `{c.gate}` without `--write`; a diff against this file fails the gate."
  , ""
  , descr
  , ""
  , "Per package: the census linter's findings over the package's root modules'"
  , "declarations, one `  <decl>` line per finding; a section with no finding"
  , "lines means zero findings. A drift (a new finding, or one adjudicated"
  , "away) fails the gate until the deliberate `--write --accept-drift`"
  , "re-baseline. Findings are DATA here (the promotion, not a hard gate);"
  , "each line is fixed, a reasoned `@[nolint]`, or this baseline's record."
  , "" ]

/-- ONE package's shard (the per-package process — the memory
discipline): the report BLOCK on stdout, the load failure on stderr. -/
unsafe def runPkg (c : Census) (pkg : PkgSpec) : IO UInt32 := do
  Lean.initSearchPath (← Lean.findSysroot)
  let base ← Lean.searchPathRef.get
  match ← Gates.analyzePkg c.gate (·.roots) (analyzeEnv c) base pkg with
  | .inl e =>
      IO.eprintln s!"{c.gate}: {pkg.dir}: LOAD FAILED — {e}"
      return 1
  | .inr decls =>
      IO.println s!"## {pkg.dir}"
      for d in decls do
        IO.println s!"  {d}"
      IO.println ""
      return 0

/-- `{c.gate} [--package=<dir>] [--write] [--accept-drift]` — the
census gate row: one child process per gated package, the blocks
assembled into the committed baseline's fresh render, the write-or-diff
tail. -/
unsafe def run (c : Census) (title descr : String)
    (write acceptDrift : Bool) (package : Option String) : IO UInt32 :=
  Gates.shardDispatch c.gate package (runPkg c) fun outs => do
    Lean.initSearchPath (← Lean.findSysroot)
    let mut failed := false
    for (code, _) in outs do
      if code != 0 then failed := true
    let blocks := outs.map (·.2)
    let text :=
      String.intercalate "\n"
        (reportHeader c title descr ++ (blocks.toList.flatMap (·.splitOn "\n")))
    Driver.reportGate c.gate c.path text write acceptDrift failed
      s!"{c.gate}: clean — the census in sync (the findings baselined, drift flagged)"
      (Driver.diffCheck c.gate "report" "the census's findings changed" c.path text)

end Gates.Census
