/-
Gates.ElabWatch — the elaboration-time regression watch
(`gates elab-watch [--write] [--accept-drift]`; notes/v3/09-gates-ops.md §7:
"type-driven gating shifts work into elaboration; the gates exe logs
per-module elaboration time and flags DELTAS against the committed
baseline — absolute budgets are noise; regressions are signal").

The measurement face, honestly: for every gated root (Gates.Packages'
table — the single source, never a parallel copy) the gate spawns
`lake env lean <source>` and wall-times it. The imports resolve to
committed oleans, so the invocation re-elaborates ONLY the module's own
declarations — the per-module elaboration cost the doctrine names —
without writing an olean (the build cache is untouched). One invocation
per module, SEQUENTIAL by default: parallelism loads the machine and
inflates the timings — a timing gate that runs its measurements on a
loaded box measures the load, not the module (GATES_ELAB_JOBS raises
the concurrency at the operator's own risk).

The delta discipline (§7): a module whose measured time exceeds 2× its
committed baseline REGRESSES — the finding. Small drifts (±20% run to
run) are noise and pass. A jitter floor (GATES_ELAB_FLOOR_MS, default
1500) keeps the sub-second modules honest: on ANY shared box (CI
runners included) a 300ms module swings past 2× under ordinary load —
its ratio is noise, not signal; the watch's signal lives in the
multi-second roots, where 2× is real elaboration work. This is a jitter
guard, NOT an absolute budget (the doctrine: absolute budgets are
noise); a module under the floor cannot flag however large its RATIO.
New modules (a gated root with no baseline row) and stale rows
(a baseline module no longer gated) are findings too — the ratchet is
fail-closed both ways (the native-policy precedent): the baseline grows
only deliberately, and never outlives its module.

The baseline (`notes/elab-baseline.tsv`, GENERATED by the write face):
one `module<TAB>millis` row per gated root, gatedPackages order, `#`
comment header. A MALFORMED row (not exactly two tab fields, non-numeric
millis) is a finding — a hand-edited baseline is a discipline violation
(the code-registry replay precedent). The write face rides the loud
re-baseline discipline (Driver.reportGate's shape): `--write` refuses a
non-empty diff without `--accept-drift` — a re-baseline must not
pre-authorize future taint; a regression accepted through
`--write --accept-drift` is a deliberate, commit-visible act.

The CI face: `just gates` runs this row; the workflow runs `just ci`
verbatim (the local/CI parity discipline, notes/v3/13-interfaces.md);
a red run names the gate + the divergence (module, baseline, budget,
measured) — never a bare failure.

Cost note (the degradation rule, 09 §7 / 01's ladder): the sweep is
one sequential `lean` invocation per gated root — the same per-module
replay cost class as the kernel-check, paid once per battery run.

The five questions (notes/v3/01-core.md):
- root: none — a host-side timing gate over the gated set (no new
root; the gated set IS Gates.Packages' Universe row).
- carrier grade: none — measured wall times, not a crossing.
- spine reading: the check face of the elaboration stage (the
committed baseline vs the fresh replay, the report-gate discipline).
- ladder rung: n/a (this IS the §7 watch).
- gate row: the elab-watch row itself (`gates elab-watch`, the
registry's newest entry).
-/
import Lean
import Kit.Correspondence
import Gates.Baselines
import Gates.Packages
import Gates.Common

namespace Gates.ElabWatch

/-! ## The baseline data (the TSV faces) -/

/-- One baseline row: the gated root's module name + its committed
    elaboration milliseconds + the reference root's milliseconds in the
    SAME sweep (the ratio is the signal; see the module header). (`mod`,
    not `module` — the latter is a parser keyword.) THE GRAMMAR LAYER's
    row: the type, the format's grammar value, and the round-trip laws
    live in `Gates.Baselines` (the CodeRegistry template's flat shape);
    this module consumes them — the hand render/parse pair died. -/
abbrev Entry := Gates.Baselines.ElabRow

/-- The reference root: the stable core-only module every sweep re-times
    alongside the gated roots — machine speed + sustained load divide
    out of the module/reference ratio. -/
def referenceMod : String := "ZSet"

/-- The committed baseline this gate diffs against. -/
def baselinePath : System.FilePath := "notes/elab-baseline.tsv"

/-- Is a (trimmed) baseline line a DATA row (neither empty nor a `#`
    comment)? -/
def isDataRow (line : String) : Bool :=
  line != "" && !line.startsWith "#"

/-- Parse one DATA line through the format's grammar: the CANONICAL
    reader (the fields' spellings exact — a hand-edited field count, a
    leading-zero millisecond, or a stray space is a REFUSAL: the drift
    tooth; the code-registry replay precedent). The zero-reference
    refusal is the READER's semantic face (a zero reference makes the
    ratio meaningless — the finding), kept at the gate's finding walk. -/
@[nolint linter.guestlang.unregisteredRoundtrip "the correspondence is registered in Gates.Baselines (elabCodec/elabIso — the grammar-layer codec with the proved laws); this is the LENIENT READER face over it (the refusals are the gate's findings, not the codec's)"]
def parseLine? (line : String) : Option Entry :=
  match TextKit.Grammar.run Gates.Baselines.elabLineG (line ++ "\n") with
  | Except.ok e => some (Gates.Baselines.elabOfRaw e)
  | Except.error _ => Option.none

/-- The correspondence, named in code: the line codec is registered in
    Gates.Baselines (the grammar-layer `Kit.Codec` with the proved
    laws); this file's `parseLine?`/`render` are its faces. -/
def elabLineCorrespondence := Gates.Baselines.elabCodec

/-- Parse the TSV: the rows + the malformed DATA lines. -/
def parse (text : String) : Array Entry × Array String :=
  let lines := text.splitOn "\n"
  let rows : Array Entry :=
    (lines.filterMap (fun l => if isDataRow l then parseLine? l else none)).toArray
  let bad : Array String :=
    (lines.filter (fun l => isDataRow l && (parseLine? l).isNone)).toArray
  (rows, bad)

/-- The fresh render (the write face's bytes): THE GRAMMAR'S DERIVED
    PRINTER — the constant header's atoms + the rows' fold (the hand
    byte-assembly died; the bytes are unchanged — the gate's green run
    without a re-baseline is the proof). The correspondence: the
    `Kit.Codec` is registered in Gates.Baselines (`elabCodec`/
    `elabIso`, the grammar-layer codec with the proved laws); this is
    its printer face. -/
@[nolint linter.guestlang.unregisteredRoundtrip "the correspondence is registered in Gates.Baselines (elabCodec/elabIso — the grammar-layer codec with the proved laws); this render is the printer face over it"]
def render (entries : Array Entry) : String :=
  Gates.Baselines.printElab entries

/-! ## The delta discipline (the pure teeth) -/

/-- One module's verdict against the baseline (the report's word). -/
inductive BaselineVerdict where
  | ok | regressed | newEntry
  deriving Repr, Inhabited, DecidableEq, BEq

/-- The verdict of one module's measured time against its baseline row,
    REFERENCE-CALIBRATED: the committed signal is the ratio
    millis/refMillis, the fresh signal the ratio measured/refNow; the
    ratio is what machine speed + sustained load divide out of. The
    comparison stays in Nat (cross-multiplied).
    - no baseline row (base = none): `.newEntry` (a gated root enters
      the baseline deliberately — the finding)
    - over 2× the committed ratio (cross-multiplied) AND over the
      jitter floor: `.regressed` (THE §7 finding)
    - else `.ok` (the normal drift passes — ±jitter is noise) -/
def verdict (base : Option Nat) (refBase measured refNow floor : Nat) :
    BaselineVerdict :=
  match base with
  | none => .newEntry
  | some b =>
    -- ratio test, cross-multiplied:
    --   measured/refNow > 2 * b/refBase  ⟺  measured * refBase > 2 * b * refNow
    if measured * refBase > 2 * b * refNow && measured > floor then .regressed
    else .ok

/-! ## The measurement face -/

/-- The gated roots, flattened to (lib, module, source path) — the
    single source is Gates.Packages' table; the path is the lakefile
    root convention (srcDir + the dotted name's slashes + `.lean`). -/
def gatedRoots : Array (String × String × String) :=
  Gates.gatedPackages.flatMap fun pkg =>
    pkg.roots.map fun root =>
      (pkg.dir, root.toString,
       pkg.srcDir ++ "/" ++ root.toString.replace "." "/" ++ ".lean")

/-- One measured module. -/
structure Measured where
  lib : String
  mod : String
  path : String
  millis : Nat
  failed : Bool
  deriving Repr, Inhabited

/-- Wall-time ONE module's re-elaboration (`lake env lean <source>`).
    The imports ride the committed oleans, so the time is the module's
    OWN elaboration; no olean is written (the build cache untouched).
    Output is captured (a module's own linter chatter must not drown
    the report); a nonzero exit marks the row failed. -/
def timeModule (path : String) : IO Measured := do
  let t0 ← IO.monoMsNow
  let out ← IO.Process.output
    { cmd := "lake", args := #["env", "lean", path] }
  let ms := (← IO.monoMsNow) - t0
  return { lib := "", mod := "", path := path
         , millis := ms, failed := out.exitCode != 0 }

/-! ## The gate -/

/-- `gates elab-watch` — the §7 watch. Exit 1 on: a REGRESSED module
    (over 2× its committed reference ratio, over the jitter floor), a
    NEW gated root absent from the baseline, a STALE baseline row, a
    missing root source, a failed replay, or a malformed baseline row.
    `--write` re-baselines (loud: non-empty diff requires
    --accept-drift). -/
unsafe def run (write acceptDrift : Bool) : IO UInt32 := do
  let floor ← Gates.envNat "GATES_ELAB_FLOOR_MS" 1500
  -- the baseline's committed rows (absent file = the empty baseline;
  -- every root then reads NEW — the bootstrap prompts the write face)
  let (committed, malformed) ←
    if ← baselinePath.pathExists then
      pure (parse (← IO.FS.readFile baselinePath))
    else pure (#[], #[])
  -- the fresh sweep (sequential: a timing gate measures on a quiet box)
  let mut measured : Array Measured := #[]
  for (lib, mod, path) in gatedRoots do
    if ← (path : System.FilePath).pathExists then
      let m ← timeModule path
      measured := measured.push { m with lib := lib, mod := mod }
    else
      measured := measured.push
        { lib := lib, mod := mod, path := path, millis := 0, failed := true }
  -- the reference's fresh time (the calibration denominator; its
  -- absence — the reference is itself a gated root, so a missing
  -- reference is a FAILED sweep row — is a finding, verdicts skipped)
  let refNow : Option Nat :=
    (measured.find? fun m => m.mod == referenceMod).map fun m => m.millis
  -- the findings
  let mut findings : Array String := #[]
  for malformedLine in malformed do
    findings := findings.push
      s!"MALFORMED baseline row (hand-edited? the file is GENERATED): {malformedLine}"
  for e in committed do
    if e.refMillis == 0 then
      findings := findings.push
        (s!"ZERO-REFERENCE baseline row ({e.mod}): the ratio's denominator is " ++
          "zero — the committed signal is meaningless (hand-edited?)")
  match refNow with
  | none =>
      findings := findings.push s!"REFERENCE {referenceMod} unavailable — \
        the sweep's calibration denominator is missing; no ratio verdicts"
  | some refMs =>
    let refBase : Option Nat :=
      (committed.find? fun e => e.mod == referenceMod).map fun e => e.refMillis
    for m in measured do
      if m.failed then
        findings := findings.push
          (s!"{m.mod}: FAILED replay (`lake env lean {m.path}` exited nonzero" ++
            (if m.millis == 0 then " — source missing)" else ")"))
        continue
      match committed.find? fun e => e.mod == m.mod with
      | some b =>
        match refBase with
        | some rb =>
          match verdict (some b.millis) rb m.millis refMs floor with
          | .regressed =>
              findings := findings.push s!"{m.mod}: REGRESSED — ratio \
                {m.millis}/{refMs} over 2× the committed {b.millis}/{rb} \
                (jitter floor {floor}ms)"
          | _ => pure ()
        | none => pure ()  -- covered by the reference-unavailable finding
      | none =>
          findings := findings.push s!"{m.mod}: NEW — no baseline row \
            (a gated root enters the baseline deliberately: \
            `lake exe gates elab-watch --write` and commit)"
    for e in committed do
      unless measured.any fun m => m.mod == e.mod do
        findings := findings.push s!"{e.mod}: STALE baseline row — the module \
          is no longer a gated root (the ratchet is fail-closed: \
          `lake exe gates elab-watch --write --accept-drift` and commit)"
  -- the report (every module's row — the log the doctrine asks for;
  -- the RATIO is the signal, the reference named beside it)
  match refNow with
  | some refMs =>
      IO.println s!"elab-watch: reference {referenceMod}: {refMs}ms \
        (the ratio module/reference is the signal)"
  | none => pure ()
  IO.println "elab-watch: per-module elaboration (module · committed · measured):"
  for m in measured do
    let base := match committed.find? fun e => e.mod == m.mod with
      | some e => s!"{e.millis}/{e.refMillis}"
      | none => "—"
    IO.println s!"  {m.mod}: {base} · {m.millis}ms"
  -- the write face (the loud re-baseline discipline — Driver.reportGate's
  -- shape; the no-write face is this gate's own findings printer)
  let fresh := render (measured.map fun m =>
    { mod := m.mod, millis := m.millis
    , refMillis := refNow.getD 0 : Entry })
  unless findings.isEmpty do
    IO.eprintln s!"elab-watch: {findings.size} finding(s) — the gate + \
      the divergence are named below (never a bare failure)"
  Driver.reportGate "elab-watch" baselinePath fresh write acceptDrift
    (!findings.isEmpty) "elab-watch: clean (all deltas within budget)" do
    for f in findings do
      IO.eprintln s!"elab-watch: {f}"
    return !findings.isEmpty

end Gates.ElabWatch
