/-
Gates.ElabWatch — the elaboration-time regression watch
(`gates elab-watch [--write] [--accept-drift]`; notes/v3/09-gates-ops.md §7:
"type-driven gating shifts work into elaboration; the gates exe logs
per-module elaboration time and flags DELTAS against the committed
baseline — absolute budgets are noise; regressions are signal").

The measurement face, honestly: for every gated root (Gates.Packages'
table — the single source, never a parallel copy) the gate spawns
`lake env lean <source>` and wall-times it. The imports resolve to
committed oleans, so the invocation re-elaborates ONLY the module's own
declarations — the per-module elaboration cost the doctrine names —
without writing an olean (the build cache is untouched). One invocation
per module, SEQUENTIAL by default: parallelism loads the machine and
inflates the timings — a timing gate that runs its measurements on a
loaded box measures the load, not the module (GATES_ELAB_JOBS raises
the concurrency at the operator's own risk).

The delta discipline (§7): a module whose measured time exceeds 2× its
committed baseline REGRESSES — the finding. Small drifts (±20% run to
run) are noise and pass. A jitter floor (GATES_ELAB_FLOOR_MS, default
1500) keeps the sub-second modules honest: on ANY shared box (CI
runners included) a 300ms module swings past 2× under ordinary load —
its ratio is noise, not signal; the watch's signal lives in the
multi-second roots, where 2× is real elaboration work. This is a jitter
guard, NOT an absolute budget (the doctrine: absolute budgets are
noise); a module under the floor cannot flag however large its RATIO.
New modules (a gated root with no baseline row) and stale rows
(a baseline module no longer gated) are findings too — the ratchet is
fail-closed both ways (the native-policy precedent): the baseline grows
only deliberately, and never outlives its module.

The baseline (`notes/elab-baseline.tsv`, GENERATED by the write face):
one `module<TAB>millis` row per gated root, gatedPackages order, `#`
comment header. A MALFORMED row (not exactly two tab fields, non-numeric
millis) is a finding — a hand-edited baseline is a discipline violation
(the code-registry replay precedent). The write face rides the loud
re-baseline discipline (Driver.reportGate's shape): `--write` refuses a
non-empty diff without `--accept-drift` — a re-baseline must not
pre-authorize future taint; a regression accepted through
`--write --accept-drift` is a deliberate, commit-visible act.

The CI face: `just gates` runs this row; the workflow runs `just ci`
verbatim (the local/CI parity discipline, notes/v3/13-interfaces.md);
a red run names the gate + the divergence (module, baseline, budget,
measured) — never a bare failure.

Cost note (the degradation rule, 09 §7 / 01's ladder): the sweep is
one sequential `lean` invocation per gated root — the same per-module
replay cost class as the kernel-check, paid once per battery run.

The five questions (notes/v3/01-core.md):
- root: none — a host-side timing gate over the gated set (no new
root; the gated set IS Gates.Packages' Universe row).
- carrier grade: none — measured wall times, not a crossing.
- spine reading: the check face of the elaboration stage (the
committed baseline vs the fresh replay, the report-gate discipline).
- ladder rung: n/a (this IS the §7 watch).
- gate row: the elab-watch row itself (`gates elab-watch`, the
registry's newest entry).
-/
import Lean
import Kit.Correspondence
import Gates.Packages
import Gates.Common

namespace Gates.ElabWatch

/-! ## The baseline data (the TSV faces) -/

/-- One baseline row: the gated root's module name + its committed
    elaboration milliseconds + the reference root's milliseconds in the
    SAME sweep (the ratio is the signal; see the module header). (`mod`,
    not `module` — the latter is a parser keyword.) -/
structure Entry where
  mod : String
  millis : Nat
  refMillis : Nat
  deriving Repr, Inhabited

/-- The reference root: the stable core-only module every sweep re-times
    alongside the gated roots — machine speed + sustained load divide
    out of the module/reference ratio. -/
def referenceMod : String := "ZSet"

/-- The committed baseline this gate diffs against. -/
def baselinePath : System.FilePath := "notes/elab-baseline.tsv"

/-- Is a (trimmed) baseline line a DATA row (neither empty nor a `#`
    comment)? -/
def isDataRow (line : String) : Bool :=
  line != "" && !line.startsWith "#"

/-- One data row's raw face: the three fields' canonical values (the
    module spelling VERBATIM, the two millis values). The byte face of
    this raw triple is `renderRow`'s spelling; the codec below declares
    the correspondence (the codec discipline's registration of the
    renderRow/parseRow pair — Kit.CodeRegistry's `registryCodec` is the
    template: the climb rides the Option grade, never failing on the
    raw face it owns). -/
abbrev RowRaw := String × Nat × Nat

/-- The row's spell (the codec's encode face): the field order IS the
    format's content. -/
def rowSpell : Entry → RowRaw := fun e => (e.mod, e.millis, e.refMillis)

/-- The row's climb (the codec's decode face). Total on the raw face:
    the canonical format carries every raw triple — `parseRow`'s
    zero-reference refusal is the READER's semantic face (a zero
    reference makes the ratio meaningless — the finding), not the
    format's. -/
def rowClimb : RowRaw → Option Entry :=
  fun (m, ms, ref) => some { mod := m, millis := ms, refMillis := ref }

/-- THE row codec: the correspondence the TSV's data row declares
    (the codec discipline — the renderRow/parseRow pair's registration;
    the law is the registry template's climb shape). -/
def rowCodec : Kit.Codec RowRaw Entry where
  encode := rowSpell
  decode := rowClimb
  policy := fun _ => True
  decode_encode := fun _ => rfl
  decode_some_policy := fun _ _ _ => trivial

/-- The rows' climb: the fold (the registry's `rowsDecode` shape). -/
def rowsClimb : List RowRaw → Option (List Entry)
  | [] => some []
  | r :: rest => (rowsClimb rest).bind fun es => (rowClimb r).map (· :: es)

/-- The climb inverts the spell, one row at a time (the law's per-row
    face — `rowCodec.decode_encode`). -/
theorem rowsClimb_map_rowSpell : ∀ (es : List Entry),
    rowsClimb (es.map rowSpell) = some es
  | [] => rfl
  | e :: rest => by
      show (rowsClimb (rest.map rowSpell)).bind
          (fun es => (rowClimb (rowSpell e)).map (· :: es))
        = some (e :: rest)
      rw [rowsClimb_map_rowSpell rest]
      rfl

/-- THE format codec: the row list ↔ the entry array — the TSV's data
    face (the header is `render`'s constant, the newline discipline
    `render`'s; the DATA is this correspondence, the codec discipline's
    registration for the render/parse pair). -/
def tsvCodec : Kit.Codec (List RowRaw) (Array Entry) where
  encode := fun es => es.toList.map rowSpell
  decode := fun raw => (rowsClimb raw).map (fun es => es.toArray)
  policy := fun _ => True
  decode_encode := fun es => by
      show (rowsClimb (es.toList.map rowSpell)).map _ = some es
      rw [rowsClimb_map_rowSpell]
      rfl
  decode_some_policy := fun _ _ _ => trivial

/-! ### THE GRADUATION (15-patterns #11 at the codec grade) -/

/-- The row decode's TOTALITY as data: `rowClimb` never refuses — the
    canonical format carries every raw triple (the doc note above). -/
def rowClimbTotal : (r : RowRaw) → {e : Entry // rowClimb r = some e}
  | (m, ms, ref) => ⟨{ mod := m, millis := ms, refMillis := ref }, rfl⟩

/-- The row decode's EXACTNESS law (~5 LOC, the audit's face): a
    successful climb determines the spell — the climb inverts the
    spell on the accepted face. -/
theorem rowSpell_of_rowClimb (r : RowRaw) (e : Entry)
    (h : rowClimb r = some e) : rowSpell e = r := by
  obtain ⟨m, ms, ref⟩ := r
  have h1 : rowClimb (m, ms, ref)
      = some { mod := m, millis := ms, refMillis := ref } := rfl
  rw [h1, Option.some.injEq] at h
  subst h
  rfl

/-- THE GRADUATION'S VALUE (the row): the raw triple ≅ the entry — a
    TRUE `Kit.Iso` from the total climb + the exactness law. -/
def rowIso : Kit.Iso RowRaw Entry :=
  rowCodec.toIsoOfExact rowClimbTotal rowSpell_of_rowClimb

/-- The rows' climb totality as data (the fold's recursion). -/
def rowsClimbTotal : ∀ (raw : List RowRaw),
    {es : List Entry // rowsClimb raw = some es}
  | [] => ⟨[], rfl⟩
  | r :: rest =>
      let t := rowsClimbTotal rest
      have hr : rowClimb r = some (rowClimbTotal r).1 := (rowClimbTotal r).2
      ⟨(rowClimbTotal r).1 :: t.1, by
        simp only [rowsClimb, t.2, hr, Option.bind_some, Option.map_some]⟩

/-- The rows' climb EXACTNESS: a successful climb determines the
    spell list — the per-row law rides the fold. -/
theorem rowsClimb_exact : ∀ (raw : List RowRaw) (es : List Entry),
    rowsClimb raw = some es → es.map rowSpell = raw := by
  intro raw
  induction raw with
  | nil =>
      intro es h
      simp only [rowsClimb, Option.some.injEq] at h
      subst h
      rfl
  | cons r rest ih =>
      intro es h
      simp only [rowsClimb, Option.bind_eq_some_iff,
        Option.map_eq_some_iff] at h
      obtain ⟨es', h1, e, h2, he⟩ := h
      rw [← he, List.map_cons, ih es' h1, rowSpell_of_rowClimb r e h2]

/-- THE GRADUATION'S VALUE (the format): the raw row list ≅ the entry
    array — a TRUE `Kit.Iso` from the total climb + the exactness law
    (the array face collapses via `Array.toList_toArray`). -/
def tsvIso : Kit.Iso (List RowRaw) (Array Entry) :=
  tsvCodec.toIsoOfExact
    (fun raw =>
      let ⟨esl, hcl⟩ : {es : List Entry // rowsClimb raw = some es} :=
        rowsClimbTotal raw
      ⟨esl.toArray, by
        show (rowsClimb raw).map (fun l => l.toArray) = some esl.toArray
        rw [hcl, Option.map_some]⟩)
    (fun raw es h => by
      have h1 : (rowsClimb raw).map (fun l => l.toArray) = some es := h
      obtain ⟨esl, hcl, hae⟩ := Option.map_eq_some_iff.mp h1
      rw [← hae, Array.toArray_toList]
      exact rowsClimb_exact raw esl hcl)

/-- Parse one DATA row: `mod<TAB>millis<TAB>refMillis`; none when
    malformed (the malformed row is a FINDING, never silently dropped —
    the hand-edit detection face; the code-registry replay precedent).
    THE READER'S FACES, deliberate (the codec is the canonical
    correspondence, this is the lenient reader): the fields are trimmed
    (a hand-edited row's stray spaces still read), a leading-zero
    spelling still reads, and a zero reference is refused (the
    semantic finding, not a format refusal). -/
def parseRow (line : String) : Option Entry :=
  match line.splitOn "\t" with
  | [mod, ms, ref] =>
      match ms.trimAscii.toString.toNat?, ref.trimAscii.toString.toNat? with
      | some n, some r =>
          if r == 0 then none  -- a zero-reference row is malformed
          else some { mod := mod.trimAscii.toString, millis := n, refMillis := r }
      | _, _ => none
  | _ => none

/-- Parse the TSV: the rows + the malformed DATA lines. -/
def parse (text : String) : Array Entry × Array String :=
  let lines := (text.splitOn "\n").map (·.trimAscii.toString)
  let rows : Array Entry :=
    (lines.filterMap (fun l => if isDataRow l then parseRow l else none)).toArray
  let bad : Array String :=
    (lines.filter (fun l => isDataRow l && (parseRow l).isNone)).toArray
  (rows, bad)

/-- The fresh render (the write face's bytes): the constant header, then
    each entry's canonical row spelling (`rowCodec`'s encode face's
    bytes), LF-joined, the final newline the file's. -/
def renderRow (e : Entry) : String := s!"{e.mod}\t{e.millis}\t{e.refMillis}"

def render (entries : Array Entry) : String :=
  let header :=
    "# The elaboration-time baseline (notes/v3/09-gates-ops.md §7).\n" ++
    "# GENERATED by `lake exe gates elab-watch --write` — do not hand-edit.\n" ++
    "# mod<TAB>millis<TAB>refMillis — the committed signal is the RATIO; a module\n" ++
    "# over 2× its committed ratio (and over the GATES_ELAB_FLOOR_MS\n" ++
    "# jitter floor) fails `gates elab-watch`.\n"
  header ++ String.intercalate "\n"
    (entries.toList.map renderRow) ++ "\n"

/-! ## The delta discipline (the pure teeth) -/

/-- One module's verdict against the baseline (the report's word). -/
inductive BaselineVerdict where
  | ok | regressed | newEntry
  deriving Repr, Inhabited, DecidableEq, BEq

/-- The verdict of one module's measured time against its baseline row,
    REFERENCE-CALIBRATED: the committed signal is the ratio
    millis/refMillis, the fresh signal the ratio measured/refNow; the
    ratio is what machine speed + sustained load divide out of. The
    comparison stays in Nat (cross-multiplied).
    - no baseline row (base = none): `.newEntry` (a gated root enters
      the baseline deliberately — the finding)
    - over 2× the committed ratio (cross-multiplied) AND over the
      jitter floor: `.regressed` (THE §7 finding)
    - else `.ok` (the normal drift passes — ±jitter is noise) -/
def verdict (base : Option Nat) (refBase measured refNow floor : Nat) :
    BaselineVerdict :=
  match base with
  | none => .newEntry
  | some b =>
    -- ratio test, cross-multiplied:
    --   measured/refNow > 2 * b/refBase  ⟺  measured * refBase > 2 * b * refNow
    if measured * refBase > 2 * b * refNow && measured > floor then .regressed
    else .ok

/-! ## The measurement face -/

/-- The gated roots, flattened to (lib, module, source path) — the
    single source is Gates.Packages' table; the path is the lakefile
    root convention (srcDir + the dotted name's slashes + `.lean`). -/
def gatedRoots : Array (String × String × String) :=
  Gates.gatedPackages.flatMap fun pkg =>
    pkg.roots.map fun root =>
      (pkg.dir, root.toString,
       pkg.srcDir ++ "/" ++ root.toString.replace "." "/" ++ ".lean")

/-- One measured module. -/
structure Measured where
  lib : String
  mod : String
  path : String
  millis : Nat
  failed : Bool
  deriving Repr, Inhabited

/-- Wall-time ONE module's re-elaboration (`lake env lean <source>`).
    The imports ride the committed oleans, so the time is the module's
    OWN elaboration; no olean is written (the build cache untouched).
    Output is captured (a module's own linter chatter must not drown
    the report); a nonzero exit marks the row failed. -/
def timeModule (path : String) : IO Measured := do
  let t0 ← IO.monoMsNow
  let out ← IO.Process.output
    { cmd := "lake", args := #["env", "lean", path] }
  let ms := (← IO.monoMsNow) - t0
  return { lib := "", mod := "", path := path
         , millis := ms, failed := out.exitCode != 0 }

/-! ## The gate -/

/-- `gates elab-watch` — the §7 watch. Exit 1 on: a REGRESSED module
    (over 2× its committed reference ratio, over the jitter floor), a
    NEW gated root absent from the baseline, a STALE baseline row, a
    missing root source, a failed replay, or a malformed baseline row.
    `--write` re-baselines (loud: non-empty diff requires
    --accept-drift). -/
unsafe def run (write acceptDrift : Bool) : IO UInt32 := do
  let floor ← Gates.envNat "GATES_ELAB_FLOOR_MS" 1500
  -- the baseline's committed rows (absent file = the empty baseline;
  -- every root then reads NEW — the bootstrap prompts the write face)
  let (committed, malformed) ←
    if ← baselinePath.pathExists then
      pure (parse (← IO.FS.readFile baselinePath))
    else pure (#[], #[])
  -- the fresh sweep (sequential: a timing gate measures on a quiet box)
  let mut measured : Array Measured := #[]
  for (lib, mod, path) in gatedRoots do
    if ← (path : System.FilePath).pathExists then
      let m ← timeModule path
      measured := measured.push { m with lib := lib, mod := mod }
    else
      measured := measured.push
        { lib := lib, mod := mod, path := path, millis := 0, failed := true }
  -- the reference's fresh time (the calibration denominator; its
  -- absence — the reference is itself a gated root, so a missing
  -- reference is a FAILED sweep row — is a finding, verdicts skipped)
  let refNow : Option Nat :=
    (measured.find? fun m => m.mod == referenceMod).map fun m => m.millis
  -- the findings
  let mut findings : Array String := #[]
  for malformedLine in malformed do
    findings := findings.push
      s!"MALFORMED baseline row (hand-edited? the file is GENERATED): {malformedLine}"
  match refNow with
  | none =>
      findings := findings.push s!"REFERENCE {referenceMod} unavailable — \
        the sweep's calibration denominator is missing; no ratio verdicts"
  | some refMs =>
    let refBase : Option Nat :=
      (committed.find? fun e => e.mod == referenceMod).map fun e => e.refMillis
    for m in measured do
      if m.failed then
        findings := findings.push
          (s!"{m.mod}: FAILED replay (`lake env lean {m.path}` exited nonzero" ++
            (if m.millis == 0 then " — source missing)" else ")"))
        continue
      match committed.find? fun e => e.mod == m.mod with
      | some b =>
        match refBase with
        | some rb =>
          match verdict (some b.millis) rb m.millis refMs floor with
          | .regressed =>
              findings := findings.push s!"{m.mod}: REGRESSED — ratio \
                {m.millis}/{refMs} over 2× the committed {b.millis}/{rb} \
                (jitter floor {floor}ms)"
          | _ => pure ()
        | none => pure ()  -- covered by the reference-unavailable finding
      | none =>
          findings := findings.push s!"{m.mod}: NEW — no baseline row \
            (a gated root enters the baseline deliberately: \
            `lake exe gates elab-watch --write` and commit)"
    for e in committed do
      unless measured.any fun m => m.mod == e.mod do
        findings := findings.push s!"{e.mod}: STALE baseline row — the module \
          is no longer a gated root (the ratchet is fail-closed: \
          `lake exe gates elab-watch --write --accept-drift` and commit)"
  -- the report (every module's row — the log the doctrine asks for;
  -- the RATIO is the signal, the reference named beside it)
  match refNow with
  | some refMs =>
      IO.println s!"elab-watch: reference {referenceMod}: {refMs}ms \
        (the ratio module/reference is the signal)"
  | none => pure ()
  IO.println "elab-watch: per-module elaboration (module · committed · measured):"
  for m in measured do
    let base := match committed.find? fun e => e.mod == m.mod with
      | some e => s!"{e.millis}/{e.refMillis}"
      | none => "—"
    IO.println s!"  {m.mod}: {base} · {m.millis}ms"
  -- the write face (the loud re-baseline discipline — Driver.reportGate's
  -- shape; the no-write face is this gate's own findings printer)
  let fresh := render (measured.map fun m =>
    { mod := m.mod, millis := m.millis
    , refMillis := refNow.getD 0 : Entry })
  unless findings.isEmpty do
    IO.eprintln s!"elab-watch: {findings.size} finding(s) — the gate + \
      the divergence are named below (never a bare failure)"
  Driver.reportGate "elab-watch" baselinePath fresh write acceptDrift
    (!findings.isEmpty) "elab-watch: clean (all deltas within budget)" do
    for f in findings do
      IO.eprintln s!"elab-watch: {f}"
    return !findings.isEmpty

end Gates.ElabWatch
