import Lean
import Lean.Compiler.LCNF
import CodegenCore
import WasmBackend
import WasmBackend.Check

/-!
# WasmBackend.GenMain — the LCNF → WAT artifact writer

The `leanir` pattern: import the target module's oleans, re-run the LCNF
pipeline (the impure-phase LCNF — Perceus RC included — is NOT persisted
in oleans), read the final `Decl`s from `impureExt`, emit WAT.

Pipeline: this exe writes `target/demo.wat` (+ the differential oracle
program); the justfile drives `wasm-tools parse -g` → binary, the
component wrap, and the differential smoke.
-/

open Lean

/-- The functions to compile — DemoFn (the compiler-line demo stage). -/
def targetDecls : Array Name := #[`double, `isBig, `adder, `area, `doubleArea, `pick, `applyAll, `runPaps]

/-- Run the LCNF pipeline + emit the module, in CoreM. -/
def emitModuleWasm : CoreM String := do
  Lean.Compiler.LCNF.main targetDecls {}
  let mut decls : List (Lean.Compiler.LCNF.Decl .impure) := []
  for n in targetDecls do
    if let some d ← Lean.Compiler.LCNF.getLocalImpureDecl? n then
      decls := d :: decls
  decls := decls.reverse
  -- Closure constants + lambdas: `_closed`/`_lam` decls (holding the
  -- paps) are generated IN-PROCESS by the re-run — never in the imported
  -- env. Include every impure decl UNDER a target's namespace.
  let mut names := targetDecls
  let all ← Lean.Compiler.LCNF.getLocalImpureDecls
  let internal := all.filter fun n =>
    let s := n.toString
    s.contains "." && targetDecls.any fun t => s.startsWith (t.toString ++ ".")
  names := names ++ internal
  let mut decls2 : List (Lean.Compiler.LCNF.Decl .impure) := []
  for n in names do
    if let some d ← Lean.Compiler.LCNF.getLocalImpureDecl? n then
      decls2 := d :: decls2
  decls2 := decls2.reverse
  -- Debug dump: the final LCNF per decl (the compiler line's x-ray).
  for d in decls2 do
    let fmt ← Lean.Compiler.LCNF.ppDecl' d .impure
    IO.eprintln s!"--- {d.name}\n{fmt}"
  let exportTargets := targetDecls.toList.map fun n =>
    (CodegenCore.Emit.kebab n.getString!, n)
  let res : Except String (String × WasmBackend.S) :=
    StateT.run (WasmBackend.emitModule decls2 exportTargets) {}
  match res with
  | .ok (wat, _) =>
    -- splice the hand-written runtime (pooled allocator + Perceus RC)
    -- into the module body: single module, no imports.
    let rt ← IO.FS.readFile "runtime.wat"
    -- WAT line comments are `;;` (doubleSlash is `//` — Rust); no
    -- CommentStyle for WAT exists yet, so the header is spelled out.
    let hdr := ";; GENERATED by wasm-backend — DO NOT EDIT\n;; spec source: DemoFn.lean\n;; regenerate via `just wasm-compile`; drift fails CI (byte-tie)\n"
    pure (hdr ++ (wat.replace "(module\n" ("(module\n" ++ rt ++ "\n")))
  | .error e => throwError e

/-- The DIFFERENTIAL ORACLE program: calls the real Lean functions over
generated inputs and prints the manifest as JSON. The Lean semantics is
the authority; the Rust diff test replays this against the emitted wasm.
(Plain string concat — braces are literal, no s! brace escapes.) -/
def oracleSrc : String := "
import DemoFn

def u64s : List UInt64 :=
  ((List.range 20).map (fun i => (i * 7 + 3) % 100)).map (fun n => n.toUInt64)

def rows : List (String × List String) :=
  (u64s.map fun a => (\"double\", [toString a]))
  ++ (u64s.map fun a => (\"is-big\", [toString a]))
  ++ (u64s.map fun a => (\"adder\", [toString a, toString (a + 3)]))
  ++ (u64s.map fun a => (\"double-area\", [toString a]))
  ++ (u64s.map fun a => (\"run-paps\", [toString a]))
  ++ (u64s.map fun a => (\"pick\", [if a % 2 == 0 then \"1\" else \"0\", toString a, toString (a + 1)]))

def resultOf (fn : String) (args : List String) : String :=
  match fn, args with
  | \"double\", [a] => toString (double a.toNat!.toUInt64)
  | \"is-big\", [a] => if isBig a.toNat!.toUInt64 then \"1\" else \"0\"
  | \"adder\", [a, b] => toString (adder a.toNat!.toUInt64 b.toNat!.toUInt64)
  | \"double-area\", [a] => toString (doubleArea a.toNat!.toUInt64)
  | \"run-paps\", [a] => toString (runPaps a.toNat!.toUInt64)
  | \"pick\", [b, a, x] => toString (pick (b == \"1\") a.toNat!.toUInt64 x.toNat!.toUInt64)
  | _, _ => \"?\"

def jsonRow (fn : String) (args : List String) (expected : String) : String :=
  \"{\" ++ \"\\\"fn\\\": \\\"\" ++ fn ++ \"\\\", \\\"args\\\": [\" ++
    String.intercalate \",\" (args.map fun a => \"\\\"\" ++ a ++ \"\\\"\") ++
    \"], \\\"expected\\\": \\\"\" ++ expected ++ \"\\\"}\"

def main : IO Unit := do
  let mut out := \"[\"
  let mut first := true
  for (fn, args) in rows do
    let expected := resultOf fn args
    if !first then out := out ++ \",\"
    first := false
    out := out ++ jsonRow fn args expected
  out := out ++ \"]\"
  IO.println out
"

unsafe def main : IO Unit := do
  Lean.initSearchPath (← Lean.findSysroot)
  Lean.enableInitializersExecution
  let env ← Lean.importModules #[`Demo, `DemoFn] (opts := {}) (loadExts := true)
  let ctx : Core.Context := { fileName := "<wasm-gen>", fileMap := default }
  let state : Core.State := { env := env }
  let (wat, _) ← emitModuleWasm.toIO ctx state
  IO.FS.createDirAll "target"
  IO.FS.writeFile "target/demo.wat" wat
  IO.FS.writeFile "target/oracle.lean" oracleSrc
  IO.println "wrote target/demo.wat + target/oracle.lean"
