// GENERATED by schema-lang — DO NOT EDIT
// spec source: Demo.lean
// regenerate via `just gen`; drift fails CI (byte-tie)
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum UserChange {
  Insert(User),
  Update(User),
  Remove(u64),
}
// ChangeSpec: the Dbsp.Change shape (patch + valid) for UserChange.
impl dbsp::Change for UserChange {
  fn patch(&self, base: &User) -> User {
    match self { Self::Insert(u) | Self::Update(u) => u.clone(), Self::Remove(_) => base.clone() }
  }
  fn valid(&self) -> bool {
    true
  }
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum OrderItemChange {
  Insert(OrderItem),
  Update(OrderItem),
  Remove(u64),
}
// ChangeSpec: the Dbsp.Change shape (patch + valid) for OrderItemChange.
impl dbsp::Change for OrderItemChange {
  fn patch(&self, base: &OrderItem) -> OrderItem {
    match self { Self::Insert(u) | Self::Update(u) => u.clone(), Self::Remove(_) => base.clone() }
  }
  fn valid(&self) -> bool {
    true
  }
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum OrderChange {
  Insert(Order),
  Update(Order),
  Remove(u64),
}
// ChangeSpec: the Dbsp.Change shape (patch + valid) for OrderChange.
impl dbsp::Change for OrderChange {
  fn patch(&self, base: &Order) -> Order {
    match self { Self::Insert(u) | Self::Update(u) => u.clone(), Self::Remove(_) => base.clone() }
  }
  fn valid(&self) -> bool {
    true
  }
}
