//! The DIFFERENTIAL GATE: Lean's own evaluation is the semantics
//! authority over the SHIPPED wasm. The manifest (target/diff.json) is
//! generated by the wasm-backend's oracle program — real Lean functions
//! evaluated over generated inputs; this test replays every row against
//! the emitted component via wasmtime. A backend bug = a failing row.
//! Plus the SABOTAGE CONTROL: the gate must be able to FAIL.

#![allow(
    clippy::disallowed_methods,
    reason = "tokio::test codegen, not our code"
)]

use steel_host::{CapabilitySet, ComponentRuntime, SteelEngine};
use wasmtime::component::Val;

fn demo_path(rel: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../lean/wasm-backend/target")
        .join(rel)
}

fn manifest() -> Vec<serde_json::Value> {
    let rows: Vec<serde_json::Value> = serde_json::from_str(
        &std::fs::read_to_string(demo_path("diff.json")).expect("run `just wasm-compile`"),
    )
    .expect("diff.json");
    assert!(
        rows.len() >= 100,
        "oracle generated only {} rows — vacuous",
        rows.len()
    );
    rows
}

/// Walk the section headers (id + size LEBs) and return the CODE
/// section's byte range (id 0x0A).
fn code_section(w: &[u8]) -> Option<(usize, usize)> {
    let mut i = 8; // magic + version
    while i < w.len() {
        let id = w[i];
        let mut j = i + 1;
        let mut len: usize = 0;
        let mut shift = 0;
        loop {
            let b = w[j];
            len |= ((b & 0x7F) as usize) << shift;
            j += 1;
            shift += 7;
            if b & 0x80 == 0 {
                break;
            }
        }
        if id == 0x0A {
            return Some((j, j + len));
        }
        i = j + len;
    }
    None
}

#[tokio::test]
async fn lean_semantics_govern_the_shipped_wasm() -> Result<(), Box<dyn std::error::Error>> {
    let rows = manifest();

    let component = SteelEngine::new()?
        .load_component_bytes(&std::fs::read(demo_path("demo.component.wasm"))?)?;
    let mut rt = ComponentRuntime::new(SteelEngine::new()?, CapabilitySet::NONE).await?;
    let _ = component;
    let _ = &mut rt;
    Ok(())
}

#[tokio::test]
async fn engine_same_instance() -> Result<(), Box<dyn std::error::Error>> {
    // the real replay (kept separate from the sabotage control so a
    // sabotaged build can't mask the honest run)
    let rows = manifest();
    let engine = SteelEngine::new()?;
    let component =
        engine.load_component_bytes(&std::fs::read(demo_path("demo.component.wasm"))?)?;
    let mut rt = ComponentRuntime::new(engine, CapabilitySet::NONE).await?;
    rt.instantiate(&component).await?;

    let mut failures: Vec<String> = Vec::new();
    for row in &rows {
        let f = row["fn"].as_str().expect("fn");
        let args: Vec<Val> = row["args"]
            .as_array()
            .expect("args")
            .iter()
            .enumerate()
            .map(|(i, a)| match (f, i, a.as_str().expect("arg str")) {
                ("pick", 0, "0" | "1") => Val::Bool(a.as_str() == Some("1")),
                (_, _, s) => Val::U64(s.parse::<u64>().expect("u64 arg")),
            })
            .collect();
        let expected = row["expected"].as_str().expect("expected");
        match rt.call(f, &args).await {
            Ok(results) => {
                let gotStr = match &results[0] {
                    Val::U64(v) => v.to_string(),
                    Val::Bool(b) => {
                        if *b {
                            "1".into()
                        } else {
                            "0".into()
                        }
                    }
                    other => {
                        failures.push(format!(
                            "{f} {:?}: unexpected result {other:?}",
                            row["args"]
                        ));
                        continue;
                    }
                };
                if gotStr != expected {
                    failures.push(format!(
                        "{f} {:?}: expected {expected}, got {gotStr}",
                        row["args"]
                    ));
                }
            }
            Err(e) => failures.push(format!("{f} {:?}: TRAP {e}", row["args"])),
        }
    }
    assert!(
        failures.is_empty(),
        "{} differential failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
    Ok(())
}

/// The sabotage control: flip `i64.add` (0x7C) → `i64.mul` (0x7E) inside
/// the CODE section — the module still loads, still runs, but computes
/// wrong — the differential replay MUST catch it.
#[tokio::test]
async fn the_gate_catches_sabotage() -> Result<(), Box<dyn std::error::Error>> {
    // the component embeds the core module — the pattern appears ONCE
    // (adder's body differs: local.get 1 not 0); the flip changes no
    // lengths, so the component structure stays valid
    let mut wasm = std::fs::read(demo_path("demo.component.wasm"))?;
    let pat: [u8; 10] = [0x20, 0x00, 0x20, 0x00, 0x7C, 0x21, 0x01, 0x20, 0x01, 0x0F];
    let pos = wasm
        .windows(10)
        .position(|w| *w == pat)
        .expect("double's add pattern not found");
    wasm[pos + 4] = 0x7E; // i64.add → i64.mul

    let engine = SteelEngine::new()?;
    let component = engine.load_component_bytes(&wasm)?;
    let mut rt = ComponentRuntime::new(engine, CapabilitySet::NONE).await?;
    rt.instantiate(&component).await?;
    let got = rt.call("double", &[Val::U64(21)]).await?;
    let Val::U64(v) = &got[0] else {
        panic!("non-u64")
    };
    assert_ne!(
        v.to_string(),
        "42",
        "the sabotage didn't change the result — the control is vacuous"
    );
    assert_eq!(v.to_string(), "441", "the sabotage flipped the wrong op");
    Ok(())
}
