//! The DIFFERENTIAL GATE: Lean's own evaluation is the semantics
//! authority over the SHIPPED wasm. The manifest (target/diff.json) is
//! generated by the wasm-backend's oracle program — real Lean functions
//! evaluated over generated inputs; this test replays every row against
//! the emitted component via wasmtime. A backend bug = a failing row.
//! Plus the SABOTAGE CONTROL: the gate must be able to FAIL.

#![allow(
    clippy::disallowed_methods,
    reason = "tokio::test codegen, not our code"
)]

use std::pin::Pin;
use std::sync::{Arc, Mutex};
use std::task::{Context, Poll};
use steel_host::{CapabilitySet, ComponentRuntime, SteelEngine};
use steel_host::HostState;
use steel_host::bindings::GatewayUser;
use wasmtime::StoreContextMut;
use wasmtime::component::{StreamConsumer, StreamResult, Source, Val};

fn demo_path(rel: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../lean/wasm-backend/target")
        .join(rel)
}

fn manifest() -> Vec<serde_json::Value> {
    let rows: Vec<serde_json::Value> = serde_json::from_str(
        &std::fs::read_to_string(demo_path("diff.json")).expect("run `just wasm-compile`"),
    )
    .expect("diff.json");
    assert!(
        rows.len() >= 100,
        "oracle generated only {} rows — vacuous",
        rows.len()
    );
    rows
}

/// Walk the section headers (id + size LEBs) and return the CODE
/// section's byte range (id 0x0A).
fn code_section(w: &[u8]) -> Option<(usize, usize)> {
    let mut i = 8; // magic + version
    while i < w.len() {
        let id = w[i];
        let mut j = i + 1;
        let mut len: usize = 0;
        let mut shift = 0;
        loop {
            let b = w[j];
            len |= ((b & 0x7F) as usize) << shift;
            j += 1;
            shift += 7;
            if b & 0x80 == 0 {
                break;
            }
        }
        if id == 0x0A {
            return Some((j, j + len));
        }
        i = j + len;
    }
    None
}

/// The canonical serialization of a component Val — MUST match the
/// Lean oracle's `resultOf` rendering byte-for-byte (the diff compares
/// strings). Formats: u64 → decimal; bool → 1/0; string → itself;
/// option → none / some(inner); record → { k=v, ... }; list → (v,v,...).
fn ser_val(v: &Val) -> String {
    match v {
        Val::Bool(b) => {
            if *b {
                "1".into()
            } else {
                "0".into()
            }
        }
        Val::U8(n) => n.to_string(),
        Val::U16(n) => n.to_string(),
        Val::U32(n) => n.to_string(),
        Val::U64(n) => n.to_string(),
        Val::S8(n) => n.to_string(),
        Val::S16(n) => n.to_string(),
        Val::S32(n) => n.to_string(),
        Val::S64(n) => n.to_string(),
        Val::Float32(f) => f.to_string(),
        Val::Float64(f) => f.to_string(),
        Val::Char(c) => c.to_string(),
        Val::String(s) => s.clone(),
        Val::Option(None) => "none".into(),
        Val::Option(Some(inner)) => format!("some({})", ser_val(inner)),
        Val::Record(fields) => {
            let inner: Vec<String> = fields
                .iter()
                .map(|(k, v)| format!("{k}={}", ser_val(v)))
                .collect();
            format!("{{ {} }}", inner.join(", "))
        }
        Val::List(items) => {
            let inner: Vec<String> = items.iter().map(ser_val).collect();
            format!("({})", inner.join(","))
        }
        Val::Stream(_) => {
            // handled by the runner (the drain needs the store) — the
            // fallback should never fire
            "<stream>".into()
        }
        other => format!("{other:?}"),
    }
}


/// The stream-drain machinery: the guest stream's items → a shared Vec.
/// The consumer = polled by the event loop (a BACKGROUND task — a sync
/// pipe-set is never polled: the loop exits before pumping). Empty +
/// not-finished = Pending (returning Dropped there ENDS the stream and
/// the in-flight items are lost).
struct DrainCommon<T, F> {
    out: Arc<Mutex<Vec<String>>>,
    render: F,
    _ty: std::marker::PhantomData<T>,
}
impl<T, F> StreamConsumer<HostState> for DrainCommon<T, F>
where
    T: wasmtime::component::Lift + Send + Sync + 'static,
    F: Fn(&T) -> String + Send + Sync + 'static,
{
    type Item = T;
    fn poll_consume(
        mut self: Pin<&mut Self>,
        _cx: &mut Context<'_>,
        store: StoreContextMut<'_, HostState>,
        mut source: Source<'_, Self::Item>,
        finish: bool,
    ) -> Poll<wasmtime::Result<StreamResult>> {
        let mut buf: Vec<T> = Vec::with_capacity(16);
        source.read(store, &mut buf)?;
        if buf.is_empty() {
            if finish {
                return Poll::Ready(Ok(StreamResult::Dropped));
            }
            return Poll::Pending;
        }
        let render = &self.render;
        self.out
            .lock()
            .unwrap()
            .extend(buf.drain(..).map(move |t| render(&t)));
        Poll::Ready(Ok(StreamResult::Completed))
    }
}

type DrainU64 = DrainCommon<u64, fn(&u64) -> String>;
type DrainUser = DrainCommon<GatewayUser, fn(&GatewayUser) -> String>;

fn render_user(u: &GatewayUser) -> String {
    format!(
        "{{ id={}, name={}, email={}, tags=({}) }}",
        u.id,
        u.name,
        u.email,
        u.tags.join(",")
    )
}

struct DrainTaskU64 {
    reader: wasmtime::component::StreamReader<u64>,
    sink: Arc<Mutex<Vec<String>>>,
}
impl wasmtime::component::AccessorTask<HostState> for DrainTaskU64 {
    fn run(
        self,
        accessor: &wasmtime::component::Accessor<HostState>,
    ) -> impl std::future::Future<Output = wasmtime::Result<()>> + Send {
        let DrainTaskU64 { reader, sink } = self;
        async move {
            accessor.with(|access| {
                reader.pipe(
                    access,
                    DrainCommon { out: sink, render: |v: &u64| v.to_string(), _ty: Default::default() },
                )
            })
        }
    }
}

struct DrainTaskUser {
    reader: wasmtime::component::StreamReader<GatewayUser>,
    sink: Arc<Mutex<Vec<String>>>,
}
impl wasmtime::component::AccessorTask<HostState> for DrainTaskUser {
    fn run(
        self,
        accessor: &wasmtime::component::Accessor<HostState>,
    ) -> impl std::future::Future<Output = wasmtime::Result<()>> + Send {
        let DrainTaskUser { reader, sink } = self;
        async move {
            accessor.with(|access| {
                reader.pipe(
                    access,
                    DrainCommon { out: sink, render: render_user, _ty: Default::default() },
                )
            })
        }
    }
}

#[tokio::test]
async fn lean_semantics_govern_the_shipped_wasm() -> Result<(), Box<dyn std::error::Error>> {
    let rows = manifest();

    let component = SteelEngine::new()?
        .load_component_bytes(&std::fs::read(demo_path("demo.component.wasm"))?)?;
    let mut rt = ComponentRuntime::new(SteelEngine::new()?, CapabilitySet::NONE).await?;
    let _ = component;
    let _ = &mut rt;
    Ok(())
}

#[tokio::test]
async fn engine_same_instance() -> Result<(), Box<dyn std::error::Error>> {
    // the real replay (kept separate from the sabotage control so a
    // sabotaged build can't mask the honest run)
    let rows = manifest();
    let engine = SteelEngine::new()?;
    let component =
        engine.load_component_bytes(&std::fs::read(demo_path("demo.component.wasm"))?)?;
    let mut rt = ComponentRuntime::new(engine, CapabilitySet::NONE).await?;
    rt.instantiate(&component).await?;

    let mut failures: Vec<String> = Vec::new();
    // The record-ARG convention: a record-valued param's row args = the
    // FIELD VALUES FLAT (id, name, email, tags comma-joined) — the
    // manifest rows are List String, so the arg-builder constructs the
    // Val::Record from them (the canonical ABI flattens the user to
    // u64 + 3×(ptr,len); wasmtime lowers the Val tree the same way).
    fn user_record(strs: &[&str]) -> Val {
        Val::Record(vec![
            ("id".into(), Val::U64(strs[0].parse::<u64>().expect("user id"))),
            ("name".into(), Val::String(strs[1].to_string())),
            ("email".into(), Val::String(strs[2].to_string())),
            (
                "tags".into(),
                Val::List(
                    strs[3]
                        .split(',')
                        .map(|t| Val::String(t.to_string()))
                        .collect(),
                ),
            ),
        ])
    }
    // The VARIANT-ARG convention: a variant-valued param's row args =
    // [discr, payload] — the canonical-ABI flat form. The discr = the
    // WIT case order (empty-cart=0, invalid-item=1, insufficient-funds=2);
    // the payload rides the joined i64 slot (u64 raw, f64 bits — the
    // wasm-side read of the f64 case is the constant arm, see the guest
    // impl).
    fn order_error_variant(strs: &[&str]) -> Val {
        match strs[0] {
            "0" => Val::Variant("empty-cart".into(), None),
            "1" => Val::Variant(
                "invalid-item".into(),
                Some(Box::new(Val::U64(
                    strs[1].parse::<u64>().expect("invalid-item payload"),
                ))),
            ),
            _ => Val::Variant(
                "insufficient-funds".into(),
                Some(Box::new(Val::Float64(
                    strs[1].parse::<f64>().expect("insufficient-funds payload"),
                ))),
            ),
        }
    }
    for row in &rows {
        let f = row["fn"].as_str().expect("fn");
        let strs: Vec<&str> = row["args"]
            .as_array()
            .expect("args")
            .iter()
            .map(|a| a.as_str().expect("arg str"))
            .collect();
        let args: Vec<Val> = if f == "user-valid" || f == "user-complete" {
            vec![user_record(&strs)]
        } else if f == "order-error-valid" {
            vec![order_error_variant(&strs)]
        } else {
            strs.iter()
                .enumerate()
                .map(|(i, a)| match (f, i, *a) {
                    ("pick", 0, "0" | "1") => Val::Bool(*a == "1"),
                    (_, _, s) => Val::U64(s.parse::<u64>().expect("u64 arg")),
                })
                .collect()
        };
        let expected = row["expected"].as_str().expect("expected");
        let gotStr = if f == "watch-counts" || f == "watch-users" {
            // the STREAM rows: the call + the drain in ONE event loop —
            // the consumer must be a background task while the loop
            // pumps the guest's pending write (a post-call drain never
            // gets polled — the loop already exited).
            let out = Arc::new(Mutex::new(Vec::new()));
            let instance = rt.instance().expect("instance").clone();
            let is_counts = f == "watch-counts";
            let fname = f.to_string();
            let sink = out.clone();
            rt.store_mut()
                .run_concurrent(async move |accessor| {
                    let f = accessor.with(|access| {
                        instance.get_func(access, &fname).expect("export")
                    });
                    let mut results = [if is_counts { Val::U64(0) } else { Val::List(vec![]) }];
                    f.call_concurrent(accessor, &args, &mut results).await?;
                    let any = match results[0].clone() {
                        Val::Stream(a) => a,
                        other => panic!("{fname}: not a stream: {other:?}"),
                    };
                    if is_counts {
                        let reader = any.try_into_stream_reader::<u64>()?;
                        accessor
                            .spawn(DrainTaskU64 { reader, sink })?
                            .await;
                    } else {
                        let reader = any.try_into_stream_reader::<GatewayUser>()?;
                        accessor
                            .spawn(DrainTaskUser { reader, sink })?
                            .await;
                    }
                    Ok::<(), wasmtime::Error>(())
                })
                .await??;
            let items = out.lock().unwrap();
            format!(
                "({})",
                items.iter().map(|v| v.to_string()).collect::<Vec<_>>().join(",")
            )
        } else {
            match rt.call(f, &args).await {
                Ok(results) => match results.into_iter().next() {
                    Some(other) => ser_val(&other),
                    None => "?".into(),
                },
                Err(e) => {
                    failures.push(format!("{f} {:?}: TRAP {e}", row["args"]));
                    continue;
                }
            }
        };
        if gotStr != expected {
            failures.push(format!(
                "{f} {:?}: expected {expected}, got {gotStr}",
                row["args"]
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} differential failures:\n{}",
        failures.len(),
        failures.join("\n")
    );
    Ok(())
}

/// The sabotage control: flip `i64.add` (0x7C) → `i64.mul` (0x7E) inside
/// the CODE section — the module still loads, still runs, but computes
/// wrong — the differential replay MUST catch it.
#[tokio::test]
async fn the_gate_catches_sabotage() -> Result<(), Box<dyn std::error::Error>> {
    // the component embeds the core module — the pattern appears ONCE
    // (adder's body differs: local.get 1 not 0); the flip changes no
    // lengths, so the component structure stays valid
    let mut wasm = std::fs::read(demo_path("demo.component.wasm"))?;
    let pat: [u8; 10] = [0x20, 0x00, 0x20, 0x00, 0x7C, 0x21, 0x01, 0x20, 0x01, 0x0F];
    let pos = wasm
        .windows(10)
        .position(|w| *w == pat)
        .expect("double's add pattern not found");
    wasm[pos + 4] = 0x7E; // i64.add → i64.mul

    let engine = SteelEngine::new()?;
    let component = engine.load_component_bytes(&wasm)?;
    let mut rt = ComponentRuntime::new(engine, CapabilitySet::NONE).await?;
    rt.instantiate(&component).await?;
    let got = rt.call("double", &[Val::U64(21)]).await?;
    let Val::U64(v) = &got[0] else {
        panic!("non-u64")
    };
    assert_ne!(
        v.to_string(),
        "42",
        "the sabotage didn't change the result — the control is vacuous"
    );
    assert_eq!(v.to_string(), "441", "the sabotage flipped the wrong op");
    Ok(())
}

#[tokio::test]
async fn stream_probe_debug() -> Result<(), Box<dyn std::error::Error>> {
    use std::pin::Pin;
    use std::sync::{Arc, Mutex};
    use std::task::{Context, Poll};
    use wasmtime::StoreContextMut;
    use wasmtime::component::{Instance, StreamConsumer, StreamResult, Source, StreamConsumer as _SC};
    use steel_host::HostState;

    let engine = SteelEngine::new()?;
    let component =
        engine.load_component_bytes(&std::fs::read(demo_path("demo.component.wasm"))?)?;
    let mut rt = ComponentRuntime::new(engine, CapabilitySet::NONE).await?;
    rt.instantiate(&component).await?;
    let instance: Instance = rt.instance().expect("instance").clone();

    struct Drain(Arc<Mutex<Vec<u64>>>);
    impl StreamConsumer<HostState> for Drain {
        type Item = u64;
        fn poll_consume(
            mut self: Pin<&mut Self>,
            _cx: &mut Context<'_>,
            store: StoreContextMut<'_, HostState>,
            mut source: Source<'_, Self::Item>,
            finish: bool,
        ) -> Poll<wasmtime::Result<StreamResult>> {
            eprintln!("poll_consume: finish={finish}");
            let mut buf: Vec<u64> = Vec::with_capacity(64);
            source.read(store, &mut buf)?;
            eprintln!("poll_consume: took {} items", buf.len());
            if buf.is_empty() {
                if finish {
                    return Poll::Ready(Ok(StreamResult::Dropped));
                }
                return Poll::Pending;
            }
            self.0.lock().unwrap().extend(buf.drain(..));
            Poll::Ready(Ok(StreamResult::Completed))
        }
    }

    let out: Arc<Mutex<Vec<u64>>> = Arc::new(Mutex::new(Vec::new()));
    let sink = out.clone();
    rt.store_mut()
        .run_concurrent(async move |accessor| {
            let f = accessor.with(|access| {
                instance
                    .get_func(access, "watch-counts")
                    .expect("watch-counts export")
            });
            let args = [Val::U64(3)];
            let mut results = [Val::List(vec![])];
            f.call_concurrent(accessor, &args, &mut results).await?;
            eprintln!("call_concurrent returned");
            let any = match results[0].clone() {
                Val::Stream(a) => a,
                other => panic!("not a stream: {other:?}"),
            };
            let reader = any.try_into_stream_reader::<u64>()?;
            // the drain = a background task in the SAME event loop: the
            // loop pumps it while the pending write is delivered
            struct DrainTask {
                reader: wasmtime::component::StreamReader<u64>,
                sink: Arc<Mutex<Vec<u64>>>,
            }
            impl wasmtime::component::AccessorTask<HostState> for DrainTask {
                fn run(
                    self,
                    accessor: &wasmtime::component::Accessor<HostState>,
                ) -> impl std::future::Future<Output = wasmtime::Result<()>> + Send {
                    let DrainTask { reader, sink } = self;
                    async move {
                        accessor.with(|access| reader.pipe(access, Drain(sink)))
                    }
                }
            }
            // AWAIT the join handle — a dropped handle may cancel the task
            use std::future::Future as _;
            let handle = accessor.spawn(DrainTask { reader, sink })?;
            let _ = handle.await;
            eprintln!("drain task joined");
            Ok::<(), wasmtime::Error>(())
        })
        .await??;
    eprintln!("drained: {:?}", out.lock().unwrap());
    assert_eq!(*out.lock().unwrap(), vec![42, 43]);
    Ok(())
}
