// GENERATED by schema-lang (lean-4.33.0) at 2026-09-15T10:31Z — DO NOT EDIT
// spec b6b4029+ | Dbsp.ChangeSpec (lean/dbsp) — the kernel-checked Change class | 16 item(s) | content hash 7133723351605466341 | regen: just gen; drift fails CI
// The guestlang change algebra — the Rust mirror of
// `Dbsp.ChangeSpec` (Lean's kernel-checked class: `Change (α Δα)`
// with `patch : α → Δα → α`, `valid : α → Δα → Prop`, and the
// diff/invert laws). GENERATED — edit the Lean class, not this.
// 
// Generality note: `patch : Row → Δ → Row` with `valid` keeping the
// base mirrors the Lean class exactly — a change is only meaningful
// against a base (Remove's `patch` keeps it; deletion is the key
// join's signal).
pub trait Change<Row> {
  fn patch(&self, base: &Row) -> Row;
  fn valid(&self, base: &Row) -> bool;
}
