// GENERATED by schema-lang (lean-4.33.0) at 2026-09-22T14:39Z — DO NOT EDIT
// spec 0f43de3+ | Demo.lean | 16 item(s) | content hash 13343525594910719474 | regen: just gen; drift fails CI
use crate::dbsp;
use crate::schema_generated::User;
use crate::schema_generated::OrderItem;
use crate::schema_generated::Order;
use crate::schema_generated::Flag;
use crate::schema_generated::AuditEntry;
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum UserChange {
  Insert(User),
  Update(User),
  Remove(u64),
}
// ChangeSpec: the Dbsp.Change shape (patch + valid) for UserChange.
impl dbsp::Change<User> for UserChange {
  fn patch(&self, base: &User) -> User {
    match self { Self::Insert(u) | Self::Update(u) => u.clone(), Self::Remove(_) => base.clone() }
  }
  fn valid(&self, _base: &User) -> bool {
    true
  }
}
#[derive(Clone, Debug, PartialEq)]
pub enum OrderItemChange {
  Insert(OrderItem),
  Update(OrderItem),
  Remove(u64),
}
// ChangeSpec: the Dbsp.Change shape (patch + valid) for OrderItemChange.
impl dbsp::Change<OrderItem> for OrderItemChange {
  fn patch(&self, base: &OrderItem) -> OrderItem {
    match self { Self::Insert(u) | Self::Update(u) => u.clone(), Self::Remove(_) => base.clone() }
  }
  fn valid(&self, _base: &OrderItem) -> bool {
    true
  }
}
#[derive(Clone, Debug, PartialEq)]
pub enum OrderChange {
  Insert(Order),
  Update(Order),
  Remove(u64),
}
// ChangeSpec: the Dbsp.Change shape (patch + valid) for OrderChange.
impl dbsp::Change<Order> for OrderChange {
  fn patch(&self, base: &Order) -> Order {
    match self { Self::Insert(u) | Self::Update(u) => u.clone(), Self::Remove(_) => base.clone() }
  }
  fn valid(&self, _base: &Order) -> bool {
    true
  }
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum FlagChange {
  Insert(Flag),
  Update(Flag),
  Remove(u64),
}
// ChangeSpec: the Dbsp.Change shape (patch + valid) for FlagChange.
impl dbsp::Change<Flag> for FlagChange {
  fn patch(&self, base: &Flag) -> Flag {
    match self { Self::Insert(u) | Self::Update(u) => u.clone(), Self::Remove(_) => base.clone() }
  }
  fn valid(&self, _base: &Flag) -> bool {
    true
  }
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum AuditEntryChange {
  Insert(AuditEntry),
  Update(AuditEntry),
  Remove(u64),
}
// ChangeSpec: the Dbsp.Change shape (patch + valid) for AuditEntryChange.
impl dbsp::Change<AuditEntry> for AuditEntryChange {
  fn patch(&self, base: &AuditEntry) -> AuditEntry {
    match self { Self::Insert(u) | Self::Update(u) => u.clone(), Self::Remove(_) => base.clone() }
  }
  fn valid(&self, _base: &AuditEntry) -> bool {
    true
  }
}
#[cfg(test)]
pub mod tests {
  use super::*;
  /// # Panics
  /// - the change laws are violated — that is the point of the test.
  #[test]
  pub fn user_change_roundtrip() {
    let base = User {id : 1, name : "a".into(), email : "a".into(), tags : vec![]};
    let delta = UserChange::Update(base.clone());
    assert_eq!(dbsp::Change::patch(&delta, &base), base);
    assert!(dbsp::Change::valid(&delta, &base));
  }
  /// # Panics
  /// - the change laws are violated — that is the point of the test.
  #[test]
  pub fn order_item_change_roundtrip() {
    let base = OrderItem {id : 1, qty : 1, price : 1.0};
    let delta = OrderItemChange::Update(base.clone());
    assert_eq!(dbsp::Change::patch(&delta, &base), base);
    assert!(dbsp::Change::valid(&delta, &base));
  }
  /// # Panics
  /// - the change laws are violated — that is the point of the test.
  #[test]
  pub fn order_change_roundtrip() {
    let base = Order {id : 1, items : vec![], total : 1.0};
    let delta = OrderChange::Update(base.clone());
    assert_eq!(dbsp::Change::patch(&delta, &base), base);
    assert!(dbsp::Change::valid(&delta, &base));
  }
  /// # Panics
  /// - the change laws are violated — that is the point of the test.
  #[test]
  pub fn flag_change_roundtrip() {
    let base = Flag {id : 1, key : "a".into(), enabled : true, rollout : 1, tags : vec![]};
    let delta = FlagChange::Update(base.clone());
    assert_eq!(dbsp::Change::patch(&delta, &base), base);
    assert!(dbsp::Change::valid(&delta, &base));
  }
  /// # Panics
  /// - the change laws are violated — that is the point of the test.
  #[test]
  pub fn audit_entry_change_roundtrip() {
    let base = AuditEntry {id : 1, flagKey : "a".into(), action : "a".into(), ts : 1};
    let delta = AuditEntryChange::Update(base.clone());
    assert_eq!(dbsp::Change::patch(&delta, &base), base);
    assert!(dbsp::Change::valid(&delta, &base));
  }
}
