// GENERATED by faults — DO NOT EDIT
// spec source: Faults/Spec/Host.lean
// regenerate via `just gen`; drift fails CI (byte-tie)
fast_observe::error! {
      pub enum HostFault {
      #[error("component not instantiated")]
      #[code = "E110", category = Invariant, advice = "call instantiate() before call()"]
      NotInstantiated,
      #[error("missing export: {name}")]
      #[code = "E111", category = Content, advice = "check the component world exports (wasm-tools component wit)"]
      MissingExport { name: String },
      #[error("unsupported result type: {ty}")]
      #[code = "E112", category = Invariant, advice = "return a scalar or handle it via typed bindings"]
      UnsupportedResult { ty: String },
      #[error("engine: {message}")]
      #[code = "E113", category = Transient, advice = "inspect the chained wasmtime error text"]
      Engine { message: String },
      }
}
pub fn init_host() {
  fast_observe::register_statics(HostFault::ENTRIES);
}
