//! lean-rust-wasm — guestlang framework crate.
#![feature(error_generic_member_access)]
//!
//! The fast-observe base wiring lives in `src/main.rs` (same shape as
//! fast-observe's `examples/demo.rs`); the library is intentionally thin
//! until the project has real shared types.

// The guestlang change algebra — OUR trait mirroring Lean's Dbsp.ChangeSpec
// (patch/valid); NOT the Feldera dbsp crate. Generated delta enums impl it.
pub mod dbsp;
pub mod dbsp_change_generated;
pub mod pipeline_generated;

// Generated by schema-lang (lean/schema-lang/GenMain.lean) — the Lean
// spec is authoritative; regenerate with `just gen`, never edit.
// rustfmt::skip on all generated modules: the emitter's output is the
// formatting authority; rustfmt reflowing generated files fights the
// byte-tie (regen would undo the reflow, fmt --check would flip forever).
#[rustfmt::skip]
pub mod schema_generated;

// Delta contracts: per-record change variants impl dbsp::Change; the
// certified-delta tests (Stage E) ride along under #[cfg(test)].
#[rustfmt::skip]
pub mod delta_generated;

// Generated by faults (lean/faults/GenMain.lean) — fast-observe error
// registry; codes allocated from the Lean registry, never hand-set.
#[rustfmt::skip]
pub mod faults_generated;
