// GENERATED by wasm-backend (lean-4.33.0) at 2026-09-14T06:22Z — DO NOT EDIT
// spec 2da229f+ | the world fold (worldExportsOf) | 16 item(s) | content hash 17000883951903747482 | regen: just gen; drift fails CI
/// One observed export: the span name + its fields + the delivery
/// contract (`once` = one result value; `stream` = incremental).
pub struct SpanSpec {
    pub name: &'static str,
    pub delivery: &'static str,
    pub fields: &'static [(&'static str, &'static str)],
}

/// The observed surface = the world's exports, in fold order.
pub const SPANS: &[SpanSpec] = &[
    SpanSpec { name: "double", delivery: "once", fields: &[("x", "u64")] },
    SpanSpec { name: "is-big", delivery: "once", fields: &[("x", "u64")] },
    SpanSpec { name: "adder", delivery: "once", fields: &[("a", "u64"), ("b", "u64")] },
    SpanSpec { name: "double-area", delivery: "once", fields: &[("r", "u64")] },
    SpanSpec { name: "pick", delivery: "once", fields: &[("b", "bool"), ("a", "u64"), ("x", "u64")] },
    SpanSpec { name: "run-paps", delivery: "once", fields: &[("x", "u64")] },
    SpanSpec { name: "total", delivery: "once", fields: &[("a", "u64"), ("b", "u64"), ("c", "u64")] },
    SpanSpec { name: "get-user", delivery: "once", fields: &[("id", "u64")] },
    SpanSpec { name: "greet", delivery: "once", fields: &[("n", "u64")] },
    SpanSpec { name: "str-len-demo", delivery: "once", fields: &[("n", "u64")] },
    SpanSpec { name: "watch-orders", delivery: "once", fields: &[("into", "order-error")] },
    SpanSpec { name: "watch-counts", delivery: "stream", fields: &[("n", "u64")] },
    SpanSpec { name: "watch-users", delivery: "stream", fields: &[("n", "u64")] },
    SpanSpec { name: "user-valid", delivery: "once", fields: &[("u", "user")] },
    SpanSpec { name: "user-complete", delivery: "once", fields: &[("u", "user")] },
    SpanSpec { name: "order-error-valid", delivery: "once", fields: &[("e", "order-error")] },
];
