// GENERATED by schema-lang (lean-4.33.0) at 2026-09-17T04:08Z — DO NOT EDIT
// spec ba4b99a+ | SchemaLang.OrderMachine (orderMachineTrans + orderMachineTableStep?_eq_step?) | 16 item(s) | content hash 8774633528911920128 | regen: just gen; drift fails CI
// GENERATED from SchemaLang.OrderMachine — the lifecycle's TYPESTATE
// projection. Each struct = one REACHABLE state (payload = the row id,
// v1: u64); each method = one non-`reset` row of `orderMachineTrans` — the SAME
// table the theorem `orderMachineTableStep?_eq_step?` pins to the machine (the
// emitter folds the table, never a hand copy; Lean pins:
// `typestate_edges_legal`, `typestate_states_reachable`).
// 
// Deliberate exclusions:
// - the `reset` edge is NOT emitted: a typestate value is consumed,
//   never rewrapped — recovery = a fresh Cart(id).
// - `stray` gets no struct: no orderMachineTrans row targets it (Inv non-vacuity).
// - `delivered`/`cancelled` get no methods (`terminal_only_reset`): the
//   illegal transition is unrepresentable, not None — no Option, no panic.
// Do not edit — regenerate.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Cart(pub u64);
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Placed(pub u64);
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Shipped(pub u64);
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Delivered(pub u64);
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Cancelled(pub u64);
impl Cart {
    pub fn place(self) -> Placed {
        Placed(self.0)
    }
    pub fn cancel(self) -> Cancelled {
        Cancelled(self.0)
    }
}

impl Placed {
    pub fn ship(self) -> Shipped {
        Shipped(self.0)
    }
    pub fn cancel(self) -> Cancelled {
        Cancelled(self.0)
    }
}

impl Shipped {
    pub fn deliver(self) -> Delivered {
        Delivered(self.0)
    }
}


pub mod tests {
  use super::*;
  #[test]
  pub fn happy_path_reaches_delivered() {
    assert_eq!(Cart(7u64).place().ship().deliver().0, 7u64);
  }
  #[test]
  pub fn cancel_paths_are_legal() {
    assert_eq!(Cart(7u64).cancel().0, 7u64);
  }
  #[test]
  pub fn cancel_after_place_is_legal() {
    assert_eq!(Placed(7u64).cancel().0, 7u64);
  }
}
