// GENERATED by schema-lang (lean-4.33.0) at 2026-09-15T09:26Z — DO NOT EDIT
// spec d9aacbc+ | SchemaLang.Pipeline (pipelineTrans + tableStep?_eq_step?) | 16 item(s) | content hash 9166310844412329388 | regen: just gen; drift fails CI
// GENERATED from SchemaLang.Pipeline (pipelineTrans) — the forge
// driver's stage machine. Agreement with the Lean machine is a
// THEOREM there (tableStep?_eq_step?); do not edit — regenerate.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]

pub enum PipelineStage {
  Idle,
  Reflecting,
  Checked,
  Emitted,
  Tied,
  Failed { stage: &'static str },
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]

pub enum PipelineEvent {
  Reflect,
  Check,
  Emit,
  Tie,
  Reset,
}

/// The machine's step: None = illegal (guard failed). `Reset` fires
/// from every state (the recovery edge) — including `Failed`, which
/// nothing else accepts (the error state is a resting place).
pub fn step(s: PipelineStage, e: PipelineEvent) -> Option<PipelineStage> {
    use PipelineStage::*;
    match (s, e) {
        (Idle, PipelineEvent::Reflect) => Some(Reflecting),
        (Reflecting, PipelineEvent::Check) => Some(Checked),
        (Checked, PipelineEvent::Emit) => Some(Emitted),
        (Emitted, PipelineEvent::Tie) => Some(Tied),
        (_, PipelineEvent::Reset) => Some(Idle),
        _ => None,
    }
}

/// The happy chain: Idle -> Reflecting -> Checked -> Emitted -> Tied
/// (Lean: `happy_path`, proved by rfl). Illegal = driver bug.
pub fn happy_path_assertions() {
    use PipelineStage::*;
    assert_eq!(step(Idle, PipelineEvent::Reflect), Some(Reflecting));
    assert_eq!(step(Reflecting, PipelineEvent::Check), Some(Checked));
    assert_eq!(step(Checked, PipelineEvent::Emit), Some(Emitted));
    assert_eq!(step(Emitted, PipelineEvent::Tie), Some(Tied));
    assert_eq!(step(Idle, PipelineEvent::Check), None);
    assert_eq!(
        step(Failed { stage: "tie" }, PipelineEvent::Reset),
        Some(Idle)
    );
}
