// GENERATED by schema-lang (lean-4.33.0) at 2026-09-16T08:52Z — DO NOT EDIT
// spec f2951ad+ | Demo.lean | 16 item(s) | content hash 1187894842610226286 | regen: just gen; drift fails CI
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct User {
  pub id : u64,
  pub name : String,
  pub email : String,
  pub tags : Vec<String>,
}
#[derive(Clone, Debug, PartialEq)]
pub struct OrderItem {
  pub id : u64,
  pub qty : u32,
  pub price : f64,
}
#[derive(Clone, Debug, PartialEq)]
pub struct Order {
  pub id : u64,
  pub items : Vec<OrderItem>,
  pub total : f64,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Role {
  Admin,
  Editor,
  Viewer,
}
#[derive(Clone, Debug, PartialEq)]
pub enum OrderError {
  EmptyCart,
  InvalidItem(u64),
  InsufficientFunds(f64),
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Flag {
  pub id : u64,
  pub key : String,
  pub enabled : bool,
  pub rollout : u64,
  pub tags : Vec<String>,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AuditEntry {
  pub id : u64,
  pub flagKey : String,
  pub action : String,
  pub ts : u64,
}
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum FlagError {
  NotFound,
  InvalidRollout(u64),
  Locked(String),
}
