// GENERATED by schema-lang (lean-4.33.0) at 2026-09-18T19:09Z — DO NOT EDIT
// spec 97ed6f4+ | SchemaLang.Meta.Reflect (updateItemExt) — schema_update | 16 item(s) | content hash 15275235971296541536 | regen: just gen; drift fails CI
// GENERATED from the schema_update registry (SchemaLang.Meta.updateItemExt) —
// do not edit — regenerate (just gen). One apply fn per update (guard via
// the evalB discipline), one tick fn per record (registration order). The
// spec of record is UpdateItem.applyRow: guard AND value read the ORIGINAL
// row; a refused row passes through untouched; the tick re-runs updates in
// registration order (v1 cascade: single-pass, single-table).

use crate::schema_generated::User;
use crate::schema_generated::Flag;

// update `reset_id` on User — writes `id`
//   guard + value read the ORIGINAL row (UpdateItem.applyRow discipline)
pub fn apply_reset_id(rows: &mut Vec<User>) {
  for r in rows.iter_mut() { if (r.id > 100u64) { r.id = 0u64; } }
}
// update `echo_email` on User — writes `email`
//   guard + value read the ORIGINAL row (UpdateItem.applyRow discipline)
pub fn apply_echo_email(rows: &mut Vec<User>) {
  for r in rows.iter_mut() { if ((r.name).len() as u64 > 3u64) { r.email = (r.name).clone(); } }
}
// update `self_bump` on User — writes `id`
//   guard + value read the ORIGINAL row (UpdateItem.applyRow discipline)
pub fn apply_self_bump(rows: &mut Vec<User>) {
  for r in rows.iter_mut() { if (0u64 == 0u64) { r.id = r.id; } }
}
// update `rolloutClamp` on Flag — writes `rollout`
//   guard + value read the ORIGINAL row (UpdateItem.applyRow discipline)
pub fn apply_rollout_clamp(rows: &mut Vec<Flag>) {
  for r in rows.iter_mut() { if (r.rollout > 100u64) { r.rollout = 100u64; } }
}
// update `keyEcho` on Flag — writes `key`
//   guard + value read the ORIGINAL row (UpdateItem.applyRow discipline)
pub fn apply_key_echo(rows: &mut Vec<Flag>) {
  for r in rows.iter_mut() { if ((r.key).len() as u64 > 0u64) { r.key = (r.key).clone(); } }
}

pub fn tick_user(rows: &mut Vec<User>) {
  apply_reset_id(rows); apply_echo_email(rows); apply_self_bump(rows);
}
pub fn tick_flag(rows: &mut Vec<Flag>) {
  apply_rollout_clamp(rows); apply_key_echo(rows);
}
