// GENERATED by schema-lang — DO NOT EDIT
// spec source: Demo.lean
// regenerate via `just gen`; drift fails CI (byte-tie)
use vortex::dtype::{DType, DecimalDType, ExtDTypeRef, Nullability, PType, StructFields, UnionVariants};
use vortex::IntoArray;
use vortex::IntoVortex;
// record: User
pub const USER_DTYPE : std::sync::LazyLock<vortex::dtype::DType> = std::sync::LazyLock::new(|| DType::Struct(StructFields::new(vec![("id".into(), DType::Primitive(PType::U64, Nullability::NonNullable)), ("name".into(), DType::Utf8(Nullability::NonNullable)), ("email".into(), DType::Utf8(Nullability::NonNullable)), ("tags".into(), DType::List(std::sync::Arc::new(DType::Utf8(Nullability::NonNullable)), Nullability::NonNullable))]), Nullability::NonNullable));
impl IntoVortex for User {
  fn into_vortex(&self) -> vortex::ArrayRef {
    vortex::StructArray::from_fields(vec![("id".into(), self.id.into_array()), ("name".into(), self.name.into_array()), ("email".into(), self.email.into_array()), ("tags".into(), self.tags.into_array())]).expect("valid struct array").into_array()
  }
}
// record: OrderItem
pub const ORDER_ITEM_DTYPE : std::sync::LazyLock<vortex::dtype::DType> = std::sync::LazyLock::new(|| DType::Struct(StructFields::new(vec![("id".into(), DType::Primitive(PType::U64, Nullability::NonNullable)), ("qty".into(), DType::Primitive(PType::U32, Nullability::NonNullable)), ("price".into(), DType::Primitive(PType::F64, Nullability::NonNullable))]), Nullability::NonNullable));
impl IntoVortex for OrderItem {
  fn into_vortex(&self) -> vortex::ArrayRef {
    vortex::StructArray::from_fields(vec![("id".into(), self.id.into_array()), ("qty".into(), self.qty.into_array()), ("price".into(), self.price.into_array())]).expect("valid struct array").into_array()
  }
}
// record: Order
pub const ORDER_DTYPE : std::sync::LazyLock<vortex::dtype::DType> = std::sync::LazyLock::new(|| DType::Struct(StructFields::new(vec![("id".into(), DType::Primitive(PType::U64, Nullability::NonNullable)), ("items".into(), DType::List(std::sync::Arc::new(DType::Struct(StructFields::new(vec![("id".into(), DType::Primitive(PType::U64, Nullability::NonNullable)), ("qty".into(), DType::Primitive(PType::U32, Nullability::NonNullable)), ("price".into(), DType::Primitive(PType::F64, Nullability::NonNullable))]), Nullability::NonNullable)), Nullability::NonNullable)), ("total".into(), DType::Primitive(PType::F64, Nullability::NonNullable))]), Nullability::NonNullable));
impl IntoVortex for Order {
  fn into_vortex(&self) -> vortex::ArrayRef {
    vortex::StructArray::from_fields(vec![("id".into(), self.id.into_array()), ("items".into(), self.items.into_array()), ("total".into(), self.total.into_array())]).expect("valid struct array").into_array()
  }
}
