;; GENERATED by wasm-backend — DO NOT EDIT
;; spec source: DemoFn.lean
;; regenerate via `just gen`; drift fails CI (byte-tie)
(module
;; guestlang runtime — pooled allocator + Perceus RC (guestlang-owned;
;; NOT Lean's C runtime). GenMain splices these funcs/globals into the
;; emitted module — single module, no imports.
;;
;; Object layout: { rc: u32 @0, tag: u8 @4, class: u8 @5, pad[2], fields @8 }
;; (one 8-byte slot per scalar field — matches the LCNF sproj offsets).
;;
;; Allocation: size-class free lists (class = (size-1)>>4, 16-byte
;; granularity, classes 0..5 = 16..96 bytes) — O(1) alloc AND free.
;; Freelist heads live at memory[0..24). Blocks >96 bytes bump-allocate
;; and never free (v1: the scalars-only demo never exceeds a class).
;; Perceus: rc_inc/rc_dec; dec→0 pushes the block back to its class.

(global $heap (mut i32) (i32.const 64))
(global $heap-end (mut i32) (i32.const 65536))

(func $alloc (param $size i32) (result i32)
  (local $cls i32) (local $blk i32) (local $old i32) (local $new i32)
  ;; class = (size-1) >> 4
  local.get $size
  i32.const 1
  i32.sub
  i32.const 4
  i32.shr_u
  local.set $cls
  ;; pooled path: class < 6 AND freelist non-empty
  local.get $cls
  i32.const 6
  i32.lt_u
  if (result i32)
    local.get $cls
    i32.const 4
    i32.mul
    i32.load
    local.set $blk
    local.get $blk
    if (result i32)
      ;; pop: freelist[cls] = blk.next; rc reset to 1
      local.get $cls
      i32.const 4
      i32.mul
      local.get $blk
      i32.load
      i32.store
      local.get $blk
      i32.const 1
      i32.store
      local.get $blk
    else
      ;; empty class → bump
      global.get $heap
      local.set $old
      global.get $heap
      local.get $size
      i32.add
      global.set $heap
      ;; grow past the page end
      global.get $heap
      global.get $heap-end
      i32.gt_u
      if
        i32.const 1
        memory.grow
        i32.const -1
        i32.eq
        if
          unreachable ;; OOM: memory.grow failed
        end
        global.get $heap-end
        i32.const 65536
        i32.add
        global.set $heap-end
      end
      ;; init header: rc = 1, class byte
      local.get $old
      i32.const 1
      i32.store
      local.get $old
      local.get $cls
      i32.store8 offset=5
      local.get $old
    end
  else
    ;; oversized (class ≥ 6): bump, class byte marks never-free
    global.get $heap
    local.set $old
    global.get $heap
    local.get $size
    i32.add
    global.set $heap
    global.get $heap
    global.get $heap-end
    i32.gt_u
    if
      i32.const 1
      memory.grow
      i32.const -1
      i32.eq
      if
        unreachable ;; OOM
      end
      global.get $heap-end
      i32.const 65536
      i32.add
      global.set $heap-end
    end
    local.get $old
    i32.const 1
    i32.store
    local.get $old
    i32.const 255
    i32.store8 offset=5
    local.get $old
  end
)

(func $rc_inc (param $p i32)
  local.get $p
  local.get $p
  i32.load
  i32.const 1
  i32.add
  i32.store
)

(func $rc_dec (param $p i32)
  (local $rc i32) (local $cls i32)
  local.get $p
  local.get $p
  i32.load
  i32.const 1
  i32.sub
  local.tee $rc
  i32.store
  ;; rc == 0 → return the block to its class pool
  local.get $rc
  if
    local.get $p
    i32.load8_u offset=5
    local.set $cls
    ;; p.next = freelist[cls]
    local.get $p
    local.get $cls
    i32.const 4
    i32.mul
    i32.load
    i32.store
    ;; freelist[cls] = p
    local.get $cls
    i32.const 4
    i32.mul
    local.get $p
    i32.store
  end
)

;; ── guestlang-std strings ──────────────────────────────────────────
;; Layout: {rc@0, tag=250@4, len u32@8, bytes@16} — variable-size
;; object, bytes INLINE (RC frees the whole string; no byte leak).
;; Byte-length semantics (== Lean's char length on ASCII only).

(func $string_len (param $s i32) (result i64)
  local.get $s
  i32.load offset=8
  i64.extend_i32_u)

(func $string_cat (param $a i32) (param $b i32) (result i32)
  (local $na i32) (local $nb i32) (local $p i32)
  local.get $a
  i32.load offset=8
  local.set $na
  local.get $b
  i32.load offset=8
  local.set $nb
  ;; alloc 16 + na + nb
  i32.const 16
  local.get $na
  i32.add
  local.get $nb
  i32.add
  call $alloc
  local.set $p
  ;; tag = 250
  local.get $p
  i32.const 250
  i32.store8 offset=4
  ;; len = na + nb
  local.get $p
  local.get $na
  local.get $nb
  i32.add
  i32.store offset=8
  ;; copy a's bytes: dst = p+16
  local.get $p
  i32.const 16
  i32.add
  local.get $a
  i32.const 16
  i32.add
  local.get $na
  memory.copy
  ;; copy b's bytes: dst = p+16+na
  local.get $p
  i32.const 16
  i32.add
  local.get $na
  i32.add
  local.get $b
  i32.const 16
  i32.add
  local.get $nb
  memory.copy
  local.get $p)

  (memory 1)
(func $double (param $x i64) (result i64)
    (local $l0 i64)
  local.get $x
  local.get $x
  i64.add
  local.set $l0
  local.get $l0
  return
)
(func $isBig (param $x i64) (result i32)
    (local $l1 i64)
    (local $l2 i32)
  i64.const 100
  local.set $l1
  local.get $l1
  local.get $x
  i64.lt_u
  local.set $l2
  local.get $l2
  return
)
(func $adder (param $a i64) (param $b i64) (result i64)
    (local $l3 i64)
  local.get $a
  local.get $b
  i64.add
  local.set $l3
  local.get $l3
  return
)
(func $area (param $s i32) (result i64)
    (local $l4 i32)
    (local $l5 i64)
    (local $l6 i64)
    (local $l7 i64)
    (local $l8 i64)
    (local $l9 i64)
  local.get $s
  i32.load8_u offset=4
  local.set $l4
  local.get $l4
  i32.const 0
  i32.eq
  if (result i64)
  local.get $s
  i64.load offset=8
  local.set $l5
  local.get $l5
  local.get $l5
  i64.mul
  local.set $l6
  local.get $l6
  return
  else
  local.get $l4
  i32.const 1
  i32.eq
  if (result i64)
  local.get $s
  i64.load offset=8
  local.set $l7
  local.get $s
  i64.load offset=16
  local.set $l8
  local.get $l7
  local.get $l8
  i64.mul
  local.set $l9
  local.get $l9
  return
  else
  unreachable ;; no matching ctor tag
  end
  end
)
(func $doubleArea (param $r i64) (result i64)
    (local $l10 i64)
    (local $l11 i32)
    (local $l12 i64)
  local.get $r
  local.get $r
  i64.add
  local.set $l10
  i32.const 16
  call $alloc
  local.set $l11
  local.get $l11
  i32.const 0
  i32.store8 offset=4
  local.get $l11
  local.get $l10
  i64.store offset=8
  local.get $l11
  call $area
  local.set $l12
  local.get $l11
  call $rc_dec
  local.get $l12
  return
)
(func $pick (param $b i32) (param $a i64) (param $x i64) (result i64)
    (local $l13 i64)
    (local $l14 i64)
  local.get $b
  i32.const 0
  i32.eq
  if (result i64)
  local.get $a
  local.get $x
  i64.mul
  local.set $l13
  local.get $l13
  return
  else
  local.get $b
  i32.const 1
  i32.eq
  if (result i64)
  local.get $a
  local.get $x
  i64.add
  local.set $l14
  local.get $l14
  return
  else
  unreachable ;; no matching scalar case
  end
  end
)
(func $applyAll (param $fs i32) (param $x i64) (result i64)
    (local $l15 i32)
    (local $l16 i32)
    (local $l17 i32)
    (local $l18 i64)
    (local $l19 i32)
    (local $l20 i32)
    (local $l21 i64)
  local.get $fs
  i32.load8_u offset=4
  local.set $l15
  local.get $l15
  i32.const 0
  i32.eq
  if (result i64)
  local.get $x
  return
  else
  local.get $l15
  i32.const 1
  i32.eq
  if (result i64)
  local.get $fs
  i32.load offset=8
  local.set $l16
  local.get $l16
  call $rc_inc
  local.get $fs
  i32.load offset=16
  local.set $l17
  local.get $l17
  call $rc_inc
  local.get $fs
  call $rc_dec
  local.get $l17
  local.get $x
  call $applyAll
  local.set $l18
  i32.const 16
  call $alloc
  local.set $l19
  local.get $l19
  local.get $l18
  i64.store offset=8
  local.get $l16
  local.get $l19
  local.get $l16
  i32.load offset=8
  call_indirect (type $sig_1box)
  local.set $l20
  local.get $l20
  i64.load offset=8
  local.set $l21
  local.get $l20
  call $rc_dec
  local.get $l21
  return
  else
  unreachable ;; no matching ctor tag
  end
  end
)
(func $runPaps (param $x i64) (result i64)
    (local $l22 i32)
  call $runPaps._closed_3
  local.set $l22
  local.get $l22
  call $rc_inc
  local.get $l22
  local.get $x
  return_call $applyAll
)
(func $curried (param $a i64) (param $x i64) (param $y i64) (result i64)
    (local $l23 i64)
    (local $l24 i64)
  local.get $a
  local.get $x
  i64.add
  local.set $l23
  local.get $l23
  local.get $y
  i64.add
  local.set $l24
  local.get $l24
  return
)
(func $apply2All (param $fs i32) (param $x i64) (param $y i64) (result i64)
    (local $l25 i32)
    (local $l26 i64)
    (local $l27 i32)
    (local $l28 i32)
    (local $l29 i32)
    (local $l30 i32)
    (local $l31 i32)
    (local $l32 i64)
  local.get $fs
  i32.load8_u offset=4
  local.set $l25
  local.get $l25
  i32.const 0
  i32.eq
  if (result i64)
  local.get $x
  local.get $y
  i64.add
  local.set $l26
  local.get $l26
  return
  else
  local.get $l25
  i32.const 1
  i32.eq
  if (result i64)
  local.get $fs
  i32.load offset=8
  local.set $l27
  local.get $l27
  call $rc_inc
  local.get $fs
  i32.load offset=16
  local.set $l28
  local.get $l28
  call $rc_inc
  local.get $fs
  call $rc_dec
  i32.const 16
  call $alloc
  local.set $l29
  local.get $l29
  local.get $x
  i64.store offset=8
  i32.const 16
  call $alloc
  local.set $l30
  local.get $l30
  local.get $y
  i64.store offset=8
  local.get $l27
  local.get $l29
  local.get $l30
  local.get $l27
  i32.load offset=8
  call_indirect (type $sig_2box)
  local.set $l31
  local.get $l31
  i64.load offset=8
  local.set $l32
  local.get $l31
  call $rc_dec
  local.get $l28
  local.get $l32
  local.get $y
  return_call $apply2All
  else
  unreachable ;; no matching ctor tag
  end
  end
)
(func $useCurried (param $a i64) (result i64)
    (local $l33 i32)
    (local $l34 i32)
    (local $l35 i32)
    (local $l36 i32)
    (local $l37 i64)
    (local $l38 i64)
  i32.const 16
  call $alloc
  local.set $l33
  local.get $l33
  local.get $a
  i64.store offset=8
  i32.const 24
  call $alloc
  local.set $l34
  local.get $l34
  i32.const 254
  i32.store8 offset=4
  local.get $l34
  i32.const 0
  i32.store offset=8
  local.get $l34
  local.get $l33
  i32.store offset=16
  i32.const 8
  call $alloc
  local.set $l35
  local.get $l35
  i32.const 0
  i32.store8 offset=4
  i32.const 24
  call $alloc
  local.set $l36
  local.get $l36
  i32.const 1
  i32.store8 offset=4
  local.get $l36
  local.get $l34
  i32.store offset=8
  local.get $l36
  local.get $l35
  i32.store offset=16
  i64.const 3
  local.set $l37
  i64.const 4
  local.set $l38
  local.get $l36
  local.get $l37
  local.get $l38
  return_call $apply2All
)
(func $sumList (param $xs i32) (param $acc i64) (result i64)
    (local $l39 i32)
    (local $l40 i32)
    (local $l41 i32)
    (local $l42 i64)
    (local $l43 i64)
  local.get $xs
  i32.load8_u offset=4
  local.set $l39
  local.get $l39
  i32.const 0
  i32.eq
  if (result i64)
  local.get $acc
  return
  else
  local.get $l39
  i32.const 1
  i32.eq
  if (result i64)
  local.get $xs
  i32.load offset=8
  local.set $l40
  local.get $xs
  i32.load offset=16
  local.set $l41
  local.get $l40
  i64.load offset=8
  local.set $l42
  local.get $acc
  local.get $l42
  i64.add
  local.set $l43
  local.get $l41
  local.get $l43
  return_call $sumList
  else
  unreachable ;; no matching ctor tag
  end
  end
)
(func $total (param $a i64) (param $b i64) (param $c i64) (result i64)
    (local $l44 i32)
    (local $l45 i32)
    (local $l46 i32)
    (local $l47 i32)
    (local $l48 i32)
    (local $l49 i32)
    (local $l50 i32)
    (local $l51 i64)
    (local $l52 i64)
  i32.const 8
  call $alloc
  local.set $l44
  local.get $l44
  i32.const 0
  i32.store8 offset=4
  i32.const 16
  call $alloc
  local.set $l45
  local.get $l45
  local.get $c
  i64.store offset=8
  i32.const 24
  call $alloc
  local.set $l46
  local.get $l46
  i32.const 1
  i32.store8 offset=4
  local.get $l46
  local.get $l45
  i32.store offset=8
  local.get $l46
  local.get $l44
  i32.store offset=16
  i32.const 16
  call $alloc
  local.set $l47
  local.get $l47
  local.get $b
  i64.store offset=8
  i32.const 24
  call $alloc
  local.set $l48
  local.get $l48
  i32.const 1
  i32.store8 offset=4
  local.get $l48
  local.get $l47
  i32.store offset=8
  local.get $l48
  local.get $l46
  i32.store offset=16
  i32.const 16
  call $alloc
  local.set $l49
  local.get $l49
  local.get $a
  i64.store offset=8
  i32.const 24
  call $alloc
  local.set $l50
  local.get $l50
  i32.const 1
  i32.store8 offset=4
  local.get $l50
  local.get $l49
  i32.store offset=8
  local.get $l50
  local.get $l48
  i32.store offset=16
  i64.const 0
  local.set $l51
  local.get $l50
  local.get $l51
  call $sumList
  local.set $l52
  local.get $l50
  call $rc_dec
  local.get $l52
  return
)
(func $strLenDemo (param $n i64) (result i64)
    (local $l53 i64)
    (local $l54 i32)
  i64.const 0
  local.set $l53
  local.get $l53
  local.get $n
  i64.lt_u
  local.set $l54
  local.get $l54
  i32.const 0
  i32.eq
  if (result i64)
  return_call $strLenDemo._closed_1
  else
  local.get $l54
  i32.const 1
  i32.eq
  if (result i64)
  return_call $strLenDemo._closed_3
  else
  unreachable ;; no matching scalar case
  end
  end
)
(func $greet (param $n i64) (result i32)
    (local $l55 i64)
    (local $l56 i32)
    (local $l57 i32)
    (local $l58 i32)
  i64.const 0
  local.set $l55
  local.get $l55
  local.get $n
  i64.lt_u
  local.set $l56
  local.get $l56
  i32.const 0
  i32.eq
  if (result i32)
  call $greet._closed_0
  local.set $l57
  local.get $l57
  call $rc_inc
  local.get $l57
  return
  else
  local.get $l56
  i32.const 1
  i32.eq
  if (result i32)
  call $greet._closed_1
  local.set $l58
  local.get $l58
  call $rc_inc
  local.get $l58
  return
  else
  unreachable ;; no matching scalar case
  end
  end
)
(func $runPaps._closed_0._boxed_const_1  (result i32)
    (local $l59 i64)
    (local $l60 i32)
  i64.const 1
  local.set $l59
  i32.const 16
  call $alloc
  local.set $l60
  local.get $l60
  local.get $l59
  i64.store offset=8
  local.get $l60
  return
)
(func $useCurried._boxed (param $a i32) (result i32)
    (local $l61 i64)
    (local $l62 i64)
    (local $l63 i32)
  local.get $a
  i64.load offset=8
  local.set $l61
  local.get $a
  call $rc_dec
  local.get $l61
  call $useCurried
  local.set $l62
  i32.const 16
  call $alloc
  local.set $l63
  local.get $l63
  local.get $l62
  i64.store offset=8
  local.get $l63
  return
)
(func $isBig._boxed (param $x i32) (result i32)
    (local $l64 i64)
    (local $l65 i32)
    (local $l66 i32)
  local.get $x
  i64.load offset=8
  local.set $l64
  local.get $x
  call $rc_dec
  local.get $l64
  call $isBig
  local.set $l65
  i32.const 16
  call $alloc
  local.set $l66
  local.get $l66
  local.get $l65
  i32.store offset=8
  local.get $l66
  return
)
(func $runPaps._lam_1._boxed (param $_x.1 i32) (param $_y.2 i32) (result i32)
    (local $l67 i64)
    (local $l68 i64)
    (local $l69 i64)
    (local $l70 i32)
  local.get $_x.1
  i64.load offset=8
  local.set $l67
  local.get $_x.1
  call $rc_dec
  local.get $_y.2
  i64.load offset=8
  local.set $l68
  local.get $_y.2
  call $rc_dec
  local.get $l67
  local.get $l68
  call $runPaps._lam_1
  local.set $l69
  i32.const 16
  call $alloc
  local.set $l70
  local.get $l70
  local.get $l69
  i64.store offset=8
  local.get $l70
  return
)
(func $strLenDemo._closed_3  (result i64)
    (local $l71 i32)
    (local $l72 i64)
  call $strLenDemo._closed_2
  local.set $l71
  local.get $l71
  call $string_len
  local.set $l72
  local.get $l72
  return
)
(func $greet._closed_1  (result i32)
    (local $l73 i32)
  i32.const 27
  call $alloc
  local.set $l73
  local.get $l73
  i32.const 250
  i32.store8 offset=4
  local.get $l73
  i32.const 11
  i32.store offset=8
  local.get $l73
  i32.const 104
  i32.store8 offset=16
  local.get $l73
  i32.const 101
  i32.store8 offset=17
  local.get $l73
  i32.const 108
  i32.store8 offset=18
  local.get $l73
  i32.const 108
  i32.store8 offset=19
  local.get $l73
  i32.const 111
  i32.store8 offset=20
  local.get $l73
  i32.const 32
  i32.store8 offset=21
  local.get $l73
  i32.const 103
  i32.store8 offset=22
  local.get $l73
  i32.const 117
  i32.store8 offset=23
  local.get $l73
  i32.const 101
  i32.store8 offset=24
  local.get $l73
  i32.const 115
  i32.store8 offset=25
  local.get $l73
  i32.const 116
  i32.store8 offset=26
  local.get $l73
  return
)
(func $strLenDemo._closed_0  (result i32)
    (local $l74 i32)
  i32.const 17
  call $alloc
  local.set $l74
  local.get $l74
  i32.const 250
  i32.store8 offset=4
  local.get $l74
  i32.const 1
  i32.store offset=8
  local.get $l74
  i32.const 33
  i32.store8 offset=16
  local.get $l74
  return
)
(func $runPaps._closed_1._boxed_const_1  (result i32)
    (local $l75 i64)
    (local $l76 i32)
  i64.const 2
  local.set $l75
  i32.const 16
  call $alloc
  local.set $l76
  local.get $l76
  local.get $l75
  i64.store offset=8
  local.get $l76
  return
)
(func $runPaps._closed_3  (result i32)
    (local $l77 i32)
    (local $l78 i32)
    (local $l79 i32)
  call $runPaps._closed_2
  local.set $l77
  call $runPaps._closed_0
  local.set $l78
  local.get $l77
  call $rc_inc
  local.get $l78
  call $rc_inc
  i32.const 24
  call $alloc
  local.set $l79
  local.get $l79
  i32.const 1
  i32.store8 offset=4
  local.get $l79
  local.get $l78
  i32.store offset=8
  local.get $l79
  local.get $l77
  i32.store offset=16
  local.get $l79
  return
)
(func $pick._boxed (param $b i32) (param $a i32) (param $x i32) (result i32)
    (local $l80 i32)
    (local $l81 i64)
    (local $l82 i64)
    (local $l83 i64)
    (local $l84 i32)
  local.get $b
  i32.load offset=8
  local.set $l80
  local.get $a
  i64.load offset=8
  local.set $l81
  local.get $a
  call $rc_dec
  local.get $x
  i64.load offset=8
  local.set $l82
  local.get $x
  call $rc_dec
  local.get $l80
  local.get $l81
  local.get $l82
  call $pick
  local.set $l83
  i32.const 16
  call $alloc
  local.set $l84
  local.get $l84
  local.get $l83
  i64.store offset=8
  local.get $l84
  return
)
(func $apply2All._boxed (param $fs i32) (param $x i32) (param $y i32) (result i32)
    (local $l85 i64)
    (local $l86 i64)
    (local $l87 i64)
    (local $l88 i32)
  local.get $x
  i64.load offset=8
  local.set $l85
  local.get $x
  call $rc_dec
  local.get $y
  i64.load offset=8
  local.set $l86
  local.get $y
  call $rc_dec
  local.get $fs
  local.get $l85
  local.get $l86
  call $apply2All
  local.set $l87
  i32.const 16
  call $alloc
  local.set $l88
  local.get $l88
  local.get $l87
  i64.store offset=8
  local.get $l88
  return
)
(func $total._boxed (param $a i32) (param $b i32) (param $c i32) (result i32)
    (local $l89 i64)
    (local $l90 i64)
    (local $l91 i64)
    (local $l92 i64)
    (local $l93 i32)
  local.get $a
  i64.load offset=8
  local.set $l89
  local.get $a
  call $rc_dec
  local.get $b
  i64.load offset=8
  local.set $l90
  local.get $b
  call $rc_dec
  local.get $c
  i64.load offset=8
  local.set $l91
  local.get $c
  call $rc_dec
  local.get $l89
  local.get $l90
  local.get $l91
  call $total
  local.set $l92
  i32.const 16
  call $alloc
  local.set $l93
  local.get $l93
  local.get $l92
  i64.store offset=8
  local.get $l93
  return
)
(func $runPaps._closed_0  (result i32)
    (local $l94 i32)
    (local $l95 i32)
  call $runPaps._closed_0._boxed_const_1
  local.set $l94
  local.get $l94
  call $rc_inc
  i32.const 24
  call $alloc
  local.set $l95
  local.get $l95
  i32.const 254
  i32.store8 offset=4
  local.get $l95
  i32.const 1
  i32.store offset=8
  local.get $l95
  local.get $l94
  i32.store offset=16
  local.get $l95
  return
)
(func $double._boxed (param $x i32) (result i32)
    (local $l96 i64)
    (local $l97 i64)
    (local $l98 i32)
  local.get $x
  i64.load offset=8
  local.set $l96
  local.get $x
  call $rc_dec
  local.get $l96
  call $double
  local.set $l97
  i32.const 16
  call $alloc
  local.set $l98
  local.get $l98
  local.get $l97
  i64.store offset=8
  local.get $l98
  return
)
(func $curried._boxed (param $a i32) (param $x i32) (param $y i32) (result i32)
    (local $l99 i64)
    (local $l100 i64)
    (local $l101 i64)
    (local $l102 i64)
    (local $l103 i32)
  local.get $a
  i64.load offset=8
  local.set $l99
  local.get $a
  call $rc_dec
  local.get $x
  i64.load offset=8
  local.set $l100
  local.get $x
  call $rc_dec
  local.get $y
  i64.load offset=8
  local.set $l101
  local.get $y
  call $rc_dec
  local.get $l99
  local.get $l100
  local.get $l101
  call $curried
  local.set $l102
  i32.const 16
  call $alloc
  local.set $l103
  local.get $l103
  local.get $l102
  i64.store offset=8
  local.get $l103
  return
)
(func $strLenDemo._closed_1  (result i64)
    (local $l104 i32)
    (local $l105 i64)
  call $strLenDemo._closed_0
  local.set $l104
  local.get $l104
  call $string_len
  local.set $l105
  local.get $l105
  return
)
(func $sumList._boxed (param $xs i32) (param $acc i32) (result i32)
    (local $l106 i64)
    (local $l107 i64)
    (local $l108 i32)
  local.get $acc
  i64.load offset=8
  local.set $l106
  local.get $acc
  call $rc_dec
  local.get $xs
  local.get $l106
  call $sumList
  local.set $l107
  local.get $xs
  call $rc_dec
  i32.const 16
  call $alloc
  local.set $l108
  local.get $l108
  local.get $l107
  i64.store offset=8
  local.get $l108
  return
)
(func $adder._boxed (param $a i32) (param $b i32) (result i32)
    (local $l109 i64)
    (local $l110 i64)
    (local $l111 i64)
    (local $l112 i32)
  local.get $a
  i64.load offset=8
  local.set $l109
  local.get $a
  call $rc_dec
  local.get $b
  i64.load offset=8
  local.set $l110
  local.get $b
  call $rc_dec
  local.get $l109
  local.get $l110
  call $adder
  local.set $l111
  i32.const 16
  call $alloc
  local.set $l112
  local.get $l112
  local.get $l111
  i64.store offset=8
  local.get $l112
  return
)
(func $doubleArea._boxed (param $r i32) (result i32)
    (local $l113 i64)
    (local $l114 i64)
    (local $l115 i32)
  local.get $r
  i64.load offset=8
  local.set $l113
  local.get $r
  call $rc_dec
  local.get $l113
  call $doubleArea
  local.set $l114
  i32.const 16
  call $alloc
  local.set $l115
  local.get $l115
  local.get $l114
  i64.store offset=8
  local.get $l115
  return
)
(func $runPaps._closed_1  (result i32)
    (local $l116 i32)
    (local $l117 i32)
  call $runPaps._closed_1._boxed_const_1
  local.set $l116
  local.get $l116
  call $rc_inc
  i32.const 24
  call $alloc
  local.set $l117
  local.get $l117
  i32.const 254
  i32.store8 offset=4
  local.get $l117
  i32.const 1
  i32.store offset=8
  local.get $l117
  local.get $l116
  i32.store offset=16
  local.get $l117
  return
)
(func $strLenDemo._boxed (param $n i32) (result i32)
    (local $l118 i64)
    (local $l119 i64)
    (local $l120 i32)
  local.get $n
  i64.load offset=8
  local.set $l118
  local.get $n
  call $rc_dec
  local.get $l118
  call $strLenDemo
  local.set $l119
  i32.const 16
  call $alloc
  local.set $l120
  local.get $l120
  local.get $l119
  i64.store offset=8
  local.get $l120
  return
)
(func $applyAll._boxed (param $fs i32) (param $x i32) (result i32)
    (local $l121 i64)
    (local $l122 i64)
    (local $l123 i32)
  local.get $x
  i64.load offset=8
  local.set $l121
  local.get $x
  call $rc_dec
  local.get $fs
  local.get $l121
  call $applyAll
  local.set $l122
  i32.const 16
  call $alloc
  local.set $l123
  local.get $l123
  local.get $l122
  i64.store offset=8
  local.get $l123
  return
)
(func $runPaps._closed_2  (result i32)
    (local $l124 i32)
    (local $l125 i32)
    (local $l126 i32)
  i32.const 8
  call $alloc
  local.set $l124
  local.get $l124
  i32.const 0
  i32.store8 offset=4
  call $runPaps._closed_1
  local.set $l125
  local.get $l125
  call $rc_inc
  i32.const 24
  call $alloc
  local.set $l126
  local.get $l126
  i32.const 1
  i32.store8 offset=4
  local.get $l126
  local.get $l125
  i32.store offset=8
  local.get $l126
  local.get $l124
  i32.store offset=16
  local.get $l126
  return
)
(func $runPaps._boxed (param $x i32) (result i32)
    (local $l127 i64)
    (local $l128 i64)
    (local $l129 i32)
  local.get $x
  i64.load offset=8
  local.set $l127
  local.get $x
  call $rc_dec
  local.get $l127
  call $runPaps
  local.set $l128
  i32.const 16
  call $alloc
  local.set $l129
  local.get $l129
  local.get $l128
  i64.store offset=8
  local.get $l129
  return
)
(func $runPaps._lam_1 (param $_x.1 i64) (param $_y.2 i64) (result i64)
    (local $l130 i64)
  local.get $_x.1
  local.get $_y.2
  i64.add
  local.set $l130
  local.get $l130
  return
)
(func $strLenDemo._closed_2  (result i32)
    (local $l131 i32)
  i32.const 27
  call $alloc
  local.set $l131
  local.get $l131
  i32.const 250
  i32.store8 offset=4
  local.get $l131
  i32.const 11
  i32.store offset=8
  local.get $l131
  i32.const 104
  i32.store8 offset=16
  local.get $l131
  i32.const 101
  i32.store8 offset=17
  local.get $l131
  i32.const 108
  i32.store8 offset=18
  local.get $l131
  i32.const 108
  i32.store8 offset=19
  local.get $l131
  i32.const 111
  i32.store8 offset=20
  local.get $l131
  i32.const 32
  i32.store8 offset=21
  local.get $l131
  i32.const 119
  i32.store8 offset=22
  local.get $l131
  i32.const 111
  i32.store8 offset=23
  local.get $l131
  i32.const 114
  i32.store8 offset=24
  local.get $l131
  i32.const 108
  i32.store8 offset=25
  local.get $l131
  i32.const 100
  i32.store8 offset=26
  local.get $l131
  return
)
(func $greet._closed_0  (result i32)
    (local $l132 i32)
  i32.const 19
  call $alloc
  local.set $l132
  local.get $l132
  i32.const 250
  i32.store8 offset=4
  local.get $l132
  i32.const 3
  i32.store offset=8
  local.get $l132
  i32.const 98
  i32.store8 offset=16
  local.get $l132
  i32.const 121
  i32.store8 offset=17
  local.get $l132
  i32.const 101
  i32.store8 offset=18
  local.get $l132
  return
)
(func $area._boxed (param $s i32) (result i32)
    (local $l133 i64)
    (local $l134 i32)
  local.get $s
  call $area
  local.set $l133
  local.get $s
  call $rc_dec
  i32.const 16
  call $alloc
  local.set $l134
  local.get $l134
  local.get $l133
  i64.store offset=8
  local.get $l134
  return
)
(func $greet._boxed (param $n i32) (result i32)
    (local $l135 i64)
  local.get $n
  i64.load offset=8
  local.set $l135
  local.get $n
  call $rc_dec
  local.get $l135
  return_call $greet
)
(func $double_abi (param $x i64) (result i64)

  local.get $x
  call $double
)
(func $isBig_abi (param $x i64) (result i32)

  local.get $x
  call $isBig
)
(func $adder_abi (param $a i64) (param $b i64) (result i64)

  local.get $a
  local.get $b
  call $adder
)
(func $area_abi (param $s i32) (result i64)
  (local $b0 i32)
  i32.const 16
  call $alloc
  local.set $b0
  local.get $b0
  local.get $s
  i32.store offset=8
  local.get $b0
  local.get $s
  i32.store8 offset=4
  local.get $b0
  call $area
)
(func $doubleArea_abi (param $r i64) (result i64)

  local.get $r
  call $doubleArea
)
(func $pick_abi (param $b i32) (param $a i64) (param $x i64) (result i64)

  local.get $b
  local.get $a
  local.get $x
  call $pick
)
(func $applyAll_abi (param $fs i32) (param $x i64) (result i64)

  local.get $fs
  local.get $x
  call $applyAll
)
(func $runPaps_abi (param $x i64) (result i64)

  local.get $x
  call $runPaps
)
(func $curried_abi (param $a i64) (param $x i64) (param $y i64) (result i64)

  local.get $a
  local.get $x
  local.get $y
  call $curried
)
(func $apply2All_abi (param $fs i32) (param $x i64) (param $y i64) (result i64)

  local.get $fs
  local.get $x
  local.get $y
  call $apply2All
)
(func $useCurried_abi (param $a i64) (result i64)

  local.get $a
  call $useCurried
)
(func $sumList_abi (param $xs i32) (param $acc i64) (result i64)
  (local $b0 i32)
  i32.const 16
  call $alloc
  local.set $b0
  local.get $b0
  local.get $xs
  i32.store offset=8
  local.get $b0
  local.get $xs
  i32.store8 offset=4
  local.get $b0
  local.get $acc
  call $sumList
)
(func $total_abi (param $a i64) (param $b i64) (param $c i64) (result i64)

  local.get $a
  local.get $b
  local.get $c
  call $total
)
(func $strLenDemo_abi (param $n i64) (result i64)

  local.get $n
  call $strLenDemo
)
(func $greet_abi (param $n i64) (result i32)
  (local $p i32)
  local.get $n
  call $greet
  local.set $p
  i32.const 48
  local.get $p
  i32.const 16
  i32.add
  i32.store
  i32.const 48
  local.get $p
  i32.load offset=8
  i32.store offset=4
  i32.const 48
)
(func $pap_curried._boxed_1 (param $c i32) (param $x0 i32) (param $x1 i32) (result i32)
  local.get $c
  i32.load offset=16
  local.get $x0
  local.get $x1
  call $curried._boxed
)
(func $pap_runPaps._lam_1._boxed_1 (param $c i32) (param $x0 i32) (result i32)
  local.get $c
  i32.load offset=16
  local.get $x0
  call $runPaps._lam_1._boxed
)
  (type $sig_2box (func (param i32) (param i32) (param i32) (result i32)))
  (type $sig_1box (func (param i32) (param i32) (result i32)))
  (table 2 funcref)
  (elem (i32.const 0) $pap_curried._boxed_1 $pap_runPaps._lam_1._boxed_1)
  (export "double" (func $double_abi))
  (export "is-big" (func $isBig_abi))
  (export "adder" (func $adder_abi))
  (export "area" (func $area_abi))
  (export "double-area" (func $doubleArea_abi))
  (export "pick" (func $pick_abi))
  (export "apply-all" (func $applyAll_abi))
  (export "run-paps" (func $runPaps_abi))
  (export "curried" (func $curried_abi))
  (export "apply2-all" (func $apply2All_abi))
  (export "use-curried" (func $useCurried_abi))
  (export "sum-list" (func $sumList_abi))
  (export "total" (func $total_abi))
  (export "str-len-demo" (func $strLenDemo_abi))
  (export "greet" (func $greet_abi))
  (export "memory" (memory 0))
)