/-
# LedgerES — the event-sourced ledger dogfood (W5.1 phase 2)

The verified-ledger study's shape, expressed on the toolkit: the
`@[event_sourced]` records (`Account`/`Entry` in Ledger.lean) supply the
delta variant + journal codec + replay + upcaster + RewindableMachine;
this module is the MODEL layer:

- **Posting an entry = appending a delta.** `postEntry e log = log ++
  [.insert e]` — the entry log is append-only (an entry is never
  edited; a reversal is a compensating entry, the accounting rule).
- **Balance = replay.** `balances log = Entry.replay log []` — the
  entry table is the materialization of the log; `balanceOf a` derives
  an account's balance from it (credits minus debits, in `Int` — the
  amount's machine width is the wire's concern; the model sums in ℤ,
  and the transfer identity `+amt`/`−amt` is exact there).
- **Conservation** (`total_post_conserves`): over a FIXED account
  universe `ids`, posting an entry whose endpoints are both in the
  universe leaves the total balance invariant. Stated over the model
  and PROVED — so the obligation row (`conservationObligation`) rides
  the OBLIGATION substrate at the tightest tier that computes:
  `.provedAtElab`, evidence `.citedProof`.
- **Reversal = the inverse delta**: `Account.esMachine` is THE first
  constructed `Machines.RewindableMachine` (the review's pin-only
  island graduates here); `transfer_rewind` instantiates
  `rewind_runLogged` — reverting the recorded journal restores the
  initial table — and `transfer_replay` pins the transfer fixture.

The negative controls (sabotaged replay log / journal bytes / journal
length / one-legged posting) live in Tests/Main.lean beside the
positive fixtures.

W9.5 adds the guestVerified MIGRATION dogfood (design-guest-verified
§4, the consumer half): a v1→v2 field migration of `Account` (the id
widened u32→u64 — the shipped `widenU32U64` remedy at the ledger's own
schema), its witness GENERATED by W9.4's machinery (`selfChecked?` —
reused, not duplicated), and the replay-through-migration gated by
`EventSourced.replayMigrated?`: the segment applies ONLY under an
accepting witness; refusal names the obligation's label + the class
(`diverged` / `fuelExhausted`). The obligation row rides the kit's
fifth tier (`.guestVerified` / `.guestWitness`).
-/

import SchemaLang
import SchemaLang.Emit.Witness
import Machines
import Ledger

namespace LedgerES

/-! ## Posting and derived balances -/

/-- Posting an entry IS appending its insert-delta to the log. -/
def postEntry (e : Entry) (log : List Entry.Event) : List Entry.Event :=
  log ++ [.insert e]

/-- The entry table: the log's replay (balance = replay — the table is
    a derived view; the log is the truth). -/
def balances (log : List Entry.Event) : List Entry := Entry.replay log []

/-- The derived balance of account `a` from an entry table: credits
    (entries with `dst = a`) minus debits (`src = a`), summed in `Int`. -/
def balanceOf (a : UInt64) (es : List Entry) : Int :=
  ((es.filter (fun e => e.dst == a)).map (fun e => e.amount.toInt)).sum
  - ((es.filter (fun e => e.src == a)).map (fun e => e.amount.toInt)).sum

/-- The total balance over a fixed account universe. -/
def total (ids : List UInt64) (es : List Entry) : Int :=
  (ids.map (fun a => balanceOf a es)).sum

/-! ## The conservation proof -/

/-- Posting touches the derived balance of exactly the two endpoints:
    `dst` gains the amount, `src` loses it (as Int — exact). -/
theorem balanceOf_snoc (a : UInt64) (es : List Entry) (e : Entry) :
    balanceOf a (es ++ [e])
      = balanceOf a es
        + (if e.dst = a then e.amount.toInt else 0)
        - (if e.src = a then e.amount.toInt else 0) := by
  by_cases hto : e.dst = a <;> by_cases hfr : e.src = a <;>
    simp [balanceOf, hto, hfr, List.sum_append] <;> try omega

/-- Sum distributes over pointwise addition of mapped functions (Int). -/
theorem sum_map_add (f g : α → Int) (l : List α) :
    (l.map fun a => f a + g a).sum = (l.map f).sum + (l.map g).sum := by
  induction l with
  | nil => rfl
  | cons a as ih => simp [List.map_cons, List.sum_cons, ih]; omega

/-- Sum distributes over pointwise subtraction (Int). -/
theorem sum_map_sub (f g : α → Int) (l : List α) :
    (l.map fun a => f a - g a).sum = (l.map f).sum - (l.map g).sum := by
  induction l with
  | nil => rfl
  | cons a as ih => simp [List.map_cons, List.sum_cons, ih]; omega

/-- An indicator sum over a list the key is ABSENT from is zero. -/
theorem sum_indicator_eq_zero (ids : List UInt64) (x : UInt64) (hx : x ∉ ids) (m : Int) :
    (ids.map fun a => if x = a then m else 0).sum = 0 := by
  induction ids with
  | nil => rfl
  | cons a as ih =>
    simp only [List.mem_cons, not_or] at hx
    simp [List.map_cons, List.sum_cons, hx.1, ih hx.2]

/-- An indicator sum over a NODUP list containing the key is the mass:
    exactly one position matches. -/
theorem sum_indicator_eq_single (ids : List UInt64) (h : ids.Nodup)
    (x : UInt64) (hx : x ∈ ids) (m : Int) :
    (ids.map fun a => if x = a then m else 0).sum = m := by
  induction ids with
  | nil => contradiction
  | cons a as ih =>
    simp only [List.nodup_cons] at h
    simp only [List.map_cons, List.sum_cons]
    by_cases hxa : x = a
    · subst hxa
      have hzero := sum_indicator_eq_zero as x h.1 m
      simp [hzero]
    · have hx' : x ∈ as := by
        rcases List.mem_cons.mp hx with h_eq | h_mem
        · exact absurd h_eq hxa
        · exact h_mem
      simp [hxa, ih h.2 hx']

/-- CONSERVATION over the table: appending an entry whose endpoints are
    both in the universe leaves the total invariant (the credit leg and
    the debit leg cancel — the double-entry rule as a theorem). -/
theorem total_snoc_closed (ids : List UInt64) (hids : ids.Nodup)
    (es : List Entry) (e : Entry)
    (hfrom : e.src ∈ ids) (hto : e.dst ∈ ids) :
    total ids (es ++ [e]) = total ids es := by
  have hmap : ids.map (fun a => balanceOf a (es ++ [e]))
      = ids.map (fun a => balanceOf a es
          + (if e.dst = a then e.amount.toInt else 0)
          - (if e.src = a then e.amount.toInt else 0)) :=
    List.map_congr_left (fun a _ => balanceOf_snoc a es e)
  show (ids.map (fun a => balanceOf a (es ++ [e]))).sum
    = (ids.map fun a => balanceOf a es).sum
  rw [hmap, sum_map_sub, sum_map_add,
    sum_indicator_eq_single ids hids e.dst hto,
    sum_indicator_eq_single ids hids e.src hfrom]
  ring

/-- A fresh key's findIdx is the length (no match anywhere). -/
theorem findIdx_fresh_eq_length (tbl : List Entry) (e : Entry)
    (hfresh : ∀ x ∈ tbl, x.id ≠ e.id) :
    tbl.findIdx (fun r => Entry.esKey r == Entry.esKey e) = tbl.length := by
  apply List.findIdx_eq_length_of_false
  intro x hx
  show (Entry.esKey x == Entry.esKey e) = false
  exact beq_eq_false_iff_ne.mpr (hfresh x hx)

/-- CONSERVATION, the event-sourced statement: posting an entry to the
    LOG (append its insert-delta) leaves the total balance of a fixed
    account universe invariant — replay-after-append, the fresh-key
    upsert, and the closed-universe sum telescope. -/
theorem total_post_conserves (ids : List UInt64) (hids : ids.Nodup)
    (log : List Entry.Event) (e : Entry)
    (hfrom : e.src ∈ ids) (hto : e.dst ∈ ids)
    (hfresh : ∀ x ∈ Entry.replay log [], x.id ≠ e.id) :
    total ids (balances (postEntry e log)) = total ids (balances log) := by
  show total ids (Entry.replay (log ++ [.insert e]) [])
    = total ids (Entry.replay log [])
  rw [Entry.replay_snoc]
  have happly :
      SchemaLang.EventSourced.apply Entry.esKey (.insert e) (Entry.replay log [])
        = Entry.replay log [] ++ [e] := by
    show SchemaLang.EventSourced.upsert Entry.esKey e _ = _
    exact SchemaLang.EventSourced.upsert_eq_append Entry.esKey e _
      (findIdx_fresh_eq_length _ e hfresh)
  rw [happly]
  exact total_snoc_closed ids hids _ e hfrom hto

/-! ## W9.5 — the guestVerified migration dogfood (the witness-gated replay)

The consumption half of design-guest-verified §4, at the ledger's own
schema. The v1 `Account` shape (the id was u32) is Lean DATA here —
the committed registry carries only v2; detection/re-baselining is the
breaking gate's lane (W6.5), this dogfood owns the CONSUMPTION half:
the committed v1 segment migrates, the witness certifies the invariant
over the migrated rows, and the replay is GATED on the check. -/

/-- The v1 account row (the migration's SOURCE shape): the id was a
    u32; v2 — the committed schema — widened it to u64. -/
structure AccountV1 where
  id : UInt32
  label : String
  balance : Int64
deriving BEq, Repr, DecidableEq

/-- The v1 event log's delta type (the same `EventSourced.Delta` shape,
    keyed by the v1 id). -/
abbrev AccountV1.Event := SchemaLang.EventSourced.Delta AccountV1 UInt32

/-- The remedy row (the `Demo.registeredMigrations` precedent — the
    shape, at the ledger's own schema): `Account.id` widens u32→u64,
    the shipped exemplar remedy. -/
def ledgerRegisteredMigrations : List SchemaLang.Migration :=
  [ { item := "Account", fields := [SchemaLang.widenU32U64 "id"] } ]

/-- The remedy row COVERS the widening finding (the `Migration.remedies`
    verdict, exercised — the breaking gate's `remedied` arm's input). -/
theorem ledgerMigration_remedies :
    ledgerRegisteredMigrations.any (·.remedies
      (.changed "Account" [.fieldTypeChanged "id" .u32 .u64])) = true := by decide

/-- The row map the remedy induces: the id widened, the rest carried. -/
def migrateAccountV1 (a : AccountV1) : Account :=
  ⟨a.id.toUInt64, a.label, a.balance⟩

/-- The remedy's row-level soundness (the `widenU32U64_sound` shape):
    the migrated id IS the old id's number. -/
theorem migrateAccountV1_id (a : AccountV1) :
    (migrateAccountV1 a).id.toNat = a.id.toNat := rfl

/-- The event-level upcaster the gate replays through: insert/update
    payloads migrate row-wise; remove's key widens. -/
def upcastAccountV1 : AccountV1.Event → Account.Event
  | .insert r => .insert (migrateAccountV1 r)
  | .update r => .update (migrateAccountV1 r)
  | .remove k => .remove k.toUInt64

/-- The committed v1 segment's base row (the chain claim's initial
    row — shipped migrated, per the gate's contract). -/
def accountV1Init : AccountV1 := ⟨1, "alice", 100⟩

/-- The committed v1 segment: two more accounts (insert-only — the
    entry lane's convention). -/
def accountV1Segment : List AccountV1 := [⟨2, "bob", 50⟩, ⟨3, "carol", 75⟩]

/-- The segment as a v1 event log. -/
def accountV1Log : List AccountV1.Event := accountV1Segment.map fun a => .insert a

/-- The decoded context the witness certifies — DERIVED by the gate's
    own construction (`migrationCtx`: the checked rows ARE the rows
    under application; a hand-mirrored context cannot drift). The
    surface is Account's ATTRIBUTE-DERIVED field list (`esFields`) and
    row bridge (`esToRow`) — renaming an Account field fails THIS
    module's elaboration. -/
def accountV1V2Ctx : SchemaLang.WitnessCheck.RowValsP :=
  SchemaLang.EventSourced.migrationCtx Account.esToRow upcastAccountV1
    (migrateAccountV1 accountV1Init) accountV1Log

/-- The obligation's registration row (the `demoWitnesses` precedent):
    replaying the v1 segment through the migration preserves the
    id-nonzero half of `ledger_valid` — claim + derived context + the
    artifact name the discharge's evidence cites. -/
def accountV1V2WitnessSpec : SchemaLang.WitnessSpec :=
  { label := "account-v1-v2-id-nonzero"
  , artifact := "witnesses/account-v1-v2-id-nonzero.wtn"
  , claim := .chain [⟨0⟩, ⟨1⟩] (.gt (.col "id") (.lit 0))
  , ctx := accountV1V2Ctx }

/-- The semantic premise: the claim HOLDS over the derived context (the
    migrated ids 1, 2, 3 are all nonzero) — the reason a certificate
    exists at all (W9.4's completeness cites exactly this shape). -/
theorem accountV1V2_holds :
    SchemaLang.WitnessCheck.WHolds accountV1V2WitnessSpec.claim
      accountV1V2Ctx.row accountV1V2Ctx.log := by
  apply SchemaLang.WitnessCheck.WHolds.chain
  · decide
  · intro s hs
    fin_cases hs
    · exact ⟨Account.esToRow (migrateAccountV1 ⟨2, "bob", 50⟩), rfl, by decide⟩
    · exact ⟨Account.esToRow (migrateAccountV1 ⟨3, "carol", 75⟩), rfl, by decide⟩

/-- Generation is complete for this TRUE claim (W9.4's
    `selfChecked?_of_WHolds`, CITED — the premise above is the proof
    input, not a recomputation). -/
theorem accountV1V2_selfChecked :
    (SchemaLang.Emit.Witness.selfChecked? accountV1V2WitnessSpec).isSome = true :=
  SchemaLang.Emit.Witness.selfChecked?_of_WHolds _ accountV1V2_holds

/-- The certificate — W9.4's machinery REUSED (`selfChecked?`: the
    claim-matched proof term, the `consumed × 4` pinned fuel, the
    in-process self-check; the `.get` proof IS the self-check pin — an
    uncheckable spec fails THIS elaboration). -/
def accountV1V2Witness : SchemaLang.Witness.Witness :=
  (SchemaLang.Emit.Witness.selfChecked? accountV1V2WitnessSpec).get (by decide)

/-- THE CHECKPOINT, EXERCISED end to end (design §4 steps 3–5): the
    committed v1 segment, upcast, witness-checked through the
    `verifyWitness` seam over the derived context, and only then
    replayed onto the base table. -/
def accountV1V2Replay :
    Except SchemaLang.EventSourced.MigrationRefusal (List Account) :=
  SchemaLang.EventSourced.replayMigrated? Account.esKey Account.esToRow
    upcastAccountV1 accountV1V2Witness (migrateAccountV1 accountV1Init)
    accountV1Log [migrateAccountV1 accountV1Init]

/-- The migrated segment REPLAYS under the valid witness — the
    post-state, pinned (the decide IS the gate run: classify, check,
    apply). -/
theorem accountV1V2Replay_ok :
    accountV1V2Replay = .ok [⟨1, "alice", 100⟩, ⟨2, "bob", 50⟩, ⟨3, "carol", 75⟩] := by
  decide

/-- The acceptance, CITED through the gate's soundness wrapper
    (`replayMigrated?_ok`): the claim's denotation holds over the
    derived context — the segment's rows are guest-certified per step. -/
theorem accountV1V2_certified :
    SchemaLang.WitnessCheck.WHolds accountV1V2Witness.claim
      accountV1V2Ctx.row accountV1V2Ctx.log :=
  (SchemaLang.EventSourced.replayMigrated?_ok Account.esKey Account.esToRow
    upcastAccountV1 accountV1V2Witness (migrateAccountV1 accountV1Init)
    accountV1Log [migrateAccountV1 accountV1Init] _ accountV1V2Replay_ok).2

/-- `id`'s path in Account's derived field list (the resolution
    evidence the mirror cites). -/
def accountIdPath : SchemaLang.ColPath "id" .u64 Account.esFields := .here

/-- The certified invariant in compiled form (the id-nonzero half of
    `ledger_valid`): `id > 0` over Account's derived fields. -/
def accountIdPositiveInv : SchemaLang.VExpr Account.esFields .bool :=
  .gt (.col "id" accountIdPath) (.lit 0)

/-- The claim/compiled mirror (W9.2's `WBMirror`, ctor-for-ctor). -/
theorem accountIdPositiveMirror :
    SchemaLang.WitnessCheck.WBMirror (.gt (.col "id") (.lit 0)) accountIdPositiveInv :=
  .gt (.col "id" accountIdPath) (.lit 0)

/-- THE BRIDGE, EXECUTED (W9.2's `WHolds.chain_validates`, cited —
    under the derived field list's name uniqueness, discharged by
    decide): the guest-certified chain certifies the COMPILED
    `validates` verdict at the base row and at every referenced
    segment row. -/
theorem accountV1V2_validates :
    SchemaLang.validates accountIdPositiveInv accountV1V2Ctx.row = true ∧
      ∀ s, s ∈ ([⟨0⟩, ⟨1⟩] : List SchemaLang.Witness.WStep) →
        ∃ r, accountV1V2Ctx.log[s.offset]? = some r ∧
          SchemaLang.validates accountIdPositiveInv r = true :=
  SchemaLang.WitnessCheck.WHolds.chain_validates accountIdPositiveMirror (by decide)
    accountV1V2_certified

/-- THE POST-STATE INVARIANT on the replayed table itself: whatever the
    gate applied, every row satisfies the compiled invariant. The
    certification chain does the work (the base row is
    `accountV1V2_validates.1`; the segment rows are its `.2` at the
    chain's offsets — the replayed table IS base ∪ segment here). -/
theorem accountV1V2_post_valid (st : List Account)
    (hst : accountV1V2Replay = .ok st) :
    ∀ r ∈ st, SchemaLang.validates accountIdPositiveInv (Account.esToRow r) = true := by
  rw [accountV1V2Replay_ok] at hst
  cases hst
  intro r hr
  fin_cases hr
  · exact accountV1V2_validates.1
  · obtain ⟨r', hget, hr'⟩ := accountV1V2_validates.2 ⟨0⟩ List.mem_cons_self
    have hrr : r' = Account.esToRow ⟨2, "bob", 50⟩ := (Option.some.inj hget).symm
    rw [hrr] at hr'
    exact hr'
  · obtain ⟨r', hget, hr'⟩ := accountV1V2_validates.2 ⟨1⟩
      (List.mem_cons_of_mem _ List.mem_cons_self)
    have hrr : r' = Account.esToRow ⟨3, "carol", 75⟩ := (Option.some.inj hget).symm
    rw [hrr] at hr'
    exact hr'

/-! ## The obligation row (the tightest tier that computes) -/

/-- The ledger's obligations: the kit's shape (`CodegenCore.Obligation`)
    instantiated with the cited theorem's name as the payload. -/
abbrev LedgerObligation := CodegenCore.Obligation Lean.Name

/-- The discharge: a proved row's evidence is its citation (the
    `SchemaObligation.discharge` pattern — a `none` here would be the
    loud gap). The W9.5 arm: a `guestVerified` row's evidence is the
    witness artifact + label, firing ONLY when the obligation's label
    IS the certificate's (the mis-wire check) AND the `verifyWitness`
    seam accepts the certificate over the derived context (the
    checker's verdict — the W9.3 arm's shape, at the kit level). -/
def LedgerObligation.discharge (o : LedgerObligation) :
    Option CodegenCore.Obligation.Evidence :=
  match o.tier with
  | .provedAtElab => some (.citedProof o.payload)
  | .guestVerified =>
      if o.label == accountV1V2Witness.label &&
          SchemaLang.WitnessCheck.verifyWitness accountV1V2Witness accountV1V2Ctx then
        some (.guestWitness accountV1V2WitnessSpec.artifact o.label)
      else none
  | _ => none

/-- CONSERVATION as an obligation: the proof IS statable over the model
    (`total_post_conserves`), so the tier is `.provedAtElab` — the
    tightest rung — and the evidence is the citation. -/
def conservationObligation : LedgerObligation :=
  { label := "ledger-conservation"
  , tier := .provedAtElab
  , payload := ``LedgerES.total_post_conserves
  , provenance := ``LedgerES.total_post_conserves }

/-- The conservation obligation discharges (the armed-and-FIRED check:
    a proved-tier row that cannot name its evidence fails here). -/
theorem conservation_discharges :
    conservationObligation.discharge.isSome = true := rfl

/-- The MIGRATION obligation at the fifth tier (`.guestVerified` — the
    W9.3 rung): replaying the committed v1 segment through the id
    widening preserves `id > 0`, certified by the guest-checked
    witness. The payload/provenance name the certificate; the evidence
    names the artifact + label. -/
def accountMigrationObligation : LedgerObligation :=
  { label := "account-v1-v2-id-nonzero"
  , tier := .guestVerified
  , payload := ``LedgerES.accountV1V2Witness
  , provenance := ``LedgerES.accountV1V2Witness }

/-- The migration obligation DISCHARGES at the fifth tier: the label
    matches and the seam accepts (the decide IS the checker run —
    label check + `verifyWitness`, both). -/
theorem accountMigration_discharges :
    accountMigrationObligation.discharge =
      some (.guestWitness "witnesses/account-v1-v2-id-nonzero.wtn"
        "account-v1-v2-id-nonzero") := by
  decide

/-- The discharge's evidence tier always matches the obligation's tier
    (the kit's mis-wired check, discharged for this lane). -/
theorem discharge_tier_agrees (o : LedgerObligation)
    (ev : CodegenCore.Obligation.Evidence) (h : o.discharge = some ev) :
    ev.tier = o.tier := by
  obtain ⟨label, tier, payload, provenance⟩ := o
  cases tier <;> simp [LedgerObligation.discharge] at h ⊢
  · subst h; rfl
  · -- guestVerified: a `some` here carries `.guestWitness` evidence
    -- (simp rewrote the conditional discharge to its conjunction form)
    obtain ⟨⟨_hlabel, _hcheck⟩, hev⟩ := h
    cases hev
    rfl

/-! ## The RewindableMachine instance, exercised (reversal = the inverse delta) -/

/-- The fixture's two accounts. -/
def alice : Account := ⟨1, "alice", 100⟩
def bob : Account := ⟨2, "bob", 50⟩

/-- A transfer as account-log deltas: open both accounts, then the two
    update legs (debit alice, credit bob). -/
def transferEvents (amount : Int64) : List Account.Event :=
  [ .insert alice, .insert bob
  , .update { alice with balance := alice.balance - amount }
  , .update { bob with balance := bob.balance + amount } ]

/-- The replay materializes the post-transfer table (the fixture pin —
    `decide` over the generated replay). -/
theorem transfer_replay :
    Account.replay (transferEvents 30) [] = [⟨1, "alice", 70⟩, ⟨2, "bob", 80⟩] := by
  decide

/-- THE REWIND LAW, instantiated: reverting the recorded journal
    restores the initial table (reversal = the inverse delta — the
    `RewindableMachine.rewind_runLogged` family, the island's first
    resident). -/
theorem transfer_rewind (tr ds fin) :
    Machines.RewindableMachine.runLogged Account.esMachine [] (transferEvents 30)
      = some (tr, ds, fin) →
    Account.esMachine.rewind ds.reverse fin = [] :=
  fun h => Machines.RewindableMachine.rewind_runLogged Account.esMachine _ _ _ _ _ h

/-- REWIND-K = UNDO-K, instantiated: reverting the last K deltas
    restores the state after the first length−K events (the
    `RewindableMachine.rewind_suffix` family). -/
theorem transfer_rewind_suffix (tr ds fin) (K : Nat)
    (h : Machines.RewindableMachine.runLogged Account.esMachine []
      (transferEvents 30) = some (tr, ds, fin))
    (hK : K ≤ (transferEvents 30).length) :
    ∃ mid tr1 ds1,
      Machines.RewindableMachine.runLogged Account.esMachine []
        ((transferEvents 30).take ((transferEvents 30).length - K)) = some (tr1, ds1, mid) ∧
      Account.esMachine.rewind (ds.drop ((transferEvents 30).length - K)).reverse fin = mid :=
  Machines.RewindableMachine.rewind_suffix Account.esMachine _ _ _ _ _ h K hK

/-- The logged run's delta count IS the event count (the journal has
    one entry per posting). -/
theorem transfer_journal_length (tr ds fin) :
    Machines.RewindableMachine.runLogged Account.esMachine [] (transferEvents 30)
      = some (tr, ds, fin) →
    ds.length = (transferEvents 30).length :=
  fun h => Machines.RewindableMachine.runLogged_length Account.esMachine _ _ _ _ _ h

end LedgerES
