-- GENERATED by scaffold (lean-4.33.0) at - — DO NOT EDIT
-- spec scaffold-golden | AppSpec LedgerApp | 5 item(s) | content hash 8688468338461771112 | regen: just gen; drift fails CI
/-
# LedgerApp.App — the generated application module (Scaffold)

The lane consumption lives HERE (the Reg module's initializers
ran at ITS import — the LaneReg→LaneDemo discipline).

Five questions (notes/v3/01-core.md), filled from the AppSpec:
- root: crossing
- carrier grade: the posting over the registry's nodup-in-type substrate
- spine reading: registration = append; the ledger folds the replay
- ladder rung: generated
- gate row: axioms, docs-check
Consumes (the schema registry refs): Order
Capabilities generated: registry-lane, emitter, checks, diagnostics, tests
-/

import Kit.Emit
import Kit.Obligation
import Kit.Derive.Evidence
import Kit.Diag
import LedgerApp.Reg

namespace LedgerApp

/-! ## The consumed items (the AppSpec's echo) -/

/-- The schema items this app consumes (the AppSpec's echo — the
    consumption wiring lands with the schema lanes; the schema is
    the schema lane's artifact, never the scaffold's). -/
def ledgerAppItemConsumes : List String := ["Order"]

/-! ## The lane consumption (capability: registry-lane) -/

/-- One sample entry — the lane consumption's live seed (the
    attribute appends at elaboration; the replay reads it in the
    consumers of this module). -/
@[ledgerAppItem]
def sampleEntry : LedgerAppItem := { name := "sample", weight := 1 }

/-! ## The obligation view (15-patterns #4 — one row per item) -/

/-- The obligation row over one item: the label, the COMPUTED
    tier, the payload, the provenance — and THE CLAIM AS THE TYPE
    INDEX (the row claims the item's name is nonempty — the
    naming fn's precondition), so the tier/evidence/discharge can
    never drift from the claim. The tier is COMPUTED from the
    evidence kind (Kit.Derive.Evidence — 16-surface §3): the claim
    is decidable over the closed field space, the kernel decides —
    the machinery cannot mislabel. The discharge rides the
    KIT backends (`Kit.Obligation.decideDischarge` — it discharges
    the row's OWN index; there is no claim parameter to mis-wire),
    never a hand-rolled trio. -/
def ledgerAppItemObligation (it : LedgerAppItem) : Kit.Obligation String (it.name ≠ "") :=
  { label := s!"LedgerApp/" ++ it.name
    tier := (Kit.Derive.Evidence.evidenceKindOfShape
              Kit.Derive.Evidence.CarrierShape.closedFinite).tier!
    payload := it.name
    provenance := `LedgerApp }

/-! ## The check face (capability: checks — R5) -/

/-- The checker face the skeleton pins: a decidable legality over
    one item. FILL OBLIGATIONS (R5): the Statement instance (the
    checker + `sound`; completeness `.missing` unless proved) and
    the mounts (gate/lint/test/obligation/monitor) land when the
    app's real judgment exists — never new check-shaped
    infrastructure. -/
def ledgerAppItemCheck (it : LedgerAppItem) : Bool :=
  !it.name.isEmpty

/-- The check's curated refusal shape (the ONE envelope; the
    closed-world constructor fills the valid space + the
    did-you-mean). -/
def ledgerAppItemCheckDiag (it : LedgerAppItem) : Kit.Diag :=
  Kit.Diag.closedWorld ⟨"SCF0013"⟩  -- eSCF0013: Scaffold.Spec's
    -- allocated row (the persisted registry; never a hand-strung code)
    (s!"LedgerApp: item " ++ it.name
      ++ " fails ledgerAppItemCheck — the name must be nonempty")
    .error it.name ["a nonempty name"]

/-! ## The diagnostics rows (capability: diagnostics — 05 §4) -/

/-- The usage-Diag helper (the `Kit.Lane.usageDiag` shape): every
    failure path constructs the ONE envelope, the E-code named at
    the call site (the persisted registry allocates them — never
    position-derived). -/
def ledgerAppItemUsageDiag (code message : String) : Kit.Diag :=
  { code := ⟨code⟩, message := message, severity := .error }

end LedgerApp
